### ISSUE TITLE
Block cmp.quantcast.com

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#1007]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
Rethink DNS

<br>

**Domains:**
```
cmp.quantcast.com
quantcast.com
```
<br>

**Details:**
A handful blocklists block these two domains: https://archive.is/jZ5J0

**Comment by badmojr** [comment]
Prefer blocking this by its subdomains. Likely to break GDPR CCP, especially for EU users.
