### ISSUE TITLE
Question regarding grs.dbankcloud.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#103]
Hi @badmojr,

Just out of curiosity... what is the "story" behind blocking `grs.dbankcloud.com`?
What is the reason to block it or not to block it?

I have noticed that when blocking `grs.dbankcloud.com` then the `huawei` phone starts to use `grs.dbankcloud.cn`.
If I additionally block `grs.dbankcloud.cn`, beside `grs.dbankcloud.com`, then the  `huawei` phone starts to use `grs.dbankcloud.eu` and `grs.dbankcloud.asia`.

If I understand correctly the `dbankcloud.*` is the storage cloud for those Chinese androids. 

Just wonder what is your opinion/findings. 😄 
Cheers

**Comment by badmojr** [comment]
Here's what I've found! 😄
https://github.com/bremich/Blocklists/blob/master/pi-hole/health.txt

**Comment by crssi** [comment]
Thank you, 

I see all of them there: https://github.com/bremich/Blocklists/blob/7b574d149a91340014b17dde6b39f5ce97e9d32a/pi-hole/health.txt#L6-L9

Not saying that you should, but it would make a sense, or to add them all four, or to remove the current `grs.dbankcloud.com`?

**Comment by badmojr** [comment]
Careful what you wish for!! :)

**Comment by badmojr** [comment]
Just did! incoming update in 10,9 ...
Will unbreak if problems arise.

**Comment by 3xploiton3** [comment]
block this too

grs.dbankcloud.cn

**Comment by badmojr** [comment]
> grs.dbankcloud.cn

Currently blocked by Lite, Pro, & Xtra.

**Comment by sourcetf** [comment]
its huawei user track donain, just block is ok
