### ISSUE TITLE
add track.decacopy.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#107]
One for collection, I guess.

Kid has installed `decacopy` from `decacopy.com`... who would do that when we have this functionality already in Win10.

I think if not the `decacopy.com`, as highly unwanted app, is to be added, then at least `track.decacopy.com` should be.

![image](https://user-images.githubusercontent.com/17024151/110105661-93a16780-7da0-11eb-9ebe-cc4dd26adab9.png)

We do not want to risk sharing clipboard to anyone.

Cheers

**Comment by badmojr** [comment]
Done!
