### ISSUE TITLE
New list suggestions

### ISSUE THREAD

**Issue by Marek33** [badmojr/1Hosts#11]
I'm not sure, if these lists can be used, but since Energized, uses quite a lot of stuff from other lists, you could check these lists since they look quite good: Anti-WebMiner, MinerBlock list, Malwaredomains.com, malwaredomainlist.com and maybe the Shallalist (first two are probably dead, but last 3 are frequently updated). However, I have no idea, how is it, with the copyright, since this is just a suggestion, since I do have a lot of lists, which are not updated for a long time, but they are not used in your pack, where they probably should be.

Also, the blacklist.site has some great lists, from which I would definitely use the ransomware​​​​​ one, and probably other ones, but there seems to be quite a lot of false positives. The others are either not that important or too big like the malware list.

**Comment by badmojr** [comment]
> I'm not sure, if these lists can be used, but since Energized, uses quite a lot of stuff from other lists, you could check these lists since they look quite good: Anti-WebMiner, MinerBlock list, Malwaredomains.com, malwaredomainlist.com and maybe the Shallalist (first two are probably dead, but last 3 are frequently updated). However, I have no idea, how is it, with the copyright, since this is just a suggestion, since I do have a lot of lists, which are not updated for a long time, but they are not used in your pack, where they probably should be.
> 
Do you want them included in 1Hosts or in Energized Protection?
1Hosts (Pro) edition has Malwaredomains.com, malwaredomainlist, & some of the Shallalist filters.
More info, here:- https://github.com/badmojr/code41Hosts/blob/master/etc/config/sources
  
> Also, the blacklist.site has some great lists, from which I would definitely use the ransomware​​​​​ one, and probably other ones, but there seems to be quite a lot of **false positives**. The others are either not that important or too big like the malware list.
False positives? That's a red flag for me.

**Comment by Marek33** [comment]
In the 1Hosts, since the Energized Protection has over 40 active issues, so I'm waiting, till that is fixed, and then there could be new lists added.

Yes, but not the https://mirror1.malwaredomains.com/files/domains.hosts and https://www.malwaredomainlist.com/hostslist/ip.txt

The ransomware filter, is quite small, so it shouldn't have any false positive.

**Comment by badmojr** [comment]
> In the 1Hosts, since the Energized Protection has over 40 active issues, so I'm waiting, till that is fixed, and then there could be new lists added.
> 
> Yes, but not the https://mirror1.malwaredomains.com/files/domains.hosts and https://www.malwaredomainlist.com/hostslist/ip.txt
> 

domains.hosts is the same as justdomains, the former being in the hosts-file-syntax.

By default, anything that does not mach a domain gets ditched during the build process.
Adding the above IPs list is useless.

> The ransomware filter, is quite small, so it shouldn't have any false positive.

I’d appreciate a link to the file.

**Comment by Marek33** [comment]
I see, but why, when I disable those two filters, the number of network filters is lower?

Here: https://blocklist.site/app/dl/ransomware

**Comment by badmojr** [comment]
> I see, but why, when I disable those two filters, the number of network filters is lower?
> 

Some domains from that list probably didn’t end up in 1Hosts ‘coz of some legit reasons i.e dead, false positives, etc.

> Here: https://blocklist.site/app/dl/ransomware

404. Not Found!

**Comment by Marek33** [comment]
That's interesting, and thanks for the info!

It seems, that they removed it then.

**Comment by badmojr** [comment]
> That's interesting, and thanks for the info!
> 
> It seems, that they removed it then.

They seem to be migrating to GH.
The file is available again:- https://github.com/blocklistproject/Lists/commit/ddba5a18f6846618b897a420916d55a61bc3549a

**Comment by badmojr** [comment]
Done! Added.

**Comment by Marek33** [comment]
That's good to see, but I hope, that they will have less versions, since I had some issues with it, a few days ago. It was shortly after I suggested them to you, and it seems, that it was because of the old links, which I had.
