### ISSUE TITLE
Breakage due to ccmp.eu

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#113]
Not long ago you have listed `ccmp.eu` in 1Hosts Lite, which is used as a CNAME for online catalogues.
Working sample from affiliated email: `https://l.newsletter.lidl.com/rts/go2.aspx?h=35714&tp=i-1NGB-D6-pM-cMSp-1c-Qgk-1c-cHqo-l5nj5aAaDA-WBYSD&x=3184%7c9142819`

1. Would you be so kind and remove `ccmp.eu` ?
2. Would you be so kind to let me know from which up-stream source that breakage came from into your list.

Thank you ❤️

**Comment by badmojr** [comment]
**ccmp.eu** 
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tracking
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
https://secure.fanboy.co.nz/r/fanboy-ultimate.txt

**Comment by badmojr** [comment]
Will be removed from **Lite** only 'coz it does have s/th to do with email marketing & tracking.

**Comment by badmojr** [comment]
Fixed.
