### ISSUE TITLE
Add 2mdn.net to 1Hosts Pro and Lite

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#115]
Hi @badmojr 

Would you mind adding `2mdn.net` to Pro and Lite?
I found this domain quite prevalent among "my" users and haven't found any issues with blocking it in the last year.

The reason would be the same as is for `doubleclick.net` and `invitemedia.com` which are both blocked in Pro and Lite.
All 3... that is `2mdn.net`,`doubleclick.net` and `invitemedia.com` are joint together by `doubleclick.net` owned by Google.

See `https://whotracks.me/trackers/doubleclick.html`:
![2mdn net](https://user-images.githubusercontent.com/17024151/111910729-7afca700-8a5a-11eb-8c0e-9ff6b878aba6.PNG)

Cheers

**Comment by badmojr** [comment]
affects videos!
e.g: https://www.zdnet.com/video/the-first-amendment-vs-tech-giants-ray-wang-explains-your-digital-rights/

**Comment by crssi** [comment]
Thank you. First one I see that breaks.

**Comment by crssi** [comment]
It seems that this is not the case anymore. Or is it?

Cheers

**Comment by spirillen** [comment]
nice comments about this adware here https://mypdns.org/my-privacy-dns/matrix/-/issues/2470

Teaser
`hosts-sources$ git grep '2mdn.net' | cut -d : -f 2` To much to post here.

**Comment by crssi** [comment]
For some reason I get `Server Not Found` for `https://mypdns.org/my-privacy-dns/matrix/-/issues/2470`

Do we have any sample where blocking `2mdn.net` results with breakages?

**Comment by badmojr** [comment]
Try this:
https://www.zdnet.com/article/these-android-users-wanted-to-protect-their-phones-from-hackers-instead-they-downloaded-malware/

**Comment by crssi** [comment]
I see... It does not work in that case.
Closing issue.

Thank you ❤️
