### ISSUE TITLE
cdn.iubenda.com

### ISSUE THREAD

**Issue by scafroglia93** [badmojr/1Hosts#117]
it's possible block this crap and noisy domain ?

**Comment by badmojr** [comment]
https://github.com/nextdns/metadata/issues/527

Currently blocked on **Pro**, please upgrade as stated on the quickstart guide.

**Comment by scafroglia93** [comment]
pro it's contain too much FP for italian users.

It's break bank app like Fineco and Unicredit

**Comment by badmojr** [comment]
> pro it's contain too much FP for italian users.
> 
> It's break bank app like Fineco and Unicredit

Sorry! You gonna have to manually block the domain then.
