### ISSUE TITLE
[Whitelist] ipla.hit.stat24.com

### ISSUE THREAD

**Issue by FadeMind** [badmojr/1Hosts#119]
Hi
Please add 
```
ipla.hit.stat24.com
```
to whitelist.
WHEN domain is blocked video content on some polish sites with news cannot be played at all.

AFFECTED
`polsatnews.pl` videos based on `ipla.tv`  (`ipla.pluscdn.pl`)

Example: https://www.polsatnews.pl/wiadomosc/2021-04-02/kiedy-europa-bedzie-mogla-odetchnac-od-koronawirusa-andrzej-rys-w-gosciu-wydarzen/?ref=slider
Scroll down to player to see.
With unlocked domains play well:
![20210402-1617388464-001](https://user-images.githubusercontent.com/9846948/113443727-d5025280-93f2-11eb-8c13-b7945d62960a.png)

Regards

**Comment by badmojr** [comment]
Related to https://github.com/badmojr/1Hosts/issues/98
Site is implementing anti-adblock. Won't fix.

**Comment by badmojr** [comment]
usptream:-
http://abpvn.com/android/abpvn.txt
https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
http://adfree-hosts.odiousapps.com/adfree.php
https://filters.adtidy.org/extension/chromium/filters/15.txt
e.tc
