### ISSUE TITLE
Get3.adobe.com

### ISSUE THREAD

**Issue by Marek33** [badmojr/1Hosts#12]
Get3.adobe.com shouldn't be blocked, since that's the official place to get the Flash Player updates (even if the Flash will be finally dead in the next year).

**Comment by badmojr** [comment]
Please do provide a working URL where I can verify this.

**Comment by Marek33** [comment]
For example here: https://get.adobe.com/flashplayer/ 

The filter says that 1Hosts (Pro) blocks this: **||get3.adobe.com^**

**Comment by badmojr** [comment]
Fixed!
