### ISSUE TITLE
[whitelist] sgqcvfjvr.onet.pl 

### ISSUE THREAD

**Issue by FadeMind** [badmojr/1Hosts#120]
Hi
Please add 
```
sgqcvfjvr.onet.pl
```
to whitelist.
WHEN domain is blocked video content on some polish sites with news cannot be played at all.

AFFECTED
`vod.pl`

Example: https://vod.pl/programy-onetu/onet-opinie-renata-kim-dawid-ciermiega-104/jfdernq
Scroll down to player to see.
With unlocked domains play well:
![20210402-1617389166-001](https://user-images.githubusercontent.com/9846948/113444579-750cab80-93f4-11eb-92fe-4641443a2604.png)

Regards

EDIT:  `gapl.gemius.pl` does not need be unlocked for playing. Sorry.

**Comment by badmojr** [comment]
Same as https://github.com/badmojr/1Hosts/issues/119.
Can't help. Sorry!
