### ISSUE TITLE
Block spacex-live.site

### ISSUE THREAD

**Issue by cinatime** [badmojr/1Hosts#1213]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [x] mini
- [x] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:**

<br>

**Domains:**
```
spacex-live.site
```
<br>

**Details:**
YouTube live scam

title: SpaceX Launch Crew-6 Mission! Elon Musk gives update on Starship and Falcon Heavy!

chat: We are is hosting a big Giveaway
SpaceX ​ Double (2X) your BTC & ETH or DOGE within 3-5 minutes
SpaceX ​Hurry up: [http://spacex-live.site/](https://www.youtube.com/redirect?event=live_chat&redir_token=QUFFLUhqbl80RGEwbnpfNF9ySEplYktEV2tFbUhTbUtad3xBQ3Jtc0tuRjVENlZfTXJBaVhJdXQ2eGVCMHZTdFhoSGMtX0stdWJ3VDZ3TjdVXzB2aHlJNS1obTBxdl9yLTF6Y2dPalhUbC1pcUlVQ3ozSFhiZUNWbkQtYUZidDcxdDNhcnJ2S0E1UlFkM0tUQU91MTk1RjRxUQ&q=http%3A%2F%2Fspacex-live.site%2F)
SpaceX ​Over 780 BTC & 4,800 ETH have already been sent to live stream viewers.

YouTube channel: https://www.youtube.com/channel/UCkojgYfZwYQL0272xQ895lg

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by iam-py-test** [comment]
The domain seems dead and the account has been taken down. Guess these don't last long
