### ISSUE TITLE
Unblock ip.affiliate.dmm.com

### ISSUE THREAD

**Issue by khw15** [badmojr/1Hosts#1218]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
ip.affiliate.dmm.com
```
<br>

**Details:**
The domain is safe and doesn't get blocked by other blocklist. 

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Where does it interfere with normal site/app usage?
