### ISSUE TITLE
Android AGPS Domains blocked in Pro

### ISSUE THREAD

**Issue by GynThor** [badmojr/1Hosts#122]
I noticed there are a few sub-domains blocked that may affect the time/GPS accuracy on some phones:

 izatcloud.net
 xtracloud.net
 gpsonextra.net
 belong to Qualcomm. Android devices with Snapdragon processors will  connect to download aGPS data (so a lock is faster) and also use their time servers (time.izatcloud.net).

I guess it could be used for tracking, but blocking these domains may cause some problems for mobile users.

**Comment by badmojr** [comment]
Fixed!

**Comment by GynThor** [comment]
> Fixed!

Thanks 👍
