### ISSUE TITLE
syndication.twitter.com got back to 1Hosts Lite

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#124]
Hi @badmojr 

It looks like we have a regression of `syndication.twitter.com` in `1Hosts Lite`.

Once it was removed as you can see here https://github.com/badmojr/1Hosts/issues/79

Would you please remove it from Lite version?

Thank you in advance and cheers

p.s. Sorry that I have dragged you into"fire" last time, but couldn't resist to tell what I think about their "attacks" and hypocrisy

**Comment by badmojr** [comment]
Hopefully, this should be fixed for good.
Cheers!

That was fun ;) . Let's do it again soon :)

**Comment by crssi** [comment]
😄 

Speedy and reliable as usually. 👍 

Thank you, Cheers
