### ISSUE TITLE
Block "szzhonghengda.com"

### ISSUE THREAD

**Issue by WebworkrNet** [badmojr/1Hosts#1252]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [X] Pro
- [ ] Xtra
<br>

**Client:**
Blokada/Android

<br>

**Domains:**
```
szzhonghengda.com
```
<br>

**Details:**
Spam sender

![chrome_screenshot_1679773534313](https://user-images.githubusercontent.com/43509007/227738611-87071363-c684-43a1-bcd5-fa28ced78bc9.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by cinatime** [comment]
1host seems to be dead for now if you like you can make an issue in [hagezi blacklist](https://github.com/hagezi/dns-blocklists)

**Comment by WebworkrNet** [comment]
> 1host seems to be dead for now if you like you can make an issue in [hagezi blacklist](https://github.com/hagezi/dns-blocklists)

As far as I can see, the _hagezi blacklist_ is not available for [Blokada](https://github.com/blokadaorg/blokada).
