### ISSUE TITLE
Google Datamixer

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#1254]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
datamixer-pa.googleapis.com
```
<br>

**Details:**
It is part of the Google Analytics data processing. It is used to collect, process, and aggregate data, and specifically data from Google Analytics for Firebase.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
What does that even mean?
