### ISSUE TITLE
False Positive Report skiff.com

### ISSUE THREAD

**Issue by nishils** [badmojr/1Hosts#1257]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [X] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
skiff.com
app.skiff.com
api.skiff.com
relay-proxy.skiff.com
```
<br>

**Details:**
Skiff is an end to end encrypted workspace collaboration suite. I don't understand why it would be added to these lists but it should be removed.

They provide e2ee email, calendar, document collaboration, and cloud storage products.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by amilich** [comment]
+1

**Comment by TheHolyTachanka** [comment]
+1
