### ISSUE TITLE
misblocked sites

### ISSUE THREAD

**Issue by Lky777** [badmojr/1Hosts#1266]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x ] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
adblock plus

<br>

**Domains:**
```
qulishi.com
m.qulishi.com
www.qulishi.com
openinstall.io
```
<br>

**Details:**
1."qulishi.com" is a normal site on Chinese history.
2."openinstall.io" is a normal site which used for download apps.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
openinstall.io - seems problematic. Will stay blocked!
