### ISSUE TITLE
[Obsolete block] digits.com

### ISSUE THREAD

**Issue by bmhatfield** [badmojr/1Hosts#130]
Hi there,

While reviewing adblock lists our domain shows up on, I found 1Hosts/1Hosts Mini. 

Although digits.com was once used as a web counter (in the late 90s/early 2000s), it is no longer used for any such purpose (at least 5 years). Please remove `digits.com` and `www.digits.com` from your blocklist.

Thank you!

**Comment by badmojr** [comment]
Done!

**Comment by bmhatfield** [comment]
Thank you!
