### ISSUE TITLE
Block "kfbecbpjgi.masoud.cloud"

### ISSUE THREAD

**Issue by WebworkrNet** [badmojr/1Hosts#1302]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [X] Pro
- [ ] Xtra
<br>

**Client:**
Blokada/Android

<br>

**Domains:**
```
kfbecbpjgi.masoud.cloud
```
<br>

**Details:**

Malicious/Spam

https://www.virustotal.com/gui/url/b3e647d7b1d33a1e5da2d1baefafc79f4bb1252bfbabbb6d27e5883f17c8534b?nocache=1

![chrome_screenshot_1680651493701](https://user-images.githubusercontent.com/43509007/229945557-204a108b-6672-448b-9cb9-22ac1f595d56.png)

`https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkfbecbpjgi.masoud.cloud%2FuPihceQTQm%3Fq%3D1200397661%26id%3D206&data=05%7C01%7C%7C46fd176bb3794945d19708db34f36095%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638161992124385699%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MdGyvoMe6dPOOgIdwOVw8heQjgpoUt9zs1%2BalbeE2LA%3D&reserved=0`

`https://kfbecbpjgi.masoud.cloud/uPihceQTQm?q=1200397661&id=206
`

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Domain seems to be inactive.
