### ISSUE TITLE
Check "gos-api.gos-gsp.io"

### ISSUE THREAD

**Issue by WebworkrNet** [badmojr/1Hosts#1305]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [X] Pro
- [ ] Xtra
<br>

**Client:**
Blokada/Android

<br>

**Domains:**
```
gos-api.gos-gsp.io
```
<br>

**Details:**

The *.gos-gsp.io domain is associated with the Samsung application.

- https://www.netify.ai/resources/applications/samsung
- https://www.netify.ai/resources/domains/gos-gsp.io

I suspect that the addition to the blacklist is recent. Without activating the URL, the TV app "_Zattoo_" no longer runs.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Seems sketchy.
Ref: https://doi.org/10.1371/journal.pone.0279942.s002

**Comment by WebworkrNet** [comment]
I withdraw my question and my objection. In the meantime, it has turned out that the cause was elsewhere. I was not quick enough to close this ticket in time.
