### ISSUE TITLE
Maintainer Update: Competing Demands Causing Maintenance Slowdown

### ISSUE THREAD

**Issue by badmojr** [badmojr/1Hosts#1307]
Dear Community,

I wanted to provide you with an update regarding the maintenance of this repo. As the sole maintainer, I regret to inform you that I will not be able to address issues as quickly as before due to competing demands on my time.

While I will do my utmost to attend to any critical issues, I cannot promise the same level of support as before.
I understand that this may be frustrating for some of you, and I apologize for any inconvenience caused.

Thank you for your understanding and continued support.

Sincerely,

badmojr

**Comment by spirillen** [comment]
If you like I can help you with the commits that I add to my own project. Regarding "whitelisting", well there you would be on your "own", as you know, I believes that [whitelisting is a personal choice](https://github.com/mypdns/matrix?tab=readme-ov-file#faq), not a community obligation.

**Comment by d-Rickyy-b** [comment]
Hey @badmojr, if you need help maintaining these lists, feel free to contact me. I'd be happy to help out with all the open issues

**Comment by fakeboboliu** [comment]
> If you like I can help you with the commits that I add to my own project. Regarding "whitelisting", well there you would be on your "own", as you know, I believes that [whitelisting is a personal choice](https://github.com/mypdns/matrix/blob/a1e59f5b7c844e809fe810cee4d2dff3842ddb31/README.md?plain=1#L147-L160), not a community obligation.

You're right, it comes down to the user's choices. But let's be real, this ruleset is super popular and a lot of people just blindly trust it.  Especially those who learn by watching random YouTube tutorials – they might not even realize this is what's causing their issues.

It would be helpful if there was a heads-up somewhere that this thing isn't being maintained as much, and maybe a reminder to set up a whitelist.

**Comment by spirillen** [comment]
@fakeboboliu why are you writing all this in attention to me? this is nothing new to me, and I've been doing this for decades..

So I'm a bit confused here.

**Comment by fakeboboliu** [comment]
@spirillen My bad for jumping in like that. I think I misread your message.

Just wanted to say that since this repo is popular and out there in the open, any changes could affect a ton of users. So, that whitelist is gonna be super important.
