### ISSUE TITLE
Block `ko.gl`

### ISSUE THREAD

**Issue by WebworkrNet** [badmojr/1Hosts#1321]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
Blokada/Android

<br>

**Domains:**
```
ko.gl
```
<br>

**Details:**
- Malicious
- Phishing

https://www.virustotal.com/gui/domain/ko.gl

`https://ko.gl/qdKZT`
https://www.virustotal.com/gui/url/22e4d0eb99419ee6042308c982bf861fbbde23f47f75d5acb04a0a53f9871011

![chrome_screenshot_1681587348782](https://user-images.githubusercontent.com/43509007/232250371-5cee1b1f-0b21-466b-8088-aea4cf708d9a.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Ko.gl is a URL link shortening tool.
