### ISSUE TITLE
Block `api.giphy.com`

### ISSUE THREAD

**Issue by WebworkrNet** [badmojr/1Hosts#1328]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [X] Pro
- [ ] Xtra
<br>

**Client:**
Blokada/Android

<br>

**Domains:**
```
api.giphy.com
```
<br>

**Details:**
GIPHY Analytics, part of Facebook

https://reports.exodus-privacy.eu.org/en/trackers/299/

`pingback.giphy.com` is already blocked.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
That API endpoint is used for displaying gifs.
The tracking domain above is the only that can be blocked without negatively affecting UX.

https://developers.giphy.com/docs/api#endpoint
