### ISSUE TITLE
Issues with Mojeek website

### ISSUE THREAD

**Issue by scorpioraj** [badmojr/1Hosts#136]
Mojeek search engine is not working with any of these three links. Even images are not displayed. In fact the whole website is not properly displayed. Can you please have a look into this

Also, to add into Ublock origin, which file I should use from the below mentioned files

https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/xtra/adblock.txt
https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/xtra/domains.txt
https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/xtra/wildcards.txt

Please update

Thanks

**Comment by scorpioraj** [comment]
Swisscows search engine also is not working with any of these three links. Even images are not displayed. When you search for any image, the pages instantly disappears within split seconds and all I see is a blank page on the images section.

The normal home page is also not displayed. I had to make changes in the Ublock Origin and Umatrix to gain access to SwissCows.

Mojeek is not at all working because of these 3 lists.

 Can you please have a look into this


https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/xtra/adblock.txt
https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/xtra/domains.txt
https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/xtra/wildcards.txt

Please update

Thanks

**Comment by badmojr** [comment]
Fixed!

**Comment by badmojr** [comment]
Hey, @scorpioraj
You can now use [Xtra](https://hosts.netlify.app/Xtra/adblock.txt) as a pack.
See:- https://hosts.netlify.app/

**Comment by scorpioraj** [comment]
1Hosts (Xtra) is giving problems in Threadreaderapp website. It completely
breaks the site. Please look into this


[image: image.png]

[image: image.png]
[image: image.png]
[image: image.png]



The page should be actually coming like this

[image: image.png]

Please do reactify this

Thanks



Regards,
Raj
***@***.***

**Comment by scorpioraj** [comment]
Has the threadreaderapp issue been resolved?. Please let me know.
Thanks

Regards,
Raj
***@***.***

**Comment by badmojr** [comment]
Yeah! Fixed.
