### ISSUE TITLE
Block `hdraa.duckdns.org`

### ISSUE THREAD

**Issue by WebworkrNet** [badmojr/1Hosts#1382]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [X] Pro
- [ ] Xtra
<br>

**Client:**
Blokada/Android

<br>

**Domains:**
```
hdraa.duckdns.org
```
<br>

**Details:**
Spam

- `http://hdraa.duckdns.org/etyjhkjh.html`
- `http://hdraa.duckdns.org/4/9845/36760/CNBhNRbxpu.jpg`
- `http://hdraa.duckdns.org/4/9845/36760/UhLTyQDqDQ.jpg`

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by cotusandro** [comment]
@WebworkrNet do you have some kind of mental illness? I have noticed that you open new issue everyday related to some *.duckdns.org. If this is not the case either stop creating this nonsense or make your own personal blocklist.

**Comment by WebworkrNet** [comment]
Can we agree to have a factual conversation and refrain from insults and the like?
