### ISSUE TITLE
DotDigital URLs blocked

### ISSUE THREAD

**Issue by ed4m4s** [badmojr/1Hosts#14]
Hi,

Hope you are well. 
Will it be possible to let me know as to why you have added some of the domains with regards Dotdigital on the domains.txt list and if those can be taken out? 

Domains in question:
1) dotdigital.com
2) leadvision.dotmailer.co.uk 
3) dotmailer-surveys.com

Thanks

**Comment by badmojr** [comment]
Hello,

The domains above originate from a couple of sourced  block/filter lists below:/

https://github.com/badmojr/code41Hosts/blob/master/etc/origin/abp%2B/Fanboy
https://github.com/badmojr/code41Hosts/blob/master/etc/origin/abp%2B/AdGDnS
https://github.com/badmojr/code41Hosts/blob/master/etc/origin/Ad/nxfilter

My best guess is they were listed because of being related to marketing of some sort.
Yes, they can be taken out:- any reason(s)/motivation(s) they should be removed?

**Comment by ed4m4s** [comment]
Hi,

Thanks for getting back. 
Those domains have nothing to do with advertising or tracking. It looks like this is a false positive, since the domains are owned and operated by genuine company. 

Can you exclude/whitelist the domain from your lists?

Thanks

**Comment by badmojr** [comment]
Being “owned and operated by a genuine company” isn’t a valid reason to warrant removal.
Why do you required them unblocked/removed?
Do they break certain functionality?

**Comment by ed4m4s** [comment]
They do break the functionality of our product if customers are using this list. 
Thank you

**Comment by badmojr** [comment]
Whick product are you refering to?

**Comment by ed4m4s** [comment]
I am referring to the product that Dotdigital company is providing to its customers.

**Comment by badmojr** [comment]
I aint interested in doing research on what company Dotdigital is.
If you can’t provide enough details, I’m afraid that this is gonna stay unresolved.

**Comment by badmojr** [comment]
*dotdigital.com* isn’t listed by the upstream source(s) anymore.
The rest still are..

**Comment by Jaden-J** [comment]
Can you please remove the following URL from the list,
www.bookdepository.com
www.abebooks.de

Genuine sites to buy books but this filter won't allow the login portal to open.

**Comment by badmojr** [comment]
> Can you please remove the following URL from the list,
> [www.bookdepository.com](http://www.bookdepository.com)
> [www.abebooks.de](http://www.abebooks.de)
> 
> Genuine sites to buy books but this filter won't allow the login portal to open.

Done!!
