### ISSUE TITLE
few false positive in Xtra

### ISSUE THREAD

**Issue by thomasmiddleton22** [badmojr/1Hosts#141]
found few false positive in Xtra

unblockit.onl - unblocker site, allows access to blocked torrent/ streaming services.

gog-games.com - site to download gog games for free.

adoptopenjdk.net - used to download java (open JDK Binaries)

steamunlocked.net - site to download steam games. 

b-ok.asia - mirror of Zlib/Libgen

fivebooks.com - books recommended by authors

aidungeon.io - a dungeons & dragons games, based on ai 

gametrex.com - site to download games

**Comment by badmojr** [comment]
That fast, huh! :)
Fixed.
