### ISSUE TITLE
www.vdma.org

### ISSUE THREAD

**Issue by juergen852** [badmojr/1Hosts#144]
Founded in 1892, the VDMA is today the most important voice of the mechanical engineering industry.
Having around 3,300 members makes the VDMA the largest network organization in the European mechanical engineering industry. The association represents the shared economic, technological and scientific interests of this diverse industry.

Why are they blocked in Xtra?

Match found in https://badmojr.github.io/1Hosts/Xtra/hosts.txt:
   vdma.org 
   www.vdma.org 

VDMA e. V.

Lyoner Str. 18
60528 Frankfurt

Postfach 71 08 64
60498 Frankfurt

Telefon +49 69 66 03 0
Fax +49 69 66 03 15 11

E-Mail kommunikation@vdma.org
Internet http://www.vdma.org
Das Impressum gilt auch für folgende Onlinepräsenzen. LinkedIn, Twitter, Facebook, Youtube

Präsident Karl Haeusgen

Hauptgeschäftsführer Thilo Brodtmann

Vereinsregister beim Amtsgericht Frankfurt am Main, Nr. VR4278

Inhaltlicher Verantwortlicher nach § 55 Abs. 2 RStV

Holger Paul, VDMA, Lyoner Str. 18, 60528 Frankfurt

**Comment by badmojr** [comment]
Fixed. Thanks!
