### ISSUE TITLE
c.cintnetworks.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#145]
Hi @badmojr 

I don't know where my folks find those but they do. 😄 

`c.cintnetworks.com` falls in the same category as https://github.com/badmojr/1Hosts/issues/137

I guess it should be removed from `Lite`, but will follow your wisdom. 😉 

Cheers ❤️

**Comment by badmojr** [comment]
You got a page where this domain is used?
I'd like to recheck.

**Comment by crssi** [comment]
Sure... this is exact URL my folks got over email `http://survey.marketagent.com/CEP/Entry?CPID=1580523&IDF=e5004382-7e89-af31-d153-742b3aa4b45a&Y=1`

But if you open it now, it says that survey has ended or it was already being taken.

Cheers

**Comment by badmojr** [comment]
Fixed!
