### ISSUE TITLE
r3.o.lencr.org and sqgz.veloxity.net

### ISSUE THREAD

**Issue by baronexy** [badmojr/1Hosts#146]
random.veloxity.net E.G: sqgz.veloxity.net, dacs.veloxity.net (VSKOR calculates credit score without using financial data for unbanked/underbanked individuals which make up more than 30% of adult population.) IS A TRACKER

r3.o.lencr.org (redirect virus, ads)

**Comment by badmojr** [comment]
**r3.o.lencr.org**: won't add re: https://letsencrypt.org/docs/lencr.org/

Veloxity currently blocked by Xtra. will add on Pro soon.
