### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by baronexy** [badmojr/1Hosts#149]
spotify crash: ap.spotify.com
spotify music list disabled:  audio-ak-spotify-com.akamaized.net
google play store not downloading: xxx-x-xxx.gvt1.com
general mobile android9: sqgz.generalmobile.com like sqgz.veloxity.net(I reported this before, now it is blacklisted.)
google play store does not update or download the application.
I added them to my whitelist and the issues were resolved.

**Comment by badmojr** [comment]
*.gvt1.com isn't listed on any of the lists.

The rest originate from the lists; https://github.com/DRSDavidSoft/additional-hosts.
@DRSDavidSoft what's your take on this?

**Comment by baronexy** [comment]
That's right it's not on your list.

**Comment by DRSDavidSoft** [comment]
Thanks for asking my opinion!
- `gvt1.com` is _NOT_ blocked in my lists, and it **should not** be (breaks auto-update and some other required functionality in both Chrome and Google Play).
    - It should be whitelisted, provided that `google.com` is not blocked (for privacy reasons). It servers no ads.
 - `ap.spotify.com` is in my **whitelist**, not blocked by my blacklist. Required for Spotify's native app to work
 - `audio-ak-spotify-com.akamaized.net` is **blocked** in my list. I have zero interference with this being the case, I can confirm that the Spotify's native and web app work and function properly on both my Windows and Android devices, without an issue.
     - My verdict: it should be blocked. Also recommended by @opus-x
 - `sqgz.generalmobile.com` / `sqgz.veloxity.net`: no idea, I've never seen them in my logs. The first one seems to be related to a Turkish operator (Merhaba, friend). The other one seems to be banking-related.
     - Both resolves to `40.85.255.251`, currently not blocked in my blacklist (I haven't updated it since a couple of weeks ago).
     - According to @lightswitch05's tool, only the second domain [`sqgz.veloxity.net`](https://blocklist-tools.developerdan.com/entries/search?q=sqgz.veloxity.net) is blocked, and only in *Unified* edition of Energized.
     - My verdict: more research needed, probably needs to be blocked.

Hopefully, this was helpful! 😄

**Comment by badmojr** [comment]
Hey, @DRSDavidSoft 
The CNAME for ap.spotify.com is **ap.gslb.spotify.com**, which is what's included in your list.

sqgz.veloxity.net is a tracker & is rightfully blocked. Energized Unified sources that domain from 1Hosts (Pro).

Thanks!

**Comment by baronexy** [comment]
But this is a tracker : sqgz.generalmobile.com (This is currently on my blacklist, you can add it to your filter if you want.)
Thanks for everything.

**Comment by DRSDavidSoft** [comment]
@badmojr Oh, I'm sorry that I failed to see that. The CNAME domain has been removed (https://github.com/DRSDavidSoft/additional-hosts/commit/12dbf483af242d0e383572b15dcaf5cec40a89fb), thanks for the report!

@baronexy Where would one find your blacklist? I'm interested to use it on my personal server, but can't find it anywhere.

@badmojr I used to use the Unified EP, however as it also blocked many adult websites, the users complained to me, so I had to removed.  I'm using 1Hosts Pro directly, so I should have that domain on my personal blacklist.

Thanks for informing me!

**Comment by baronexy** [comment]
> @badmojr Oh, I'm sorry that I failed to see that. The CNAME domain has been removed ([DRSDavidSoft/additional-hosts@12dbf48](https://github.com/DRSDavidSoft/additional-hosts/commit/12dbf483af242d0e383572b15dcaf5cec40a89fb)), thanks for the report!
> 
> @baronexy Where would one find your blacklist? I'm interested to use it on my personal server, but can't find it anywhere.
> 
> @badmojr I used to use the Unified EP, however as it also blocked many adult websites, the users complained to me, so I had to remove it. I'm using 1Hosts Pro directly, so I should have that domain on my personal blacklist.
> 
> Thanks for informing me!

my blacklist from NextDNS

kaspersky vpn android app (s.symcd.com from 1hosts pro but one more s.symcb.com this is not listed)

**Comment by baronexy** [comment]
> > But this is a tracker : sqgz.generalmobile.com (This is currently on my blacklist, you can add it to your filter if you want.)
> > Thanks for everything.
> 
> Where did you find it?

General Mobile GM8 Android 9 Telephone

**Comment by badmojr** [comment]
> > @badmojr Oh, I'm sorry that I failed to see that. The CNAME domain has been removed ([DRSDavidSoft/additional-hosts@12dbf48](https://github.com/DRSDavidSoft/additional-hosts/commit/12dbf483af242d0e383572b15dcaf5cec40a89fb)), thanks for the report!
> > @baronexy Where would one find your blacklist? I'm interested to use it on my personal server, but can't find it anywhere.
> > @badmojr I used to use the Unified EP, however as it also blocked many adult websites, the users complained to me, so I had to remove it. I'm using 1Hosts Pro directly, so I should have that domain on my personal blacklist.
> > Thanks for informing me!
> 
> my blacklist from NextDNS
> 
> kaspersky vpn android app (s.symcd.com from 1hosts pro but one more s.symcb.com this is not listed)

**s.symcd.com** isn't blocked by it's CNAME surely is.

**Comment by baronexy** [comment]
analytics.kkb.com.tr (credit score tracker)

**Comment by DRSDavidSoft** [comment]
@badmojr I have thse in my whitelist:
```
symcd.com
s.symcd.com
sw.symcd.com
```

There are reasons one would want to block OCSP/CRL endpoints:
 - _Can_ be used to track the user (the same way external `favicon.ico`s can be uses, I guess)
     - This works because the certificate of each website the user visits is validated against these files
 - _Might_ break jailbreak and/or some pirated apps
     - e.g. an ex-valid certificate that is used is revoked by the manufacturer or developer, thus breaking the jailbreak/cracked app

Personally, none of these reasons are applicable to the server I run, so I haven't blocked them.  In fact, if these domains (and some others, e.g. [this crl.txt](https://github.com/zeffy/dnscrypt-lists/blob/master/whitelists/crl.txt)) are blocked, the certificate will either fail to verify, or it takes a long time on some OSes (such as Windows) to validate.  Since I'm not aware of any other reason these should be blocked, I've whitelisted them.

**Comment by badmojr** [comment]
@DRSDavidSoft 
In this case too you have the above domains' CNAMEs blocked.
`e8218.dscb1.akamaiedge.net`

**Comment by DRSDavidSoft** [comment]
@badmojr Good call, I removed it plus some other similar domains.  I'll have to validate other records as well.

In the meantime, is there any other record that might need to be removed from my list?

**Comment by badmojr** [comment]
> @badmojr Good call, I removed it plus some other similar domains. I'll have to validate other records as well.
> 
> In the meantime, is there any other record that might need to be removed from my list?

Nope! So far so good.
Will definately ping you when they do.
