### ISSUE TITLE
false positive connect.facebook.net

### ISSUE THREAD

**Issue by Uranite** [badmojr/1Hosts#151]
for facebook comments
example site: https://readmanganato.com/manga-lf988940
scroll down and ull see the comment is gone

**Comment by badmojr** [comment]
We've had this discussion before @ https://github.com/badmojr/1Hosts/issues/30.
Pinging @crssi for input regarding this.

**Comment by crssi** [comment]
I have tried the OP example site with Firefox, Edge and Brave without any blocking (ADS and DNS, all caches cleared) and the FB comments still does not work.

I would say this is a false request and the problem is on the site itself.

What is your observation?

Cheers

**Comment by Uranite** [comment]
i think its also the problem on the site itself, after it getting blocked and put on the allowlist for some reason it doesnt even call for the connect.facebook.net domain and i had to disable the app im using for dns blocklist and refresh the website and reenable it again for the comment to show. but im pretty sure connect.facebook.net is preventing the comment from showing

**Comment by badmojr** [comment]
> I have tried the OP example site with Firefox, Edge and Brave without any blocking (ADS and DNS, all caches cleared) and the FB comments still does not work.
> 
> I would say this is a false request and the problem is on the site itself.
> 
> What is your observation?
> 
> Cheers

After a couple of experiments, I can confirm the domain is needed for the comments to show up.

**Comment by badmojr** [comment]
Hey, @Uranite 
Which list do you use?

**Comment by Uranite** [comment]
> Hey, @Uranite 
> Which list do you use?

1hosts lite

**Comment by badmojr** [comment]
Will exclude this from Lite & will continue to block it on Pro.
Thanks @crssi .
Cheers.

**Comment by crssi** [comment]
No problem @badmojr , but funny is that I cannot replicate here and whatever I do the FB comments just doesn't work in this site.
Maybe is GeoIP related?

**Comment by badmojr** [comment]
Nope! Might have to do with caches; both browsers & adblock client.

**Comment by crssi** [comment]
Nah... tried on a friends computer at her place... vanilla browser, nothing cached, no blocking at the browser level, not OS level and also not at the network level.

**Comment by badmojr** [comment]
Which vanilla browser?

**Comment by crssi** [comment]
I meant any browser that is in original form, without any modifications and without any addon. In this case were used Firefox, Chrome, Opera, Brave.

See vanilla definition: https://en.wikipedia.org/wiki/Vanilla_software

😉 

Cheers

**Comment by badmojr** [comment]
Oh! How about that browser's inbuilt (adblock) protection, third-party cookies blocking, etc?
Checked?

**Comment by Uranite** [comment]
chrome://net-internals/#dns
chrome is using its own cache not operating system cache i think

**Comment by crssi** [comment]
I know its late, but anyway. Just have a feeling that I am in debt to return the info.

Today I have tried again and I can reproduce now here too.

Cheers
