### ISSUE TITLE
new lists

### ISSUE THREAD

**Issue by scafroglia93** [badmojr/1Hosts#153]
- https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt
- https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-personal.txt
- https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list

**Comment by scafroglia93** [comment]
-https://raw.githubusercontent.com/hpthreatresearch/iocs/main/TA551/domains.txt
- https://github.com/hpthreatresearch/iocs/blob/main/gootloader/urls.txt
- https://github.com/hpthreatresearch/iocs/blob/main/hancitor/urls.txt

**Comment by scafroglia93** [comment]
https://github.com/marco-acorte/antispam-it/blob/main/antispam-it.txt

**Comment by badmojr** [comment]
These are well-suited for dns services such as NextDNS where the're no limits to the number of rules/domains.
Won't be including them. Sorry!
