### ISSUE TITLE
I found more tracking domains inside of Grammarly.

### ISSUE THREAD

**Issue by MrWaste** [badmojr/1Hosts#156]
# Found From f-log-editor-debug.grammarly.io  Website: https://threatintelligenceplatform.com/report/f-log-editor-debug.grammarly.io/wyzUoORAhx

f-log-editor-debug.grammarly.io
f-log-at.grammarly.io
f-log-balto.grammarly.io
f-log-csp.grammarly.io
f-log-editor.grammarly.io
f-log-extension.grammarly.io
f-log-js-plugin.grammarly.io
f-log-mac-extension.grammarly.io
f-log-mobile-ios.grammarly.io
ec2-52-21-152-200.compute-1.amazonaws.com
ec2-107-23-202-169.compute-1.amazonaws.com
ec2-54-86-111-163.compute-1.amazonaws.com
ec2-52-72-165-80.compute-1.amazonaws.com
ec2-52-20-187-139.compute-1.amazonaws.com
ec2-54-87-110-85.compute-1.amazonaws.com
f-log-mobile.grammarly.io
ec2-54-81-133-1.compute-1.amazonaws.com
f-log-pl.grammarly.io
f-log-officeaddin.grammarly.io
ec2-3-208-239-138.compute-1.amazonaws.com
f-log.grammarly.io
f-log-officeaddinjs.grammarly.io
f-log-win-extension.grammarly.io
f-log-test.grammarly.io
f-log-wrex.grammarly.io
f-log-features-ci.grammarly.io
f-log-editor-debug.grammarly.io

I have my own block list of uncommon domains but still tracks users. I these are the new domains I just found today. The others are in my list somewhere as well as other tracking domains.

https://github.com/MrWaste/Ad-BlockList-2019-08-31/blob/master/Pi-Hole%20BackUps/Black%20List/All%20Server%20Black%20List

**Comment by badmojr** [comment]
Done https://github.com/badmojr/1Hosts/commit/01b7286cd45973c89e1fc88f5c252f50a9d7de92 !
