### ISSUE TITLE
cerberusapp.com www.cerberusapp.com

### ISSUE THREAD

**Issue by p1r473** [badmojr/1Hosts#159]
Hi,
This is an Android 'track lost phone' software and is not malicious
Thanks

Ive noticed a lot of new false positives recently- did you add a new source to the inputs?

**Comment by badmojr** [comment]
Hello.
It originates from: https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Malware#L2471
cc: @ShadowWhisperer

**Comment by badmojr** [comment]
> Ive noticed a lot of new false positives recently- did you add a new source to the inputs?

Every single source/asset used can be found [here](https://github.com/badmojr/1Hosts/blob/master/statics/assets.txt).

**Comment by p1r473** [comment]
> > Ive noticed a lot of new false positives recently- did you add a new source to the inputs?
> 
> Every single source/asset used can be found [here](https://github.com/badmojr/1Hosts/blob/master/statics/assets.txt).

Just FYI you have a lot of dead sources

**Comment by badmojr** [comment]
> > > Ive noticed a lot of new false positives recently- did you add a new source to the inputs?
> > 
> > 
> > Every single source/asset used can be found [here](https://github.com/badmojr/1Hosts/blob/master/statics/assets.txt).
> 
> Just FYI you have a lot of dead sources

Which dead sources?

**Comment by p1r473** [comment]
> > > > Ive noticed a lot of new false positives recently- did you add a new source to the inputs?
> > > 
> > > 
> > > Every single source/asset used can be found [here](https://github.com/badmojr/1Hosts/blob/master/statics/assets.txt).
> > 
> > 
> > Just FYI you have a lot of dead sources
> 
> Which dead sources?

I went through your sources and about 10% of them were 404

Old gits, etc.

**Comment by badmojr** [comment]
I am aware. Planning on fixing that when I've got enough time.

**Comment by p1r473** [comment]
Feel free to use my adlist its curated
https://github.com/p1r473/hosts/blob/master/adlists.txt

**Comment by badmojr** [comment]
> Feel free to use my adlist its curated
> https://github.com/p1r473/hosts/blob/master/adlists.txt

All known & previously thoroughly tested. 
Unfortunately, they never made the cut.
