### ISSUE TITLE
Ubuntu mirrors not working

### ISSUE THREAD

**Issue by Kai-s-cmd** [badmojr/1Hosts#1596]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
mirror.cc.vt.edu
mirror.nodesdirect.com
mirror.cepatcloud.id
mirror.logol.ru
mirror.transip.net
```
<br>

**Details:**
Can't update my OS "sudo apt update" because of domains above are banning.

![image](https://github.com/badmojr/1Hosts/assets/93368311/54f35c0a-d63e-4da1-9a8c-79c11880b57f)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
Because you should have the ip locally addressed, since node are using a lot of DNS tracking and redirects. This is just another case where #RPZ wins over RFC:952 and RFC:953

Meaning, it would be wrong to delist these records, but right to at the IP of the destinations

**Comment by Kai-s-cmd** [comment]
One still blocked

![image](https://github.com/badmojr/1Hosts/assets/93368311/05dd5c1d-6e82-40a5-b9b8-9fb3baaf19c0)

![Screenshot from 2023-10-16 13-13-15](https://github.com/badmojr/1Hosts/assets/93368311/34e79ba0-5fa0-4493-8527-2b10b2d96d9d)

**Comment by Kai-s-cmd** [comment]
Thanks its work now.
