### ISSUE TITLE
res.wx.qq.com was blocked, which breaks wechat.com severely

### ISSUE THREAD

**Issue by David-H-1** [badmojr/1Hosts#16]
This domain is essential to load wechat.com and all *.wx.qq.com domains. This is a legitimate domain please remove from blocklist
![image](https://user-images.githubusercontent.com/60801469/88089409-73a79580-cb7b-11ea-8a3d-6906a4051770.png)
This is what the webpage wechat.com looks like because that domain is blocked. I cannot click any of those links to download WeChat chatting software. The whole layout is broken.

**Comment by badmojr** [comment]
Fixed! Thanks.
