### ISSUE TITLE
*.easycontrols.net is false positive

### ISSUE THREAD

**Issue by juergen852** [badmojr/1Hosts#162]
Match found in https://badmojr.github.io/1Hosts/Xtra/hosts.txt:
   easycontrols.net 
   status.easycontrols.net 

*.easycontrols.net is provided by Helios Ventilatoren GmbH for their customers.
It allows customers to remote control their ventilation devices and to collect performance-data of their devices.

Communication to easycontrols.net can be completely switched off by customer (by using a single software-switch) on the ventilation device itself, so no need to block it.

Please unblock to avoid customer complaints.

**Comment by badmojr** [comment]
Fixed.
