### ISSUE TITLE
Unblock simplex.im 

### ISSUE THREAD

**Issue by epoberezkin** [badmojr/1Hosts#1653]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**

RethinkDNS

<br>

**Domains:**
```
simplex.im
```
<br>

**Details:**

Currently it is in this list: https://github.com/badmojr/1Hosts/blob/master/Xtra/domains.wildcards

This is the domain name of the preset servers for SimpleX Chat (https://simplex.chat)

Can you please let me know why/remove?

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by epoberezkin** [comment]
@cybeleroma thank you!

**Comment by y1111** [comment]
its still in the list by now
