### ISSUE TITLE
trust.zone

### ISSUE THREAD

**Issue by kzshantonu** [badmojr/1Hosts#166]
Is a legitimate VPN service provider

**Comment by badmojr** [comment]
Originates from:-
https://github.com/12425/adblist/raw/master/adbhost.txt : @12425
https://asc.hk/adplus.txt
https://raw.github.com/anudeepND/blacklist/master/adservers.txt : @anudeepND
https://raw.githubusercontent.com/bjornstar/hosts/master/hosts : @bjornstar

verdict:
S/th shady is goin' on with this domain.
Furthur investigation needed.

**Comment by 12425** [comment]
Mine comes from energized-spark.
https://block.energized.pro/

**Comment by kzshantonu** [comment]
It happens to be a less-than-mediocre VPN, judging from the play/appstore reviews

**Comment by badmojr** [comment]
ok! Should be fixed by now.

Cheers!
