### ISSUE TITLE
All upstream DNS down since Feb 1st?

### ISSUE THREAD

**Issue by thomasmerz** [badmojr/1Hosts#1678]
According to my dnsping-monitoring from different locations (vodafone at my home, hetzner in NBG, FSN and HEL) it seems that your upstream DNS servers 76.76.2.38 and 76.76.2.39 are down/not responding anymore since Feb, 1st:

https://thomasmerz.github.io/dnspingtest_rrd_ka/dashboard_month.html
https://thomasmerz.github.io/dnspingtest_rrd_nbg/dashboard_month.html
https://thomasmerz.github.io/dnspingtest_rrd_fsn/dashboard_month.html
https://thomasmerz.github.io/dnspingtest_rrd_hel/dashboard_month.html

https://o0.pages.dev/ also says "status: Unable to check!"

A quick test with the other DNS servers (`dnsping -s 76.76.10.38 web.de`) did also timeout…

Can you please check or give feedback? Thanks :)

**Comment by hagezi** [comment]
@thomasmerz 

These are not 1Hosts servers, but ControlD free servers: https://docs.controld.com/docs/free-dns

They work ...

```
dig @76.76.10.38 web.de
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.16.44-Debian <<>> @76.76.10.38 web.de
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54625
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;web.de.                                IN      A

;; ANSWER SECTION:
web.de.                 60      IN      A       82.165.229.138
web.de.                 60      IN      A       82.165.229.83

;; Query time: 15 msec
;; SERVER: 76.76.10.38#53(76.76.10.38)
;; WHEN: Tue Feb 13 08:56:46 CET 2024
;; MSG SIZE  rcvd: 67
```

**Comment by thomasmerz** [comment]
@hagezi , I agree that they work - but since Feb 1st a little bit different than before. I should remove them from my dnsping-monitoring via UDP or add a switch for checking via TCP.
Thanks for your help/tipp/hint 😉

**Comment by thomasmerz** [comment]
Fixed my dnsping-monitoring: https://github.com/thomasmerz/dnspingtest_rrd_ka/commit/c0793d1dd76be615efac30c518ec5bb3c115edf7 👍🏼 (plus some more repos)

**Comment by thomasmerz** [comment]
@hagezi - I contacted ControlD and they fixed there DNS servers because this was not intended!? 🤷🏼‍♂️ UDP queries are working fine again 👍🏼
