### ISSUE TITLE
arctic.de why is this even blocked?

### ISSUE THREAD

**Issue by Crylune** [badmojr/1Hosts#1683]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
arctic.de
*.arctic.de
```
<br>

**Details:**

This is literally the website for a well known PC cooling solution manufacturer. Why was this even blocked? Every day I'm closer to ditching this blocklist.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by iam-py-test** [comment]
The maintainer of this filterlist is busy and lacks the time to quickly address every issue: https://github.com/badmojr/1Hosts/issues/1307
Thank you.
