### ISSUE TITLE
peeksoft.co, www.peeksoft.co

### ISSUE THREAD

**Issue by mikezliu** [badmojr/1Hosts#17]
Could the following two domains be whitelisted?
https://peeksoft.co
https://www.peeksoft.co

The domain is for a portfolio management application. Most of the app functionalities are broken, such as sync'ing data across devices, fetching news, financial data, in general using the app is broken, etc. The app only uses google for advertising. May I ask which upstream list the domain was pulled from?

**Comment by p1r473** [comment]
Agreed, this is a false positive

**Comment by badmojr** [comment]
> Could the following two domains be whitelisted?
> https://peeksoft.co
> https://www.peeksoft.co
> 
> The domain is for a portfolio management application. Most of the app functionalities are broken, such as sync'ing data across devices, fetching news, financial data, in general using the app is broken, etc. The app only uses google for advertising. May I ask which upstream list the domain was pulled from?

Fixed! Thank you.
Origin:- https://github.com/ftpmorph/ftpihole/raw/master/blocklists/smartphone-ads-tracking.txt
