### ISSUE TITLE
Microsoft Update Catalog

### ISSUE THREAD

**Issue by fancybody** [badmojr/1Hosts#1700]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
scdn1f003.wpc.ad629.nucdn.net
```
<br>

**Details:**
The above-mentioned domain currently blocks the direct downloading from Microsoft Update Catalog.
Sample Link: https://www.catalog.update.microsoft.com/Search.aspx?q=KB5035853

![image](https://github.com/badmojr/1Hosts/assets/87397831/caa75cfa-1869-46b7-b40e-58e13108517c)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
> The above-mentioned domain currently blocks the direct downloading from Microsoft Update Catalog.

Upgrade to Linux.... then problem solved for ever
