### ISSUE TITLE
Legit Domains.

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#171]
I thought it will be easier for you to get the list instead of a screen shot. 

instagram.com
tumblr.com
cdninstagram.com
api.twitter.com
pbs.twimg.com
abs.twimg.com
twitter.com
www.linkedin.com
www.businessinsider.com
cdn.syndication.twimg.com
in.appcenter.ms
aureus-payment.multimediabs.com
cdn.mgig.fr
www.reddit.com
gql.reddit.com
v.redd.it
www.finder.com
appsmobiles.flex.bouyguesbox.fr
muckrack.com
www.arounddeal.com
www.retaildive.com
www.dealstreetasia.com
www.shrm.org
www.euronews.com
oauth.reddit.com
preview.redd.it
external-preview.redd.it
www.swisslife.fr

You can also download the TXT file at:
https://www.swisstransfer.com/d/87d6742d-85f3-4b36-afcc-7da585d8cec3

**Comment by Quorum75** [comment]
Let me know which domain you agree to whitelist then I will remove it from my allow list. Cheers.

**Comment by badmojr** [comment]
Surely not everything in here is blocked, is it?

**Comment by badmojr** [comment]
Fixed almost everything except the 3 domains above, in https://github.com/badmojr/1Hosts/commit/5362adbe752b6f11b3ba094c4682371a05c68978.
Need more info on them.

Please recheck &  confirm!

**Comment by Quorum75** [comment]
All the domains I sent you had to be added to my Allow List. 
To be honest I sent you the full list, while I was sending you before each domain one by one.  

Also, I am not sure the first few social media domains were on your list. However I know they are on Stevenblack one because I use his biggest host. 

Regarding:

**- appsmobiles.flex.bouyguesbox.com**
It is needed to access my ISP mobile application (https://apps.apple.com/tr/app/espace-client-bouygues-telecom/id422590767)

**- ￼aureus-payment.multimediabs.com**
Needed to access a banking payement website in Turkey. 

**- in.appcenter.ms**
I don't remember. I have to delete it to see what was the issue. 

By the way, do you thing that some of the list I use are causing duplicates with yours? I don't which sources you are using. 
![image](https://user-images.githubusercontent.com/49731083/123167609-0da44c00-d477-11eb-9bde-3aa611ac9a6f.png)

**Comment by badmojr** [comment]
1Hosts blocklists are not really "merged" lists in the absolute sense of the word.
Though I do "merge" from alot of lists, it doesn't mean that every domain on those lists gets included.

Take the Pro version for example.
Its only 180k in domains total; for the domains.txt variant & 100k for the adblock.txt variant.
This number is considerably smaller than the total amount of domains of [all the upstream/origin sources in use](https://github.com/badmojr/1Hosts/blob/master/statics/assets.txt), if "merged".

You should consider  the 1Hosts lists as transformative, & then make an informed choice as to what list to enable/disable.

Cheers!

**Comment by Quorum75** [comment]
Thanks for the feedback. 

I was asking because I don't know what do you include in your list and I couldn't find any information on that topic.  

For instance I could see that adult sites are not blocked for instance. One reason I have to use Stevenblack black.

**Comment by badmojr** [comment]
I don't block porn in any of the lists.
Most of my focus is in blocking ads, analytics, trackers, and all their worthless siblings.

**Comment by Quorum75** [comment]
So phishing, malware, adware, PUP, malicious sites and social media are not in the list, correct?

**Comment by badmojr** [comment]
They are, except social media sites.
Worthless siblings, remember? Check the upstream souces used for more info.

**Comment by Quorum75** [comment]
Will do Cheers.

**Comment by badmojr** [comment]
A malware feed that hasn't received an update in a month? Thank you, but no thanks.
![WS-malware](https://user-images.githubusercontent.com/40524316/123314760-a4ced980-d533-11eb-9f37-ac971b38cda8.PNG)

**Comment by Quorum75** [comment]
I won't argue on that. 
However like he said there are many false positive in many lists on the web. 
Also I found many domains in their lists that I don't find in others that are updated every week...

I do trust Yegor co-Founder at Windscribe, but it is a personal opinion.

**Comment by badmojr** [comment]
They are many domains in the list that you can't find on other lists; I agree.
Contains fewer false positives; definitely.

My only problem with the list is on its curation & update frequency.

**Comment by Quorum75** [comment]
> Fixed almost everything except the 3 domains above, in https://github.com/badmojr/1Hosts/commit/5362adbe752b6f11b3ba094c4682371a05c68978.
> 
> Need more info on them.
> 
> 
> 
> Please recheck &  confirm!

Everything is fine now 👍🏻👏🏻

**Comment by T145** [comment]
@Quorum75 Do you know anything about Windscribe's cryptomining and social blacklists? I was able to find their other lists by some simple guesswork. Info is here: https://github.com/T145/the-blacklist/issues/27

**Comment by Quorum75** [comment]
@T145 I do use Winscribe Pro and ControlD on my devices. 

Why the question?

**Comment by T145** [comment]
As my issue details, I'm trying to track down the endpoints for Windscribe's custom cryptomining and social blacklists. They're in a format similar to https://assets.windscribe.com/custom_blocklists/ads.txt, and I'm wondering if you might have any leads.

**Comment by Quorum75** [comment]
Sorry for the late reply but the thread being closed I get no notifications. 

I talked with Yegor in the past about their different lists used in Windscribe or ControlD. 
I understood they use some public lists in order to build their own to avoid any false positive. 

I don't have any other info. You may want to contact him on Windscribe Discord.

**Comment by chirag127** [comment]
> A malware feed that hasn't received an update in a month? Thank you, but no thanks.
> ![WS-malware](https://user-images.githubusercontent.com/40524316/123314760-a4ced980-d533-11eb-9f37-ac971b38cda8.PNG)

how did you get that info.

**Comment by badmojr** [comment]
> > A malware feed that hasn't received an update in a month? Thank you, but no thanks.
> > ![WS-malware](https://user-images.githubusercontent.com/40524316/123314760-a4ced980-d533-11eb-9f37-ac971b38cda8.PNG)
> 
> how did you get that info.

Through curl. Here's how!
 `curl -fsSLI https://assets.windscribe.com/extension/ws/malwaredomains.txt`
