### ISSUE TITLE
Hostname: sp-dir.uwn.com - Please Allow

### ISSUE THREAD

**Issue by YipYup** [badmojr/1Hosts#1713]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [x] mini
- [x] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:**
NextDNS.io

<br>

**Domains:**
```
sp-dir.uwn.com
```
<br>

**Details:**

This hostname is used by Ubiquiti routers to retrieve a list of speed-test endpoints, which are used to perform speed tests by the user in the web interface of the router. Blocking it prevents the router from getting a list of available speed test servers, and thus breaks the speed test the user has initiated.

**Comment by spirillen** [comment]
> speed tests by the user in the web interface of the router.

You can't make any reliable speed test within any browsers as the are using the TCP protocol vs FTP test that uses the UDP protocoll, with way less header and footers which make the test way more reliable and correct. 

http://speedtest.tele2.net/

PS: Alway use the reliable Linux/Unix OS platform's to make these test.
