### ISSUE TITLE
Cameleon hosts are deprecated

### ISSUE THREAD

**Issue by T145** [badmojr/1Hosts#172]
`last-modified: Tue, 15 Dec 2020 07:26:16 GMT`
https://sysctl.org/cameleon/

It leveraged Squid too, so it probably used that ancient tar archive mirror that's still up.

**Comment by badmojr** [comment]
Hola!
Only a handful of domains from that source are included.
Domains that may be covered by other sources used, so it's only there for redundant purposes.
Long story short, not such a biggie considering I never include 100% of it.


```
#!/bin/bash
#----------

analyze() {
deDuplicate() { awk '!visited[$0]++'; }
sanitize() {
sed -e "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/
		s/[[:space:]]\+/ /g; s/^[[:space:]]\+//; s/[[:space:]]\+$//;
		s/\(^\|\s\)\(#\|\!\).*//;
		s/^\(\(host\|domain\)\(-suffix\|\)\),//; s/,reject$//;
		s:^\(address\|server\)=/::; s|\/0\.0\.0\.0$||;
		s/^\(\(\(0\|127\)\.\([[:digit:]]\{1,3\}\.\)\{2\}[[:digit:]]\{1,3\}\)\|::\|0\)\s//;
		s/[\^\$,]\(important\|empty\|first-party\|1p\|3p\|popup\|popunder\|third-party\|script\)//g;
		s/[\^\$,]\(~third-party\|image\|media\|subdocument\|document\|doc\|object\|~object-subrequest\|frame\|all\|domain=in-addr\.arpa\)//g;
		s/^\(\(||\)\{0,1\}\(|\)\{0,1\}\(\*\.\)\{0,1\}\(\.\)\{0,1\}\(=\)\{0,1\}\(-d\s\)\{0,1\}\)//;
		:loop; s|[\*\^\/\?\|]$||; t loop;
		/^[^.*\..]*$/d;
		/\.\localdomain$/d;
		/[^a-z0-9.\_-]/d;
		/^[^a-z0-9]/d;
		/[^a-z0-9]$/d;
		"; }

originURL="$1"
data_origin=$(curl -fsSL "$originURL" |sanitize |deDuplicate)
data_main=$(curl -fsSL --compressed https://hosts.netlify.app/Xtra/domains.txt |sanitize |deDuplicate)
count_originalDomains=$(echo "$data_origin" |wc -l)
count_includedDomains=$(awk 'FNR==NR{a[$1];next}($1 in a){print}' <(echo "$data_origin") <(echo "$data_main") |wc -l)
((count_ommittedDomains=$count_originalDomains - $count_includedDomains))
((print_percent_included=100*$count_includedDomains/$count_originalDomains))
((print_percent_ommitted=100 - $print_percent_included))


echo -e -n "
Source: $originURL
Total: $count_originalDomains domains.
Domains included by 1Hosts (Xtra): $count_includedDomains
Domains ommitted: $count_ommittedDomains
included: $print_percent_included%
ommitted: $print_percent_ommitted%
"
}

analyze https://sysctl.org/cameleon/
```

**Comment by T145** [comment]
Ah interesting; I have a general idea of what you're doing then. I'm guessing this is your "above method" mentioned in #173? I'm also guessing this either a pre-build action where you then include sources that are not redundant, or post-build action where you then verify if some sources didn't make it in, therefore fulfilling your desire "for redundancy purposes." In the latter case you'd be including dead hosts.

A couple notes on the script:
- `mawk` is faster than base `awk` on the de-dupe operation
- You shouldn't need the `-e` flag on `sed`, or if you're going to use it then break up your current command into multiple `-e` statements.
Idk why you don't just make the building source open so people can optimize it and suggest new features.

**Comment by badmojr** [comment]
Nope!
I wrote the script today just to show that a source being deprecated does not affect in any way the effectiveness of the lists 'coz only a certain percentage of domains from such a list makes it up onto the end-result 1Hosts lists.
In the script above, only 25%.

Regarding the project being close sourced:
Made it open once. Nobody bothered to contribute anything!

**Comment by T145** [comment]
That was before you had a following 😉
