### ISSUE TITLE
CSS loading fail

### ISSUE THREAD

**Issue by maruka252** [badmojr/1Hosts#1723]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**

<br>

**Domains:**
```
css-load.com
```
<br>

**Details:**
When accessing ygosu.com, CSS does not load properly. After checking the network list, if you block css-load.com, you will see that the CSS does not load as shown on the screen.
The ad doesn't pop up, but blocking that domain will cause the screen to break, so I believe I should only exclude it from the lite version.

1hosts(uBO 1hosts light filter)
<img width="1508" alt="image" src="https://github.com/badmojr/1Hosts/assets/165761204/8b62f9a5-81b1-4279-b43a-c6d187d46717">

Whitelist domain
<img width="1510" alt="image" src="https://github.com/badmojr/1Hosts/assets/165761204/77363b87-7e54-4bd0-9ef2-ebf3cc081515">

<img width="1512" alt="image" src="https://github.com/badmojr/1Hosts/assets/165761204/55b73b81-2f64-41fc-bb8c-053e545ccf53">

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
All test indicates this would be a bad idea, but feel free to whitelist it localy, as this clearly is tracking

dsearch css-load.com

## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

remote: Enumerating objects: 379, done.
remote: Counting objects: 100% (379/379), done.
remote: Compressing objects: 100% (150/150), done.
remote: Total 379 (delta 290), reused 317 (delta 228), pack-reused 0
Receiving objects: 100% (379/379), 35.01 MiB | 5.44 MiB/s, done.
Resolving deltas: 100% (290/290), completed with 9 local objects.
From github.com:Import-External-Sources/hosts-sources
80b8868d3..f49586b07  master     -> 0xacab/master
```css
data/badmojr1Hosts.txt:css-load.com
data/badmojr1Hosts.txt:0.css-load.com
```

#### Sorted result

```css
0.css-load.com
css-load.com
```

### Search result from easylist

remote: Enumerating objects: 213, done.
remote: Counting objects: 100% (213/213), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 213 (delta 141), reused 199 (delta 135), pack-reused 0
Receiving objects: 100% (213/213), 1.72 MiB | 1.98 MiB/s, done.
Resolving deltas: 100% (141/141), completed with 7 local objects.
From github.com:easylist/easylist
ee06cb15c1c..afcb5d9e9df  master     -> origin/master
e914b14c8c0..877dff58936  gh-pages   -> origin/gh-pages
```css
easylist/easylist_adservers.txt:||css-load.com^$document,popup
easylist/easylist_adservers_popup.txt:||css-load.com^$popup
```

## Search in [Matrix](https://mypdns.org/)


Search results from [Matrix](https://mypdns.org) blacklist project

```css
source/adware/wildcard.list:css-load.com
```


Found these RPZ records from My Privacy DNS
```sql
id      domain records  type    content
24405660        *.css-load.com.adware.mypdns.cloud      type    .
24405659        css-load.com.adware.mypdns.cloud        type    .
```

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
\+ Thanks to [My Privacy DNS](https://mypdns.org/) for this knowledge
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Drilling for css-load.com

css-load.com.   172800  IN      NS      veda.ns.cloudflare.com.
css-load.com.   172800  IN      NS      houston.ns.cloudflare.com.

**Comment by iam-py-test** [comment]
You are correct @spirillen. This domain is used by AdShield
As for the breakage, AdShield deliberately breaks the website: https://github.com/AdguardTeam/AdguardFilters/issues/169825#issuecomment-1876446822
To the OP, I am sorry, but [this issue has already been reported](https://github.com/badmojr/1Hosts/issues?q=css-load.com).
Thanks
