### ISSUE TITLE
Lite, ygosu.com not available.

### ISSUE THREAD

**Issue by loana2918** [badmojr/1Hosts#1727]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
uBO

<br>

**Domains:**
```
css-load.com
```
<br>

**Details:**
Lite is said to minimize web page damage, but I don't think it's any different from PRO.
![image](https://github.com/badmojr/1Hosts/assets/164298716/dc91a39d-dda8-4e3f-a4e4-c23b5ed13fc1)
![image](https://github.com/badmojr/1Hosts/assets/164298716/408a023c-8027-481e-ac68-1855b1e91f45)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
have you searched for the tracking domain for other open issues?? https://github.com/badmojr/1Hosts/issues?q=is%3Aissue+is%3Aopen+css-load.com


## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```css
data/badmojr1Hosts.txt:css-load.com
```

#### Sorted result

```css
css-load.com
```

### Search result from easylist

```css
easylist/easylist_adservers.txt:||css-load.com^$document,popup
easylist/easylist_adservers_popup.txt:||css-load.com^$popup
```

## Search in [Matrix](https://mypdns.org/)


Search results from [Matrix](https://mypdns.org) blacklist project

```css
source/adware/wildcard.list:css-load.com
```


Found these RPZ records from My Privacy DNS
```sql
id      domain records  type    content
24405660        *.css-load.com.adware.mypdns.cloud      type    .
24405659        css-load.com.adware.mypdns.cloud        type    .
```

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
\+ Thanks to [My Privacy DNS](https://mypdns.org/) for this knowledge
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
