### ISSUE TITLE
"etoday.co.kr" not working.

### ISSUE THREAD

**Issue by minu38849** [badmojr/1Hosts#1730]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**NEXT DNS

<br>

**Domains:**
```
css-load.com
```
<br>

**Details:**
etoday.co.kr 이라는 웹 사이트에서 css 로딩이 안 돼요.
network tab에서 봤더니 css-load.com...? 이 도메인이 차단 당할 때만 화면이 깨지더라구요.
lite adblock.txt에 ||css-load.com^ 필터가 있던데 해당 필터를 lite에선 제거해야 되지 않을까 싶습니다.
lite 버전에선 화면이 깨지는 것을 최대한 방지를 해야 한다고 생각합니다.

이건 문제 화면 입니다.
<img width="758" alt="image" src="https://github.com/badmojr/1Hosts/assets/165756413/de5f528e-1443-4557-9b8c-e0dd1700a599">

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```css
data/badmojr1Hosts.txt:css-load.com
```

#### Sorted result

```css
css-load.com
```

### Search result from easylist

remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 16 (delta 13), reused 16 (delta 13), pack-reused 0
Unpacking objects: 100% (16/16), 1.93 KiB | 13.00 KiB/s, done.
From github.com:easylist/easylist
68d1fb78e8b..2108bb6de5d  master     -> origin/master
9df7e0e2420..7703da8d164  gh-pages   -> origin/gh-pages
```css
easylist/easylist_adservers.txt:||css-load.com^$document,popup
easylist/easylist_adservers_popup.txt:||css-load.com^$popup
```

## Search in [Matrix](https://mypdns.org/)


Search results from [Matrix](https://mypdns.org) blacklist project

```css
source/adware/wildcard.list:css-load.com
source/tracking/wildcard.list:css-load.com
```


Found these RPZ records from My Privacy DNS
```sql
id      domain records  type    content
24676019        *.css-load.com.adware.mypdns.cloud      type    .
24676018        css-load.com.adware.mypdns.cloud        type    .
24676016        *.css-load.com.tracking.mypdns.cloud    type    .
24676015        css-load.com.tracking.mypdns.cloud      type    .
```

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
\+ Thanks to [My Privacy DNS](https://mypdns.org/) for this knowledge
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
