### ISSUE TITLE
Blocker warning

### ISSUE THREAD

**Issue by renatoyamane** [badmojr/1Hosts#1733]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [X] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**

Adguard Home 0.107.48

<br>

**Domains:**
```
https://www.androidpolice.com/android-15-smart-home-controls/
```
<br>

**Details:**

This website above is showing an Blocker warning as per the screenshot below:

![Screenshot_20240413-133737](https://github.com/badmojr/1Hosts/assets/31208391/a350313f-f059-42b0-a894-8ef4676926f8)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by hagezi** [comment]
@renatoyamane unblock `succeedscene.com`

**Comment by renatoyamane** [comment]
@hagezi fixed!! Thanks!!
