### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#174]
Legit website blocked in the Pro list. 

https://www.paymentsjournal.com

**Comment by badmojr** [comment]
This originates from https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist
Pinging @mitchellkrogza .

**Comment by Quorum75** [comment]
No what I get in AG log activity. 
![image](https://user-images.githubusercontent.com/49731083/123409218-3bd87780-d5ae-11eb-9220-9c6ba383af5c.png)

**Comment by Quorum75** [comment]
> This originates from https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist
> 
> Pinging @mitchellkrogza .

I tried this Host in the past, too many legit blockings. Same issue I had with Xtra.

**Comment by badmojr** [comment]
You got nothing to worry about.
I employ a method that removes/commits quite a large of false positives.
Keep using Pro. 😉

**Comment by badmojr** [comment]
Found one more that's needed for the site to normally work.
**hb-minify-juc1ugur1qwqqqo4.stackpathdns.com**: CNAME for hb.wpmucdn.com

Origin:
https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt :@jawz101
https://blokada.org/blocklists/exodusprivacy/standard/hosts.txt :@kar

**Comment by Quorum75** [comment]
I am still wondering how such websites are ending up on blocking lists... Just pro stuff. 
Do the people still read... 😔

**Comment by badmojr** [comment]
Should be fixed now.

**Comment by Quorum75** [comment]
Indeed. 👍🏻

**Comment by jawz101** [comment]
@Quorum75 I try to research as much as possible but there are various ways they've ended up on Adaway.  There are a few false positives such as this one but, frankly, the Adaway list's coverage alone speaks to how relatively few entries you need to get wide coverage.

Personally, I go through a mental checklist.

- If I see it in one of my log files and it has a curious name.  A lot of these companies in the ad & tracking business use a certain lingo for everything.
- Do a web search to see what a company's business is.
- I'll check [VirusTotal](https://www.virustotal.com/gui/domain/data.flurry.com/relations) to see if an entry is observed to be communicated from Android applications
- Check the [Cisco Umbrella Top 1 Million list](http://s3-us-west-1.amazonaws.com/umbrella-static/index.html) to see if it's common enough to be beneficial.  If it doesn't show up or used to be relevant 2 years ago, there's really no reason to keep it (ex: businesses go out of business.)

I will say that this one does sound to be a false positive and I've removed it immediately.

Most lists have so much dead domains, uncommon entries that 80% of the entries are irrelevant.  You could get away with a few thousand entries and block 90% of what you would encounter.  Really.

The only things I try not to block are web-only domains (there are a million lists for those), malware & phishing (they'll naturally vanish after a few months anyways), email spam, and anything that causes breakage for the user.
