### ISSUE TITLE
www.businessinsider.fr

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#175]
Legit website blocked in Pro list. 

www.businessinsider.fr

**Comment by badmojr** [comment]
Origin:- https://blokada.org/blocklists/ddgtrackerradar/standard/hosts.t

Pinging @kar .

**Comment by badmojr** [comment]
Info:-
Its CNAME is the one being blocked i.e **402dd31d7a-2.optimicdn.com**

**Comment by Quorum75** [comment]
Still active?


![image](https://user-images.githubusercontent.com/49731083/123408999-fa47cc80-d5ad-11eb-94cd-075cf1d361bb.png

**Comment by badmojr** [comment]
Sent an incomplete URL. It's missing some letters at the end. 
Sorry!

https://blokada.org/blocklists/ddgtrackerradar/standard/hosts.txt

**Comment by Quorum75** [comment]
Yes I saw a domain but it static.businessinsider.com not www.businessinsider.fr

So why is the French version full domain blocked?

**Comment by badmojr** [comment]
Through its CNAME.
https://github.com/badmojr/1Hosts/issues/175#issuecomment-868388781

Should work fine now.

**Comment by Quorum75** [comment]
Nope. Still blocked, only the.com is accessible.

**Comment by badmojr** [comment]
Screenshots, please! Got nothing to work with.
Works fine on my side of things.

**Comment by Quorum75** [comment]
OK it's now working. 👍🏻
Maybe a delay in the list update.
