### ISSUE TITLE
CNAMEs of aus5.mozilla.org breaks firefox and thunderbird update functionality

### ISSUE THREAD

**Issue by kzshantonu** [badmojr/1Hosts#178]
This one:
`prod.balrog.prod.cloudops.mozgcp.net`

**Comment by kzshantonu** [comment]
[Here's](https://support.mozilla.org/en-US/questions/1103008) the clarification on mozilla support page

**Comment by badmojr** [comment]
Originates from:
https://github.com/parseword/nolovia/raw/master/skel/hosts-nolovia.txt: @parseword

**Comment by badmojr** [comment]
https://github.com/badmojr/1Hosts/commit/5119bb3ecd0fb3212941ba32e988527483d0e093 fixes this. Thank you!

**Comment by parseword** [comment]
> Originates from:
> https://github.com/parseword/nolovia/raw/master/skel/hosts-nolovia.txt: @parseword

Thanks for the heads-up! Fixed in https://github.com/parseword/nolovia/commit/7c62959b7b101468475fc00de8620a77e0ca67c8
