### ISSUE TITLE
Google Ads

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#179]
These requests are tagged by AG Pro as advertising but they are not blocked. Is it normal?

pki-goog.l.google.com

gstaticadssl.l.google.com

![image](https://user-images.githubusercontent.com/49731083/123544741-fa360100-d754-11eb-8aeb-66687d19f615.png)

![image](https://user-images.githubusercontent.com/49731083/123544746-fd30f180-d754-11eb-96ad-a7065a143056.png)

**Comment by badmojr** [comment]
pki-goog.l.google.com - Google certificates
gstaticadssl.l.google.com - Fonts

They are CNAMES of fonts.gstatic.com & ocsp.pki.goog, respectively.
They are unblocked by default/design, not a mistake.

**Comment by Quorum75** [comment]
Doesn't make sense to categorize them in Ad category. Hello AG 😁
