### ISSUE TITLE
False positive: d.toutiao.com

### ISSUE THREAD

**Issue by David-H-1** [badmojr/1Hosts#18]
It serves as a download link to Douyin, a common app used by Mainland Chinese people. It is the Chinese version for Tiktok. It is not malicious. Please unblock it from your lists. Thank you!

**Comment by David-H-1** [comment]
This is the URL to download the app.
https://d.toutiao.com/ab/heB7/

**Comment by David-H-1** [comment]
even the mini pack blocks it and there is no other way to download this software because those third party sites may contain viruses and malware

**Comment by badmojr** [comment]
The domain seems to be used for redirects & not for the actual download links.
Care to share where you found the above link?

**Comment by David-H-1** [comment]
Go to Douyin.com on mobile and click the large button (or the android icon) written in Chinese
________________________________

**Comment by badmojr** [comment]
Thanks!
This can be closed now.
