### ISSUE TITLE
Analytics dealabs.digidip.net

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#180]
Advertising/Analytics not blocked. 

dealabs.digidip.net

From https://digidip.net

I blocked it and at the present time I don't see any issue on https://www.dealabs.com

![image](https://user-images.githubusercontent.com/49731083/123544854-9a8c2580-d755-11eb-9299-22c7cae331f5.png)

**Comment by badmojr** [comment]
You won't be able to open links to buy stuff, then.
![link](https://user-images.githubusercontent.com/40524316/123548366-2e1d2080-d76d-11eb-9fca-61e5be400704.PNG)

Those are affiliate links that go through the above domain.
![affiliate-digidip](https://user-images.githubusercontent.com/40524316/123548453-80f6d800-d76d-11eb-9fcf-52527b961548.PNG)

**Comment by Quorum75** [comment]
Thanks. I didnt check that one. I was just browsing with no concern. 

Good eyes 😁
