### ISSUE TITLE
Analytics cds.s5x3j6q5.hwcdn.net

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#181]
Identified as analytics. 

vip0x01e.map2.ssl.hwcdn.net

cds.s5x3j6q5.hwcdn.net

https://www.highwinds.com

![image](https://user-images.githubusercontent.com/49731083/123544949-0a9aab80-d756-11eb-9595-14ecc7c7bf6c.png)

**Comment by badmojr** [comment]
This is a CDN.
Could break a lot of sites if blocked.

**Comment by Quorum75** [comment]
After extensive search I found that  in general hwcdn.net is a content delivery network and Windows is using some of their domains to deliver updates. 
Again AG confused me 😡

So for Windows users not a good idea indeed. However I will keep it blocked on my side as I am.not a Wondows user. 

https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions
