### ISSUE TITLE
MS News app

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#182]
Sometimes the news are blocked sometimes there are not. 
I can't figure out what wrong as many requests are blocked. 

https://apps.apple.com/tr/app/microsoft-news/id945416273

**Comment by badmojr** [comment]
Screenshots, please! Not an iPhone owner.

**Comment by Quorum75** [comment]
It is also available on Android 😉

https://play.google.com/store/apps/details?id=com.microsoft.amp.apps.bingnews&hl=en&gl=US

Nothing special about the screen it just says that there is an error. 
![image](https://user-images.githubusercontent.com/49731083/123808270-e2937f80-d8f0-11eb-99f5-ca9a6e1e016f.png)

**Comment by Quorum75** [comment]
I think I might find the problem.
Not sure though. Because when I added the request to Allow list I can access the news. But when I remove it I can still access the news. Cache reasons?

superapp.msn.com

**Comment by badmojr** [comment]
Unfortunately, the app isn't available for my device.
I gonna have to rely on your log screen screenshots to troubleshoot this.

**Comment by Quorum75** [comment]
Just for my info what can of phone or tablet do you have?

**Comment by Quorum75** [comment]
I don't know if it can help but I took the screen shots of AG Block list. Before I reset it to zero and closed all the apps on my iPhone then I open MS News app. 

![image](https://user-images.githubusercontent.com/49731083/123878776-07fbaa00-d940-11eb-8b06-11a7a0b924c4.png)

![image](https://user-images.githubusercontent.com/49731083/123878790-0b8f3100-d940-11eb-8e2c-2aa3f22ae35e.png)

![image](https://user-images.githubusercontent.com/49731083/123878796-0f22b800-d940-11eb-8b42-364a31fdc19c.png)

**Comment by badmojr** [comment]
> Not sure the screen shot will be of any help. Just for my info what can of phone or tablet do you have?

Prefer not to say. Thanks for the ss.

**Comment by badmojr** [comment]
Is this all the logs?
if so, try excluding:
```
mssl.fwmrm.net
prod.rewardsplatform.microsoft.com
token.safebrowsing.apple
```

**Comment by Quorum75** [comment]
Nope it does not work. In fact only the **superapp.msn.com** seems to do the trick. And I guess I was right about the application cache which brought me some confusion. 

Also, by researching the links you provided I think there is one you need to white list:
"**token.safebrowsing.apple**"
It is a feature called "Fraudulent Website Warning."

More info here: 
_https://www.macrumors.com/2021/02/11/ios-14-5-beta-safe-browsing-safari-apple-google/_

**Comment by badmojr** [comment]
`superapp.msn.com` originates from: https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
Pinging @Jawz101 for input.

**Comment by badmojr** [comment]
`token.safebrowsing.apple` 
origin: https://raw.githubusercontent.com/ookangzheng/blahdns/master/hosts/blacklist.txt - @ookangzheng

**Comment by jawz101** [comment]
removed.  thanks

**Comment by badmojr** [comment]
same to you.

**Comment by Quorum75** [comment]
Thanks guys.

**Comment by Quorum75** [comment]
> `token.safebrowsing.apple` 
> 
> origin: https://raw.githubusercontent.com/ookangzheng/blahdns/master/hosts/blacklist.txt - @ookangzheng
> 
> 

Hi any feedback?
