### ISSUE TITLE
Unblock URL shortener bitly.cx

### ISSUE THREAD

**Issue by zhg7** [badmojr/1Hosts#1832]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [X] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
bitly.cx
```
<br>

**Details:**
False positive - URL shortener.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
It is tagged as phishing by the phishing.database, so it seems to be in the right place 

## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```css
data/1Hosts.csv:bitly.cx
data/phishing_database/ALL-phishing-links.csv:bitly.cx
```

#### Sorted result

```css
```

### Search result from easylist

```css
```

## Search in [Matrix](https://www.mypdns.org/)


Search results from [Matrix](https://www.mypdns.org) blacklist project

```css
source/redirector/wildcard.list:bitly.cx
source/tracking/wildcard.list:bitly.cx
```


Found these RPZ records from My Privacy DNS
```sql
id      domain records  type    content
33539819        *.bitly.cx.redirector.mypdns.cloud      CNAME   .
33540189        bitly.cx.redirector.mypdns.cloud        CNAME   .
33542509        *.bitly.cx.tracking.mypdns.cloud        CNAME   .
33550991        bitly.cx.tracking.mypdns.cloud  CNAME   .
```

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
\+ Thanks to [My Privacy DNS](https://www.mypdns.org/) for this knowledge                         +
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by Vardorien** [comment]
> I don't see anything inherently malicious about that domain. It's [just another URL shortener](https://www.google.com/search?q=site%3Abitly.cx) that could have been used to redirect to some malicious site and therefore ended up listed in a phishing list.

It's flagged by multiple security vendors for phishing. While yes abuse is probably one reason it's on there another one is most likely because it's ripping off Bitly's name, and is going to be considered phishing.
