### ISSUE TITLE
Wrong blocking

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#188]
Hi. 

There is a legit website which should not be blocked. 

www.bcg.com

Thanks.

**Comment by badmojr** [comment]
Hello!
How's **Pro** treating you? 🥰 

origin: https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/raw/master/TOP_EU_US_Ads_Trackers_ABP - @Kees1958

**Comment by Kees1958** [comment]
Honered to mentioned @badmojr, but do I need to whitelist a website of remove an entry, please explain

**Comment by badmojr** [comment]
🙏🏾 
The reported domain can be traced back to the list yours.
Just wanted to give you a heads-up.

**Comment by Kees1958** [comment]
Thanks removed this domain. I hope this will be the last FP of my 2020 source mistake.

**Comment by badmojr** [comment]
Appreciate it! Closing..

**Comment by Quorum75** [comment]
> Hello!
> 
> How's **Pro** treating you? 🥰 
> 
> 
> 
> origin: https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/raw/master/TOP_EU_US_Ads_Trackers_ABP - @Kees1958

Much better. As you can see I have less false positive. Browsing is much easier now 😉
