### ISSUE TITLE
False Positive: Product images on mindfactory.de (online shop)

### ISSUE THREAD

**Issue by d-Rickyy-b** [badmojr/1Hosts#189]
Hi there, on www.mindfactory.de the product images are filtered out.

![grafik](https://user-images.githubusercontent.com/5798157/124389163-3e417c80-dce6-11eb-8b2e-0f426a897596.png)

It's because of this filter.
`||cdn.macovi.de^`

The images are located at: `https://cdn.macovi.de/images/catalog/1611670861.png`

**Comment by badmojr** [comment]
Fixed!
