### ISSUE TITLE
get.adobe.com is wrongly blocked in 1Hosts Pro

### ISSUE THREAD

**Issue by David-H-1** [badmojr/1Hosts#19]
I cannot even go to Adobe's official site to download Adobe DC Reader because of this.
![image](https://user-images.githubusercontent.com/60801469/89345491-0cb7cf80-d697-11ea-81e1-23a2424e72ef.png)

**Comment by badmojr** [comment]
**get.adobe.com** is actually not blocked...
Coudn't find it on any of the **Pro** variants.

**Comment by Marek33** [comment]
Yes, the get.adobe.com is not blocked, but the geo2.adobe.com is.

**Comment by badmojr** [comment]
> Yes, the get.adobe.com is not blocked, but the geo2.adobe.com is.

Why do you need it unblocked?
What does it break?

**Comment by Marek33** [comment]
It seems that's some tracking service, so I would leave it as it is.

**Comment by David-H-1** [comment]
It is on https://forum.xda-developers.com/android/general/badmojr-one-host-file-to-block-t3713360

Maybe the XDA forum didn’t update it

**Comment by badmojr** [comment]
> It is on https://forum.xda-developers.com/android/general/badmojr-one-host-file-to-block-t3713360 Maybe the XDA forum didn’t update it

What do you mean by that?

**Comment by badmojr** [comment]
UPDATE!
Reading https://github.com/nextdns/metadata/issues/361, it seems that the culprit isn't **get.adobe.com** .
The offending domain is  **get.wip4.adobe.com** which is a CNAME of the above mentioned..
![wtf-NextDNS](https://user-images.githubusercontent.com/40524316/89461416-9ab5b800-d774-11ea-89cf-fdf05ff15c80.PNG)

**Comment by badmojr** [comment]
Fixed!

**Comment by obeho** [comment]
@David-H-1  Which service is this screenshot from?
![89345491-0cb7cf80-d697-11ea-81e1-23a2424e72ef](https://user-images.githubusercontent.com/71698631/96847592-00126e80-1471-11eb-872c-5ac09ec8abae.png)

**Comment by David-H-1** [comment]
nextdns log On Thu, Oct 22, 2020 at 1:46 AM, obeho <notifications@github.com> wrote:  
@David-H-1  Which service is this screenshot from?
