### ISSUE TITLE
Apple Safe Browsing.

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#190]
BTW what about?

"token.safebrowsing.apple" "proxy.safebrowsing.apple" "safebrowsing.g.applimg.com"

Did you white list them? Thx.

More info here:
https://www.macrumors.com/2021/02/11/ios-14-5-beta-safe-browsing-safari-apple-google/

**Comment by badmojr** [comment]
Yes. I did!

**Comment by Quorum75** [comment]
Thank you!
