### ISSUE TITLE
False Positive: Alternative api login for Windscribe vpn software is blocked

### ISSUE THREAD

**Issue by j-moriarti** [badmojr/1Hosts#194]
These domains are blocked by **1Hosts/Xtra**:
```
api.3ba1aa644b7cc041073eb39e95a8877cfc9c7ea4.com
api.84b2f7886490591bf20a4ea2363b04209e977ee9.com
api.e52f615381d798fcdfb63fa89f30b3ac885bbbdd.com
```
According to my short-time testing, these domains (and maybe more) are used for api login in the mentioned app (only if connection to api.windscribe.com is blocked)

**Comment by badmojr** [comment]
Fixed.
