### ISSUE TITLE
tradingview.com "telemetry" domain

### ISSUE THREAD

**Issue by baronexy** [badmojr/1Hosts#200]
prod-telemetry-eu.tradingview.com
prod-telemetry-oc.tradingview.com
prod-telemetry-other.tradingview.com
prod-telemetry-us.tradingview.com
telemetry-default.tradingview.com
telemetry-new.tradingview.com
telemetry-partial.tradingview.com
telemetry-v2.tradingview.com
telemetry.tradingview.com

**Comment by badmojr** [comment]
I first have to know where the domains originate from.
Were they accessed/called by an app/website?

**Comment by baronexy** [comment]
> I first have to know where the domains originate from.
> Were they accessed/called by an app/website?

I don't know if it was called or not.
From: tradingview.com

**Comment by badmojr** [comment]
Which version of the lists do u use?

**Comment by baronexy** [comment]
> Listelerin hangi sürümünü kullanıyorsunuz?

1Hosts Pro, energized ultimate, oisd

**Comment by badmojr** [comment]
Great! Should be fixed on the next update.
