### ISSUE TITLE
pubsub-rc.pubnub.com, pubnub.com

### ISSUE THREAD

**Issue by p1r473** [badmojr/1Hosts#202]
This is a real-time API  to build engaging remote experiences using in-app chat, push notifications, etc
pubsub-rc.pubnub.com is a CNAME for ringcentral.pubnubapi.com which is RingCentral, a teleconferencing system
I dont believe blocking an API is a good idea. Rather, we should block malicious apps that may leverage an API.

![image](https://user-images.githubusercontent.com/9235633/126562804-51ec234d-242b-4c49-a1b7-cd2fa50c7d85.png)

**Comment by badmojr** [comment]
10x. Done!
