### ISSUE TITLE
Doubt with your hosts

### ISSUE THREAD

**Issue by gallegonovato** [badmojr/1Hosts#207]
Buenas tardes: First of all let me thank you for all your work, effort and everything. Turns out I've been using your hosts for a long time: 1 Host Pro. but today I looked at your github and saw Xtra (which is bigger than Pro) and a question arose. The Xtra that is an addition to the other hosts. Or does it include, for example, already within Xtra the 1 Host Pro ?. I don't know if you would be so kind as to answer this question for me? a hug and a million thanks for all your help.

**Comment by badmojr** [comment]
Hello!

It does, yes. **Xtra** is the superset of **Pro**.
It's quite extreme & unstable though, so use with caution.

**Comment by Marek33** [comment]
I have to agree with this, since the Xtra is really broken. I found at least 60 Slovak only domains, which shouldn't be there (it was 80 before, but there was an update meanwhile). Thou, the Pro has also a lot of domains, but less than the Xtra. I get, that more domains mean more bugs, but there are just too many bugs to me.

**Comment by badmojr** [comment]
> I have to agree with this, since the Xtra is really broken. I found at least 60 Slovak only domains, which shouldn't be there (it was 80 before, but there was an update meanwhile). Thou, the Pro has also a lot of domains, but less than the Xtra. I get, that more domains mean more bugs, but there are just too many bugs to me.

If u had them reported, they won't have been taken care of long ago.
That's the least you'd have done. B*tchin' & whining does not help.

Stop wasting my f0cking time. Find an alternative already, or downgrade to **Lite**.

**Comment by Marek33** [comment]
Do you really think, that I would be checking the list, every six hours when it's updated? Especially, when there is a ton of legit domains blocked? Sorry, but if you behave like this, then there is no reason, to support you anymore.

No, I will stop using this list, since it blocks way too much stuff, and it's way better to use official and proper filters.

**Comment by badmojr** [comment]
> Do you really think, that I would be checking the list, every six hours when it's updated? Especially, when there is a ton of legit domains blocked? Sorry, but if you behave like this, then there is no reason, to support you anymore.
> 
> No, I will stop using this list, since it blocks way too much stuff, and it's way better to use official and proper filters.

I agree. Good luck!

**Comment by gallegonovato** [comment]
Good afternoon @badmojr Thanks for your help and for your time. And I apologize if I am heavy or uneducated on these issues. So Xtra includes the Pro. This (Xtra) being more restrictive. Correct me if it is like that or I misunderstood you. I wanted to take advantage of the opportunity, if you will allow me. To tell you about possible sources for your host. They are based on privacy, and even avoiding google, and Mozilla telemetry, and others. I take this opportunity. To inform you of some possible new sources for your host lists. To make your host lists more impenetrable. I am sorry and I apologize, if what I am doing seems wrong to you. It is not my intention to offend you. Nor underestimate your work. Just help you and the only way I could think was this. The new sources for your hosts that I wanted to tell you about are:

Adguard Mobile Dns
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt
            
Anudeep Coinminer
https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt

Biroloter
https://raw.githubusercontent.com/biroloter/Mobile-Ad-Hosts/master/hosts

Blocklistproject
https://blocklistproject.github.io/Lists/ads.txt

Blocklistproject Tracking
https://blocklistproject.github.io/Lists/tracking.txt

D3ward
https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt

Data Master
https://raw.githubusercontent.com/DataMaster-2501/DataMaster-Android-AdBlock-Hosts/master/hosts

Developerdan Extended
https://www.github.developerdan.com/hosts/lists/hate-and-junk-extended.txt

Frogeye
https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt

Frogeye 2
https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt
            
GoodbyeAds
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt

Jmdugan
https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/google/all

Kaabir
https://raw.githubusercontent.com/kaabir/AdBlock_Hosts/master/host.txt

Kaabir Android
https://raw.githubusercontent.com/kaabir/AdBlock_Hosts/master/Android.txt


Jmdugan
https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/google/non_localized 

Jorgu81 Google
https://gitlab.com/Jorgu81/hosts/raw/master/Google/HostsGoogle

Jorgu81 Mozilla
https://gitlab.com/Jorgu81/hosts/raw/master/Mozilla/Mozilla

Jorgu81 Blocklist
https://gitlab.com/Jorgu81/hosts/raw/master/Router/Blocklist

Leftover
https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover.txt

Leftover Agresive
https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover_aggressive.txt

Molinero
https://hblock.molinero.dev/hosts

Nickspaargaren
https://raw.githubusercontent.com/nickspaargaren/no-google/master/google-domains

Nocoin
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt

Notracking
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt

Oisd Basic
https://hosts.oisd.nl/basic/

Orca
https://orca.pet/notonmyshift/hosts.txt
 
Pete Lowe blocklist hosts
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
           
Privacy Block List
https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/newhosts-final-Dual.hosts

Sebsauvage
https://sebsauvage.net/hosts/hosts

Ultimate Host
https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/master/hosts/hosts0

Winhelp 2002
https://winhelp2002.mvps.org/hosts.txt

ZeroDot1
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts

ZeroDot1  Browser
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts_browser

ZeroDot1 Opcional
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts_optional

https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/download_here/mobile/hosts ( https://github.com/Clefspeare13/pornhosts )

https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt

https://github.com/KodoPengin/GameIndustry-hosts-Template

https://github.com/blocklistproject/Lists?

https://codeberg.org/twann/filters

I hope they can be of help to you in your work. And make your host lists more impenetrable.

I apologize if I did something wrong or offended you. It was not my intention. On the contrary.

Receive a warm embrace

**Comment by badmojr** [comment]
Hi!
I actually already reference most of the lists above.
See https://github.com/badmojr/1Hosts/blob/master/statics/assets.txt .

And, no. You did nothing wrong.

**Comment by gallegonovato** [comment]
> Hi!
> I actually already reference most of the lists above.
> See https://github.com/badmojr/1Hosts/blob/master/statics/assets.txt .
> 
> And, no. You did nothing wrong.

good afternoon @badmojr

for example an interesting host list for their sources I see

https://blokada.org/mirror/v5/exodusprivacy/standard/hosts.txt.

https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/adservers-and-trackers.txt

https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/fake-domains.txt

https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileAds.txt

https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt

https://github.com/migueldemoura/ublock-umatrix-rulesets/tree/master/Hosts

Receive a warm hug and thank you very much for your help and time. And I'm sorry for the inconvenience.

**Comment by gallegonovato** [comment]
Good afternoon:

I don't know if it can help you or what you think:

https://gitlab.com/AuroraOSS/AppWarden/-/raw/master/hosts/warden_trackers.txt

https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt

https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/adservers-and-trackers.txt

https://v.firebog.net/hosts/Airelle-trc.txt

https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt

https://hostfiles.frogeye.fr/multiparty-only-trackers-hosts.txt

https://infinitytec.github.io/blocklists/blocklists.html

https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt

Best regards and sorry for the inconvenience. And I hope they will be useful to add to the host.

**Comment by badmojr** [comment]
Hello!

Checked them.
Some are already included & some are outdated, huge in size (cough. cough! inactive domains), and bloated .
Sorry!

**Comment by gallegonovato** [comment]
good afternoon: 

I'm sorry the host lists I suggested are not good. I do not know if you are looking for a specific topic or type? 

a hug and thank you very much for your time

**Comment by badmojr** [comment]
> good afternoon:
> 
> I'm sorry the host lists I suggested are not good. I do not know if you are looking for a specific topic or type?
> 
> a hug and thank you very much for your time

I check the lists thoroughly & then judge if they pass for inclusion. 
Not looking for any specific topic or type. It's just that they did not pass the test.
