### ISSUE TITLE
some trackers and others

### ISSUE THREAD

**Issue by saurane** [badmojr/1Hosts#209]
It is not on any list.

track.salesflare.com
tracking.salesflare.com
analytics.alloka.ru
mail.analytics.alloka.ru
analytics.sandbox.alloka.ru
analytics.staging.alloka.ru
tracking.letgo.com
cookieseal.com
xenn.io
adnboost.com
espncdn.com
l-stat.livejournal.net

**Comment by badmojr** [comment]
Good find! Added.

**Comment by chirag127** [comment]
xenn.io is nx domain
 espncdn.com is a cdn just go to https://www.espn.in/ eg https://a.espncdn.com/combiner/i?img=/i/teamlogos/countries/500/chn.png&w=32

**Comment by saurane** [comment]
Yes, it's not added. Thank you for details.

**Comment by badmojr** [comment]
> xenn.io

Hey,
_espcdn.com_ never ended up on the lists.
_xenn.io_ is nx domain, but **s.xenn.io** isn't.
