### ISSUE TITLE
advertising technology [korean company]

### ISSUE THREAD

**Issue by saurane** [badmojr/1Hosts#215]
tpmn.io

Almost all subdomains are for tracker or analysis purposes.

**Comment by badmojr** [comment]
Hey,
Do you have a link to a site or an app that's actively using the above domain?
Was not able to find any.

**Comment by saurane** [comment]
I found these in my neighbor's NextDNS log. Most likely alibaba.com android app.
1-) https://www.hizliresim.com/bi6p4sz
2-) https://www.hizliresim.com/asixg0p

**Comment by badmojr** [comment]
Cool! :ok_hand:

**Comment by badmojr** [comment]
done. 10x!
