### ISSUE TITLE
click.spe.ometria.email listed in PRO

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#217]
Hi @badmojr 

Link sent over email does not open due to `click.spe.ometria.email` liste in PRO which is a CNAME resolution of `https://clickom.josephjoseph.com/f/a/9d8tbqYVmytB-31zytR3fQ~~/AAAAAQA~/RgRi65-9P0UFMTowOjCEGQFodHRwczovL2V1Lmpvc2VwaGpvc2VwaC5jb20vY29sbGVjdGlvbnMvc3RvcmFnZT9vbV9jYW1wYWlnbj1vbW1lXzczMzhjNWQ4LTI0Y18xNzc2M185MTA4MyZvbV9wcm9maWxlPTJiYjgtMGM4ZDg1LTAyNWIyNWQ3Jm9tX3NlbmQ9ZTg3YmJkZTQ2YTIwNGM5OWI3YWFlOWNlZGU2NzRjMzEmdXRtX2NhbXBhaWduPW9tbWVfNzMzOGM1ZDgtMjRjXzAzMDgyMDIxX3N0b3JhZ2Vfc29sdXRpb25zJnV0bV9jb250ZW50PWV1X2N1c3RvbWVycyZ1dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9b21ldHJpYVcHb21ldHJpYUIKYQS9GglhEDFJ9FIRaGVyYmVydEBrbmF2cy5uZXRYBAAAALw~`.

Cheers

**Comment by badmojr** [comment]
That's definitely a tracker, @crssi .

**Comment by crssi** [comment]
I know it is... but it happens only when clicked on received email and these days there are not many such emails without the trackers and anyone can expect it. 😉

**Comment by badmojr** [comment]
I thought you liked **Lite**! What's the motivation behind the recent upgrade? 😄

**Comment by crssi** [comment]
😄 
I always aimed for **Pro** for my self, but I don't want to deal with breakages and grumpiness from other users... so they are on **Lite**.
But lately I find **Pro** more user friendly than before (good work btw and thank you) and maybe soon I will "upgrade" other users. 😉

**Comment by badmojr** [comment]
> it happens only when clicked on received email

If that's the case, then I'll remove it.

**Comment by crssi** [comment]
Thank you ❤️

**Comment by badmojr** [comment]
Fixed!
