### ISSUE TITLE
whitelist and blacklist

### ISSUE THREAD

**Issue by saurane** [badmojr/1Hosts#219]
Blacklist:
s.fullhdfilmizlesene.com (stats)
dengage.com This is a cdn or user tracking service. Blocked but there is no crash. (from: sozcu.com.tr)
activity.alibaba.com (tracker)
pozitron.com (data analytics system) from: opet.com.tr

Whitelist: 
ciceksepeti.bnydns.net (cdn server of ciceksepeti.com. example: cdn03.ciceksepeti.com)

I added it by mistake, sorry. You can add them to the white list. Is required for the bcvc.com.
punosy.best
cdnbcvc.com

**Comment by badmojr** [comment]
```
punosy.best
cdnbcvc.com`
```
These are not actually required for the site to work.
It's just that the site is implementing anti-Adblock, a problem I've before refused to address such as in https://github.com/badmojr/1Hosts/issues/98

**Comment by badmojr** [comment]
Should be fixed now!
