### ISSUE TITLE
1Hosts Pro incorrectly blocks Falun Gong domains

### ISSUE THREAD

**Issue by DandelionSprout** [badmojr/1Hosts#22]
A scandal was revealed to the international adblocking community a week ago, when it turned out that multiple Chinese regional lists that were meant to block ads and tracking, [were blocking Falun Gong domains due to the listmakers' own personal tastes](https://github.com/AdguardTeam/AdGuardHome/issues/1988).

*anti-ad* and *neoHosts Full* are considered to be the main perpetrators of this scandal, and I could see the affected domains be blocked in 1Hosts Pro (e.g. `shenyun.com`). I therefore presume that whichever of those two lists you use as a source, should be removed from the source list pretty quickly; or, if *neoHosts Full* is the source of those entries, replace it with *neoHosts Basic*.

**Comment by badmojr** [comment]
I run your FalukorvList against the sources used in 1Hosts (Pro) & got 4 sources that were including those domains.
The sources won't be completely removed.

But rather, I'll keep on doing what I've always done, completely remove the domains from all lists.
Cheers!

**Comment by badmojr** [comment]
Fixed! Lemme know if there's anything else in need of fixing.
Thank you!

**Comment by DandelionSprout** [comment]
There's nothing I know of at the time of writing, but I'll of course tell you if I do stumble across something.
