### ISSUE TITLE
v-mate.mobi

### ISSUE THREAD

**Issue by chirag127** [badmojr/1Hosts#220]
api.v-mate.mobi which is cname to api.apk.v-mate.mobi is required for vidmate app to load anything.

v.starhalo.mobi is used for images e.g. http://v.starhalo.mobi/sh/pic/04/3d/p18mt0043d.jpg

please unblock

1. api.v-mate.mobi
2. comment.v-mate.mobi
3. emo.v-mate.mobi
4. img.vidmatefilm.org
5. v.starhalo.mobi 

 from pro.

**Comment by badmojr** [comment]
Fixed!
