### ISSUE TITLE
Question about geo.cdn.springernature.io listed in Pro

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#224]
Stumbled upon `https://github.com/stoically/temporary-containers/issues/496#issuecomment-894282148`
tried the links mentioned on that issue:
`https://www.aerztezeitung.de/Nachrichten/Fachgesellschaften-fuer-COVID-Impfung-in-der-Stillzeit-416348.html`
and
`https://signon.springer.com/login?gateway=true&service=https://www.aerztezeitung.de/User/Modules/LoginModuleHandler.ashx?Cmd=SmSsoLogin&CurrentUrl=%2FNachrichten%2FFachgesellschaften-fuer-COVID-Impfung-in-der-Stillzeit-416348.html`
you can see that we have a breakage due denying `signon.springer.com` resolved over CNAME `geo.cdn.springernature.io` listed in Pro.

Is that OK?

Cheers

**Comment by badmojr** [comment]
Hey,
Blocked due to fingerprinting by duckduckgo tracker-radar: https://github.com/duckduckgo/tracker-radar/blob/main/domains/US/springernature.io.json

You sure u need it removed?

**Comment by crssi** [comment]
> You sure u need it removed?

No. Not at all.

Just wanted to point it out in case if it is false positive and will leave it to your wisdom. 😉 

Cheers

**Comment by badmojr** [comment]
What's that site though? Is it important?

**Comment by crssi** [comment]
Its some German news site. I don't really understand German very well, so I can't judge... as I said, I noticed that its blocked when I have stumbled on that issue and tried the link to see where it the problem with Firefox Temporary Containers Extension.

Cheers
