### ISSUE TITLE
Suggested host source

### ISSUE THREAD

**Issue by gallegonovato** [badmojr/1Hosts#225]
Good afternoon:

I am writing to you with a question or suggestion.

I happened to be looking at the Exodus Privacy website for an application. It occurred to me that it would be wonderful to have a host on Exodus Adaway (for example).

I went looking to see if there was one. And I only found https://blokada.org/mirror/v5/exodusprivacy/standard/hosts.txt but it is for blokada.

So, I don't know what you think. But it would be a very good option to add to your lists or as a source for your hosts.

I hope you take my suggestion into consideration. Best regards and thank you for your time.

**Comment by badmojr** [comment]
Thanks for the list suggestion.
Fortunately, it is already being included.
See https://github.com/badmojr/1Hosts/blob/master/-data/lists/assets.txt#L205

**Comment by gallegonovato** [comment]
Good afternoon @badmojr

You are a genius. A thousand thanks for your work. I take off my hat and more with all your work.

I wanted to recommend two hosts, which I thought I did not see in your sources. They would be:

https://raw.githubusercontent.com/jjjxu/NSO_Pegasus_Blocklist/master/Pegasus-Hosts-Formatted.txt

https://raw.githubusercontent.com/jerrimath/GalComm_Blocklist/master/Galcomm-Hosts-Formatted.txt

https://github.com/BrendanSilva/Project-Calibos

https://gitlab.com/curben/urlhaus-filter/

https://gitlab.com/Jorgu81/hosts/raw/master/Mozilla/Mozilla

https://gitlab.com/curben/urlhaus-filter#urlhaus

https://raw.githubusercontent.com/durablenapkin/block/master/streaming.txt

I apologize if you already have them in your host fonts. 

I'm trying to help and I can't think of any other way.

Thanks a million for all your work and effort.

Pd: if I use your host pro, I can put the xtra which is more complete and already includes your 1hostspro.?.

**Comment by badmojr** [comment]
> Good afternoon @badmojr
> 
> You are a genius. A thousand thanks for your work. I take off my hat and more with all your work.
> 
> I wanted to recommend two hosts, which I thought I did not see in your sources. They would be:
> 

> https://raw.githubusercontent.com/jjjxu/NSO_Pegasus_Blocklist/master/Pegasus-Hosts-Formatted.txt
> 
Contains entries that are not active. So not so useful!
>
> https://raw.githubusercontent.com/jerrimath/GalComm_Blocklist/master/Galcomm-Hosts-Formatted.txt
> 
Used to be included! Was removed for the same reason as above
>
> https://github.com/BrendanSilva/Project-Calibos
> 
Blocks categories that we generally do not block such as porn, gambling, etc
>
> https://gitlab.com/curben/urlhaus-filter/
> 
This is a remake/mirror of https://urlhaus.abuse.ch/ , which we already include.
>
> https://gitlab.com/Jorgu81/hosts/raw/master/Mozilla/Mozilla
> 
Too restrictive & maybe block useful features such as updates.
We already have coverage for Mozilla tracking & telemetry in the lists, so no need for that list.
>
> https://gitlab.com/curben/urlhaus-filter#urlhaus
> 
See above explanation on the same link.
>
> https://raw.githubusercontent.com/durablenapkin/block/master/streaming.txt
> 
Kudos for this one! It's very useful.

> I apologize if you already have them in your host fonts.
> 
> I'm trying to help and I can't think of any other way.
> 
> Thanks a million for all your work and effort.
> 
> Pd: if I use your host pro, I can put the xtra which is more complete and already includes your 1hostspro.?.

**Comment by badmojr** [comment]
About the last question:

Yes, **1Hosts Xtra** includes mini, Lite, & Pro.. It's the superset of them all.
Be advised though, it's very restrictive.
