### ISSUE TITLE
Request to remove a Netflix owned domain

### ISSUE THREAD

**Issue by sathyacs** [badmojr/1Hosts#229]
Hi,

Netflix recently launched a reality casting site for consumers to upload their casting video: http://netflixreality.com/ . The domain netflixreality.com is recorded in some of your files as suspicious. We received reports from consumers that they are not able to load the site due to warning messages. We can guarantee that the site does not contain any malicious content. Request you to kindly remove our domain from your block lists so our consumers can continue using the site without any issues.

Thanks
Sathya

Senior Security Engineer
Netflix

**Comment by badmojr** [comment]
Hello! 
Sorry for the inconvenience.
Flagged by an upstream, https://blocklistproject.github.io/Lists/alt-version/phishing-nl.txt as phishing.

Pinging @gap579137 , @blocklistproject .

**Comment by crssi** [comment]
Interestingly `netflix.com` does not have hidden registrant https://domainbigdata.com/netflix.com,
where `netflixreality.com` do https://domainbigdata.com/netflixreality.com

I am wonder why?

**Comment by sathyacs** [comment]
I do see that netflixreality.com registration is not hidden here:
https://whois.domaintools.com/netflixreality.com

Sathya

**Comment by crssi** [comment]
Soon after my initial post I have updated it with the same observation. I have also hidden the post, since its not relevant.... sry for spam.

Cheers

**Comment by blocklistproject** [comment]
> Hi,
> 
> Netflix recently launched a reality casting site for consumers to upload their casting video: http://netflixreality.com/ . The domain netflixreality.com is recorded in some of your files as suspicious. We received reports from consumers that they are not able to load the site due to warning messages. We can guarantee that the site does not contain any malicious content. Request you to kindly remove our domain from your block lists so our consumers can continue using the site without any issues.
> 
> Thanks
> Sathya
> 
> Senior Security Engineer
> Netflix

I am going to go ahead and get this fixed pushed but if you (@sathyacs) could please create an issue for this on our [GH](https://github.com/blocklistproject/Lists/issues/new/choose) for our records it would be much appreciated. Thank you.

**Comment by sathyacs** [comment]
Thank you for the quick action. I will create an issue as requested.

Thanks
Sathya

**Comment by badmojr** [comment]
Thanks everyone! 
Fixed & Closing...
