### ISSUE TITLE
sia.socialblade.com

### ISSUE THREAD

**Issue by Marek33** [badmojr/1Hosts#23]
Is blocked by 1Hosts, as well as the Energized Ultimate. It is a part, of the socialblade.com, which is useful for knowing stuff about websites like the YouTube, Twitch and so on.

**Comment by badmojr** [comment]
The main site seems to work pretty well.
Why do you need the subdomain unblocked?

**Comment by Marek33** [comment]
Because unless I whitelist it, the site, doesn't work properly.

**Comment by badmojr** [comment]
Good for you!
Lemme know if something breaks again.

**Comment by Marek33** [comment]
I will, and for now, I will close it.
