### ISSUE TITLE
In game info blocked due to fe-ed.wgcrowd.io listed in Pro

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#233]
Hi @badmojr 

See blocked (the middle info/news window):
![wot-blocked](https://user-images.githubusercontent.com/17024151/129952550-46d4e22d-6b20-40f5-85b8-0a18295caedb.JPG)

See when fe-ed.wgcrowd.io is allowed:
![wot-notblocked](https://user-images.githubusercontent.com/17024151/129952616-03d08976-2eb9-4b5c-a6d2-d3024a73d67a.JPG)

Thank you in advance ❤️ 
Cheers

**Comment by badmojr** [comment]
Removed! Thanks.
