### ISSUE TITLE
few entries to remove

### ISSUE THREAD

**Issue by kzshantonu** [badmojr/1Hosts#239]
`eu.adyen.link`
legitimate payment processor

`samsungiotcloud.com`
required for Samsung SmartThings app/system

`samsungosp.com`
required to sign in to Samsung account

**Comment by badmojr** [comment]
If you could provide me with the required subdomains too, that would certainly be helpful.
Thanks.

**Comment by kzshantonu** [comment]
Not 100% sure about `invitation.samsungiotcloud.com` and `uimetadata.samsungiotcloud.com` but `ocfconnect*.samsungiotcloud.com` is needed for the app to work. Not sure about `gld.push.samsungosp.com` either

**Comment by badmojr** [comment]
Should be fixed! Please confirm.
