### ISSUE TITLE
wmflabs.org

### ISSUE THREAD

**Issue by Marek33** [badmojr/1Hosts#24]
Is blocked by 1Hosts, as well as the Energized Ultimate. It is a part of the _Wikimedia Cloud Services_.

**Comment by badmojr** [comment]
Does it break some service/app/website from functioning properly?

**Comment by Marek33** [comment]
Yes, but I can't remember which one, since I had it, noted for almost a week. Thou, since it's blocked, one would need to whitelist it, in the uBlock Origin, which defeats the point, of blocking third party all together.

**Comment by badmojr** [comment]
Can’t reproduce, can’t remove.
Sorry!

**Comment by Marek33** [comment]
That's a pity, but if you visit the wmflabs.org, you should get a warning.

**Comment by badmojr** [comment]
Send some screenshots plz so that we’re on the samepage.

**Comment by Marek33** [comment]
Unfortunately, I don't have any screenshot, since I don't know where exactly that domain was in the third party. 

However, when I have this: 
![1Hosts](https://user-images.githubusercontent.com/19204886/90323071-88016700-df5c-11ea-8144-c1073ac303ed.jpg)

**Comment by badmojr** [comment]
I can’t remove the domain without knowing what site/service/app it breaks.

So sorry!!

**Comment by Marek33** [comment]
No problem and when I will find a site, where it makes problem, then I will notify you.

**Comment by badmojr** [comment]
Cool! Thanks.

**Comment by Marek33** [comment]
@badmojr  I found it: Its blocked on this page: https://www.lightningmaps.org/#y=46.8283;x=22.8653;z=8;t=4;m=osn;r=0;s=0;o=0;b=0.00;n=0;d=8;dl=8;dc=0;ts=0;tr=1;tc=1;

**Comment by badmojr** [comment]
Comfirmed! Thank you.

**Comment by badmojr** [comment]
Fixed!
