### ISSUE TITLE
Breakage due to ads.api.24ur.si listed in Pro

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#240]
`https://www.24ur.com` is a news site where there are also posted video articles.
See for example the site `https://www.24ur.com/novice/slovenija/upokojenci-prevoz.html` and try to start video.

Blocking `ads.api.24ur.si` (listed in **Pro),** prevents XHR requests which triggers ADS detection and thus prevents playing the video.

I haven't seen that the `ads.api.24ur.si` would really have anything with the ADS, but for sure not 3rd party ADS (`24ur.com` and `24ur.si` are actually 1st party, just not "technically").

I would `vote` to remove listing of  `ads.api.24ur.si` from **Pro**

Cheers

**Comment by badmojr** [comment]
You can try it now. Everything looking good?
How about the video ads? Blocked or still playing?

**Comment by crssi** [comment]
Now all its great. 👍 
I knew I can count on you as always.

❤️
