### ISSUE TITLE
Legit app Blocked

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#242]
With **cognito-identity.eu-west-1.amazonaws.com** blocked I can't access my ISP (Bouygues Télécom) iOS application to download my invoices. 

https://apps.apple.com/tr/app/espace-client-bouygues-telecom/id422590767

**Comment by badmojr** [comment]
Hello!
Please send s-shots of the error you've encountered.

**Comment by Quorum75** [comment]
There is no error. When I try to login nothing happens. I get stucked on the login screen. 
However when I added the rule to my whitelist I could get into the application.

**Comment by badmojr** [comment]
ok. Fixed!
