### ISSUE TITLE
False Positive: Ticket shop for holidaypark.de not working

### ISSUE THREAD

**Issue by d-Rickyy-b** [badmojr/1Hosts#243]
Hi, it's me again. Today I found out that the ticket shop for the German amusement park "Holiday Park" is not working, because they host a script for the webshop on googletagmanager.

They even write [on their website](https://www.holidaypark.de/de/wiederoeffnung-holiday-park-fragen-und-antworten) (translated by Chrome):
![grafik](https://user-images.githubusercontent.com/5798157/132260648-92adada4-709f-4588-8caa-c2e8659e4071.png)

But this is not about "outdated" versions. It's just that several filter lists block googletagmanager in general and hence also block there script at.
```
www.googletagmanager.com/gtm.js?id=GTM-M2XPLS9
```

![grafik](https://user-images.githubusercontent.com/5798157/132260696-e62b8430-a532-499b-a8a4-f45843892ad9.png)
(Peter Lowe's Ad and tracking server list, StevenBlack/hosts with the fakenews and gambling extensions, and this list, 1Hosts (Pro)).

But apart from that, some block lists also block another script file:

```
www.holidaypark.de/sites/default/files/public/google_tag/google_tag.script.js?qxo8te
```

I'm not sure if you want to fix this behaviour. I just wanted to report and let other people know how to fix this issue.
___
The workaround I implemented locally:
```
@@||www.holidaypark.de/sites/default/files/public/google_tag/google_tag.script.js?qxo8te$script,domain=www.holidaypark.de
@@||www.googletagmanager.com/gtm.js?id=GTM-M2XPLS9$script,domain=www.holidaypark.de
```

Cheers!

**Comment by badmojr** [comment]
Can't reproduce! Please provide a link to the mentioned broken page.

**Comment by d-Rickyy-b** [comment]
URL: https://www.holidaypark.de/de

Firefox with uBlock & 1Hosts:
![grafik](https://user-images.githubusercontent.com/5798157/132400948-9f278cf6-d95b-4380-af68-00dcb3d7177d.png)

Edge without uBlock:
![grafik](https://user-images.githubusercontent.com/5798157/132401009-3fe9cadf-db42-468a-a90f-65adecfa3a2a.png)

**Comment by badmojr** [comment]
Got it! 
Related: https://github.com/uBlockOrigin/uAssets/issues/9368, https://github.com/uBlockOrigin/uAssets/issues/8918, https://github.com/AdguardTeam/AdguardFilters/issues/69692

Unfortunately, we only maintain dns/network blocking filters.
Removing the GTM entry, especially from 1Hosts (Pro) is a bad idea. I recommend that manual removal be undertaken.
Sorry!

**Comment by d-Rickyy-b** [comment]
No need to be sorry! I already assumed that adding exceptions for things such as GTM would be hard. At least we got it documented here for people googling for it.
Thank you!
