### ISSUE TITLE
ocsp.entrust.net

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#245]
Hi. 

Not fun but still... Had to pay my property taxes on my iOS government application and the above rule blocked the payment. 

Cheers.

**Comment by badmojr** [comment]
It's CNAME, `e6913.dscx.akamaiedge.net` is the one being blocked.
Will fix ASAP!

**Comment by crssi** [comment]
There are a few more:
`ocsp.verisign.com, ocsp.geotrust.com, ts-ocsp.ws.symantec.com, ocsp.thawte.com` > `e8218.dscb1.akamaiedge.net`

Cheers 😉

**Comment by badmojr** [comment]
😆 😄 
Thank you!

**Comment by badmojr** [comment]
Fixed!
