### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by specter78** [badmojr/1Hosts#247]
`ingame-news.ubi.com` and `events.fgol.mobi` are necessary for playing Ubisoft games.

**Comment by badmojr** [comment]
Hello!
 Any specific errors that you've encountered playing the games?
Mind attaching some screenshots?

**Comment by specter78** [comment]
`ingame-news.ubi.com` is used for in-app offers. `events.fgol.mobi` is used for in-game online competitions. I face the issue in hungry shark iOS game.

**Comment by badmojr** [comment]
I could not find much info on `events.fgol.mobi`. It's was found blocked on the upstream sources below:-
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tracking

Please take it up with any of the sources to get it removed and/or find out more on why it's blocked.

I'll remove the rest from the lists.
