### ISSUE TITLE
Spotify. iOS. No music playing

### ISSUE THREAD

**Issue by Exisfy** [badmojr/1Hosts#248]
1Hosts (Pro). Music is not playing because of this domain: "audio-ak-spotify-com.akamaized.net".

Music that was previously downloaded for offline listening - is played. It's the non-cached and non-downloaded tracks that don't play, i.e. tracks that I turn on for the first time.

If I whitelist this domain, the music will start playing again.

![FD32EEA7-5DF2-4EA5-81D1-DF7D4985A1D6](https://user-images.githubusercontent.com/59131374/134092416-afaf9ce5-e5bd-442a-b715-12b5b3fb16be.jpeg)

**Comment by badmojr** [comment]
Hello! 
Thanks for the detailed info provided.

Origin: https://github.com/DRSDavidSoft/additional-hosts/raw/master/domains/blacklist/adservers-and-trackers.txt
Ping: @DRSDavidSoft

**Comment by DRSDavidSoft** [comment]
@badmojr Issue fixed, also removed similar domains (originally sourced by @opus-x in [here](https://gist.github.com/opus-x/3e673a9d5db2a214df05929a4eee6a57))
```
audio-ak-spotify-com.akamaized.net
audio-akp-spotify-com.akamaized.net
audio-ak.spotify.com.eip.akadns.net
audio4-akp.spotify.com.edgesuite.net
audio4-ak.spotify.com.edgesuite.net
audio-akp.spotify.com.edgesuite.net
audio-ak.spotify.com.edgesuite.net
audio-ake.spotify.com.edgesuite.net
eip-onnet.audio-ak.spotify.com.akahost.net
eip-tata.audio-ak.spotify.com.akahost.net
eip-ntt.audio-ak.spotify.com.akahost.net
```

Personally, I find [https-filtering of 2 urls](https://gist.github.com/opus-x/3e673a9d5db2a214df05929a4eee6a57#gistcomment-3354703) better suited for preventing Spotify ads, it blocks 100% of them.

**Comment by badmojr** [comment]
Thanks David.
