### ISSUE TITLE
wemod.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#249]
Hi @badmojr

My kid found out about `wemod.com`, which is listed in `1Hosts Pro`.

Do you have any simple way to find out the reason to be listed?

Thank you in advance
Cheers

UPDATE: Asking because I cannot find any element as a reason to be listed.

**Comment by badmojr** [comment]
Hola!
It was erroneous parsed from https://hosts.gameindustry.eu/ .

Cheers!

**Comment by crssi** [comment]
Thank you @badmojr . You are efficient as always. 😄 👍
