### ISSUE TITLE
Deny unagi-eu.amazon.com

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#250]
1Hosts (Pro) denies [`unagi.amazon.in`](https://rethinkdns.com/search?q=unagi.amazon.in) and [`unagi.amazon.com`](https://rethinkdns.com/search?q=unagi.amazon.com)

I am not sure which host files those two are sourced from, but should consider adding `unagi-eu.amazon.com` to those very same upstreams so that 1Hosts (Pro) may pick it up for itself.

See also: anudeepND/blacklist/issues/175

**Comment by badmojr** [comment]
Hi!
iirc, this was reported as to be affecting Amazon's autocomplete-/ion.
Couldn't thoroughly verify it. Since u use the service, what's your experirnce with the above said problem?

**Comment by badmojr** [comment]
See also: https://oisd.nl/excludes.php?w=unagi.amazon.co.jp

**Comment by ignoramous** [comment]
Hm, closing this until I figure out a way to test. I'll reopen this issue if autocomplete works fine despite block.
