### ISSUE TITLE
linksynergy.com affiliate links not blocked

### ISSUE THREAD

**Issue by SilkArt** [badmojr/1Hosts#251]
Rakuten Linkshare affiliate links (linksynergy.com) are not blocked. I would like to see them in the filter list.

**Comment by badmojr** [comment]
Hola!
Where did you encounter it? Please provide links.

**Comment by badmojr** [comment]
> Hola!
> Where did you encounter it? Please provide links.

@SilkArt

**Comment by badmojr** [comment]
Last chance @SilkArt . Please share with us the link/page where this was observed.
10x.

**Comment by SilkArt** [comment]
Example: You visit a site for WebRoot SecureAnywhere AntiVirus review. Webroot runs its affiliate program through Linkshare, so for example go to [https://www.pcmag.com/reviews/webroot-secureanywhere-antivirus](https://www.pcmag.com/reviews/webroot-secureanywhere-antivirus). Then you click on "see it" and it leads to [
https://click.linksynergy.com/deeplink?id=yr7LsPS5ySE&mid=24709&murl=https%3A%2F%2Fwww.webroot.com%2Fus%2Fen%2Fhome%2Faffiliates%2Fpcm&u1=007ZjLLI2a3i2QhQ76wwzX8). I've also seen ad.linksynergy.com banners on various sites.

**Comment by badmojr** [comment]
I don't think this (`click.linksynergy.com`) deserves being blocked, 'coz it does not get called ( i.e show on my logs), unless one manually click the affiliate link.

**Comment by SilkArt** [comment]
But what about some https://ad.linksynergy.com banners?

**Comment by SilkArt** [comment]
Ex: https://ad.linksynergy.com/fs-bin/show if you add some tracking parameters to this image it will show a banner ad.

**Comment by badmojr** [comment]
This one has been on the lists for a while now.
Isn't it blocked on your end?

**Comment by SilkArt** [comment]
It also might be a tracking pixel.

**Comment by badmojr** [comment]
I agree. It is blocked though on Lite -> Pro.
Is it not the case for u?

See: https://blocklist-tools.developerdan.com/entries/search?q=ad.linksynergy.com

**Comment by SilkArt** [comment]
Yes, its blocked. So you can close this issue now.

**Comment by badmojr** [comment]
Ok! Thanks for confirmation.
Closing...
