### ISSUE TITLE
unblock cloudproxy.app

### ISSUE THREAD

**Issue by SilkArt** [badmojr/1Hosts#252]
When I try to connect to my Google Cloud Compute Engine Instance via Web SSH, it displays the following error:
"Connection via Cloud Identity-Aware Proxy Failed
Please ensure you can make a proper https connection to the IAP for TCP hostname:[https://tunnel.cloudproxy.app](https://tunnel.cloudproxy.app).
You may be able to connect without using the Cloud Identity-Aware Proxy."
When I visit [https://tunnel.cloudproxy.app](https://tunnel.cloudproxy.app), the uBlock Origin block page appears.
So it is reasonable to unblock cloudproxy.app in hosts file.

**Comment by badmojr** [comment]
Fixed. Thank you!
