### ISSUE TITLE
whitelist referrer.disqus.com

### ISSUE THREAD

**Issue by Uranite** [badmojr/1Hosts#256]
whitelist
referrer.disqus.com
for 1hosts lite it causes disqus to not load for me

**Comment by badmojr** [comment]
Hola!
Where does it happen? Links please.
Screenshots are helpful. Please do share them if possible.

**Comment by Uranite** [comment]
huh now it loads so i guess it was just a coincidence maybe

**Comment by badmojr** [comment]
Uh! 🤣 Sh!7 happens.
Glad u it now resolved.
