### ISSUE TITLE
Blocklist collections?

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#26]
Hi @badmojr 

Do you have anywhere a list of blocklists that are in collection of 1hosts (complete)?

Thank you in advance and wish you best
Cheers

**Comment by badmojr** [comment]
Hey,
The complete variants don't have their own list of blocklists... they borrow their list of domains from the Pro versions.
Confusing?

Just consider the complete versions as toned-down versions of the Pro variants.

**Comment by crssi** [comment]
My bad English... 😉 

I meant what is the sources list for 1hosts (complete)?

If I am informed well, for example the 1hosts (mini) is/was a collection of (consider that I can be very wrong):
```
ABPVN List
AdAway default blocklist - Blocking mobile ad providers and some analytics providers
AdGuard Annoyances filter
AdGuard Base filter
AdGuard Dutch filter
AdGuard English filter
AdGuard French filter
AdGuard German filter
AdGuard Japanese filter
AdGuard Mobile Ads filter
AdGuard Russian filter
AdGuard Safari filter
AdGuard Simplified domain names filter
AdGuard Spanish/Portuguese filter
AdGuard Tracking Protection filter
AdGuard Turkish filter
Adware filters
Anudeep's Blacklist
BadHosts-mai
BarbBlock
Cameleon
EasyList
Fanboy+Easylist-Merged Ultimate List
GJTech
Go-AD
MVPS
NoTrack Tracker Blocklist - Quidsup
Peter Lowe - pgl@yoyo.org
Prigent-Ads
ReddestDream
StevenBlack
UncheckyAds
Vokins
WaLLy3K
YousList
bBlock
bjornStar
hernDL
hostsVN
hpHosts - Ad and Tracking servers only
sbl-dg-ads - Squid-ADs
someonewhocares
turk-adlist
zeroDot1-browsers
```

Cheers

**Comment by badmojr** [comment]
You are right! The above blocklists are used in **1Hosts (mini)**.

The **1Hosts (complete)** versions are made up of  **blocklists used in 1Hosts (mini)** + **some top domains used in 1Hosts (Pro)**.
Hope that's not unclear.

**Comment by crssi** [comment]
Thank you.

Which are the "some top domains used in 1Hosts (Pro)"?

Cheers

**Comment by badmojr** [comment]
> Thank you.
> 
> Which are the "some top domains used in 1Hosts (Pro)"?
> 
> Cheers

Simple!
```
git clone --depth 1 https://github.com/badmojr/1Hosts.git
cd 1Hosts
comm -23 <(sort complete/domains.txt) <(sort mini/domains.txt) >results.txt
```

**Comment by crssi** [comment]
👍 you rock ❤️ 

Thank you and cheers

**Comment by crssi** [comment]
Actually, I am not interested in diff between mini and complete, but which additional sources are added on top of mini. 😉 
Do you have anywhere documented those?

Cheers and stay safe

**Comment by badmojr** [comment]
> Actually, I am not interested in diff between mini and complete, but which additional sources are added on top of mini. 😉
> Do you have anywhere documented those?
> 
> Cheers and stay safe

They aren't any sources added on top of it.
Only partial domains (4k+).

**Comment by crssi** [comment]
Ahhhh... 😄 

Thank you man.

Cheers

**Comment by crssi** [comment]
And I forgot to mention the most important: thank you for your work.
I am using 1hosts (complete) and works very well for me.

Cheers

**Comment by badmojr** [comment]
> And I forgot to mention the most important: thank you for your work.
> I am using 1hosts (complete) and works very well for me.
> 
> Cheers

No, thank you! for the thank.
