### ISSUE TITLE
whitelist bing

### ISSUE THREAD

**Issue by gitthangbaby** [badmojr/1Hosts#264]
r.bing.com is blocked in this list (and Energized Basic+), rendering lot of UI unusable. I've searched the internet and it's the only source of this blocking. It is also whitelisted by blockconvert (https://mkb2091.github.io/blockconvert/). Is this a tracking server?

**Comment by badmojr** [comment]
Hola!
Origin: https://github.com/migueldemoura/ublock-umatrix-rulesets/blob/master/Hosts/ads-tracking
cc: @migueldemoura

I doubt it is. Where does it break the said UI?

**Comment by migueldemoura** [comment]
I can remove it from the list if needed, can you provide a link where blocking that one breaks the website?

**Comment by migueldemoura** [comment]
I can't reproduce this with that URL and settings (there's no request to `r.bing.com`). My crawler hasn't gotten any hits for this host in a while, so I'll investigate this when I get some data. In the meantime, I've moved this host to [ads-tracking-breaking](https://github.com/migueldemoura/ublock-umatrix-rulesets/blob/master/Hosts/ads-tracking-breaking) with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/80f8a17a778bbd412d62a907d36bc7d8b405b3d1.

**Comment by crssi** [comment]
It might be geo position trigered. 

Cheers
