### ISSUE TITLE
Whitelist my-m.lazada.com.ph

### ISSUE THREAD

**Issue by FBIAgent05** [badmojr/1Hosts#267]
It's needed for showing reviews

**Comment by badmojr** [comment]
Links! Links! Where do I reproduce this?

**Comment by badmojr** [comment]
cc: @What-Zit-Tooya
The referenced domains on the above commit originate from https://github.com/What-Zit-Tooya/Ad-Block/raw/main/Main-Blocklist/Ad-Block-HOSTS.txt

**Comment by What-Zit-Tooya** [comment]
Fixed.
If not, just ping me.
