### ISSUE TITLE
anibis.ch

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#268]
Hy @badmojr 
`anibis.ch` listed in PRO seem to be a secondhand market site.

Not saying that it should be de-listed, but I still wonder why it is listed?

Cheers

**Comment by badmojr** [comment]
Hey,
This originates from http://www.shallalist.de/Downloads/shallalist.tar.gz; **adv** category.
You can see it's unpacked version here: https://github.com/cbuijs/shallalist .
