### ISSUE TITLE
g.live.com -> g.msn.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#274]
When visiting OneDrive site, click on link to download onedrive client redirects you to download URL over `g.live.com` where that redirection is blocked by the CNAME `g.msn.com` listed in Pro.

Cheers

**Comment by badmojr** [comment]
cc: @DRSDavidSoft
origin: https://github.com/DRSDavidSoft/additional-hosts/raw/master/domains/blacklist/adservers-and-trackers.txt

David,
This may be of interest to you.

**Comment by DRSDavidSoft** [comment]
@badmojr Thanks for the tip, removed the host! 😃

**Comment by badmojr** [comment]
a'ight!
