### ISSUE TITLE
2ip.ru

### ISSUE THREAD

**Issue by mehov** [badmojr/1Hosts#288]
Hi,

I'm used to using 2ip.ru to quickly check what network am I on, whether my VPN is running, etc.

I just started using your Pro list (thank you for your work), and my dnsmasq.log says you have 2ip.ru banned.

Is there something I don't know about that website? Been using it for 10+ years and it seemed legit to me.

Only downside is it has lots of Google Ads all over the place, but they themselves don't do any ads to my knowledge.

(Or maybe I should use this situation as the tipping point to finally find a new go-to website with less ads.)

**Comment by badmojr** [comment]
Hello!

Origin: https://raw.githubusercontent.com/ookangzheng/blahdns/master/hosts/blacklist.txt
cc: @ookangzheng
