### ISSUE TITLE
[False positive] www.tm.a.prd.aadg.akadns.net is CNAME of Microsoft auth websites

### ISSUE THREAD

**Issue by goodness-from-me** [badmojr/1Hosts#29]
`www.tm.a.prd.aadg.akadns.net` is a CNAME of `login.microsoftonline.com` (Microsoft account login portal) and `mobileappcommunicator.auth.microsoft.com` (Microsoft Authenticator mobile app API).

Both become unusable when `www.tm.a.prd.aadg.akadns.net` is blocked.

**Comment by badmojr** [comment]
Fixed1
