### ISSUE TITLE
Delete sharepoint.com

### ISSUE THREAD

**Issue by Srgr0** [badmojr/1Hosts#295]
Sharepoint is a service of Microsoft, and it is essential for users of that service to resolve this DNS query.
Therefore, I would like to ask you to delete "sharepoint.com".

Thank you.

**Comment by matt2hews** [comment]
Today, due to the changes to Pro, I've whitelisted sharepoint.com, login.windows.net, azurewebsites.net, and ajax.aspnetcdn.com. I'm not sure why these were added - they are critical urls for business.

**Comment by badmojr** [comment]
Hello!

Fixed the root cause of all the recent chaos.
All is fine & this won't happen again!

I apologize for any inconvinience!

related: #296
