### ISSUE TITLE
bit.ly listed in Pro

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#296]
Hi @badmojr... hope you are great 😄 
Lately the `bit.ly` is listed in `Pro` and it causes the problems. 😉

Cheers

**Comment by badmojr** [comment]
Hi! 😄
Should never have been in the first place.
This was all a big, costly, and unintentional mistake.

Sorry for that. Won't happen again!

related: #297

**Comment by crssi** [comment]
I was sure something went south in the last day(s). 😄 

Thank you @badmojr for taking care for us. ❤️

**Comment by matt2hews** [comment]
Thanks @badmojr! Like I said, I whitelisted what I needed. I didn't want anyone else to suffer unnecessarily. I use NextDNS which ingests your updates very aggressively.
