### ISSUE TITLE
Website Broken - intercom.com

### ISSUE THREAD

**Issue by gyCfjSnO** [badmojr/1Hosts#298]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):

```
intercom.com
```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.13

### Detail:

- Your Issue Detail: Breaks the Live Chat function on websites running 'Intercom'. For example unable to use the Live Chat function on Digital Surge website - ```https://digitalsurge.com.au/```

**Comment by badmojr** [comment]
Hello!

Everything works flawlessly on my side.
Please do share some screenshots or any domains, as I'm not able to reproduce this.

**Comment by gyCfjSnO** [comment]
> Hello!
> 
> Everything works flawlessly on my side. Please do share some screenshots or any domains, as I'm not able to reproduce this.

If it's easier when using Blocklist 1Hosts: Pro or Xtra I am unable to visit the website ```intercom.com``` I should be able to view a businesses website.

**Comment by crssi** [comment]
Just heads up 😉 
In case of using NextDNS as solution then blocking `intercom.com` is the same as blocking `*.intercom.com`.

Cheers
