### ISSUE TITLE
blocking graph.facebook.com breaks messenger groups

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#30]
Blocking `graph.facebook.com` breaks facebook messenger invitation messages which as a result prevents you to join groups and receive messages from those.

Cheers

**Comment by badmojr** [comment]
It's blocked deliberately in Complete & Pro packs/variants.
I'm aware it breaks a bunch of Facebook services, but because it's also used to track users (even when not signed in) & serve adverts... it's gonna have to stay blocked.

**Comment by crssi** [comment]
OK... thank you for explanation.

Cheers

**Comment by badmojr** [comment]
If you don't mind, I'll pin this for future references.

**Comment by crssi** [comment]
Not at all. 😃

**Comment by badmojr** [comment]
With **mini**, it's extremely lenient. They gonna have to put up with an occassional ad or 2.

**Comment by crssi** [comment]
Did you mean `connect.facebook.net` or `connect.facebook.com`?

**Comment by badmojr** [comment]
My bad.
`graph.facebook.com,
connect.facebook.net`

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/98874031-0910c180-24ac-11eb-8aac-de19c659c82f.png)

maybe in lite mode should be whitelist, break many function on facebook

**Comment by badmojr** [comment]
I'm aware of that. It's why I recommend users to whitelist it on an individual level.

**Comment by nishaddesilva** [comment]
Maybe you can whitelist ```graph.facebook.com``` & ```connect.facebook.net``` in both MINI and LITE lists and block them only in PRO list because blocking these two domains breaks not only FB messenger, but also the Facebook app itself.
That way you can let the regular users who wants to use Facebook make full use of the LITE list and the highly privacy conscious users can go for the PRO list as desired. PRO list can be your flagship list :)

**Comment by crssi** [comment]
^^ maybe only `graph.facebook.com`, but not `connect.facebook.net`... I would live `connect.facebook.net` blocked

Where do you find that blocking `connect.facebook.net` breaks FB? I am asking since I do not use FB, but my parents do intensively and they do not complain that `connect.facebook.net` would break anything.

**Comment by badmojr** [comment]
> Maybe you can whitelist `graph.facebook.com` & `connect.facebook.net` in both MINI and LITE lists and block them only in PRO list because blocking these two domains breaks not only FB messenger, but also the Facebook app itself.
> That way you can let the regular users who wants to use Facebook make full use of the LITE list and the highly privacy conscious users can go for the PRO list as desired. PRO list can be your flagship list :)

Done!
`graph.facebook.com` removed from all Lite variants.
Will only be blocked on the non-forgiving PRO variants from now on.

**Comment by nishaddesilva** [comment]
> > Maybe you can whitelist `graph.facebook.com` & `connect.facebook.net` in both MINI and LITE lists and block them only in PRO list because blocking these two domains breaks not only FB messenger, but also the Facebook app itself.
> > That way you can let the regular users who wants to use Facebook make full use of the LITE list and the highly privacy conscious users can go for the PRO list as desired. PRO list can be your flagship list :)
> 
> Done!
> `graph.facebook.com` removed from all Lite variants.
> Will only be blocked on the non-forgiving PRO variants from now on.

Great!!! Keep up the good work! :D

**Comment by crssi** [comment]
Thank you @badmojr, you are a 💎 😃
