### ISSUE TITLE
Breaking TikTok Thumbnails

### ISSUE THREAD

**Issue by p1r473** [badmojr/1Hosts#300]
Hi,
The *.ttlivecdn.com.* and *.fcdn.us.tiktokv.com.* and *.tiktokcdn-us.com.* blocks are breaking TikTok thumbnails. I am using Deep Packet Inspection which is blocking CNAMEs

I would recommend not blocking CDNs (Content Delivery Networks) as they serve all sorts of content, valid domains included.
I wish I could provide the domains, but there are so many of them, and Im not sure which is doing what.

While trying to figure out exactly which domain was causing the issues, I ended up trying to whitelist more than 20 domains, unable to figure out which was the culprit.
For example, it could have been:
push-rtmp-f5-gcp01.ttlivecdn.com.c.worldfcdn.com (CNAME for push-rtmp-f5-gcp01.ttlivecdn.com)
push-rtmp-f5-tt01.fcdn.us.tiktokv.com.c.worldfcdn2.com (CNAME for push-rtmp-f5-tt01.fcdn.us.tiktokv.com)
pull-f5-va01.ttlivecdn.com.c.worldfcdn.com (CNAME for pull-f5-va01.ttlivecdn.com)
p16-ad-sg.ibyteimg.com
p16-sign.tiktokcdn-us.com
frontier-va.tiktokv.com
Or one of countless others.

There are literally tons of these and iterations like these in the traffic logs. Without being familiar with TikTok's architecture and load balancers, I have no idea. I am trying to whitelist one at a time but there are so many I can't figure it out.

![Screenshot_20211103-214349](https://user-images.githubusercontent.com/9235633/140244643-69c79b48-d762-403c-98ed-48daad461f9f.png)

**Comment by p1r473** [comment]
I am linking these 2 issues because out of my [500 blocklists](https://github.com/p1r473/hosts/blob/master/hosts.txt), only these two are blocking these domains
![image](https://user-images.githubusercontent.com/9235633/140246648-65afb8ce-57ca-4457-a691-529421e9882f.png)
https://github.com/EnergizedProtection/block/issues/824

**Comment by p1r473** [comment]
Theres so much TikTok traffic I cant for the life of me figure out which are breaking thumbnails
Here are some of the ones I am seeing now
pull-cmaf-f5.tiktokcdn.com.c.worldfcdn.com
pull-f5-ab.tiktokcdn.com.c.worldfcdn.com
pull-f5-gcp01.tiktokcdn.com.c.worldfcdn.com
pull-f5-gcp01.ttlivecdn.com.c.worldfcdn.com
pull-f5-sg01.tiktokcdn.com.c.worldfcdn.com
pull-f5-sg01.ttlivecdn.com.c.worldfcdn.com
pull-f5-tt01.tiktokcdn.com.c.worldfcdn.com
pull-f5-va01.ttlivecdn.com.c.worldfcdn.com
pull-q5-sg01.tiktokcdn.com.c.worldfcdn.com
pull-q5-va01.tiktokcdn.com.c.worldfcdn.com
pull-w5-sg01.tiktokcdn.com.c.worldfcdn.com
pull-w5.tiktokcdn.com.c.worldfcdn.com
pull-w5-va01.tiktokcdn.com.c.worldfcdn.com
push-rtmp-f5-ab.tiktokcdn.com.c.worldfcdn.com
push-rtmp-f5-gcp01.tiktokcdn.com.c.worldfcdn.com
push-rtmp-f5-gcp01.ttlivecdn.com.c.worldfcdn.com
push-rtmp-f5-sg01.tiktokcdn.com.c.worldfcdn.com
push-rtmp-f5-sg01.ttlivecdn.com.c.worldfcdn.com
push-rtmp-f5-va01.ttlivecdn.com.c.worldfcdn.com

**Comment by badmojr** [comment]
How about now? Works okay, I guess?

**Comment by p1r473** [comment]
I will do some testing and let you know
Thanks

**Comment by badmojr** [comment]
@p1r473,
Anything new you've observed & wanna share?

**Comment by p1r473** [comment]
They seem to be working now, so I will close the issue, and will reopen if it reoccurs.
I am also waiting for the domains to be fixed from the linked Energized Protection block list
