### ISSUE TITLE
App Broken - mybbc-analytics.files.bbci.co.uk

### ISSUE THREAD

**Issue by gyCfjSnO** [badmojr/1Hosts#301]
### Issue(s):

- App Broken

### Domain(s):

- Domain(s): ```mybbc-analytics.files.bbci.co.uk```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.13

### Detail:

- Unable to load BBC iPlayer app on Google/Android TV. When whitelisting the domain the app is able to be loaded.

### Blocklist: 

- 1Hosts (Lite)

**Comment by badmojr** [comment]
origin:
http://abpvn.com/android/abpvn.txt
https://github.com/pirat28/IHateTracker/raw/master/iHateTracker.txt
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
https://someonewhocares.org/hosts/zero/hosts
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt
https://raw.github.com/anudeepND/blacklist/master/adservers.txt
https://github.com/ftpmorph/ftprivacy/raw/master/regex-blocklists/smartphone-and-general-ads-analytics-regex-blocklist-ftprivacy.txt
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.tx
https://github.com/migueldemoura/ublock-umatrix-rulesets/raw/master/Hosts/ads-tracking
https://github.com/parseword/nolovia/raw/master/skel/hosts-nolovia.txt
https://raw.githubusercontent.com/tiuxo/hosts/master/ads
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tracking

cc: @pirat28, @anudeepND, @ftpmorph, @lightswitch05, @migueldemoura, @parseword, @tiuxo, @ShadowWhisperer

**Comment by badmojr** [comment]
@crssi,
What do u think?

**Comment by crssi** [comment]
Sorry 😢 , but I am not from UK and I don't think I could try BBC Player without some sort of subscription.

Otherwise I would be happy to help.

**Comment by ShadowWhisperer** [comment]
I see it also whitelisted here: _https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212/135_

The _BBC News_ app (Android Phone) does call out to it, and fully functions, when blocked.

_https://www.bbc.co.uk/iplayer_ Also calls out to it.

Not being from the UK, I am unable to test further.

**Comment by migueldemoura** [comment]
I'm afraid I'm unable to reproduce the issue.

However if you'd like, I'm happy to move the host from:
https://github.com/migueldemoura/ublock-umatrix-rulesets/raw/master/Hosts/ads-tracking to https://github.com/migueldemoura/ublock-umatrix-rulesets/raw/master/Hosts/ads-tracking-breaking
while this gets investigated.

**Comment by gyCfjSnO** [comment]
Please let me know how I can help in reproducing the issue.

**Comment by badmojr** [comment]
Maybe attach a video or some screenshots.
@gyCfjSnO

**Comment by ftpmorph** [comment]
I am in the UK and am perfectly able to watch BBC iPlayer. This domain does get called but iPlayer works fine without it. I will try it on Google TV specifically soon to see if I can reproduce the issue.

**Comment by gyCfjSnO** [comment]
I'm trying to replicate on Android Mobile device so I can screen record but can't replicate the issue. It's only persistent on Android TV. I don't particularly want to have to record my TV/living room and somehow also show at the same time blocking and unblocking of the domain in AdGuard Home.

**Comment by badmojr** [comment]
Since this is definetely used for tracking, and only affects TVs; it's gonna have to stay blocked on Pro - Xtra.
