### ISSUE TITLE
Website Broken - self.events.data.microsoft.com

### ISSUE THREAD

**Issue by gyCfjSnO** [badmojr/1Hosts#304]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):

```self.events.data.microsoft.com```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail:

Endpoint ```self.events.data.microsoft.com``` is used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser. If you turn off traffic for these endpoints, users won't be able to save documents to the cloud or see their recently used documents.

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints

**Comment by badmojr** [comment]
I'm afraid this one got to stay on Pro - Xtra.
Will remove it from **Lite** though.

**Comment by crssi** [comment]
@gyCfjSnO I have tried to reproduce your problem, but failed.

1. logged on to office.com with enterprise account
2. pick one of the recent docs and made some changes
3. the changed doc was saved OK
4. the changed doc was moved to the most recent document

Can you recheck and write exact steps for reproduction.
