### ISSUE TITLE
media.architecturaldigest.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#307]
Should `media.architecturaldigest.com` really be blocked in `Pro`?

See example page `https://www.architecturaldigest.com/story/european-town-built-resemble-lego-blocks`.

Cheers

**Comment by badmojr** [comment]
origin: https://github.com/migueldemoura/ublock-umatrix-rulesets/raw/master/Hosts/ads-tracking
cc: @migueldemoura

**Comment by crssi** [comment]
The exclusion does not work.
Is there everything OK behind the scenes?

Cheers and thank you

**Comment by migueldemoura** [comment]
It's a false positive, removed it with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/7ed375350dd2e65d3c2728045547ea664caf13fb and added it to my allowed list so it doesn't get flagged again by mistake. Thanks, @crssi!

**Comment by crssi** [comment]
Thank you both @badmojr and @migueldemoura
👍

**Comment by badmojr** [comment]
> The exclusion does not work. Is there everything OK behind the scenes?
> 
> Cheers and thank you

It's additionally blocked through CNAME, i.e **vulcan.condenastdigital.com**

**Comment by badmojr** [comment]
What the  fu!?

**Comment by badmojr** [comment]
What say you @crssi ?

**Comment by crssi** [comment]
I would say a good catch 👍 😄

**Comment by badmojr** [comment]
@crssi 
Should we remove the exclusion then? :)

**Comment by crssi** [comment]
Yes, please. 👍 

Thank you ❤️
