### ISSUE TITLE
get-express-vpn.space

### ISSUE THREAD

**Issue by minoplhy** [badmojr/1Hosts#308]
should be block

**Comment by badmojr** [comment]
I see you already have have it included on https://github.com/minoplhy/filters/raw/main/Resources/blocked.txt, which we actively source as seen in https://github.com/badmojr/1Hosts/blob/master/-data/lists/assets.txt#L218 .

It will be automatically picked so there's no need to re-add it. 10X!

**Comment by minoplhy** [comment]
didn't notice that, sorry!
