### ISSUE TITLE
Website Broken - ||analytics.linkre.direct^

### ISSUE THREAD

**Issue by gyCfjSnO** [badmojr/1Hosts#312]
I am trying to open a water bill I have received from my utility provider but when trying to open it I get a `DNS_PROBE_FINISHED_NXDOMAIN` error message. When checking logs in AdGuard Home the request was blocked as rules matched your blocklist 1Hosts (Lite) `||analytics.linkre.direct^`. Whitelisting the domain allows me to access my bill for my water usage.

**Comment by badmojr** [comment]
To be unblocked only on Lite.
