### ISSUE TITLE
cookie and marketing

### ISSUE THREAD

**Issue by saurane** [badmojr/1Hosts#313]
list: 1hosts pro
client: nextdns

cookie: cookielaw.emea.fcagroup.com
marketing: ibmmarketingcloud.com

**Comment by badmojr** [comment]
Any pages where I can find these being actively used? Share please!

**Comment by saurane** [comment]
https://www.fiat.com.tr/
https://otomobil.fiat.com.tr/
Trust me, I'm not reporting dead domains.

**Comment by badmojr** [comment]
It's not that I don't believe you, I just like to be thorough. :)
