### ISSUE TITLE
RPZ zonenames

### ISSUE THREAD

**Issue by spirillen** [badmojr/1Hosts#315]
if you appended a "real" zone name I could hosts these over real DNS servers via IXFR...

Example this is the current SOA with no `$zone.name`
```
@ SOA localhost. root.localhost. 1637501490 43200 3600 259200 300
  NS  localhost.
```

if you changers this to for example

```
xtra.1hosts.rpz 86400   IN      SOA     ns1.mypdns.org. need.to.know.only. 2021042716 300 60 604800 3600
xtra.1hosts.rpz 86400   IN      NS      ns1.mypdns.org.
xtra.1hosts.rpz 86400   IN      NS      ns2.mypdns.org.
```
(My syntax is in absolutes do to powedns)

Then I could load it in to my powerdns and distributed them via IXFR.
Another huge beneficial is when you have to track down from which zone a records was served from (log output)

PS: RPZ zone files does not requires NS records (but they are good to have for exchanging data :smirk:

**Comment by badmojr** [comment]
Hola!

We mainly act as distributors of the feeds. You are very welcome to play around with them, make some changes & see what best fits your specific usecase.
As for your above request; There's no place like 127.0.0.1 so let's leave it at it.
