### ISSUE TITLE
tracker or analytics, i dont know.

### ISSUE THREAD

**Issue by saurane** [badmojr/1Hosts#316]
domain: a.fc4d74be804f943caa3621b864c54ff0d19c0aca87671ceb51aec5e8.com
I don't know where it came from, maybe TikTok.

nextdns log ss
![oa](https://user-images.githubusercontent.com/87908352/142978278-939acfe2-6ffa-4656-b5db-b22ec2fe24d9.png)

yeah, of course from TikTok app
![11](https://user-images.githubusercontent.com/87908352/142978809-756efc89-236a-4bb5-9e7c-6a393085d861.png)

**Comment by spirillen** [comment]
Having the full url would have help to know which script is was calling, hence a change to read the purpose.

**Comment by badmojr** [comment]
It's blocked by Xtra... :)

**Comment by spirillen** [comment]
> It's blocked by Xtra... :)

As adware? or Tracking? Spyware? or something else?

**Comment by badmojr** [comment]
siblings of such domain can be found on :
https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Ads#L236
https://github.com/AdguardTeam/AdguardFilters/blob/master/MobileFilter/sections/adservers.txt#L97

So, I'd say all the categories above.

see also: #198
