### ISSUE TITLE
Add metric.gstatic.com to blocklist

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#317]

**Comment by spirillen** [comment]
Seems like a god suggestion :)

```
metric.gstatic.com   CNAME . ; Tracking
*.metric.gstatic.com   CNAME . ; Tracking
```

<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/issues/-/issues/67

</details>

**Comment by spirillen** [comment]
PS:

You should make them as wildcard...

|name|type|content|
|----|----|-------|
|v6exp3-v4.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|
|p5-lj5aujgj7jl7w-r2pmxqvndsgx2im2-931517-i1-v6exp3-v4.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|
|p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-164149-i1-v6exp3-v4.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|
|p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-164149-s1-v6exp3-v4.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|
|p2-n3zurhre4jjvk-can5rb2f2a4urcxh-if-v6exp3-v4.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|
|p2-f6rp6piuxns4u-uzq4vp76bu3w2tso-if-v6exp3-v4.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|
|p2-aahhyknavsj2m-wtnlrzkba6lht33q-if-v6exp3-v4.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|
|p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-if-v6exp3-v4.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|
|v6exp3-ds.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|
|p5-lj5aujgj7jl7w-r2pmxqvndsgx2im2-931517-i2-v6exp3-ds.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|
|p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-164149-i2-v6exp3-ds.metric.gstatic.com.rpz.mypdns.cloud|CNAME|.|

**Comment by crssi** [comment]
Just FYI... see `https://help.nextdns.io/t/60hz6md/metric-gstatic-com-is-not-blocked-but-it-should-be`

Cheers

**Comment by spirillen** [comment]
> 

I most say i greatly agree with you here @crssi 

https://help.nextdns.io/t/60hz6md?r=35hzmc3

But there is one question left unanswered, and with the common knowledge of google anti-privacy:
Why all these uniq urls?? `*-dnsotls-ds.metric.gstatic.com` it stinks of spying as you also indicates in the thread.

NOTE: Just like @crssi I have never had any issue blacking `*.metric.gstatic.com`

**Comment by crssi** [comment]
From my observation the `*-dnsotls-ds.metric.gstatic.com` requests are made only by android devices when `Private DNS` is enforced.
Other `metric.gstatic.com` requests are extreme rarity and made, again, only by android devices or devices connected/logged-in somehow with `google`.

In both cases the user is already `busted` by `google` and I don't see a reason to block those.

But, that is just my humble opinion and I will leave the decision to joda-fu masters like you and @badmojr.

Cheers

**Comment by spirillen** [comment]
> In both cases the user is already busted by google and I don't see a reason to block those.

5 minutes of laughing, couldn't agree more, but no reason to give them more than necessary and help them.

**Comment by badmojr** [comment]
Couple of notes:
https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/d91e954f8537844ffeb8c295a05dc476a719536c/Filters/exceptions.txt#L168
https://github.com/notracking/hosts-blocklists/issues/504
https://ipv6test.google.com/


I seems Google mostly uses the domain for debugging/diagnostic purposes i.e 'connectivity check' and not for tracking per se.

**Comment by spirillen** [comment]
I can't make the same assumption.

I have 2 android's a tablet and a Nvidia shields and both are behind my DNS firewall, which is blocking

```
ssl.gstatic.com.blacklist.matrix.lan
*.metric.gstatic.com.tracking.mypdns.cloud
```

Plus I in the local dnsdist have these

```
addAction(RegexRule('time(\\d+)?[.](android|google)[.]com'), SpoofCNAMEAction('nfs.matrix.lan'))
addAction(RegexRule('(^|(www|play|connectivitycheck|cloudconfig|clients([0-9]{1}|[.]l)|firebaseinstallations|play)[.])(android|google|gstatic|googleapis)[.][a-z]{2,5}(([.][a-z]{2})?)$'), SpoofAction('192.168.1.5'))
```

There are only issues IF I mistakenly getting launched a app that try to connect to the `play "store"`

On `192.168.1.5` I then have set up NGINX to play gstatic.com|android etc. to spoof all the unneeded "connectivity" and "time" `checks`

**Comment by badmojr** [comment]
The evidence points to this being used for legit purposes, hence blocking it breaks a couple of features.
Unless I see the evidence otherwise, this is gonna have to stay unblocked.

**Comment by badmojr** [comment]
Thanks everyone for chiping in.
Closing...

**Comment by Rexadev** [comment]
Can be added to extreme list

**Comment by badmojr** [comment]
No.

**Comment by spirillen** [comment]
@Rexadev if you like you can apply your existing list with mine, **_HOWEVER_** these lists requires you to maintain your own whitelist, as I will not participate in what should be spying upon anybody, that is a personal choice: https://mypdns.org/my-privacy-dns/matrix#faq
