### ISSUE TITLE
Add *.android-appboot.netflix.com to blocklist

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#318]
Reason nothing breaks and must be spying.

**Comment by badmojr** [comment]
I dare you to:
- block the domain
- 'clear data' of Netflix app
- Re-launch the Netflix app

**Comment by spirillen** [comment]
I dare you to:
- Block the domain
- close netflix app
- 'clear data' of Netflix app
- uninstall the Netflix app

You gain the flexibility to obtain better quality videos and better privacy with hole less tracking :yum:

**Comment by badmojr** [comment]
I tried blocking this domain before & it did not go well.

see:
https://t.me/EnergizedProtection/124522
https://blocklist-tools.developerdan.com/entries/search?q=android-appboot.netflix.com

**Comment by spirillen** [comment]
t.me is blacklisted with me, could you hand the real url of destination?

The above was mostly meant as a bit of fun to your comment as I'm no fan of people making money by selling only 1/8 of the actual product. (You only get between 1/4 and 1/8 of the images in the image stream compared to a full video stream)

**Comment by badmojr** [comment]
Here's a screenshot.
![JHBSKIKjkls](https://user-images.githubusercontent.com/40524316/143595227-00411dae-c162-40b1-9973-aebb39e50b0f.PNG)

**Comment by spirillen** [comment]
Makes one think, how can it be protection if you removes the protection. kind a like:

Her: did you wear a condom while we **BLIIP**
Him: I sure did darling, It never left my pocket...

**Comment by badmojr** [comment]
Regardless, this isn't candidate for inclusion. I suggest manual blocking be undertaken.
Sorry!

**Comment by Rexadev** [comment]
> Regardless, this isn't candidate for inclusion. I suggest manual blocking be undertaken. Sorry!

Can it added to extreme list

**Comment by badmojr** [comment]
Wich extreme list are u refering to?
There isn't such a list.

**Comment by spirillen** [comment]
@Rexadev do you actually have any data that supports your suspicion of this sub-domain is used for tracking?

**Comment by Rexadev** [comment]
> I dare you to:
> 
> * block the domain
> * 'clear data' of Netflix app
> * Re-launch the Netflix app

Did it and I it works I can clear data and login again with the domain blocked

**Comment by spirillen** [comment]
> Did it and it works I can clear data and login again with the domain blocked 

I for sure find this interesting, but as @badmojr mentioned https://github.com/badmojr/1Hosts/issues/318#issuecomment-977802484 a few more who can confirm this observation would be needed
