### ISSUE TITLE
cdn.bestreviews.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#319]
`bestreviews.com` uses quite a lot of `cdn*.bestreviews.com`
See for example site `https://bestreviews.com/best-pulse-oximeters`

Is there any point to block only `cdn.bestreviews.com` and not the others?
With blocking `cdn.bestreviews.com` the images in this site does not get updated.

Cheers

**Comment by spirillen** [comment]
Hey @crssi why is it you believe `cdn.bestreviews.com` should be blacklisted?? When I visit the link above I do not see anything that caught my eyes as undesired

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 |  |  | bestreviews.com | 1 | image | `https://cdn.bestreviews.com/images/v4desktop/image-full-page-1040/b3af15f15539a887b3ff9f3af537ab94.jpg` |
| +1 |  |  | bestreviews.com | 1 | image | `https://cdn.bestreviews.com/images/v4desktop/layout-120x120px/56797f5b7eff5a82d05eac830738734a.jpg` |
| +1 |  |  | bestreviews.com | 1 | image | `https://cdn.bestreviews.com/images/v4desktop/layout-120x120px/fbaf3230fa7373c8ab79fac1050a17fb.jpg` |
| +1 |  |  | bestreviews.com | 1 | image | `https://cdn.bestreviews.com/images/v4desktop/layout-120x120px/a0dad0731621223f311c9fbfde7a59b8.jpg` |
| +1 |  |  | bestreviews.com | 1 | image | `https://cdn.bestreviews.com/images/v4desktop/image-full-page-680/442519eb62e51e3508a71b8ca413eeda.jpg` |
| +1 |  |  | bestreviews.com | 1 | image | `https://cdn.bestreviews.com/images/v4desktop/layout-120x120px/80ec6964969c267985649a22c5a86190.jpg` |
| +1 |  |  | bestreviews.com | 1 | image | `https://cdn.bestreviews.com/images/v4desktop/layout-120x120px/ce35aad2cd1d154eb8367cdd3875d987.jpg` |
| +1 |  |  | bestreviews.com | 1 | image | `https://cdn.bestreviews.com/images/v4desktop/image-full-page-1040/ec19ce5e5def40a148584cbf7289710e.jpg` |
| +1 |  |  | bestreviews.com | 1 | image | `https://cdn.bestreviews.com/images/categories/desktop/h-w1-cd80.jpg` |
| +1 |  |  | bestreviews.com | 1 | image | `https://cdn.bestreviews.com/images/logo.svg` |
</details>

**Comment by crssi** [comment]
Not blacklisted, but might needing to be **delisted** from `Pro`.

Cheers
