### ISSUE TITLE
Add these Amazon Tracking links

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#322]
*.asmw.amazon.in
*.msh.amazon.in
*.alexa-smart-nudge.amazon.in

**Comment by badmojr** [comment]
Please include more details about the domains.
There isn't much here to work with.

**Comment by badmojr** [comment]
@Rexadev

**Comment by Rexadev** [comment]
> @Rexadev

Blocked it doesn't break anything. These are created by amazon shopping android app.

**Comment by badmojr** [comment]
Sorry! Still no proof.

**Comment by spirillen** [comment]
> Sorry! Still no proof.

@badmojr I thinks showing some example of what we would expect is a solution here as he obviously want to helps out I think it can be to a mutual beneficial to explain what information we needs to base our decisions from.

Just to point to a couple of related situations:
- https://github.com/tiuxo/hosts/pull/33#pullrequestreview-817175244
- https://github.com/tiuxo/hosts/pull/40#issuecomment-981714233

@Rexadev This is not to provoke you or anything badly intended, but as mention before, you would need to provide more information to for example a script, you provide at minimum the full URL to that script encapsulated in back-ticks ``` to avoid linking to potential badware and if possible extract the code part you suspect and post the inside a code-block 
![image](https://user-images.githubusercontent.com/44526987/144264647-2f00d253-5a84-4d26-828b-2f1fcbd9fbef.png) This one from the text areas menu.

The same here: https://github.com/tiuxo/hosts/pull/37#discussion_r759341677 where you reply that you some where on the domain found something. Cool, but where??
You are needed to provide information about:
1. Where did find this (Most of the times a `link`)
2. How did/do you find this contents (for replication) to confirm your provided data.

And lastly @Rexadev don't believe we are after you, we are literally trying to help you understand the environment surrounding the blacklist maintenance to make you a ACTIVE and POSITIVE contributor rather than a time consuming source only serving pure quality contributions.

Al this said, I have this made this [guide](https://mypdns.org/mypdns/support/-/wikis/Contributing) for contributing, Let me just be the first one admit it can handle more work and any contributions are welcome. When/If you read the guide, keep in mind it is supported by the issue templates that is used per project.

Hoping we ca help each other here on several levels and that there will be a will to ongoing constructive cooperation.

**Comment by spirillen** [comment]
PS: forgot to mention my writers guide, which is a very important appendix to the contribution document: https://mypdns.org/mypdns/support/-/wikis/contributing/Writing-Guide

**Comment by badmojr** [comment]
Closing.. for lack of enough actionable details.
