### ISSUE TITLE
Add aliyuncs.com to blocklist

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#323]

**Comment by badmojr** [comment]
Please include more details about the domain.
There isn't much here to work with.

**Comment by badmojr** [comment]
@Rexadev

**Comment by Rexadev** [comment]
> @Rexadev

Some app tries to use DoH with this domain. It is owned by alibaba cloud and the device doesn't use its services. Maybe Paytm App or Xiaomi connects to it. 
Blocking doesn't break anything. 
Also most of the sub domains are blocked by other blocklists

**Comment by badmojr** [comment]
I'm sorry! Still not enough proof to warrant a block!

**Comment by spirillen** [comment]
@badmojr I did actually read something about this (DoH in alibaba software/codebase) in another project... was it easylist ?

Non the less this is an old known tracker. Issue with log output can be found here: https://mypdns.org/my-privacy-dns/matrix/-/issues/1932

**Comment by badmojr** [comment]
Lacks enough actionable details. Hence, I suggest manual blocking be undertaken,
Closing..
