### ISSUE TITLE
Breaking thumbnails interia.pl

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#326]
used list: Lite
subdomain: hit.interia.pl
![Zrzut ekranu z 2021-11-30 01-02-53](https://user-images.githubusercontent.com/80338577/143961887-2be83986-c079-479b-9c8c-b2dd4db5b637.png)
![Zrzut ekranu z 2021-11-30 01-03-05](https://user-images.githubusercontent.com/80338577/143961892-e5977a5b-d1bf-4ef1-a5cf-26dd5fefbdc5.png)

**Comment by badmojr** [comment]
Hello! Any speciifc page that this happens?
Having a hard time getting to any page where I can reproduce this.

Please share the link to the above page's screenshot.

**Comment by badmojr** [comment]
nvm. It was on the homepage! 🙊

**Comment by badmojr** [comment]
Resolved! 👌🏾 

closing...
