### ISSUE TITLE
Domains breaking embedded videos

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#329]
redefine.hit.stat24.com
https://panstwowpanstwie.polsatnews.pl/odcinek/to-sie-musialo-tak-skonczyc/
![Zrzut ekranu z 2021-11-30 04-44-14](https://user-images.githubusercontent.com/80338577/143982145-4ea370ce-2444-4982-81e7-5c449ab8ffa8.png)

ipla.hit.stat24.com
https://www.polsatnews.pl/wiadomosc/2021-11-29/koronawirus-raport-dnia-rzadowy-pakiet-alertowy-poniedzialek-29-listopada/?ref=slider
![Zrzut ekranu z 2021-11-30 04-45-03](https://user-images.githubusercontent.com/80338577/143982240-f519f26f-e208-4dfc-a9df-cefc5a2a58c0.png)

**Comment by badmojr** [comment]
Hello!

Couldn't verify if the last link works alright 'coz the video is unavailable due to geolocation.
Re-check & reopen if it still doesn't work.
