### ISSUE TITLE
whitelist go-mpulse.net

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#330]
https://github.com/StevenBlack/hosts/issues/1756

**Comment by badmojr** [comment]
Couldn't find any proof from the above. Only a report that wasn't even verified.
Sorry! It's gonna have to stay blocked.

**Comment by spirillen** [comment]
This domain is [Tracking](https://mypdns.org/mypdns/support/-/wikis/TrackWare) : https://mypdns.org/my-privacy-dns/matrix/-/issues/3518 My personal opinion is to leave it with the information that some "dealers" chooses to collect and share your data and if you really like this to de the case with you purchase (data selling) Please do greylist this on your own. This is your warning.
