### ISSUE TITLE
ads or tracker

### ISSUE THREAD

**Issue by saurane** [badmojr/1Hosts#331]
Client: NextDNS
Used list: 1Hosts pro, energized ultimate and other
from TikTok APP

1-) tnc16-alisg.byteoversea.com (blocked by my blacklist / not on any list)
2-) a.f18597036f4034883ad83eaeb38250b39241210076555a33a60171b6.com (not on any list)

Domains in the screenshot:
a.f18597036f4034883ad83eaeb38250b39241210076555a33a60171b6.com
a.6984f5d294b35c5575efc0312f3e6e03bbb4437adb0e92f297ec07e1.com
a.320981a9244924ef86ebdbb9eb877e9f21ce83f1e3cc89b2c5e7c3ff.com

tnc16-useast1a.byteoversea.com
tnc16-useast1a.isnssdk.com
tnc16-alisg.byteoversea.com

![Ekran görüntüsü 2021-11-30 114618](https://user-images.githubusercontent.com/87908352/144015707-99671c2f-029e-4e35-855c-b881a20a472f.png)

**Comment by badmojr** [comment]
Hello!

available on Xtra.
```
a.f18597036f4034883ad83eaeb38250b39241210076555a33a60171b6.com
```
<br>

available on Pro, & Xtra.
```
tnc16-useast1a.byteoversea.com
a.6984f5d294b35c5575efc0312f3e6e03bbb4437adb0e92f297ec07e1.com
```
<br>

available on mini, Lite, Pro, & Xtra.
```
a.320981a9244924ef86ebdbb9eb877e9f21ce83f1e3cc89b2c5e7c3ff.com
tnc16-useast1a.isnssdk.com
```
<br>

not blocked yet. Probably becaused I messed up in https://github.com/badmojr/1Hosts/commit/3e39fa7e4d6b0e1d6cf93598a3133bdc4d27777e 🤣 
```
tnc16-alisg.byteoversea.com
```
