### ISSUE TITLE
amd driver setup log

### ISSUE THREAD

**Issue by saurane** [badmojr/1Hosts#335]
subdomain: amd-athena-rs-install-logs.s3.amazonaws.com
app: radeon software installer

**Comment by spirillen** [comment]
Doing what

**Comment by saurane** [comment]
> Doing what?
> 

Log request of AMD Radeon installer.

**Comment by spirillen** [comment]
Ok I elaborate :smiley:  Should I understand this as it should be considered / handled as tracking, because:

The log process while installing some of AMD's drivers automatically and without user consent are sending identifiable data to amazons network?

**Comment by saurane** [comment]
> Ok I elaborate :smiley:  Should I understand this as it should be considered / handled as tracking, because:
> 
> The log process while installing some of AMD's drivers automatically and without user consent are sending identifiable data to amazons network?

It sends a log while manually installing the Amd driver.
