### ISSUE TITLE
kaspersky statistic and other

### ISSUE THREAD

**Issue by saurane** [badmojr/1Hosts#336]
subdomain: statistic.content.ipm-klca.kaspersky.com
client: nextdns
app: kaspersky internet security

blocked: ff.kis.v2.scr.kaspersky-labs.com

not blocked: gc.kis.v2.scr.kaspersky-labs.com
not blocked: kis.v2.scr.kaspersky-labs.com

**Comment by badmojr** [comment]
Got proof they are trackers?

**Comment by saurane** [comment]
> Got proof they are trackers?

statistic.content.ipm-klca.kaspersky.com : It always sends a request when entering any website in the browser, and it's obvious from its name, it's a tracker.

gc.kis.v2.scr.kaspersky-labs.com and kis.v2.scr.kaspersky-labs.com : This domain is in the 1Hosts Pro list, I think it should be added to the list because of the subdomain similarity. 

Blocking them won't break anything. I don't use now Kaspersky anymore so I can't provide you with a proof.

**Comment by badmojr** [comment]
**statistic.content.ipm-klca.kaspersky.com**: Will be added.
The rest won't. Sorry but I can't block them based on that reason.

**Comment by badmojr** [comment]
Taking @ spirillen's above suggestion, I believe that 'does not break anything' isn't sufficient enough to warrant a block least we break core, and critical functionalities of the said product.
Sorry @saurane .
