### ISSUE TITLE
Add samsungpositioning.com to the blocklist

### ISSUE THREAD

**Issue by MrBridgeSix** [badmojr/1Hosts#337]
Domain used by Samsung phones to get general location data, my 2 Samsung phones manage to query this domain 10k times a day, I've been blocking it manually for the past 2 weeks have not noticed anything to be broken, even find my device still works fine.

**Comment by spirillen** [comment]
Thanks @MrBridgeSix

**Comment by badmojr** [comment]
It's listed for removal @ https://github.com/EnergizedProtection/unblock/blob/master/basic/formats/domains.txt#L1327
Sorry! Gonna need more satisfactory evidence as to its alleged abuse of users' data.

**Comment by MrBridgeSix** [comment]
> It's listed for removal @ https://github.com/EnergizedProtection/unblock/blob/master/basic/formats/domains.txt#L1327 Sorry! Gonna need more satisfactory evidence as to its alleged abuse of users' data.

Okay, If it has been whitelisted it must break something, I simply blocked the domain because of the sheer amount of queries to it and have not observed anything to be broken after doing so. I lack the knowledge necessary to provide the evidence requested so I will be closing this issue. Thanks!
