### ISSUE TITLE
False Positive : alawar.com, tempspeedtest.nl1.privex.cc, tor-exit-nl1.privex.cc, tor-exit-se1.privex.cc

### ISSUE THREAD

**Issue by minoplhy** [badmojr/1Hosts#339]
alawar.com is Alawar Game Publisher Site
tempspeedtest.nl1.privex.cc is Temporary speed test site for Privex Netherlands region
tor-exit-nl1.privex.cc ?
tor-exit-se1.privex.cc ?

**Comment by badmojr** [comment]
marked as malicious:
https://www.virustotal.com/gui/domain/tempspeedtest.nl1.privex.cc

**Comment by badmojr** [comment]
1 detected files communicating with this domain:
https://www.virustotal.com/gui/domain/alawar.com/relations

**Comment by minoplhy** [comment]
In Case of tempspeedtest.nl1.privex.cc and tor-exit-nl1.privex.cc since they're hosting on the same ip (VirusTotal detection didn't get much info on Domain Name so i'll go with plain ip{185.130.47.58}). This ip had been flagged by 5 security vendors as malicious . But seem like it had been flagged because Some Malicious file HTTP Requests to its Tor Directory in Node along with others node . including tor-exit-se1.privex.cc . so i don't think tempspeedtest.nl1.privex.cc, tor-exit-nl1.privex.cc and tor-exit-se1.privex.cc should be block because of that


![image](https://user-images.githubusercontent.com/67270651/146013857-a84f22bd-9da3-484b-ad7b-5da9eefd222d.png)

**Comment by badmojr** [comment]
origin: https://www.threatsourcing.com/dnall-free.txt

A reputable list. I'm yet to be convinced otherwise.
Sorry!

**Comment by minoplhy** [comment]
In case of Privex . this is all i can do about this so, I'll contact Privex about their Tor Node has been mark as malicious so they can clean this . If i get any response i'll update later.

In case of Alawar . Alawar seem to be a legitimate Russian Game Publisher/Developer(Based on https://company.alawar.com and wikipedia) . and **most** of their subdomain seem to be fine . IMO only element.alawar.com seem to really have problem with virustotal
![image](https://user-images.githubusercontent.com/67270651/146146544-83ab3c6a-de22-4db9-8e0f-90549b38166a.png)

**Comment by minoplhy** [comment]
That's ok, I'll try on upstream if i have time then.
