### ISSUE TITLE
rec.quartic.pl - Website Broken

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#341]
`nexto.pl`
Blocked
![Zrzut ekranu z 2021-12-07 08-57-55](https://user-images.githubusercontent.com/80338577/144990514-434a2b68-02fb-4456-8fcc-cd9a1da6fea8.png)
Unlocked
![Zrzut ekranu z 2021-12-07 08-59-03](https://user-images.githubusercontent.com/80338577/144990542-9d0c149d-9aeb-4a63-8a60-66142cbd2f76.png)

**Comment by badmojr** [comment]
I believe u use **Lite**, correct?

**Comment by gita6t5** [comment]
Yes.

**Comment by badmojr** [comment]
Perfect. Will exclude it from Lite!

**Comment by crssi** [comment]
Why not from Pro also?
`rec` seem to be recommendations and not recordings/tracking.

**Comment by badmojr** [comment]
recommendations = Affiliate Marketing.
It also comes bundled with tracking..
see: https://rec.quartic.pl/quartic.js
