### ISSUE TITLE
Deny goodlessyndication.com and its subdomains

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#345]
Its javascript ads-sdk, strangely enough, hijacks webpages...

Visit: [GoodlessSyndication in action](https://twocircles.net/2011aug26/how_dawoodi_bohras_observe_ramzan.html) (notice the redirect _after_ the actual webpage loads).

Subdomains I could find:

```
ww82.goodlessyndication.com
pagead2.goodlessyndication.com
``` 

Will report this unto jerryn70 as well.

**Comment by badmojr** [comment]
Hello!

The domain was listed before, and was then delisted.
see: https://blocklist-tools.developerdan.com/entries/search?q=pagead2.goodlessyndication.com
https://dnslytics.com/domain/goodlessyndication.com

**Comment by ignoramous** [comment]
Why not? It seems like it has *hijacked* a website that embeds its JavaScript... and redirects it to a parked page. Or, is that what they do?

**Comment by badmojr** [comment]
There are some 14k+ parked domains similar to pagead2.goodlessyndication.com.
see: https://dnslytics.com/reverse-ip/46.8.8.100

We avoid retaining previously listed domains, that are now parked; we basically consider them harmless.
Doing so ensures the lists don't beome bloated over time.

**Comment by badmojr** [comment]
Is it still the case for u. I don't seem to be observing the above anymor.

**Comment by ignoramous** [comment]
Yeah, I don't see the redirect anymore, but I did capture it the first time I saw it a few days back: https://archive.md/hocgJ

May be someone fixed something somewhere. Closing this for now.
