### ISSUE TITLE
googletagmanager.com

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#348]
Blocks entry into articles on the website filmomaniak.pl

https://user-images.githubusercontent.com/80338577/145750712-dd1162c4-daf0-4661-a966-1a8e9c4cf695.mp4

**Comment by spirillen** [comment]
Eh what??

You might elaborate what you want here.

**Comment by badmojr** [comment]
Hello!

I'm afraid this won't be delisted. Sorry!
Instead:
- Please downgrade to **mini** .
- Make of of **'right click**' & '**Open link in a new tab**'.
