### ISSUE TITLE
add telemetrydeck.com

### ISSUE THREAD

**Issue by iuniio** [badmojr/1Hosts#350]
According it's own site: Lightweight Analytics That's Not Evil
But still an analytics tool

My nextdns log is full of this subdomain: nom.telemetrydeck.com

**Comment by spirillen** [comment]
Thanks for sharing

**Comment by iam-py-test** [comment]
Sample site with this?

**Comment by spirillen** [comment]
@iam-py-test if you read the site and it purposes, then example sites become rather unnecessary if you ask me. This is a self declared in program tracker without opt-out option (as far I could spot) The only reason I did not add it spyware... See https://mypdns.org/my-privacy-dns/matrix/-/issues/3918 (I hate replicate my self )

**Comment by iorjun** [comment]
> Sample site with this tracker?

For now apollo reddit for ios

![IMG_0051](https://user-images.githubusercontent.com/66678781/146569005-d9bc7f51-7385-4278-9929-96fa6da0fcdd.jpg)

And many requests blocked manually (added on denylist) on nextdns

![IMG_0050](https://user-images.githubusercontent.com/66678781/146569026-c0e2f909-c20f-422f-ad06-1a8ce0c2be96.jpg)
