### ISSUE TITLE
snrcdn.net

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#354]
Products can't be added to cart 
https://www.x-kom.pl/p/320832-dysk-hdd-seagate-ironwolf-cmr-10tb-7200obr-256mb.html
Click "Dodaj do koszyka"
![Zrzut ekranu z 2021-12-19 02-18-52](https://user-images.githubusercontent.com/80338577/146660368-168877f2-49bb-42ad-986f-ba1a5f4f1eab.png)
List: Lite

**Comment by spirillen** [comment]
- https://github.com/easylist/easylist/issues/5172
- https://mypdns.org/my-privacy-dns/matrix/-/issues/3956
