### ISSUE TITLE
mozilla.org

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#355]
Blocks www.mozorg.moz.works so it makes the mozilla.org not functional.

**Comment by crssi** [comment]
From whichever source this came from I would say that source is completely unreliable. 😉

**Comment by spirillen** [comment]
> From whichever source this came from I would say that source is completely unreliable. :wink:

Not entirely if it slip into the public by a mistake, I block it privately to avoid the spam from them (vpn | upgrades | new tabs)
