### ISSUE TITLE
ncsi.4-c-0003.c-msedge.net is a CNAME for www.msftconnecttest.com

### ISSUE THREAD

**Issue by p1r473** [badmojr/1Hosts#356]
ncsi.4-c-0003.c-msedge.net is a CNAME for www.msftconnecttest.com
This is the microsoft connection test domain to see if your computer has internet access
Not malicious

**Comment by spirillen** [comment]
Actually also used for tracking (logging your ip/OS) it should usual be safe to leave this to an internal IP address, As it actually can (will) brake network where there are NO Internet only InTRAnet.

As I side note I can mention this also applies to android.

My personal judgement would say it is pine to leave this pointing to a RFC1918 address in 99% of any cases.
