### ISSUE TITLE
neu.frontdoor.licensing.commerce.microsoft.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#357]
`licensing.mp.microsoft.com` is blocked due to listing `neu.frontdoor.licensing.commerce.microsoft.com` / `CNAME`

This listing prevents downloading apps from MS store.

Does this come from the same source as https://github.com/badmojr/1Hosts/issues/355#issue-1083999714 and https://github.com/badmojr/1Hosts/issues/356#issue-1084025275 ?

**Comment by badmojr** [comment]
Indeed.
It's also related to a similar issue we've resolved before.
see: https://github.com/badmojr/1Hosts/issues/249

So imma fix it once and for all by ditching the list in question.

**Comment by crssi** [comment]
@badmojr , which list was/is the culprit?

Thank you 😄

**Comment by badmojr** [comment]
see: https://github.com/badmojr/1Hosts/issues/249

**Comment by crssi** [comment]
Ahhh... I do also need a coffee... or several cups to be sure. 😄 

Thank you ❤️
