### ISSUE TITLE
Xbox licence server blocked 

### ISSUE THREAD

**Issue by RouterCFW** [badmojr/1Hosts#358]
`licensing.mp.microsoft.com` Is a false positive which is being blocked which is preventing Xbox games from checking the licence server so the games can’t launch

**Comment by badmojr** [comment]
I don't see it as actively blocked by any of the lists.
see: https://blocklist-tools.developerdan.com/entries/search?q=licensing.mp.microsoft.com

**Comment by RouterCFW** [comment]
Yeah I think it was a problem with NextDNS sorry about that

**Comment by RouterCFW** [comment]
> I don't see it as actively blocked by any of the lists.
> see: https://blocklist-tools.developerdan.com/entries/search?q=licensing.mp.microsoft.com

Yeah I think it was a problem with NextDNS sorry about that

**Comment by crssi** [comment]
> Yeah I think it was a problem with NextDNS sorry about that

Not really... see https://github.com/badmojr/1Hosts/issues/357#issue-1084037211

**Comment by crssi** [comment]
> I don't see it as actively blocked by any of the lists.

Lack of coffee? 😄 
It is a CNAMEd with `neu.frontdoor.licensing.commerce.microsoft.com` which is actually blocked. 😉 

❤️

**Comment by RouterCFW** [comment]
> > Yeah I think it was a problem with NextDNS sorry about that
> 
> Not really... see [#357 (comment)](https://github.com/badmojr/1Hosts/issues/357#issue-1084037211)

Thanks ❤️
