### ISSUE TITLE
collector.githubapp.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#360]
Due to `collector.githubapp.com` is listed, I get a breakage when opening pages like https://github.com/badmojr/1Hosts/commit/47f24f92ba6d57408f78e45aa166be74d061b7f6... see screenshot:

![image](https://user-images.githubusercontent.com/17024151/146880660-5c255576-8ead-4e1c-8344-40a158c5dd30.png)

Thank you and cheers 😄

**Comment by badmojr** [comment]
How did u narrow down the offender to that domain?
The error always seem to happen at random, in my experience. even with the domain unblocked!

**Comment by crssi** [comment]
Hmmm... you are right.
When I have tested always worked when allowing `collector.githubapp.com` and never when denying.
Now it seem that that was just a coincidence.

Sorry for wrong reporting. 😢
