### ISSUE TITLE
Whitelist presearch.org.

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#362]

**Comment by spirillen** [comment]
Warum (Why)

**Comment by Rexadev** [comment]
> Warum
It is a decentralized search engine. What's bad about that?

**Comment by spirillen** [comment]
> > Warum
> 
> It is a decentralized search engine. What's bad about that?

probably nothing :smile: It just you only throw a domain without any notes

**Comment by badmojr** [comment]
According to virustotal: 5 detected file communicating with this domain
see: https://www.virustotal.com/gui/domain/presearch.org/relations

**Comment by Rexadev** [comment]
> According to virustotal: 5 detected file communicating with this domain see: https://www.virustotal.com/gui/domain/presearch.org/relations

Not necessarily bad for example glasswire (firewall network monitoring)could be using it to get information about domains

**Comment by Ventus221** [comment]
A file, this one ([here](https://www.virustotal.com/gui/file/fd654367ef547a305a8ea3bcfdb4e3bb11e78d8ab166681dfbeb2671aa6b9884)) contacts this domain and is flagged by 46 AVs.

**Comment by spirillen** [comment]
Actually 49 vendors from a fresh scan. Than will in my opinion make this a malicious domain. and next to that, it is simply a hotlink site, not a search engine.

**Comment by badmojr** [comment]
There u have it, @Rexadev .
Too many a bunch of red flags.
