### ISSUE TITLE
pls unblock "data.sensor.community" it only sounds bad

### ISSUE THREAD

**Issue by LtqxWYEG** [badmojr/1Hosts#369]
Hello :)

Yea, it is a site for sharing sensor data like air quality, temperatur and other weather stuff.

Its inclusion (or exclusion?) breaks my air-quality app on my phone.

Please unblock :)

**Comment by Ventus221** [comment]
Hey,

Could provide some more details, I mean which app exactly?

I can see the weather, air-quality and other stuff just right, on my android device. (Google weather sourced from weather.com)

**Comment by LtqxWYEG** [comment]
Sure
de.kaffeemitkoffein.feinstaubwidget

Some sensor locations are hosted by that domain

**Comment by Ventus221** [comment]
Hey,

I think "data.sensor.community" has already been whitelisted, 

I tried the app and everything loads up just fine (The Mobile Section), also, the domain is no longer being blocked by any of 1Hosts' lists.

Could you try the app again at your end?

**Comment by LtqxWYEG** [comment]
Oops I should have said that I use the XTRA list. And it is definitely in there. I just looked again

**Comment by Ventus221** [comment]
Oh, alright, Xtra has some false positives.

I can attest that the domain is safe, and since its not present in Pro, @badmojr will remove it soon enough.

**Comment by LtqxWYEG** [comment]
Yay! Thank you!

**Comment by LtqxWYEG** [comment]
Btw, I think you guys would benefit from a issue template. So ppl don't forget to include which list they're using etc :)

**Comment by LtqxWYEG** [comment]
Thank you very much! I'll close this issue now

**Comment by LtqxWYEG** [comment]
It's blocked again or it was never unblocked and I made a mistake. *shrug

**Comment by LtqxWYEG** [comment]
Thank you :)
