### ISSUE TITLE
a1768.g1.akamai.net CNAME for clientconfig.akamai.steamstatic.com

### ISSUE THREAD

**Issue by p1r473** [badmojr/1Hosts#37]
This is Akamai, a load balancer type service, and this domain is a CNAME for clientconfig.akamai.steamstatic.com
This domain is used for storing client configuration for Steam gaming client
This domain does not host any ads, spyware, or malware.

**Comment by badmojr** [comment]
Fixed!

**Comment by p1r473** [comment]
Thanks!
