### ISSUE TITLE
Add Nahimic telemetry to blocklist

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#370]
```
void.steelseries.com
a-volute.com
```

Used my Nahimic Audio Software. Internet is not needed for Nahimic to work

**Comment by spirillen** [comment]
I would say some logs would be useful here, which is showing is fetched from those domain as I don't find any suspect by visiting the site. 

Found a few Spywares, that was about it, but not you suggested domains

**Comment by Rexadev** [comment]
> I would say some logs would be useful here, which is showing is fetched from those domain as I don't find any suspect by 

App doesn't need internet yet it connects, bypassing WFP Firewall, isn't enough for it to be considered spyware?

I don't what to do what logs?

**Comment by spirillen** [comment]
From your firewall for example

**Comment by Rexadev** [comment]
> From your firewall for example or where you found these records, show it 😏

I use NextDNS...

**Comment by spirillen** [comment]
@badmojr What do you think?

**Comment by badmojr** [comment]
related: https://discourse.pi-hole.net/t/steelseries-engine-3-connections/17764

**Comment by badmojr** [comment]
Again, no proof! Only suspicions. Imma need more than that.
Closing...
