### ISSUE TITLE
Block these xiaomi spyware domains

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#375]
```
idmb-app-chat-global-proxy-proto-1114919025.ap-south-1.elb.amazonaws.com
idmb-app-chat-global-xiaomi03new-426797692.ap-south-1.elb.amazonaws.com
idmb-app-chat-global-xiaomi05-1961044139.ap-south-1.elb.amazonaws.com
idmb-app-chat-global-xiaomi04-1301562198.ap-south-1.elb.amazonaws.com
idmb-app-chat-global-xiaomi-1108233833.ap-south-1.elb.amazonaws.com
idmb-app-chat-global-xiaomi02-1415306822.ap-south-1.elb.amazonaws.com
idmb-app-chat-global-xiaomi06-2047145834.ap-south-1.elb.amazonaws.com
resolver-msg-xiaomi-net-665721575.ap-south-1.elb.amazonaws.com
```
Found theses in my log
I don't use any xiaomi chat app

**Comment by spirillen** [comment]
@Rexadev you need to make more comments :smiley: 

Such as: where/how did you find these, the relation, in short attach some kind of profs. 

It is not an assay that is requested, but enough comments for other to reproduce (to confirm) you commit

however these do not make me think tracking domains, (they are) but thinking they are connections to the backend for message exchange `idmb-app-chat-global-`

**Comment by badmojr** [comment]
The only thing I'm sure of is that all the domains have _Mumbai, Maharashtra,  India (IN)_ as their destination.
No conclusive proof has been provided that they are trackers.

I, therefore, suggest that manual blocking be undertaken. Sorry!
