### ISSUE TITLE
pcapredict.com

### ISSUE THREAD

**Issue by gyCfjSnO** [badmojr/1Hosts#376]
Domain: pcapredict.com

Detail: This site needs to be whitelisted as it's for address verification & data cleansing

**Comment by badmojr** [comment]
I see it actively being used as a third-party. Therefore, I suspect some tracking of sorts involved.
see: https://publicwww.com/websites/%22pcapredict.com%22/

**Comment by gyCfjSnO** [comment]
It's used to type in your address and it pops up with autofill information

**Comment by gyCfjSnO** [comment]
Here is their GitHub https://github.com/PCAPredict
