### ISSUE TITLE
whitelist: log.mmstat.com

### ISSUE THREAD

**Issue by Lonelier** [badmojr/1Hosts#38]
youku.com Video can't be played, shows cookies are disabled

**Comment by badmojr** [comment]
Which version(s)/variant)(s) do you need the domain removed from?
It's current unblocked on the mini versions/variants..

This is a tracking/analytics sub/domain, BTW.

**Comment by Lonelier** [comment]
I'm using the Lite version/variant.
I know it's a tracking/analytics sub/domain, but youku.com needs this domain to play videos correctly.
Is it possible to whitelist this domain?(ALL)

**Comment by badmojr** [comment]
Cool!
Removing it only from the Lite versions. Standby...!

**Comment by Lonelier** [comment]
Thanks for the work.
