### ISSUE TITLE
Wi-Fi disconnect 

### ISSUE THREAD

**Issue by ghwiz313** [badmojr/1Hosts#381]
This list is causing my iPhone 13 to disconnect from my home Wi-Fi. Using via AdGuard. I have disabled every other filter to double check. Enabling this list alone reproduces the issue. Any idea why this just started happening?

**Comment by Ventus221** [comment]
Hey,
Could you share your logs? Especially right after enabling any of the 1Host Lists.

**Comment by badmojr** [comment]
Not enough actionable details are provided.
Closing...
