### ISSUE TITLE
haphazardhum.com

### ISSUE THREAD

**Issue by SilkArt** [badmojr/1Hosts#391]
Adsterra alert!!!
Reason belongs to Adsterra, notorious ad network known for terraclicks:
1. Points to Adsterra IP.
2. Redirects to google.com.

**Comment by badmojr** [comment]
https://blocklist-tools.developerdan.com/entries/search?q=haphazardhum.com

**Comment by badmojr** [comment]
From the above link, this has been blocked on Pro since _Thu Dec 09 2021_ .
