### ISSUE TITLE
data.mistat.intl.xiaomi

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#392]
Blocks update checking
https://www.reddit.com/r/oisd_blocklist/comments/m6j6fg/oisd_domain_blocklist/gxe4f7d/?context=3
List Lite

**Comment by badmojr** [comment]
I do not have a Mi device to reproduce.  Will have to stay blocked on Pro-Xtra.

**Comment by crssi** [comment]
I have (actually my son have) an Xiaomi phone. I can see in the logs that before a few hours ago the `data.mistat.intl.xiaomi` was blocked and now its not due to recent update.

If you need me to make some test, just let me know the steps and will report results back.

Cheers

**Comment by spirillen** [comment]
@crssi could you do me a favor and test my lists (https://mypdns.org/my-privacy-dns/matrix/-/issues/2295) for which most was collected via https://github.com/easylist/easylist/pull/8527

**Comment by crssi** [comment]
@spirillen are your lists part of any lists published on NextDNS?
My son have Xiaomi phone, not me, on which the PDNS is set to NextDNS where I can diagnose more.
His phone is rarely connected to my WiFi, so I also can't use some on the local network solution.

**Comment by spirillen** [comment]
> re your lists part of any lists published on NextDNS?

I don't know what is currently happening on that front, but in the past they did use the porn-records, but not sure they do currently.  And which RPZ zones they may use I can't say as I do not log for privacy.

But as far I know you should be able to include black- whitellist for your self on NextDNS

I was reaching out for you as you said

> I have (actually my son have) an Xiaomi phone. I can see in the logs

So was hoping you could have been giving a feedback.

**Comment by crssi** [comment]
I am still willing to make some tests, if needed, within the boundaries of my possibilities.

Cheers

**Comment by spirillen** [comment]
That would be great to eliminate FP's
