### ISSUE TITLE
Add app-prod.dreamplug.in to blocklist

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#398]
Don't know what uses it just a suspicious domain in my network that i manage and nothing breaks

**Comment by badmojr** [comment]
Blocked on **Xtra**. Please upgrade!
see: https://blocklist-tools.developerdan.com/entries/search?q=app-prod.dreamplug.in

**Comment by Rexadev** [comment]
> Blocked on **Xtra**. Please upgrade! see: https://blocklist-tools.developerdan.com/entries/search?q=app-prod.dreamplug.in

For some domains you ask for more information How do you know what domains need are bad?

**Comment by badmojr** [comment]
![jghgjghgh](https://user-images.githubusercontent.com/40524316/150317451-d0278537-3900-4d08-8553-84c2a2c6e19a.PNG)
It has been on Xtra for a while now, since Sun Aug 29 2021.
I did not add it. Only sourced it.
