### ISSUE TITLE
googlezip.net add to blocklist

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#399]
```
*.dns-tunnel-check.googlezip.net
*.tls-tunnel-check.googlezip.net
*.googlezip.net
*.tunnel.googlezip.net
```

**Comment by badmojr** [comment]
No, thank you!
see:
https://github.com/chromium/chromium/commits/main/chrome/browser/prefetch/prefetch_proxy/prefetch_proxy_params.cc
https://github.com/chromium/chromium/blob/main/chrome/browser/prefetch/prefetch_proxy/prefetch_proxy_params.cc
