### ISSUE TITLE
whitelist:rm.api.weibo.com

### ISSUE THREAD

**Issue by Lonelier** [badmojr/1Hosts#40]
I'm using the Lite version/variant.
Weibo.com requires this domain for web video playback.

**Comment by badmojr** [comment]
Please provide a URL to the said video!

**Comment by Lonelier** [comment]
Sorry, I just tested it, it's a browser issue. I apologize for my lack of precision.

**Comment by badmojr** [comment]
It's alright, happens to the best of us.
