### ISSUE TITLE
Add supl servers to blocklist

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#400]
```
*.supl.vodafone.com
*.supl.google.com
```
Leaks location to sup server when using AGPS and also makes GPS faster

**Comment by badmojr** [comment]
I sure this will break Location services, a functionality which a lot of users might need.
So, thanks! But no, thanks.

**Comment by Rexadev** [comment]
> I sure this will break Location services, a functionality which a lot of users might need. So, thanks! But no, thanks.

https://forum.f-droid.org/t/supl-server-recommendation/16074/2

**Comment by badmojr** [comment]
I never said " Location Provider", but " Location services".
Nevertheless, based on #122 , I'd like to refrain from blocking anything releated to any "Location Service" functionality.
