### ISSUE TITLE
Add these facebook links to blocklist portal.fb.com connect.facebook.net

### ISSUE THREAD

**Issue by Rexadev** [badmojr/1Hosts#403]
```
*.portal.fb.com
*.connect.facebook.net
```

**Comment by badmojr** [comment]
`connect.facebook.net`: Blocked on Pro & Xtra.
see: https://blocklist-tools.developerdan.com/entries/search?q=connect.facebook.net

`portal.fb.com`: I do not have enough details nor info to warrant its blockage. Sorry!

**Comment by spirillen** [comment]
As far as I remembers (Notice remembers)

then `portal.fb.com` is similar to `connect.facebook.net`
