### ISSUE TITLE
Repo wiped?

### ISSUE THREAD

**Issue by bodinsamuel** [badmojr/1Hosts#408]
Hey,

Just noticed that the repo seems to have been wiped, what happened?
Can we trust the changes here?

Best Regards

**Comment by bodinsamuel** [comment]
Thanks, 
I appreciate your work 🙏🏻

**Comment by badmojr** [comment]
update:
Repo size reduced. It now down to a meager 40 MB, compared to the previous 6.26 GB.
😀

**Comment by badmojr** [comment]
> ❓ Is there a simpler solution? 🤔

https://github.com/badmojr/1Hosts/blob/master/.github/workflows/init.yml

**Comment by badmojr** [comment]
I'm open to ideas.
