### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by obeho** [badmojr/1Hosts#41]
`perf.hsforms.com` domain.

Websites like `https://forms.hsforms.com/` & `https://share.hsforms.com/1N6aQgP9bQq2SmRziqOqMTw16gmf` and many other which contain `hsforms.com` in the name aren't getting loaded because of this. Please whitelist in Pro pack too.

Also, can you tell which of these [lists](https://github.com/badmojr/1Hosts/issues/26#issuecomment-683470737) this domain is from so that I can request for whitelist on their page too?

**Comment by badmojr** [comment]
The above form has expired/closed!
Please provide another link that works.

**Comment by obeho** [comment]
Yes, it has been closed, and I was able to confirm this by temporarily stop using your blocklist. When I tried to open it using my default configuration, which includes 1Hosts (Pro), the site isn't even loaded because its not even resolved.

**Comment by badmojr** [comment]
Hey,
Here are the domains required for the forms above to load:-
`static.hsappstatic.net`
`js.hs-scripts.com`

**Comment by badmojr** [comment]
Fixed!
