### ISSUE TITLE
Unblock services.mathworks.com & more

### ISSUE THREAD

**Issue by Ventus221** [badmojr/1Hosts#410]
Hey @badmojr 

I was installing MathWorks Matlab via their installer and the installer tried to connect to:

`udc-service.mathworks.com`
`services.mathworks.com`

Which are both blocked in 'Pro' and are used to authenticate accounts.

I have whitelisted them for the time being, but couldn't install the software with them blocked.

**Comment by badmojr** [comment]
origin: https://github.com/WellWells/adblock-list/raw/main/AdBlock.csv
cc: @WellWells
