### ISSUE TITLE
SteelSeries GG Engine "Analytics"

### ISSUE THREAD

**Issue by saurane** [badmojr/1Hosts#413]
legacy._segment._tcp.steelseries.com
engine._google-analytics._tcp.steelseries.com
From the SteelSeries GG Engine application. It's a "Windows App".
Client: AdGuard for Windows + NextDNS
Not on any list

**Comment by spirillen** [comment]
Hmm seems inactive..

![image](https://user-images.githubusercontent.com/44526987/152298425-db8042a2-57d1-4207-9684-cfb506b8bf7d.png)

**Comment by saurane** [comment]
> 

I didn't check if it's alive, sorry. When the application runs, it sends a DNS request to these domains.

**Comment by saurane** [comment]
> Hmm seems inactive..
> 

I didn't check if it's alive, sorry. When the application runs, it sends a DNS request to these domains.

**Comment by spirillen** [comment]
> > Hmm seems inactive..
> 
> I didn't check if it's alive, sorry. When the application runs, it sends a DNS request to these domains.

So can you see some live response or should this issue be closed?

**Comment by saurane** [comment]
> > > Hmm seems inactive..
> > 
> > 
> > I didn't check if it's alive, sorry. When the application runs, it sends a DNS request to these domains.
> 
> So can you see some live response or should this issue be closed?

DNS response showing it is alive.
![ss](https://user-images.githubusercontent.com/87908352/152302243-97e619f2-bd93-48f1-acc1-8ebcb3055971.png)

**Comment by minoplhy** [comment]
## legacy._segment._tcp.steelseries.com
![image](https://user-images.githubusercontent.com/67270651/152349839-aebbeb76-23a5-4b71-894b-99f7105d9b4f.png)
This domain only had TXT Record as far as i known and it seem to be the exact same answer as image above

## engine._google-analytics._tcp.steelseries.com
didn't get any answer from Unfiltered DNS Resolver and from my quick research this isn't seem to be any Google Analytics Domain Verification method either

also, it's uncommon for me that analytics will served through TXT Record
