### ISSUE TITLE
log and tracker

### ISSUE THREAD

**Issue by saurane** [badmojr/1Hosts#415]
from: advantech.com
#
advwebtracking.advantech.com 
cname: advwebtracking.trafficmanager.net - curation-acl-1.advantech.com
#
adv-web-tracking-logs.azurewebsites.net
hosts.adv-web-tracking-logs.azurewebsites.net
cname: hosts.adv-web-tracking-logs.azurewebsites.net
#
advwebtracking-cloud.advantech.com

used list: 1Hosts Xtra
Client: AdGuard

**Comment by saurane** [comment]
It's a DNS request and cname: hosts.adv-web-tracking-logs.azurewebsites.net

**Comment by badmojr** [comment]
Only one of them suffices. No need for the CNAME.

**Comment by saurane** [comment]
> Only one of them suffices. No need for the CNAME.

But it's also a dns request. When you enter the website, it will send a dns request.

**Comment by badmojr** [comment]
I could not observe that. Got a screenshot for me?

**Comment by saurane** [comment]
> I could not observe that. Got a screenshot for me?
![ss (2)](https://user-images.githubusercontent.com/87908352/152673668-edfc52d7-47e6-4132-887d-7e026c2317f8.png)

**Comment by badmojr** [comment]
You see, even `curation-acl-1.advantech.com` is marked as such.
It's just the way your client processes the requests.
