### ISSUE TITLE
https://app-measurement.com/sdk-exp

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#416]
Shouldn't this request be blocked?

![image](https://user-images.githubusercontent.com/49731083/152687670-5f300c97-c243-45b7-bbbc-205eb46dc09f.png)

**Comment by badmojr** [comment]
Hello!
Which of the lists are using?

**Comment by Quorum75** [comment]
The one you recommended me to use. 

https://badmojr.github.io/1Hosts/Pro/domains.txt

**Comment by badmojr** [comment]
If that's so, then it should blocked by the list.
see:
https://blocklist-tools.developerdan.com/entries/search?q=app-measurement.com

![ug7ipiu](https://user-images.githubusercontent.com/40524316/152717660-93a5d8e2-85a7-4b8a-add9-bddd77657807.PNG)

**Comment by Quorum75** [comment]
Indeed. So it is very strange it is not happening...

**Comment by Quorum75** [comment]
A trick question :)

Why the Pro list get different rule numbers?
![image](https://user-images.githubusercontent.com/49731083/152801658-1fb3a3f9-05e6-4e81-8b00-bf0815942aab.png)

![image](https://user-images.githubusercontent.com/49731083/152801676-fd37f86b-a698-47df-b42a-9aa84baf6197.png)

**Comment by badmojr** [comment]
The latter does not include redundant subdomains.
It's designed for clients that block subdomains by default, if the root domain is listed.

**Comment by Quorum75** [comment]
FYI https://github.com/AdguardTeam/AdGuardDNS/issues/217#issuecomment-1032291213

**Comment by badmojr** [comment]
Good to know! :)
