### ISSUE TITLE
||mon-va.byteoversea.com^ breaks TikTok video

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#42]
`||mon-va.byteoversea.com^` breaks second TikTok video at `https://okusno.je/triki-in-nasveti/koncno-znano-kako-se-naredi-peceno-jajce-ki-je-pred-kratkim-navdusilo-splet.html`

Cheers

**Comment by badmojr** [comment]
Can't reproduce! Both videos play just fine.

**Comment by crssi** [comment]
Crap... let me check again, please.

**Comment by crssi** [comment]
Beat me if I know what happened... I could swear the it didn't work before, but it mught be just a constalation of the planets.

Anyway, thank you for double check and sorry for false report. 😢
