### ISSUE TITLE
r.stripe.com

### ISSUE THREAD

**Issue by p1r473** [badmojr/1Hosts#429]
This is a subdomain required for payment processor Stripe
It has broken the signup of a page I am using that requires stripe
I believe this is a non malicious FP

**Comment by badmojr** [comment]
I'm still convinced this one is used for tracking.
Maybe some more actionable details might help change that.

Are there any that u can probably share perhaps? So, I too can reproduce the issue above?

Origin:
https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Tracking
https://github.com/migueldemoura/ublock-umatrix-rulesets/blob/master/Hosts/ads-tracking

cc: @ShadowWhisperer, @migueldemoura

**Comment by migueldemoura** [comment]
I had some issues with this one too, same as `m.stripe.com` which seems to send back mouse movement timings. The tracking involved here is usually to catch bots, so we really have no other choice but to allow it. Removed the subdomain from mine, see: https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/fe487b99a53c8a2175b3f3f832cbbadb66523a36.

**Comment by ShadowWhisperer** [comment]
I block both `q.stripe.com`  and `r.stripe.com`. I haven't noticed any issues, but I don't use Strip/haven't seen a site that only accepts Stripe.

@ p1r473  Could you provide the URL for the site you were on, for further investigation?

**Comment by ShadowWhisperer** [comment]
I found a site that has Stripe as an option.   `https://curiositystream.com/payment-step`
Any time you click anywhere `https://r.stripe.com/0`, calls out.

**Comment by p1r473** [comment]
Please try to sign up and log into locals.com with this domain blocked
I was not able to.

**Comment by ShadowWhisperer** [comment]
Odd, it doesn't call out to anything Stripe related, for me.

![1](https://user-images.githubusercontent.com/61057625/155614816-0c436260-8472-4fa4-8df5-ded9708fe51a.PNG)

It does call out to `r.stripe.com`, if it go to `https://locals.com/profile/manage?tab=3`, but still works when blocked. *As far as I can tell, without giving a credit card.

**Comment by p1r473** [comment]
> Odd, it doesn't call out to anything Stripe related, for me.
> 
> ![1](https://user-images.githubusercontent.com/61057625/155614816-0c436260-8472-4fa4-8df5-ded9708fe51a.PNG)
> 
> It does call out to `r.stripe.com`, if it go to `https://locals.com/profile/manage?tab=3`, but still works when blocked. *As far as I can tell, without giving a credit card.

Sorry, can you try on `https://heresyfinancial.locals.com/` instead?
I tried locals.com and it was fine, but I can reproduce the issue on `https://heresyfinancial.locals.com/`

Behaviour seems to be stuck at loading while r.stripe.com is blocked

![image](https://user-images.githubusercontent.com/9235633/155626464-23b110e1-1be2-4668-8624-85be545147ca.png)

Also @ShadowWhisperer  how did you get that list of domains? I am using a Chrome extension called AdamOne to do something similar.

**Comment by ShadowWhisperer** [comment]
Weird, works there also.  *A bit more junk in the log, as I opened the log before the temp email site.
Also tried Firefox, just for kicks.

![Capture](https://user-images.githubusercontent.com/61057625/155628918-7b64acc0-2e79-4c99-b9e0-59db7379dcd1.PNG)

The log it just a custom script that parses the dnsmasq log. Dnsmsq and some files have to be setup a certain way to make it work. Green has been checked and is safe (checks one of my filter lists, red is denied (according to log), and white means unchecked.

**Comment by p1r473** [comment]
OK, I guess I will close this and have to do more investigation. Will reopen if I can figure it out.
Thanks all!
