### ISSUE TITLE
rule ||intel11.edgekey.net^ blocks multiple intel.com subdomains

### ISSUE THREAD

**Issue by muradnik** [badmojr/1Hosts#43]
I'm using AdGuard Home with your blocklist `1Hosts Lite` and after yesterday's update (31.10.2020) the new rule `||intel11.edgekey.net^` blocks multiple `*.intel.com` subdomains;

for example:
- `downloadcenter.intel.com`
- `downloadmirror.intel.com`
- `software.intel.com`
- ...

Screenshot from AdGuard Home:

![adguard](https://user-images.githubusercontent.com/73789362/97808548-e4287d00-1c67-11eb-902d-beb00871b19a.png)

**Comment by badmojr** [comment]
Fixed!

**Comment by muradnik** [comment]
thanks
