### ISSUE TITLE
Breakage due to tracking.s24.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#44]
Steps to reproduce:

1. Visit `https://www.vergleich.org/chilimuehle/`
2. In the last row and second cell of comparison table, find image/icon `OTTO` and click on it.

Cheers

**Comment by badmojr** [comment]
What's getting broken? Could u attach some ss?

**Comment by crssi** [comment]
For you I can make a screen recording. 😄 
Just let me a few hours to find me some time.

Cheers

**Comment by crssi** [comment]
[Allow tracking.s24.com](https://www.dropbox.com/s/quu32skva8ex9dd/allow_tracking.s24.com.webm?dl=0)

[Deny tracking.s24.com](https://www.dropbox.com/s/s02b7qxplr2ddz8/deny_tracking.s24.com.webm?dl=0)

Cheers 😄

**Comment by badmojr** [comment]
> [Allow tracking.s24.com](https://www.dropbox.com/s/quu32skva8ex9dd/allow_tracking.s24.com.webm?dl=0)
> 
> [Deny tracking.s24.com](https://www.dropbox.com/s/s02b7qxplr2ddz8/deny_tracking.s24.com.webm?dl=0)
> 
> Cheers 😄

Thank you.

**Comment by badmojr** [comment]
& Fixed!

**Comment by crssi** [comment]
Thank you ❤️
