### ISSUE TITLE
www.trackmyshipment.co trackmyshipment.co

### ISSUE THREAD

**Issue by p1r473** [badmojr/1Hosts#443]
tracking online shopping purchases / parcels 
false positive / not malicious

**Comment by spirillen** [comment]
Are you sure... the only thing I can see is spyware on that domain

![image](https://user-images.githubusercontent.com/44526987/155748992-c60a5fd0-01df-48fe-8a8d-cc527b198de3.png)

**Comment by p1r473** [comment]
I am using them for multiple packages myself :)
![image](https://user-images.githubusercontent.com/9235633/155808100-2c8ec662-0c5f-475f-a1c9-98e86b514ee6.png)
![image](https://user-images.githubusercontent.com/9235633/155808233-db0b99db-a05b-4853-96b7-670d5da38b93.png)
