### ISSUE TITLE
listed push.api.bbci.co.uk prevents navigation on 

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#444]
Hi @badmojr

Listed `push.api.bbci.co.uk` prevents navigation on BBC pages at the bottom of page.

See for example `https://www.bbc.com/news/live/world-europe-60542877` and click navigation buttons:
![image](https://user-images.githubusercontent.com/17024151/155876009-796e58db-dd4a-4484-9143-c61d4a43b981.png)

Cheers

**Comment by badmojr** [comment]
origin:
https://secure.fanboy.co.nz/r/fanboy-ultimate.txt
https://dnsdian.com/OpenWRT/user.txt
https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-annoyances.txt
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Ads

cc: @Yuki2718, @ShadowWhisperer

**Comment by Yuki2718** [comment]
@ryanbr

**Comment by Yuki2718** [comment]
Removed from my list.

**Comment by crssi** [comment]
Guys, you are effective as usual. Kudos 👍 ❤️

**Comment by ShadowWhisperer** [comment]
Whitelist in mine as well. Thanks for the heads up!

**Comment by Yuki2718** [comment]
Now removed from the fanboy list, so maybe only `https://dnsdian.com/OpenWRT/user.txt` is left.

**Comment by badmojr** [comment]
No longer listed in any of the lists above.
Thanks everyone for your apt responses.

Closing...
