### ISSUE TITLE
remove app.statuscake.com

### ISSUE THREAD

**Issue by kzshantonu** [badmojr/1Hosts#451]
statuscake.com is an uptime monitoring service

**Comment by badmojr** [comment]
**Origin**:
https://github.com/parseword/nolovia/raw/master/skel/hosts-nolovia.txt
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tracking

**cc**:
@parseword, @ShadowWhisperer

**Comment by ShadowWhisperer** [comment]
Homepage

> We'll keep an eye on your website performance for you in the background.

Potentially used to track users.  `https://www.statuscake.com/privacy-policy/`

> In addition to Registration Cookies we may from time-to-time use other types of Cookie to gather information. Such Cookies may include, but not be limited to “session-based” Cookies which are allotted to Your Computer for the duration of your visit to the TrafficCake Websites
  
  
It doesn't say specifically how it's able to check website performance.  I've seen software like this that tracks visitors, to gather this information.   It's been removed, but not whitelisted. Add to my grey list.
