### ISSUE TITLE
https://pets.ettoday.net/amp/amp_news.php7?news_id=2207777&from=google.com

### ISSUE THREAD

**Issue by a77841s** [badmojr/1Hosts#453]
There are two ads on the amp page of the news that have not been blocked, ad1.ettoday.net and ad2.ettoday.net

**Comment by a77841s** [comment]
Hi, I use NextDNS with 1hosts(lite) list

**Comment by badmojr** [comment]
Give **Pro** a trial drive. It has the domains u mentioned, already blocked.

**Comment by a77841s** [comment]
OK, it works.
But it also means that I have to add graph.facebook.com to the whitelist in order to display Facebook messages properly, right?

**Comment by crssi** [comment]
Yes... and, not connected to FB, but probably `syndication.twitter.com` too.

**Comment by spirillen** [comment]
Don't forget the ad. (https://mypdns.org/my-privacy-dns/matrix/-/issues/912993)

```
ad.ettoday.net   CNAME . ; AdWare
ad1.ettoday.net   CNAME . ; AdWare
ad2.ettoday.net   CNAME . ; AdWare

ettoday.net   CNAME . ; News
*.ettoday.net   CNAME . ; News
```
