### ISSUE TITLE
vendorlist.dmcdn.net listed in PRO breaks dailymotion

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#455]
Hi @badmojr 

`vendorlist.dmcdn.net` listed in `PRO` breaks dailymotion

Example site: `https://www.dailymotion.com/video/x814h71`

Cheers ❤️ 

p.s. Hope you are OK? since there is less activity recently

**Comment by spirillen** [comment]
@crssi it is used for tracking

My vote would be individual whitelisting.

**Comment by badmojr** [comment]
Hola!
The sample video provided plays just fine on my end.
Tested on PC. Please recheck!

**Comment by crssi** [comment]
I have rechecked and I can confirm that the problem still persist.

This is what I get when `vendorlist.dmcdn.net` is blocked.
![image](https://user-images.githubusercontent.com/17024151/162139282-82a1273b-38b3-426e-8670-182d51490122.png)

When you have checked, was `vendorlist.dmcdn.net` blocked in the logs.
DId you check with uBO and using also `uBlock filters – Unbreak`? Since in `uBlock filters – Unbreak` there is a rule `||vendorlist.dmcdn.net^$badfilter` linked to `https://forums.lanik.us/viewtopic.php?p=162736#p162736`

Cheers

**Comment by badmojr** [comment]
I use AdGuardHome only. No browser addons!
![vhjjlh](https://user-images.githubusercontent.com/40524316/162142895-87d31dbb-98d4-456a-84de-8635b55fddf8.PNG)
![hkjgghk](https://user-images.githubusercontent.com/40524316/162142924-a6b08060-d10e-4b5c-9305-dc0f8fba0712.PNG)

**Comment by crssi** [comment]
What can I say... maybe is GEO located problem, I don't know.
But, since there the `||vendorlist.dmcdn.net^$badfilter` is listed in `uBlock filters – Unbreak` there might be a reason.

I did a new test with the fresh computer, connected directly to Internet without any interfering solution in between.
Started a fresh Firefox profile. The site works as expected.
The I have added `0.0.0.0	vendorlist.dmcdn.net` to `/etc/hosts` file and site doessn't work anymore.

Anyway, I do not use DM, it just happened that I have stumbled on and out of a few dozen users here (logs in the last 6 months), no-one (except me) didn't stumbled on even once.

**Comment by crssi** [comment]
Maybe I can try to access over some proxy around the globe.
Do you have any suggestion, which continent or country is best?
ATM I am accessing from Europe.

**Comment by badmojr** [comment]
Europe? That explains it.
DM could be enforcing GDPR.

**Comment by crssi** [comment]
Seems like it...
I have tested now from EU, US, Korea, Thailand, Malaysia, Vietnam and China.

EU doesn't work as we know already, and China too due to great FW of China.

US, Korea, Thailand, Malaysia and Vietnam works OK.

Cheers

**Comment by badmojr** [comment]
**Origin:**
https://raw.githubusercontent.com/bjornstar/hosts/master/hosts
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Ads

**cc:**
@bjornstar, @ShadowWhisperer

**Comment by ShadowWhisperer** [comment]
USA - Plays fine, with blocks

Canada (1), France (2),  Germany (1), and Poland (1) VPNs - No blocks of any kind. 
> "Unexpected Error. This video can't be displayed right now, sorry"

I am unable to play any videos on Dailymotion outside the USA.

vendorlist.dmcdn.net --> https://pastebin.com/raw/LDQ84dn3
