### ISSUE TITLE
whitelist: data.bilibili.com

### ISSUE THREAD

**Issue by Lonelier** [badmojr/1Hosts#46]
I'm using the Lite version/variant.
This domain name is just for transferring data, the mobile app often does not work properly after blocking.

**Comment by badmojr** [comment]
Needed more info to get this fixed coz I do not have a mobile device to repdroduce this.
Visited the website & the only  time the above domain poped up was to log s/th.

**Comment by Lonelier** [comment]
![photo_2020-11-13_22-41-06](https://user-images.githubusercontent.com/50671671/99085951-d083fb80-2603-11eb-9dc2-a60dd3dcf4db.jpg)
![photo_2020-11-13_22-40-58](https://user-images.githubusercontent.com/50671671/99085978-d7ab0980-2603-11eb-84da-9d3d747b63d8.jpg)

**Comment by Lonelier** [comment]
Video cannot be played correctly

**Comment by badmojr** [comment]
> Video cannot be played correctly

A screen recording of it happening might be more helpful.
Or please provide me with a webpage URL where such breakage happens.

**Comment by Lonelier** [comment]
> 
> 
> > Video cannot be played correctly
> 
> A screen recording of it happening might be more helpful.
> Or please provide me with a webpage URL where such breakage happens.

![photo_2020-11-13_22-40-58](https://user-images.githubusercontent.com/50671671/99140449-22b53300-267d-11eb-8ab8-51857a3e55b0.jpg)

After blocking data.bilibili.com, the video will show "loading failed" in the mobile app, as shown above. Everything works fine after whitelisting (NextDNS)
