### ISSUE TITLE
Please remove false positive (www.)ip-api.com

### ISSUE THREAD

**Issue by thomasmerz** [badmojr/1Hosts#461]
Please remove (www.)ip-api.com from "Pro" and "Xtra" lists because this is a false positive. It has been also removed from other major blocklists:
https://blocklist-tools.developerdan.com/entries/search?q=ip-api.com

I will also inform the owners of the remaining lists to remove this domain(s).

Because of this blocklist entry, someone isn't able to gather ASN infos for a given IP or domain 😞 
```
# https://github.com/trimstray/the-book-of-secret-knowledge#shell-functions-toc
function getASN () {
    local _ip="$1";
    local _curl_base="curl --request GET";
    local _timeout="15";
    _asn=$($_curl_base -ks -m "$_timeout" "http://ip-api.com/line/${_ip}?fields=as");
    _state=$(echo $?);
    if [[ -z "$_ip" ]] || [[ "$_ip" == "null" ]] || [[ "$_state" -ne 0 ]]; then
        echo -en "Unsuccessful ASN gathering.\\n";
    else
        echo -en "$_ip > $_asn\\n";
    fi
}
```

**Comment by spirillen** [comment]
Used for tracking https://mypdns.org/my-privacy-dns/matrix/-/issues/967390

**Comment by thomasmerz** [comment]
Regarding your @spirillen issue/tracker:

I'm also using uBlock Origin and it's not blocked anymore (?) which might also be an explanation that it has been removed from other major blocklists in the wild:

<img width="785" alt="grafik" src="https://user-images.githubusercontent.com/18568381/160172649-f53f7e57-1e1f-400d-b8fa-da772501c20a.png">

**Comment by spirillen** [comment]
what is a major blacklist?? isn't that a rather personal preference?

And for your easylist assumption...

```
easylist$ git grep 'ip-api.com'
easyprivacy/easyprivacy_allowlist.txt:@@||pro.ip-api.com/json$xmlhttprequest,domain=aljazeera.com|cookappsgames.com|nontongp.xyz|sheee.co.il|walla.co.il
easyprivacy/easyprivacy_trackingservers.txt:||ip-api.com^$third-party
```

**Comment by spirillen** [comment]
Or if you search down the archive you'll see this is nearly a two years old commit https://archive.mypdns.org/T601 or 

```
git blame source/tracking/wildcard.list | grep 'ip-api.com'
Blaming lines: 100% (5622/5622), done.
481fd85395 (spirillen             2022-03-25 18:35:05 +0100 2558) ip-api.com
```

**Comment by thomasmerz** [comment]
Maybe this Site changed from Saulus to Paulus (as we say in Deutschländ) during the last years. Or why should others have removed it from their blocklist? 🤷🏻‍♂️ For example: Google hasn't been block-worthy some years/decades ago. But now every privacy-aware (wo)man should and will block most or all Google domains.
