### ISSUE TITLE
Why is this repo a template and not a fork-able repo?

### ISSUE THREAD

**Issue by thomasmerz** [badmojr/1Hosts#462]
It's impossible to fork this "public template" and contribute via PRs to this repo.
Why?
By accident or has this been intentionally done? 🤔

**Comment by spirillen** [comment]
Seems very fork-able to me

![image](https://user-images.githubusercontent.com/44526987/160165531-3b9e65c6-8784-489d-aad1-ed80e0932492.png)

**Comment by thomasmerz** [comment]
Hmpf. That's right. And I'm wrong. Sorry.

**Comment by spirillen** [comment]
It is human to makes mistakes :+1: especially when you are big enough to admit it.
