### ISSUE TITLE
Missing domains, suggestions and questions

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#464]
**The missing domains**
I've detected some tracking domains in my DNS logs (while I use 1Hosts Pro):
1. *.firebaseio.com
![large](https://user-images.githubusercontent.com/71935156/161620372-0b2b75f8-cd42-4ea7-b96a-3a25f31832e3.jpg)
2. *.metric.gstatic.com
![large (1)](https://user-images.githubusercontent.com/71935156/161620541-aaf92467-9643-4e3f-bc39-e518abf24b69.jpg)
3. *.grs.platform.dbankcloud.ru (Why are the international, european, asian and chinese domains blocked but not the russian one ??)
![large (2)](https://user-images.githubusercontent.com/71935156/161620645-c5df5291-7660-44c8-9e6b-266c6328a800.jpg)
4. *.logs.prod.flamingo.apelabs.net (Data and logs collector from Space Ape (a branch of Supercell))
![large (3)](https://user-images.githubusercontent.com/71935156/161621174-62efe028-17a5-44f4-8eb0-e836d28b208f.jpg)
6. *.firebaseremoteconfig.googleapis.com
![large (4)](https://user-images.githubusercontent.com/71935156/161621256-5f737be0-450f-40d1-93fd-3bce9102cdab.jpg)
7. *.skmarketingassetsprod.blob.core.windows.net (Used by Microsoft Swiftkey)
![image](https://user-images.githubusercontent.com/71935156/161621380-adf0c8eb-36ec-4322-842f-7ebfc30f3601.png)
8. [](https://github.com/)*.firefox.settings.services.mozilla.com (This domain makes many requests for absolutely nothing and I think, from what I've read, that it's part of Mozilla Telemetry or something,... (I advise you, however, to check to be 100% sure))

**Some questions now**
1. I've noticed that a looooot of graph.something... are blocked (graph.facebook.com, graph.instagram.com, etc...) but why isn't graph.microsoft.com blocked ? I've seen it in my DNS logs:
![large (5)](https://user-images.githubusercontent.com/71935156/161622647-846d822c-a2c5-4749-8f56-85debadbcfb3.jpg)
2. Are these Google domains tracking us ? The names are soooo weird (infinitedata, datamixer)
![large (6)](https://user-images.githubusercontent.com/71935156/161623009-9bff5310-4881-4ce6-861e-27bb30570f82.jpg)
![large (7)](https://user-images.githubusercontent.com/71935156/161623022-b0825533-8abc-41ab-9ed8-2ade729e14a6.jpg)
3. This domain spams literally my DNS, and it contains "logger", so, is it a logs collector ?
![large (8)](https://user-images.githubusercontent.com/71935156/161623324-afc6e18b-326b-4784-9738-5a98478296e0.jpg)
5. These domains begin by "log" and come from TikTok, are they dangerous ?
![large (9)](https://user-images.githubusercontent.com/71935156/161623594-4c096a83-2ab4-4a94-b367-5ecb7c258f57.jpg)
![large (10)](https://user-images.githubusercontent.com/71935156/161623607-564ec4c4-8ac2-4c31-92f5-3236a7f3f2e6.jpg)
6. Why is fonts.googleapis.com blocked but not fonts.gstatic.com ?
![large (11)](https://user-images.githubusercontent.com/71935156/161623780-95633b8d-573c-4df5-b82d-7c17fe5211de.jpg)
8. I've seen this weird domain in my DNS logs, and I didn't found anything about it on the Internet...
![large (12)](https://user-images.githubusercontent.com/71935156/161623998-86f8b2c3-762e-4dc5-a9f2-fcc0473445ee.jpg)

Thank you so much for your work !! 😉

**Comment by crssi** [comment]
As for `*-dnsotls-ds.metric.gstatic.com` you can find the answer here `https://help.nextdns.io/t/60hz6md/metric-gstatic-com-is-not-blocked-but-it-should-be`.

As for `graph.microsoft.com` you can find what that is here `https://docs.microsoft.com/en-us/graph/overview`.
If you are using some MS services, like o365, blocking MS graph might break things.

**Comment by crssi** [comment]
Where did you get `fonts.googleapis.com`?... it is not blocked by `1Hosts`.

**Comment by spirillen** [comment]
> Where did you get `fonts.googleapis.com`?... it is not blocked by `1Hosts`.

That is a "old" one not that I have it my zone as I in my personal filter have blacklisted all `*google*` but it do pops up in the logs constantly

You can just see in this search https://mypdns.org/search?scope=issues&search=fonts.googleapis.com know many site is including this record :wink:

**Comment by spirillen** [comment]
You can't blacklist *.firebaseio.com by wildcard... only on subdomain level https://mypdns.org/my-privacy-dns/matrix/-/issues/966846

https://github.com/mitchellkrogza/Phishing.Database/blob/master/input-source/domains/bolonobolo/coronavirus-covid19-phishing-domains.txt

**Comment by spirillen** [comment]
`*.logs.prod.flamingo.apelabs.net` what do you have of knowledge to that records, I can't find any source holding any infomation regarding `apelabs.net`

**Comment by MaXfAa** [comment]
> As for *-dnsotls-ds.metric.gstatic.com you can find the answer here https://help.nextdns.io/t/60hz6md/metric-gstatic-com-is-not-blocked-but-it-should-be.

So, I can block metric.gstatis.com, no ? That's what I am at the moment and I have no problem...

> As for graph.microsoft.com you can find what that is here https://docs.microsoft.com/en-us/graph/overview.
If you are using some MS services, like o365, blocking MS graph might break things.

Ok ok, thank you !! 😃

**Comment by MaXfAa** [comment]
> Where did you get `fonts.googleapis.com`?... it is not blocked by `1Hosts`.

Oops sorry, it's blocked by Energized Xtreme Extension. But now, I've whitelisted it (because I had some problems).

**Comment by MaXfAa** [comment]
> > Where did you get `fonts.googleapis.com`?... it is not blocked by `1Hosts`.
> 
> That is a "old" one not that I have it my zone as I in my personal filter have blacklisted all `*google*` but it do pops up in the logs constantly
> 
> You can just see in this search https://mypdns.org/search?scope=issues&search=fonts.googleapis.com know many site is including this record 😉

Ok ok. As I said "it's blocked by Energized Xtreme Extension. But now, I've whitelisted it (because I had some problems)."

Oh :(
![image](https://user-images.githubusercontent.com/71935156/161985866-a57d612e-d215-4b47-9b88-261c83bc32fb.png)

**Comment by MaXfAa** [comment]
> You can't blacklist *.firebaseio.com by wildcard... only on subdomain level https://mypdns.org/my-privacy-dns/matrix/-/issues/966846

Why can't I ?? I currently do it... (However I've whitelisted some domains (two) for a service I use (a small service hosted on firebase by a small developer).)

> https://github.com/mitchellkrogza/Phishing.Database/blob/master/input-source/domains/bolonobolo/coronavirus-covid19-phishing-domains.txt

Sorry but I don't care about COVID phishing 😄; I just don't want to have queries from/to Firebase in my Internet traffic...

**Comment by MaXfAa** [comment]
> `*.logs.prod.flamingo.apelabs.net` what do you have of knowledge to that records, I can't find any source holding any information regarding `apelabs.net`

Sometimes when I launch one of their games this request appears in the logs of my DNS. I blocked it to test and it doesn't change anything in the game or anywhere. It's a safe bet that this is an area of data collection.

And more precisely about apelabs.net; after several tests, the requests to apelabs.net appear **only** when I open the game (which is developed by Space Ape), so... It's sure !

**Comment by badmojr** [comment]
Hello!

1. *.firebaseio.com
Legit and good content is hosted on the domain.

2. *.metric.gstatic.com
ref: #317 

3. *.grs.platform.dbankcloud.ru (Why are the international, european, asian and chinese domains blocked but not the russian one ??)
ref:
#260 
#103 

4. *.logs.prod.flamingo.apelabs.net (Data and logs collector from Space Ape (a branch of Supercell))
🆗

5. *.firebaseremoteconfig.googleapis.com
Breaks Android apps that rely on Firebase. Related to no. 1

6. *.skmarketingassetsprod.blob.core.windows.net (Used by Microsoft Swiftkey)
Is it used for tracking though?
Seems it only hosts files. e.g: https://skmarketingassetsprod.blob.core.windows.net/files/SwiftKey7.xIntegrationGuide.pdf)/files/SwiftKey7.xIntegrationGuide.pdf

7. *.firefox.settings.services.mozilla.com (This domain makes many requests for absolutely nothing and I think, from what I've read, that it's part of Mozilla Telemetry or something,... (I advise you, however, to check to be 100% sure))
ref: https://github.com/anudeepND/blacklist/issues/14



> 
> **Some questions now**
> 

1. I've noticed that a looooot of graph.something... are blocked (graph.facebook.com, graph.instagram.com, etc...) but why isn't graph.microsoft.com blocked ? I've seen it in my DNS logs:
The graph.something above are blocked due to their highly privacy intrusive nature.
I'm not well informed about the Microsoft one.

2. Are these Google domains tracking us ? The names are soooo weird (infinitedata, datamixer)
Those are better blocked at the individual level. Will break a bunch of Google apps' core functionalities if blocked.

3. This domain spams literally my DNS, and it contains "logger", so, is it a logs collector ?
Perhaps. 

4. These domains begin by "log" and come from TikTok, are they dangerous ?
Most likely. The only problem is that there are a sh*t load of such domains.
You'd be better off ditching that spyware of an app.

5. Why is fonts.googleapis.com blocked but not fonts.gstatic.com ?
None of them is blocked. Please recheck!

6. I've seen this weird domain in my DNS logs, and I didn't found anything about it on the Internet...
**scdn.com** is owned by Spotify. The use it mostly to deliver content to their users.

**Comment by MaXfAa** [comment]
> Hello!

Hi !
> 1. *.firebaseio.com
>    Legit and good content is hosted on the domain.

Ok
> 2. *.metric.gstatic.com
>    ref: [Add metric.gstatic.com to blocklist #317](https://github.com/badmojr/1Hosts/issues/317)

I didn't understand everything, should we block it yes or no? I've been blacklisting it for quite a while now and it hasn't affected me...
> 3. *.grs.platform.dbankcloud.ru (Why are the international, european, asian and chinese domains blocked but not the russian one ??)
>    ref:
>    [collector (blacklist) #260](https://github.com/badmojr/1Hosts/issues/260)
>    [Question regarding grs.dbankcloud.com #103](https://github.com/badmojr/1Hosts/issues/103)

Perfect !
> 4. *.logs.prod.flamingo.apelabs.net (Data and logs collector from Space Ape (a branch of Supercell))
>    🆗

😎
> 5. *.firebaseremoteconfig.googleapis.com
>    Breaks Android apps that rely on Firebase. Related to no. 1

Oooh, ok !
> 6. *.skmarketingassetsprod.blob.core.windows.net (Used by Microsoft Swiftkey)
>    Is it used for tracking though?
>    Seems it only hosts files. e.g: https://skmarketingassetsprod.blob.core.windows.net/files/SwiftKey7.xIntegrationGuide.pdf)/files/SwiftKey7.xIntegrationGuide.pdf

Yes, It's not just for files, I was using SwiftKey and I noticed this domain in my DNS logs, these logins were done in the background (I wasn't opening PDFs,...)
> 7. *.firefox.settings.services.mozilla.com (This domain makes many requests for absolutely nothing and I think, from what I've read, that it's part of Mozilla Telemetry or something,... (I advise you, however, to check to be 100% sure))
>    ref: [Possible false positives for mozilla anudeepND/blacklist#14](https://github.com/anudeepND/blacklist/issues/14)

Ok ok, thanks !
> 1. I've noticed that a looooot of graph.something... are blocked (graph.facebook.com, graph.instagram.com, etc...) but why isn't graph.microsoft.com blocked ? I've seen it in my DNS logs:
>    The graph.something above are blocked due to their highly privacy intrusive nature.
>    I'm not well informed about the Microsoft one.

According to another answer to my post, we can block this domain but at our own risk; some Microsoft app features depend on it.
> 2. Are these Google domains tracking us ? The names are soooo weird (infinitedata, datamixer)
>    Those are better blocked at the individual level. Will break a bunch of Google apps' core functionalities if blocked.

Oh, ok
> 3. This domain spams literally my DNS, and it contains "logger", so, is it a logs collector ?
>    Perhaps.

Hahaha
> 4. These domains begin by "log" and come from TikTok, are they dangerous ?
>    Most likely. The only problem is that there are a sh*t load of such domains.
>    You'd be better off ditching that spyware of an app.

Oh noooo 😢. Don't get upset but I use TikTok and Douyin haha 😅
> 5. Why is fonts.googleapis.com blocked but not fonts.gstatic.com ?
>    None of them is blocked. Please recheck!

Oops, sorry: wrong list.
> 6. I've seen this weird domain in my DNS logs, and I didn't found anything about it on the Internet...
>    **scdn.com** is owned by Spotify. The use it mostly to deliver content to their users.

Ok "marketing" is insignificant

**Comment by badmojr** [comment]
> > 2. *.metric.gstatic.com
> >    ref: [Add metric.gstatic.com to blocklist #317](https://github.com/badmojr/1Hosts/issues/317)
> 
> I didn't understand everything, should we block it yes or no? I've been blacklisting it for quite a while now and it hasn't affected me...
> 

example:
The domain is  used  on this page for testing purposes.
https://ipv6test.google.com/

**Comment by MaXfAa** [comment]
> example:
The domain is used on this page for testing purposes.

So I can block this domain, no ?
