### ISSUE TITLE
uriports.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#469]
Is there any reason for `uriports.com` to be listed?

Sample site: `https://www.uriports.com/blog/introduction-to-spf-dkim-and-dmarc/`

Thank you and cheers

**Comment by badmojr** [comment]
Origin: https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tracking
cc: @ShadowWhisperer

**Comment by ShadowWhisperer** [comment]
**Homepage**  
> With our advanced analytics tool, you can monitor all types of web and mail reports like DMARC, Content Security Policy (CSP), Network Error Logging, and many more  

**https://www.uriports.com/faq** 
> Once you've added the correct HTTP response headers to your website, your visitors' browsers are instructed to send reports to a configured address.

**Associated**
```
009bdxat.uriports.com      #Alive
69hyjq1t.uriports.com        #Dead
8rwweb66.uriports.com      #Alive
98t3qetg.uriports.com        #Dead
app.uriports.com           #Alive
ayba8dhs.uriports.com        #Dead
ecpsecure.uriports.com       #Dead
ee33uafj.uriports.com        #Dead
gfqhh49h.uriports.com        #Dead
givergy.uriports.com         #Dead
s1unbzdt.uriports.com      #Alive
```

**Comment by crssi** [comment]
That is magnitude less intensive than, for example, almost every JavaScript framework.
In the last half a year DNS log for a few dozen users here, not a single request was made towards any `*.uriports.com`, except me visiting the URL set as an example in the first post. 😉

**Comment by badmojr** [comment]
Similar domains include:
report-uri.com
a.nel.cloudflare.com
csp-reporting.cloudflare.com

Sorry @crssi ! Can't get myself to exclude the domain.

**Comment by crssi** [comment]
No worries at all. 😉 
Thank you for your work ❤️
