### ISSUE TITLE
Request for tracker block: tct-teye.com [Android App]

### ISSUE THREAD

**Issue by DRSDavidSoft** [badmojr/1Hosts#48]
### Description

Hey there, @badmojr 

Can you please block `tct-teye.com` and `www.tct-teye.com` domains?  It's being used as a tracker in certain apps.

If you'd like to see more information, here's some more description:  

<details>
<summary>For more details, click here to show</summary>

After installing a **[Gallery app](https://play.google.com/store/apps/details?id=com.tclhz.gallery&hl=en_US&gl=US)** from the Developer **[Cloud Innovation Studio](https://play.google.com/store/apps/developer?id=Cloud+Innovation+Studio)** on a secondary Android device, I noticed that it started to communicate with the domain: ```www.tct-teye.com```

Here's a dump of requests that were made to this domain:

- `GET https://www.tct-teye.com/get-config/?configurationName=datahub&version=-1&appName=com.tclhz.gallery`  
    ```json
    {"datahub":"on","max_mobile_events_un_upload":100,"max_failed_times":50,"schedule_interval_second":"86400","upload_policy_flag":47,"upload_control_req_flag":7,"counts_policy_schedule_interval_hours":24,"request_service_config_interval_hours":"24","switch_off_versions":["2.00.14"],"switch_off_countries":["250","310","311","312","313","314","315","316","330","332","534","535","544","208","308","340","543","546","547","647","742","204","362","363","238","288","290","235","266","346","348","350","354","376","750","262","222","206","270","272","202","214","268","232","244","240","260","230","216","231","293","280","278","247","246","248","284","226","219"]}
    ```

- `POST https://www.tct-teye.com/collection/mobile-data/dailyData/`  
    ```Content-Disposition: form-data; name="phoneData"; filename="comp_data.zip"```
    ```json
    {"msg":"success","data":"save file success","code":200}
    ```

Here's the scary part: the `comp_data.zip` file that is being uploaded as `phoneData`, is a ZIP file that includes the following JSON data:

```json
{
    "timeZone": "GMT+xx:xx",
    "baseInfo": {
        "teyeId": "xxxxxxxxxxx",
        "deviceName": "xxxxxx",
        "model": "xxxxxxx",
        "countryNo": "xx",
        "androidVersion": "x.x.x",
        "romVersion": "xxxxxxx_xxxxxx-xxxxxxxxx x.x.x XXXXXX xxxxxxxxxx xxxx-xxxx",
        "timeZone": "GMT+xx:xx",
        "mcc": "xxx",
        "appName": "Gallery",
        "appVersion": "v8.3.0.0.G078.0",
        "appInstallTime": 1599965043887,
        "appLastUpdateTime": 1599965043887,
        "appInstallSource": "com.android.packageinstaller",
        "packageName": "com.tclhz.gallery"
    },
    "eventList": [{
        "_id": 62,
        "happenTime": "1605291103280",
        "packageName": "com.tclhz.gallery",
        "teyeId": "xxxxxxxxxxx",
        "appVersion": "v8.3.0.0.G078.0",
        "activityName": "com.tcl.gallery.app.GalleryActivity",
        "actionName": "ActivitySession",
        "duration": "8820"
    }]
}
```

I have redacted the fields that reveal my secondary device.  It seems that `teyeId` is a uniquely generated identifier that tracks the installation, as well as information regarding the device.

Based on [this repo](https://github.com/yifan-Eric/teye-dist/blob/master/src/js/config/api.js) ([backup](https://web.archive.org/web/20201125114327if_/https://raw.githubusercontent.com/yifan-Eric/teye-dist/master/src/js/config/api.js)), I can some other endpoints / package names as well that might be affected:

```javascript
const loginUrl = 'https://www.test-teye.com/chaos/login.html';

const apiTest = [
    '/getAllData',
    '/postPerfData',
    '/report/com.tct.camera/getAppPMActiveInfo',
    '/report/retention',
    '/report/hotevent',
    '/report/com.tct.camera/appUserActiveInfo',
    '/report/getAppDistribution',
    '/report/getDeviceNumber',
    '/report/getAndroidVersion',
    '/report/com.tclhz.gallery/getAppVersionList',
    '/report/device-report/getDeviceActiveOfDay',
    '/report/userEngagement',
    '/report/index/getPainSpotList',
    '/report/getAppList',
    '/report/getActivityCount?packageName=flink-com.tclhz.gallery',
    '/report/app/version/list'
];
```

Their base of operation seems to be located in China, and this tracking endpoint is being used to collect bid gata on mobile devices.

I have tested the app and can confirm that they work fine with this domain being blocked (in fact they start faster). As this domain is not blocked in other domain blacklists (including 1Hosts), I'd like to ask for it to be blacklisted, in order to avoid the tracking by said apps.
</details>

**Comment by badmojr** [comment]
Done! Thank you.
