### ISSUE TITLE
King Candy Crush domains linked to footprint.net

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#482]
</br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
</br>

**Client:**
NextDNS

</br>

**Domains:**
```

king-candycrush-prod.secure2.footprint.net
king-contenido-prod.secure2.footprint.net
```
</br>

**Details:**

I find it strange that the domains related to Candy Crush and King that use footprint are all blocked, except those... Is this normal ?
![cand-ss](https://user-images.githubusercontent.com/71935156/163467340-9a8286ec-288a-407c-8c69-33f246c14de4.png
)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
> king-contenido-prod.secure2.footprint.net

Orign: 
https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
https://github.com/willianreis89/ADsBlock/raw/master/list.txt
https://github.com/lesong/Surge/raw/main/rule/BanProgramAD.list


<br>

> king-candycrush-prod.secure2.footprint.net

Perhaps it's used for legit tasks. e.g
https://www.reddit.com/r/candycrush/comments/rc6pgp/does_anyone_have_a_good_f5_team_to_join/

**Comment by MaXfAa** [comment]
> > king-contenido-prod.secure2.footprint.net
> 
> Orign: https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt https://github.com/willianreis89/ADsBlock/raw/master/list.txt https://github.com/lesong/Surge/raw/main/rule/BanProgramAD.list
> 
> 
> > king-candycrush-prod.secure2.footprint.net
> 
> Perhaps it's used for legit tasks. e.g: https://www.reddit.com/r/candycrush/comments/rc6pgp/does_anyone_have_a_good_f5_team_to_join/

Oh ok so sorry ! Plus I just remembered that I shared a Candy Crush link footprint.net to a friend of mine and I had the thought that it was strange...
