### ISSUE TITLE
Appodeal ads domains

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#483]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**

<br>

**Domains:**
```
e4ff72f227653aa61de23b2379df588c0a3d3298eed535339cadbdaa.com
58dac16e7b2c86c19cfe48914a6e8fcdac9ae06fe5cf53369beaa45b.com
```
<br>

**Details:**
These domains are used for advertising, as you can see in this screenshot: (in any case for the first domain)
![image](https://user-images.githubusercontent.com/71935156/163676884-86923564-4ecf-431c-9b25-fda931cbae3b.png)

And it corresponds well to Appodeal because if you look in the DNS logs, we can see a request to Appodeal right after!
![image](https://user-images.githubusercontent.com/71935156/163676900-a8f904cf-88c7-441b-89c6-181f7678c105.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by MaXfAa** [comment]
New domain detected:
![image](https://user-images.githubusercontent.com/71935156/163730905-6e5e0d6c-a30d-46d2-8912-1218b1af0f1d.png)
26f25210fabe054e55a32c9565b0547044d0f68d87cc84c699b51c28.com

**Comment by badmojr** [comment]
https://blocklist-tools.developerdan.com/entries/search?q=a.26f25210fabe054e55a32c9565b0547044d0f68d87cc84c699b51c28.com

Domain doesn't exist. Please recheck!

**Comment by MaXfAa** [comment]
> https://blocklist-tools.developerdan.com/entries/search?q=a.26f25210fabe054e55a32c9565b0547044d0f68d87cc84c699b51c28.com
> 
> Domain doesn't exist. Please recheck!

Yes this domain exists, it has just been requested by my phone:
![image](https://user-images.githubusercontent.com/71935156/164511599-67dcc46d-04fd-41d3-b46e-d305eb12f461.png)

And can't say that it isn't Appodeal, it's obvious

**Comment by MaXfAa** [comment]
> I meant that it doesn't resolve to any valid ip.
> see: https://blocklist-tools.developerdan.com/entries/search?q=a.26f25210fabe054e55a32c9565b0547044d0f68d87cc84c699b51c28.com

Ok I see, but you can block it as a precaution. We don't know if it will work again later... maybe or maybe not...
