### ISSUE TITLE
cookiebot.com.edgekey.net makes breakage

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#49]
Hi @badmojr 

> On e.g. https://www.nuclearblast.de/ i can't use their cookie management because of this blocked domain.

See `https://github.com/nextdns/metadata/issues/461`.

The culprit is the `cookiebot.com.edgekey.net` which is a CNAME  for `consent.cookiebot.com`

Really appreciate if you can peek into. 😄 

Thank you and cheers

**Comment by badmojr** [comment]
Delisted!

**Comment by crssi** [comment]
<3
