### ISSUE TITLE
static.rocketreach.co

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#491]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
static.rocketreach.co
```
<br>

**Details:**

Breaks the page `https://rocketreach.co`

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Origin: https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
cc: @jawz101
