### ISSUE TITLE
Domain which sends diagnostic data to Microsoft

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#492]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
petrol.office.microsoft.com
```
<br>

**Details:**
This screenshot is from MS website, the other domains are already block, but not "petrol". 
![image](https://user-images.githubusercontent.com/71935156/164786622-8fe5831c-320c-45fd-b645-45cbbafaaade.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Not exactly used for tracking as it requires user action to send such data.
![hsfhknnk](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/media/console-share-feedback.png)

**Comment by MaXfAa** [comment]
> Not exactly used for tracking as it requires user action to send such data. ![hsfhknnk](https://camo.githubusercontent.com/5c8eda7dd502e54f8c4b25c6ce6c8ed670e965b1a6a328cc4a4d50f25933ff5d/68747470733a2f2f646f63732e6d6963726f736f66742e636f6d2f656e2d75732f6d656d2f636f6e6669676d67722f636f72652f756e6465727374616e642f6d656469612f636f6e736f6c652d73686172652d666565646261636b2e706e67)

Yes but "send a smile" doesn't just send an emote haha, it also send private data: "allow it to access the following internet endpoints **to send diagnostic data to Microsoft**" (as you can see in the screenshot) !

**Comment by badmojr** [comment]
My point is: it used for sending feedback.
It's only after a user clicks one of the above that such data is sent.

**Comment by MaXfAa** [comment]
> My point is: it used for sending feedback. It's only after a user clicks one of the above that such data is sent.

Everyone has an opinion.

**Comment by MaXfAa** [comment]
> My point is: it used for sending feedback. It's only after a user clicks one of the above that such data is sent.

You should add it to the Xtra block list at least

**Comment by badmojr** [comment]
Sorry! This is an in-app functionality and opt in by default.
Unless one clicks one of the buttons, nothing gets transferred.
