### ISSUE TITLE
Microsoft statics-marketingsites

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#493]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
statics-marketingsites-eas-ms-com.akamaized.net
```
<br>

**Details:**
This domain is blocked:
![image](https://user-images.githubusercontent.com/71935156/164789512-65c53d90-f51a-40fb-b70f-13fdc3809eae.png)

But this one isn't:
![image](https://user-images.githubusercontent.com/71935156/164789558-d7877e54-c87d-417e-a378-c2b720c61dda.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by MaXfAa** [comment]
`statics-marketingsites-wcus-ms-com.akamaized.net`
![image](https://user-images.githubusercontent.com/71935156/164790041-6060531e-0834-41f4-9da2-18a1f03ed5ff.png)

**Comment by badmojr** [comment]
The one blocked should probably be removed.

ref:
https://github.com/AdAway/AdAway/issues/3075
https://github.com/StevenBlack/hosts/issues/1748
