### ISSUE TITLE
backscatterer.org

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#495]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
backscatterer.org
```
<br>

**Details:**
Not sure why backscatterer.org should be listed.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
**Origin:** https://raw.github.com/anudeepND/blacklist/master/adservers.txt
**cc:** @anudeepND

**Comment by crssi** [comment]
Thank you ❤️
