### ISSUE TITLE
shopee.sg (breaking website)

### ISSUE THREAD

**Issue by 3xploiton3** [badmojr/1Hosts#50]
![image](https://user-images.githubusercontent.com/19517680/100518586-0b219280-31c5-11eb-8f7f-75185657f86a.png)

cf.shopee.sg
cv.shopee.sg

![image](https://user-images.githubusercontent.com/19517680/100518603-170d5480-31c5-11eb-97e3-53d545164856.png)

**Comment by badmojr** [comment]
Fixed!
