### ISSUE TITLE
Instagram web login broken

### ISSUE THREAD

**Issue by RouterCFW** [badmojr/1Hosts#500]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**NextDns:**

<br>

**Domains:**
```

connect.facebook.net

```
<br>

**Details:**

Can’t login to instagram on website when domain is blocked

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
ref:
https://github.com/badmojr/1Hosts/issues/30
https://github.com/badmojr/1Hosts/issues/151
https://github.com/badmojr/1Hosts/issues/403
https://github.com/badmojr/1Hosts/blob/master/-data/lists/antiAllow.lst

cc: @crssi

**Comment by crssi** [comment]
For majority of my users I am using `Lite`. I guess the ones being on `Pro` do not use IG (instag..).
Will investigate in the next days with my users on `Lite` and will let you know.

Cheers

**Comment by crssi** [comment]
I have made na IG account for test and I cannot confirm that listing of `connect.facebook.net` would break the login.

proof of succesfull login with `connect.facebook.net` being denied
![image](https://user-images.githubusercontent.com/17024151/165483429-e16cea47-8a7f-4a8d-ac3a-40eb72802580.png)

before ^^ I have blocked on NextDNS and the login was also a success
![image](https://user-images.githubusercontent.com/17024151/165484061-a17b2919-8fe6-44e8-acc6-2f795b7dc255.png)

Verdict: I cannot confirm what OP is claiming.

@badmojr if you need a special STR, just let me know. 😉

**Comment by RouterCFW** [comment]
> I have made na IG account for test and I cannot confirm that listing of `connect.facebook.net` would break the login.
> 
> proof of succesfull login with `connect.facebook.net` being denied ![image](https://user-images.githubusercontent.com/17024151/165483429-e16cea47-8a7f-4a8d-ac3a-40eb72802580.png)
> 
> before ^^ I have blocked on NextDNS and the login was also a success ![image](https://user-images.githubusercontent.com/17024151/165484061-a17b2919-8fe6-44e8-acc6-2f795b7dc255.png)
> 
> Verdict: I cannot confirm what OP is claiming.
> 
> @badmojr if you need a special STR, just let me know. 😉

Strange because after I unblocked the domain I can login I will block it again and retry

**Comment by RouterCFW** [comment]
Domain is blocked again and now sign in works weird must of been a Facebook back end change or something
