### ISSUE TITLE
Chat with MS support

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#507]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [X] Pro
- [ ] Xtra
<br>

**Client:**
uBO, NextDNS

<br>

**Domains:**
```
publisher.liveperson.net
lpcdn.lpsnmedia.net
accdn.lpsnmedia.net
lptag.liveperson.net
static-assets.fs.liveperson.com
va.idp.liveperson.net
va.v.liveperson.net
va.msg.liveperson.net

```
<br>

**Details:**
With listed domains we have a breakage trying to invoke `Questions? Talk to an expert`
![image](https://user-images.githubusercontent.com/17024151/165624496-8acb4478-b596-410e-bff3-7a30391fecdc.png)

**Comment by badmojr** [comment]
Wasn't able to successfully reproduce this issue. Any specific pages where that chat service can be found?

**Comment by crssi** [comment]
Sorry... its exact the same URL as on screenshot, but I have forgot to paste it here. 😢 
Here it is: `https://www.microsoft.com/en-us/microsoft-365/p/microsoft-365-family/cfq7ttc0k5dm`

Cheers

**Comment by badmojr** [comment]
Could u also send ss of what the chat service looks like when it properly functions?

**Comment by crssi** [comment]
Will try to record a video in the next days.

**Comment by crssi** [comment]
Updated list in OP... removed `az725175.vo.msecnd.net` and added `liveperson.com`

Give me a day or two, please, will do extensive tests.

This is without blocking:
![image](https://user-images.githubusercontent.com/17024151/166140075-a3267798-6296-4450-8ad8-0730690c4749.png)

**Comment by crssi** [comment]
From the last test it seem that unblocking `liveperson.net` and `lpsnmedia.net` is sufficient to avoid the breakage.

See video (its speed up, to be under 10Mb size limit, use play/pause):

https://user-images.githubusercontent.com/17024151/166168486-c70f0586-35da-48d1-906e-05f0cd738297.mp4

**Comment by crssi** [comment]
It seem that only `liveperson.net` and `lpsnmedia.net` must be unblocked to avoid breakage.

See video (its speed up to avoid 10Mb size limit... use play/pause):

https://user-images.githubusercontent.com/17024151/166168612-b2022289-a42f-4d9c-b5a2-4f74a1487cc6.mp4

**Comment by crssi** [comment]
I have retested ^^ again and the culprits are thefinding in the last post.
OP is accrdingly updated now.

Cheers

**Comment by badmojr** [comment]
Updated OP with the specific required domains. Thanks for your work @crssi !

**Comment by crssi** [comment]
Something still isn't right or I didn't understand the final verdict... `liveperson.net` and `lpsnmedia.net` are still listed.

Cheers

**Comment by badmojr** [comment]
Root domains get unblocked by default.
Hence, there's no need to list them too.
