### ISSUE TITLE
.home substitution domains (Google Analytics and analytics from Snapchat)

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#509]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
app-analytics-v2.snapchat.com.home
ssl.google-analytics.com.home
```
<br>

**Details:**

![image](https://user-images.githubusercontent.com/71935156/165977656-37538e2d-f6a2-45a7-bbc9-00648bd4aa64.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
The domains don't resolve. `.home` isn't a valid public suffix.

see:
https://publicsuffix.org/list/public_suffix_list.dat
https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

ref: #510

**Comment by MaXfAa** [comment]
> 

Oh ok, that's weird
