### ISSUE TITLE
ads.mopub

### ISSUE THREAD

**Issue by RicoHeat** [badmojr/1Hosts#510]
So I wanted to see if you can verify if ads.mopub.col is actually trying to be sneaky.. This is from my InviZible Pro's logs.. I have been blocking it and the app hasn't given me any issues..

PLAYit -> ads.mopub.col
ads.mopub.col -> 103.170.232.254

Normally ads.mopub.com and a few others is what I normally see in many lists but never until now have I seen this with .col

This is the Playstore link incase you want to dig into it a bit

https://play.google.com/store/apps/details?id=com.playit.videoplayer

**Comment by badmojr** [comment]
The domain doesn't resolve. `.col` isn't a valid public suffix.

see:
https://publicsuffix.org/list/public_suffix_list.dat
https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains
