### ISSUE TITLE
www.kantar.com

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#519]
Lists in use: Pro

Client: NextDNS 

Domains: https://www.kantar.com

Details: Kantar is a professional company like the Gartner specialized in business insights. 
It shouldn't be blocked.

**Comment by badmojr** [comment]
**Origin:**
https://github.com/migueldemoura/ublock-umatrix-rulesets/raw/master/Hosts/ads-tracking

cc: @migueldemoura

**Comment by migueldemoura** [comment]
I don't have the stats for this one, so removed for now: https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/240c7d3cc9219015f5836a3e62f7c195747ac024.

**Comment by Quorum75** [comment]
> **Origin:**
> 
> https://github.com/migueldemoura/ublock-umatrix-rulesets/raw/master/Hosts/ads-tracking
> 
> 
> 
> cc: @migueldemoura

I understand but as I mentioned it is the same type of company than the Gartner (market esearch/insights) but don't do ads like Google.
Gartner for instance isn't blocked so why them?

**Comment by Quorum75** [comment]
> I don't have the stats for this one, so removed for now: https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/240c7d3cc9219015f5836a3e62f7c195747ac024.

Thank you.
