### ISSUE TITLE
Imgur doesn't work

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#532]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
maybe p.imgur.com or t.imgur.com
```
<br>

**Details:**
Imgur doesn't work

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Screenshots & dns logs please!. Mine works just fine.

**Comment by MaXfAa** [comment]
DNS logs:
![image](https://user-images.githubusercontent.com/71935156/168434380-8dc57b18-86d2-4495-ba5d-74032d87d7f7.png)
![image](https://user-images.githubusercontent.com/71935156/168434521-93bd3434-ad25-471c-9504-cc998784d175.png)
![image](https://user-images.githubusercontent.com/71935156/168434580-d2eaf0a3-d8eb-4a6d-bb02-4a2ac15426cc.png)

Screenshot:
![image](https://user-images.githubusercontent.com/71935156/168434688-79ad1bd8-933f-42f3-b970-40be2fb77aa9.png)
(My extensions are disabled)

**Comment by badmojr** [comment]
What blocklist that you have enabled keeps on blocking `js.media-lab.ai`?

**Comment by MaXfAa** [comment]
> What blocklist that you have enabled keeps on blocking `js.media-lab.ai`?

![image](https://user-images.githubusercontent.com/71935156/168440839-a851ea78-2a27-437b-a46c-67f9cd5a3972.png)
And it's because of ``https://js.media-lab.ai/ana-sentry.js``

**Comment by badmojr** [comment]
> I mean, there is some tracking stuff host on this domain)

Well! see:
#276 
#466

**Comment by crssi** [comment]
Here works just fine with `Pro`, but if I deny `js.media-lab.ai` then its broken... but `*.media-lab.ai` is not listed in `Pro`.

**Comment by MaXfAa** [comment]
@badmojr Ok I understand, so:
You haven't need to block the domain because it breaks Imgur
and for the privacy-side, it doesn't matter because uBlock blocks the specific tracking (sentry) ressource.

**Comment by MaXfAa** [comment]
> Here works just fine with `Pro`, but if I deny `js.media-lab.ai` then its broken... but `*.media-lab.ai` is not listed in `Pro`.

Ok, thanks a lot, I understand!
