### ISSUE TITLE
PayPal app needs c.paypal - (to whitelist)

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#533]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domain:**
```
c.paypal.com
```
<br>

**Details:**
c.paypal is required by the PayPal app to work.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Need more details. Not enough to work with on your report.

**Comment by MaXfAa** [comment]
> Need more details. Not enough to work with on your report.

Without c.paypal, you can't log into the app. It requests the password again and again (I mean, if the password is correct a loading animation appear and then it asks again the password). And the app crashes too.

**Comment by MaXfAa** [comment]
I tested several things (whitelisted some domains, etc...) and it's c.paypal which is the cause.

**Comment by crssi** [comment]
No issues here on PayPal with `Pro`.
![image](https://user-images.githubusercontent.com/17024151/168461661-ddba4bc6-7669-47fd-a19c-c1e416d4298f.png)

**Comment by MaXfAa** [comment]
> No issues here on PayPal with `Pro`.
> ![image](https://user-images.githubusercontent.com/17024151/168461661-ddba4bc6-7669-47fd-a19c-c1e416d4298f.png)
> 

No, I have issues with the Android app!

**Comment by crssi** [comment]
I see... I have tested on desktop browsers and on iOS devices, which doesn't suffer, but not Android.

**Comment by badmojr** [comment]
related: #421

**Comment by badmojr** [comment]
> And the app crashes too.

Screenshots/video of the app breaking please!

**Comment by MaXfAa** [comment]
> related: #421

Not really related because t.paypal isn't required by the app, and works perfectly without it (only c.paypal is whitelisted while t.paypal isn't).

**Comment by MaXfAa** [comment]
> > And the app crashes too.
> 
> Screenshots/video of the app breaking please!

Unfortunately I can't, because:
1. I'm already logged in
2. I can't record the PayPal app (it's considered like a bank app so the recording feature is blocked)
