### ISSUE TITLE
Algolia

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#538]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
Every algolia.net domains in general
```
<br>

**Details:**

![image](https://user-images.githubusercontent.com/71935156/168618303-4bc8d081-5ae4-4f2e-ac53-f98ec0964035.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
![algolia](https://user-images.githubusercontent.com/40524316/168657306-38a2bc5b-4228-4bc6-ac49-1f31fadcfce5.PNG)

**Comment by badmojr** [comment]
It powers the search functionality on a lot of sites.
e.g: https://www.ubisoft.com/en-us/

**Comment by MaXfAa** [comment]
> It powers the search functionality on a lot of sites.
> e.g: https://www.ubisoft.com/en-us/
> 
> see: https://publicwww.com/websites/%22algolianet.com%22/
> 

Oh sorry, my bad 😔
