### ISSUE TITLE
doubt with sources

### ISSUE THREAD

**Issue by gallegonovato** [badmojr/1Hosts#541]
Good afternoon @badmojr 

I have been using your hosts for some time now. I use 1 Hosts Pro or 1 Hosts Xtra on my adaway.

For which I thank you a million times for all your work and effort. Thank you for your hosts and your rules.

I don't know for mobile use which you recommend more the pro or xtra version of your hosts?

And today looking I think I have things, which you already use on your hosts. And me without realizing it :(

Looking at https://github.com/badmojr/1Hosts/blob/master/-data/lists/assets.txt what are the fonts that you use on your hosts I noticed some that appear in that list and I use. So I think I could delete them. 

The ones that I have and appear in your lists are:

You use https://hostfiles.frogeye.fr/multiparty-trackers.txt and I have https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt (so I can delete mine).

Here with this https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_google_adservice_id.txt (that you use) https://raw.githubusercontent.com/kowith337/CustomHosts-via-hostsmgr/unarranged/hosts.txt and https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover_aggressive.txt . I don't know if I can delete them.

Then you use https://dbl.oisd.nl/ and I use Oisd Extra.

Then there is http://pgl.yoyo.org/adservers/serverlist.php?showintro=0;hostformat=hosts and I https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0 . So can I delete it?

https://someonewhocares.org/hosts/zero/hosts and I https://someonewhocares.org/hosts/zero/hosts so delete it.

So my question if I am right or wrong.

I take this opportunity to suggest you the following sources: https://raw.githubusercontent.com/kowith337/CustomHosts-via-hostsmgr/unarranged/hosts.txt , https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover_aggressive.txt , https://github.com/infazide/blockingjunkie , https://github.com/KodoPengin/GameIndustry-hosts-Template

Best regards and thanks a million for all your work and help.

**Comment by badmojr** [comment]
> I don't know for mobile use which you recommend more the pro or xtra version of your hosts?

I recommend following the usage guide outlined on the README.

> Looking at https://github.com/badmojr/1Hosts/blob/master/-data/lists/assets.txt what are the fonts that you use on your hosts I noticed some that appear in that list and I use. So I think I could delete them.

No. That list is for accreditation purposes only!

> I take this opportunity to suggest you the following sources: https://raw.githubusercontent.com/kowith337/CustomHosts-via-hostsmgr/unarranged/hosts.txt , https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover_aggressive.txt , https://github.com/infazide/blockingjunkie , https://github.com/KodoPengin/GameIndustry-hosts-Template

I'll see what useful content I can extract from them. Thanks!

**Comment by gallegonovato** [comment]
Good afternoon @badmojr

Thank you very much for your time and help.

I am continuing with your Xtra and pro hosts. I have been using them both for years on two terminals and always perfect.

Thank you very much for your help and time
