### ISSUE TITLE
iOS App Store Blocked

### ISSUE THREAD

**Issue by RouterCFW** [badmojr/1Hosts#545]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [x] mini
- [x] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:**
Next dns

<br>

**Domains:**
```

amp-api-edge.apps.apple.com

```
<br>

**Details:**

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by RouterCFW** [comment]
amp-api-edge.apps.apple.com Is needed for the App Store to function and it’s currently being blocked

**Comment by Domsicols** [comment]
Same. I was just going to report it now. Thanks

**Comment by badmojr** [comment]
Got some jpegs? Can't seem to find anything that may be causing the above.

**Comment by badmojr** [comment]
I'll be damned! This was a recent adddition from an uptream.
see: https://github.com/ookangzheng/blahdns/commit/c127164e18ab6150831a28ef635810411d37b282

**Comment by badmojr** [comment]
cc: @ookangzheng

**Comment by badmojr** [comment]
another related (recent) report :
https://t.me/EnergizedProtection/147360

**Comment by badmojr** [comment]
Should be fixed by now: https://github.com/badmojr/1Hosts/commit/c111d6dfaa9b7c93e232394cb23ac61356002b28

**Comment by PeterDaveHello** [comment]
Just curious, what's the upstream that affect this change?

**Comment by badmojr** [comment]
> Just curious, what's the upstream that affect this change?

https://github.com/badmojr/1Hosts/issues/545#issuecomment-1146873834
