### ISSUE TITLE
Samsung MCSVC

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#547]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
us-api.mcsvc.samsung.com (90% of the time)
us.mcsvc.samsung.com
us-rd.mcsvc.samsung.com
kr-cdn-gpp.mcsvc.samsung.com
us-cdn-gpp.mcsvc.samsung.com
kr-api.mcsvc.samsung.com
cn-api.mcsvc.samsung.com.cn
```
<br>

**Details:**
My phone requests these domains (and the "us-api" one in particular) when I use the split screen feature (display two apps at the same time on the screen).
MCSVC is a Samsung's service "for Efficient Marketing". As you can read on the following site, "create, launch, and optimize your marketing campaign for customer acquisition and retention.": https://us-mktg.mcsvc.samsung.com/

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
I find these resources to be informative.
ref: 
https://beta.pithus.org/report/58e4391da6564e5ade27f02738fea0e1a5a7392cbcff6ea96cc326dd1d835a32
https://docplayer.net/222642536-Android-mobile-os-snooping-by-samsung-xiaomi-huawei-and-realme-handsets.html
