### ISSUE TITLE
ss.phncdn.com.sds.rncdn7.com is CNAME for ss.phncdn.com and breaks PornHub

### ISSUE THREAD

**Issue by p1r473** [badmojr/1Hosts#55]
ss.phncdn.com.sds.rncdn7.com is CNAME for ss.phncdn.com and breaks PornHub
No ads served here
https://github.com/EnergizedProtection/block/issues/636

**Comment by badmojr** [comment]
Fixed!

**Comment by p1r473** [comment]
also
ev.phncdn.com.lds.rncdn7.com is CNAME for ev.phncdn.com and breaks PornHub

**Comment by badmojr** [comment]
Removed!
