### ISSUE TITLE
Whitelist : api.revenuecat.com

### ISSUE THREAD

**Issue by zeezeepiggy** [badmojr/1Hosts#553]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** 
NextDNS, AdGuard Pro

<br>

**Domains:**
```
api.revenuecat.com
```
<br>

**Details:**
This is used by 1blocker for Safari subscription. Checking subscriptions in the app fails.

![708A8998-82AE-4F30-A849-5D89A0860F5B](https://user-images.githubusercontent.com/27464836/172877076-0e114689-c8cf-4359-bbc9-198a811d8c9f.png)
![77180AB8-6C83-4932-99BF-AB6DB7ECB6CE](https://user-images.githubusercontent.com/27464836/172878962-2ac84886-4877-4bb4-9cbc-afd7ee72ed91.jpeg)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
What happens after the domain is allowed? Share a screenshot please!

**Comment by badmojr** [comment]
ref: https://github.com/StevenBlack/hosts/pull/1837

**Comment by zeezeepiggy** [comment]
Please see attached. The error box is gone and Manage my subscription is also visible at the bottom. The filters update seems to be faster too.

![1B571099-2F6F-446B-A3A2-B71B8C6E84D8](https://user-images.githubusercontent.com/27464836/172995886-91a01191-326f-4ac7-a208-c67a0d3f2e49.jpeg)
![59C142E4-CA16-4651-90A1-1010C874B9D2](https://user-images.githubusercontent.com/27464836/172995894-505a7fd1-0017-4c20-b782-66af01ca2883.png)
![06D12EA0-E3FB-4305-93D7-4A5C2FA0E0B6](https://user-images.githubusercontent.com/27464836/172995900-d8f3e402-51a9-4656-9b22-ee10278d643d.png)

**Comment by badmojr** [comment]
ok. Thank you.
