### ISSUE TITLE
Whitelist : self.events.data.microsoft.com is used by Office 365 Online

### ISSUE THREAD

**Issue by zeezeepiggy** [badmojr/1Hosts#565]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
Office Online, NextDNS

<br>

**Domains:**
```

self.events.data.microsoft.com

```
<br>

**Details:**

This domain is being used by Office 365 Online. i cannot save documents online when this is blocked. 

Can you please whitelist? I think not many people uses office online, but blocking this definitely impacts office online saving.

i found a documentation related to this:

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints

This is also whitelisted in my company’s firewall.

1host Lite is not blocking this.

i really like 1host Pro, but it’s too aggressive. I will continue to use it and just report the links that causes failure.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by zeezeepiggy** [comment]
Weird. I tried it again earlier this morning and i really cannot save when this is enabled. Im doing shared word document with collaboration. When two people is updating the doco, mine is not saving. The other people can. But when i whitelist this, mine saves as well.

should we add this in 1host Extra instead of Pro?

**Comment by badmojr** [comment]
> should we add this in 1host Extra instead of Pro?

We currently don't have this feature, as can be seen [here](https://github.com/badmojr/1Hosts/tree/master/submit_here).

**Comment by zeezeepiggy** [comment]
@badmojr i will gonna let you decide if you want to add this in the Pro list. 

At the moment, i whitelisted this in my nextdns profile.

please close if required
