### ISSUE TITLE
TikTok tracking blocklist

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#566]
Hi badmojr,
Do you know this list? https://raw.githubusercontent.com/llacb47/mischosts/master/tiktok-hosts

I asked OISD's creator why he's blocking "frontier-va" from TikTok and there is his answer:
![image](https://user-images.githubusercontent.com/71935156/173602928-27c59de3-03b8-4c23-9060-9e72674d64a1.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
It an outdated list, 2 years old. Last update was on` Dec 3, 2020`.
see: https://github.com/llacb47/mischosts/commits/master/tiktok-hosts

**Comment by MaXfAa** [comment]
> It an outdated list, 2 years old. Last update was on` Dec 3, 2020`. see: https://github.com/llacb47/mischosts/commits/master/tiktok-hosts

Oh yes that's true
