### ISSUE TITLE
Whitelist: reporting.jdsports.nl

### ISSUE THREAD

**Issue by marcocce** [badmojr/1Hosts#573]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:** NextDNS and AhaDNS

<br>

**Domains:**
```
reporting.jdsports.nl
jdinter.redeye.international
```
<br>

**Details:**
When ordering on [JD Sports](https://en.wikipedia.org/wiki/JD_Sports), the page to track the parcel does not load because it is blocked.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Hello! How do I reproduce this? Any steps?
Perhaps some screenshots too as I am not familiar with the site in question.

**Comment by marcocce** [comment]
Hi! The link is in the email they sent me, I can only access it by disabling NextDNS. I will try to investigate further.
![3E27693D-708F-4BC9-B267-13B9D217DEFA](https://user-images.githubusercontent.com/103379558/175824861-8a078f6f-85b2-4429-ae63-f236f09679a9.jpeg)

**Comment by marcocce** [comment]
If you need it, I can give you the link I have in the email... it's very weird lol

**Comment by badmojr** [comment]
> I can give you the link I have in the email

Yes. Please [dm me](mailto:badmojr@gmail.com?subject=1Hosts/issues/573).

**Comment by marcocce** [comment]
This is the error it gives me when I try to search for the two domains.
![image](https://user-images.githubusercontent.com/103379558/175826769-48a0c7dc-6811-473f-af61-9b815c8fe694.png)

I tried from computer (I was from iPhone before)... and uBlock Origin only blocks the link with Xtra list and not with Pro list anymore.
![image](https://user-images.githubusercontent.com/103379558/175826795-79d9ae66-d36c-4fd7-b277-299948501adf.png)

_I hope I have been helpful!_

**Comment by badmojr** [comment]
> I hope I have been helpful!

Send the link to my email.

**Comment by marcocce** [comment]
> Send the link to my email.

Done.

**Comment by badmojr** [comment]
This simply tracks you and redirects to the final page where the order tracking happens.

**Comment by marcocce** [comment]
> This simply tracks you and redirects to the final page where the order tracking happens.

Ok. Anyway I don't think it will happen to me again so if it does. I'll disable NextDNS for a moment.
Thanks for everything and sorry for the trouble :)
