### ISSUE TITLE
Request to Detail Difference Between Versions

### ISSUE THREAD

**Issue by sr093906** [badmojr/1Hosts#576]
Could you detail the differences between the versions given. For example, which sources are included in which versions.

**Comment by badmojr** [comment]
> For example, which sources are included in which versions.

You could do this yourself with the help of Crosscheck.
see: https://github.com/badmojr/crosscheck


Simply fork/template the repo, add the lists you want to check, and run it with GitHub Actions.

**Comment by badmojr** [comment]
Simply because it isn't as easy as you might think.
