### ISSUE TITLE
False positive: exp.host

### ISSUE THREAD

**Issue by dhruska** [badmojr/1Hosts#578]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
exp.host
```
<br>

**Details:**
This domain is used by Expo Snack (https://snack.expo.dev) for previewing mobile apps while developing them and should not be blocked.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by byCedric** [comment]
It's not just used for Snack, [Expo]()https://expo.dev) uses it to pull configuration files like:
- The [Expo app manifest schema](https://docs.expo.dev/versions/v45.0.0/config/app/)
  https://exp.host/--/api/v2/project/configuration/schema/45.0.0
- The compatible versions of libraries per Expo SDK
  https://exp.host/--/api/v2/versions

😄
