### ISSUE TITLE
Ally Bank app breakage

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#581]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
clientstream.launchdarkly.com
```
<br>

**Details:** Cannot login to my Ally bank app. After testing for 30 min., allowlisting this DNS request worked.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by yokoffing** [comment]
App: https://apps.apple.com/us/app/ally-banking-investing/id514374715

Stays stuck on loading screen if you don’t allowlist the aforementioned request: https://postimg.cc/xNMB3wLf

**Comment by badmojr** [comment]
Notes:
https://docs.launchdarkly.com/sdk/concepts/domain-list
