### ISSUE TITLE
add metric.gstatic.com

### ISSUE THREAD

**Issue by holequantum** [badmojr/1Hosts#582]
i have added manually and it does not block amy of my devices functions so it can be blocked can you add this to the repo.

**Comment by badmojr** [comment]
Hello.
We've had a discussion about this domain before.
See: #317

**Comment by holequantum** [comment]
i said it should not be blocked by i have blocked nothing breaks by blocking that so should i unblock that and can i have a reason what is this that will make it really helpful and close this topic

**Comment by badmojr** [comment]
> i said it should not be blocked by i have blocked nothing breaks by blocking that so should i unblock that and can i have a reason what is this that will make it really helpful and close this topic

Check out #317 for more info.

**Comment by holequantum** [comment]
#317 they are talking of blocking it does break wifi or something but it does not i can confirm on my android12 and 11 systems even 10. so i thing this need to be looked again thanks.

**Comment by badmojr** [comment]
What's your adblock client?

**Comment by holequantum** [comment]
https://cs.android.com/search?q=ds.metric.gstatic.com
i find it is actually from android seems like as you can see.

**Comment by badmojr** [comment]
> i also see the same error

If you block `*.metric.gstatic.com`, you'll see that error.

It should say something like this if you unblock the domain.
![20220706_154339](https://user-images.githubusercontent.com/40524316/177553092-265ec658-8425-49cd-b254-0a32a000d476.jpg)

**Comment by holequantum** [comment]
yes you are write but
i make ds.metric.gstatic.com to the allowlist and now ipv6 is ok just like yours.
but i was blocking somthing like that.
cfb6b4dc-dnsotls-ds.metric.gstatic.com
initial part is ramdom-dnsotls-ds.metric.gstatic.com
i can block this without issues.

**Comment by holequantum** [comment]
i think we can add this to the host

**Comment by badmojr** [comment]
I am afraid not. Sorry!

**Comment by holequantum** [comment]
`I am afraid not. Sorry!`
did not understand.

**Comment by badmojr** [comment]
> i think we can add this to the host

I am afraid not. Sorry!
