### ISSUE TITLE
Disney+ emails breakage

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#585]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
image.mail.disneyplus.com
```
<br>

**Details:** Breaks images from loading in Disney+ emails

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
What do I do to receive one of such emails myself?

**Comment by yokoffing** [comment]
Subscribe to Disney+...

After allowlisting `image.mail.disneyplus.com`, images show up as they're suppose to:

![1](https://user-images.githubusercontent.com/11689349/177794329-586656a7-1748-433a-b064-57f3f37fc9c2.png)
![2](https://user-images.githubusercontent.com/11689349/177794347-eed78a7e-8738-4976-bd86-e2ecee66b68a.png)
![3](https://user-images.githubusercontent.com/11689349/177794358-b0643cc0-90a8-4135-9a9a-9424add2d12e.png)

All of these were empty placeholders prior to allowlisting.

**Comment by yokoffing** [comment]
I forwarded you the email as well.

**Comment by badmojr** [comment]
The domain that's causing the above breakage is **`exacttarget.com.edgekey.net`**, which is used for email marketing and tracking.

Similar domains that use the CNAME above include:
```
image.email.microsoftemail.com
image.email.auspost.com.au
image.mail.onedrive.com
```

**Comment by yokoffing** [comment]
I can't speak for those other domains. I only know that `image.mail.disneyplus.com` will interfere with a everyday use case (e.g., my partner really annoyed me about this one lol).

If we use the guidelines posted on your repo,

```
Lite - Level 2: balanced; set & forget, doesn't hamper user experience (UX), recommended.
Pro - Level 3: strict; has some minimal breakages, prioritizes privacy & safety (adblocking) over UX e.g blocks graph.facebook.com.
```

then I would allowlist it for Lite and leave it blocked for Pro and Xtra.

Personally, would love to see it allowlisted for Lite and Pro, and blocked in Xtra, but that's just my preference.

**Comment by spirillen** [comment]
I don't see the big issue here as you should NEVER EVER include external sources into any email as they mostly are used for tracking, and you should NEVER accept html mail, only TEXT based mails, everything else should go straight to the spam/trash folder with help from your rules at server level.

**Comment by yokoffing** [comment]
> I don't see the big issue here as you should NEVER EVER include external sources into any email as they mostly are used for tracking, and you should NEVER accept html mail, only TEXT based mails, everything else should go straight to the spam/trash folder with help from your rules at server level.

That's great for privacy enthusiasts like us, but people like my partner just want their shit to work, which is why I said:

> I would allowlist it for Lite and leave it blocked for Pro and Xtra.

But in this instance, I'm okay with it being universally unblocked.

**Comment by spirillen** [comment]
> just want their shit to work,

See if he used text based mail, it have already **JUST WORKED** :wink: :stuck_out_tongue_winking_eye:
