### ISSUE TITLE
TotalAV.com false positive

### ISSUE THREAD

**Issue by curdatron** [badmojr/1Hosts#588]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [x] mini
- [x] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
www.totalav.com
track.totalav.com
```
<br>

**Details:**
NextDNS, and by extension 1Hosts is blocking access to TotalAV domains and sub-domains. TotalAV is an antivirus service certified by AV-TEST, AV Comparatives and VB100. 

TotalAV provide consumer antivirus for Windows, Mac and Android. As well as offering cloud protection, real time antivirus and on-demand anti-malware detection and removal, they also provide various ID protection, ad blocking and privacy protections services. 

Potentially, the blocking enforced here prevents virus definitions being served to existing users of the antivirus service, who also utilise 1Hosts, NextDNS or other services which utilise this feed. Please consider whitelisting TotalAV domains.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
https://www.reddit.com/r/antivirus/comments/dwlnlf/totalav_scam/
