### ISSUE TITLE
Some new to be blacklisted?... maybe

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#59]
On the site `https://klikponudba.com`, there are found many 3rd parties that could be blocked.
I am blocking the following in uBO and nothing brakes:
```
||monorail-edge.shopifysvc.com^$xhr
||d1u9wuqimc88kc.cloudfront.net^$script
||cdn-spurit.com^$script
||easygdpr.b-cdn.net^
||cdn.codeblackbelt.com^$script
||wheelioapp.azureedge.net^$script
||boostercentral.com^
||multifbpixels.website^$script
||judge.me^
||netlify.com^
||cdn.pushowl.com^
||sy.salesmanago.pl^$script
||sp-seller.webkul.com^$script
||window-shoppers.azurewebsites.net^$script
||boostifytheme.com^$script
```
and those can be also blocked as hosts:
```
monorail-edge.shopifysvc.com
d1u9wuqimc88kc.cloudfront.net
cdn-spurit.com
easygdpr.b-cdn.net
cdn.codeblackbelt.com
wheelioapp.azureedge.net
boostercentral.com
multifbpixels.website
judge.me
netlify.com
cdn.pushowl.com
sy.salesmanago.pl
sp-seller.webkul.com
window-shoppers.azurewebsites.net
boostifytheme.com
```

Maybe `azureedge.net` also as whole?

Cheers

**Comment by badmojr** [comment]
Hello! Thank you for bring these to my attention.

Fortunately, 1Hosts (Pro) has some of these included/blocked. Time to upgrade!?  😉
```
monorail-edge.shopifysvc.com
easygdpr.b-cdn.net
cdn.codeblackbelt.com
cdn.pushowl.com
sy.salesmanago.pl
```

The rest have to do with Shopify (apps), though I can't guarantee their trustworthness privacy-wise.
Here's some urls I've come accross.

```
https://spur-i-t.com/shopify-apps/
https://apps.shopify.com/wheelio-first-interactive-exit-intent-pop-up
https://boostercentral.com/booster-discount
https://sp-seller.webkul.com/mvm-landing/
https://apps.shopify.com/window-shoppers

```

The only ones that stick out like a sore thumb & seem suspicious are:-
```
d1u9wuqimc88kc.cloudfront.net
multifbpixels.website
```

Lastly,
```
azureedge.net - My gut tells me "hell no!"
judge.me - It's about reviews & sheet.
netlify.com - I for one have a website hosted by them; e.g https://hosts.netlify.app/Lite/adblock.txt

```

Note:- This was just quick observation done.
What's your take?

**Comment by crssi** [comment]
> Fortunately, 1Hosts (Pro) has some of these included/blocked. Time to upgrade!?

Nah. I am using it on NextDNS for my household and parents. They tend to hang me to the wall of shame for every breakage and thus 1Hosts (Pro), despite it is good, is too aggressive for that purpose. ;)
I am sorry that I haven't checked the Pro, before dumping those here.

> azureedge.net - My gut tells me "hell no!"

Mine too. Just asked more experienced fellow. ;)

> judge.me - It's about reviews & sheet.

Not very important I guess.

> netlify.com - I for one have a website hosted by them; e.g https://hosts.netlify.app/Lite/adblock.txt

LOL

> Note:- This was just quick observation done.

I really appreciate your time to get into this "issue".

> What's your take?

None, yet.
I have just stumbled on those and bringing it to attention.
I seems that I felt a need to contribute to addition also instead only to reduction. ;)

Wish you best and be safe... cheers ❤️

**Comment by badmojr** [comment]
Just blocked these on 1Hosts (Pro), let's see what's gonna happen.
```
d1u9wuqimc88kc.cloudfront.net
cdn-spurit.com
wheelioapp.azureedge.net
boostercentral.com
multifbpixels.website
sp-seller.webkul.com
window-shoppers.azurewebsites.net
boostifytheme.com
cdn.ghostmonitor.com
dashboard.wheelio-app.com
sr-cdn.azureedge.net
disco-flipclock.netlify.app
cdn.judge.me
```

**Comment by crssi** [comment]
Is there any special reason that you do not have those also in the 1Hosts (Lite)?
```
monorail-edge.shopifysvc.com
easygdpr.b-cdn.net
cdn.codeblackbelt.com
cdn.pushowl.com
sy.salesmanago.pl
```

Cheers

**Comment by badmojr** [comment]
> Is there any special reason that you do not have those also in the 1Hosts (Lite)?
> 
> ```
> monorail-edge.shopifysvc.com
> easygdpr.b-cdn.net
> cdn.codeblackbelt.com
> cdn.pushowl.com
> sy.salesmanago.pl
> ```
> 
> Cheers

It's because they are already included in 1Hosts (Pro)...
That's the rule. I only block a sub/domain if it missing in all 3 versions of the 1Hosts lists.

Gives people motivation to upgrade! & the quickstart guide is clear about that.

**Comment by crssi** [comment]
Oh. I see. Thx 👍
