### ISSUE TITLE
Block sp.mail.notion.so

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#590]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:**

<br>

**Domains:**
```
sp.mail.notion.so
```
<br>

**Details:**
pixel tracker embed in notion.so emails, of the form:
```
sp.mail.notion.so/q/dead4zakekkek_xoxo~~/deadbeef~/RgRg_deadbeefkekekek_wwwAAAAAAAAAAAAAAAAAAAAAAAA~~
```

**Comment by ignoramous** [comment]
As someone intimately familiar with DNS blocking, I can tell you that CNAME uncloaking works today, but it won't forever. Explicit is better than implict (:

**Comment by badmojr** [comment]
> As someone intimately familiar with DNS blocking, I can tell you that CNAME uncloaking works today, but it won't forever. Explicit is better than implict (:

That's news to me. Care to explain more?

**Comment by ignoramous** [comment]
HTTPS/SVCB records contain kv pairs. Apps may use it as an alternative to CNAME. This is still uncloakble ([how?](https://news.ycombinator.com/item?id=26298339)).

Some DNS providers use ALIAS records or flatten out the CNAME. Instead of 

```
sp.mail.notion.so.	300	IN	CNAME	spgo.io.
spgo.io.		59	IN	A	54.200.235.100
```

you'd see:

```
sp.mail.notion.so.	59	IN	A	54.200.235.100
```

----

Also, 3rd party server-side analytics is now a thing (this is where explicit blocking helps). For instance `sp.mail.notion.so` may route traffic through their IPs to `spog.io` ([ref](https://news.ycombinator.com/item?id=25169029)).

And IP-fronting (multiple domains behind a single IP) makes it even worse (or better, depending) ([ref](https://nitter.net/rethinkdns/status/1448738898998292495)).

**Comment by badmojr** [comment]
That's very insightful. Thanks!

**Comment by ignoramous** [comment]
I think it might be a good idea to keep track of all cloaked domains in `1Hosts (cloaked)`? 

This way, we can someday look back and see which ones have moved on to ALIAS records, or flattened their CNAMEs, or moved to routing tracking traffic through own IPs/servers. Thoughts?

**Comment by spirillen** [comment]
@ignoramous do you now if the following records is still in active use (not dns lookup) for tracking?

`analytics.pgncs.notion.so   CNAME . ; Tracking`

https://mypdns.org/my-privacy-dns/matrix/-/issues/967625

**Comment by ignoramous** [comment]
Sorry, can't say for sure, don't use notion myself.
