### ISSUE TITLE
this domains ahould be blocked

### ISSUE THREAD

**Issue by holequantum** [badmojr/1Hosts#591]
`firebaseinstallations.googleapis.com`
we should block this domain as it is used in firebase analytics
including this
`beacons.gcp.gvt2.com`
yahoo tracking
`s.yimg.com`

**Comment by badmojr** [comment]
Upgrade to **Pro** plz. It blocks them.

**Comment by holequantum** [comment]
> Upgrade to **Pro** plz. It blocks them.

yes 1st 2nd one was alcually blocked in pro versio
but i find some others.
 footprints-pa.googleapis.com
auditrecording-pa.googleapis.com
jnn-pa.googleapis.com
domain lenovo and motorolw devices iaed for tracking usage stats
 argo.svcmot.com
used by yahoo dont know why but blocking does not effect anything else
 s.yimg.com
 igapromomanager-pa.googleapis.com
 ulp1p-pa.googleapis.com

**Comment by badmojr** [comment]
> yes 1st 2nd one was alcually blocked in pro versio
> but i find some others.

These might negatively impact a lot of users if carelessly blocked.

**Comment by holequantum** [comment]
i was blocking those i haven't seen any issues but if we block we can remove individual accordingly.
you can also investigate if those can be blocked i have done and haven't seen any issues.

**Comment by badmojr** [comment]
> we block we can remove individual accordingly.

No. Sorry!
