### ISSUE TITLE
ens.nzz.ch

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#593]
**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:** NextDNS, uBlock Origin

<br>

**Domains:**
```
ens.nzz.ch
```
<br>

**Details:**
Blocking `ens.nzz.ch` disables the paywall on site `https://www.nzz.ch/technologie/twitter-der-streit-mit-elon-musk-wird-der-firma-schwer-schaden-ld.1693543` and prevents the login, thus prevents getting the article.

This is the same as https://github.com/nextdns/metadata/issues/1027

Thank you and cheers

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
I believe there's a login link on top-right of the page, so I don't see much of a problem here.
Anything I'm missing?

**Comment by crssi** [comment]
Maybe a hint that there is more to it 😉

**Comment by badmojr** [comment]
> Maybe a hint that there is more to it 😉

Not good enough. At least for me!
This is simply bad design.

**Comment by crssi** [comment]
No problem. Thank you for your effort. 

Cheers ❤️

**Comment by maXity** [comment]
> I believe there's a login link on top-right of the page, so I don't see much of a problem here. Anything I'm missing?

Even after logging in, the content is still missing. That may be bad design, but the end-result is unfortunately quite obstructive. I would appreciate if you could be so kind as to consider an alternative solution. Thank you very much!

**Comment by spirillen** [comment]
> > I believe there's a login link on top-right of the page, so I don't see much of a problem here. Anything I'm missing?
> 
> Even after logging in, the content is still missing. That may be bad design, but the end-result is unfortunately quite obstructive. I would appreciate if you could be so kind as to consider an alternative solution. Thank you very much!

screenshots?

**Comment by maXity** [comment]
> screenshots?

Thank you for your response! Yes, I have included a screenshot here: https://github.com/nextdns/metadata/issues/1027
