### ISSUE TITLE
[false positive] api.sec.miui.com api.miui.security.xiaomi.com

### ISSUE THREAD

**Issue by hacamer** [badmojr/1Hosts#596]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
AdGuardHome

<br>

**Domains:**
```
api.miui.security.xiaomi.com
api.sec.miui.com
```
<br>

**Details:**
These are MiPush Domains
If this domain is blocked, I cannot receive messages from MiPush 
System : Android

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Please attach some screenshots too. It'll help better describe your issue.

**Comment by hacamer** [comment]
![IMG_20220717_144228](https://user-images.githubusercontent.com/73057402/179387235-0f3bc3f9-feb8-4154-b6ec-ee99a401f8ca.jpg)
For example, this is a push notification via MIPush.  If you block these domains, I can't receive those messages.
The APP in the screenshot is CoolAPK
