### ISSUE TITLE
Remove getmonero.org from the lists

### ISSUE THREAD

**Issue by erciccione** [badmojr/1Hosts#6]
I think the getmonero.org domain was included in your lists by mistake. The website is [open source](https://repo.getmonero.org/monero-project/monero-site), it doesn't include any ad and basically no javscript. We have a mailing list, which is rarely used. The website is maintained by the community and doesn't offer paid content.

I don't know why it was included in the filters, but please remove it.

`Getmonero.org` is present in these lists:

- Pro
- complete

(For reference, i opened an issue on the getmonero repository: https://repo.getmonero.org/monero-project/monero-site/-/issues/1076)

**Comment by omurad** [comment]
The cryptominer that is bundled with the binaries on the downloads page is mostly likely the culprit which triggered the addition of getmonero.org into the blocklist.

The bundled miner is certainly not malware since the user has complete control over it.

**Comment by erciccione** [comment]
The miner and the rest of the resources are open source, so it's possible that somebody built some malware using them. Doesn't sound like a reason to consider getmonero.org spam.

The miner included with the official wallets is opt-in, so it  doesn't start unless the user specifically request it.

**Comment by badmojr** [comment]
Fixed! Thanks.

**Comment by erciccione** [comment]
Thank you for fixing @badmojr :)
