### ISSUE TITLE
should be removed from list.

### ISSUE THREAD

**Issue by opq1** [badmojr/1Hosts#600]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:** nextdns

blocks the request:
account-api.proton.me 
![Снимок экрана от 2022-07-17 01-31-56](https://user-images.githubusercontent.com/108897696/179373988-92024c89-4971-4e96-8536-7d859ffcf413.png)

When I click on the link:
https://account.proton.me/login

I just want to go to my email:
https://proton.me

**Comment by badmojr** [comment]
> should be removed from list: firestone-main.holydaygames.org

Please open a separate issue.
