### ISSUE TITLE
should be removed from list.

### ISSUE THREAD

**Issue by opq1** [badmojr/1Hosts#603]
Lists in use: Xtra

Client: nextdns

blocks the request:
firestone-main.holydaygames.org
![Снимок экрана от 2022-07-17 22-51-55](https://user-images.githubusercontent.com/108897696/179422778-dc4adf23-1b00-4e8d-bb17-f67586d9fa5c.png)

I can't get into the game because of this. Firestone Idle RPG
https://store.steampowered.com/app/1013320/Firestone_Idle_RPG/

**Comment by hacamer** [comment]
xtra has too many false positive.
I recommand you to use the lite list.

**Comment by badmojr** [comment]
> xtra has too many false positive. I recommand you to use the lite list.

https://github.com/badmojr/1Hosts#quickstart-guide
