### ISSUE TITLE
assets.adobedtm.com

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#604]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
assets.adobedtm.com
```
<br>

**Details:** Broken images `https://www.bose.com/`
![Screenshot_20220717_225820](https://user-images.githubusercontent.com/80338577/179424736-6d3c394b-def8-4cc7-ad69-2fc6abbf1e59.png)
![Screenshot_20220717_225831](https://user-images.githubusercontent.com/80338577/179424743-a6a80658-6d24-4f16-bdea-507d91742de7.png)
![Screenshot_20220717_225842](https://user-images.githubusercontent.com/80338577/179424748-70803aef-e2bd-4aff-a0af-e3af4672e552.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Not exactly.
All other pages display images normally. It's just the homepage that's misbehaving.
This is all because a third-party tracker, i.e `https://assets.adobedtm.com/launch-ENf50d3e16785c41448218df6189cad7e6.min.js`, is blocked.
Bad design anyone?

**Comment by badmojr** [comment]
On another observation:
This is used to invoke a bunch of other trackers, which are fortunately blocked.
It hides the contents of the page if the above fails.
