### ISSUE TITLE
fundingchoicesmessages.google.com

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#605]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
fundingchoicesmessages.google.com
```
<br>

**Details:** broken the website `https://stooq.com/` `https://stooq.pl/`
![Screenshot_20220717_231142](https://user-images.githubusercontent.com/80338577/179424971-a6d64655-72f8-4616-abd9-69a21d702068.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Unable to reproduce.

![ojghkj](https://user-images.githubusercontent.com/40524316/179434385-d2399441-9b0b-4450-9b1a-fcc5a0b29bce.PNG)
