### ISSUE TITLE
Several things (12 domains to probably blacklist and 1 to whitelist)

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#608]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains and details:**

1. Huawei stuff
1.1. DNKEEPER
You're already blocking ``dnkeeper.hicloud.com``, but if this domain is blocked, the phone requests: ``dnkeeper.platform.dbankcloud.cn`` (this domain is the chinese version of the hicloud.com one and it's the main secondary domain), ``dnkeeper.dbankcloud.com`` or ``dnkeeper.platform.hwcloudtest.cn``, as you can see on these screenshots:
![cn](https://user-images.githubusercontent.com/71935156/179961338-4a62b3c1-f556-44f1-a52e-8ff9c86f9f5b.jpeg)
![com](https://user-images.githubusercontent.com/71935156/179961408-8f1d6f66-d039-4098-8199-6e02d4698bc2.jpeg)
![all](https://user-images.githubusercontent.com/71935156/179961413-6e00bc52-66ee-4edf-a813-4abb2b0e3ecb.jpeg)

1.2. GRS
The russian version of the grs domains isn't blocked: ``grs.platform.dbankcloud.ru``
![image](https://user-images.githubusercontent.com/71935156/179962224-b9015d14-d1d9-48a4-928e-a051eeadc9da.png)
The phony tries every domain one by one, if you don't block the russian one then it's no use.

2. TF1
2.1. Player's metrics
This domain is used by myTF1's player for metrics purpose: ``metrics-broker.prod.p.tf1.fr``
![image](https://user-images.githubusercontent.com/71935156/179963407-9559bed2-1480-467b-9416-bb2707d4945c.png)

3. Latercera
3.1. Latercera's metrics
Main website:
``metrics.latercera.com``
AMP version:
metrics-latercera-com.cdn.ampproject.org
![image](https://user-images.githubusercontent.com/71935156/179963584-95b15107-02a7-477b-987c-cb948075790c.png)

4. Microsoft
4.1. Weird location domain
Is this domain used for geo-tracking? ``location.microsoft.com``
(I blocked it and nothing changed apparently)

5. Gigya
5.1. Socialize domains
You should block Gigya's socialize domains: ``socialize.eu1.gigya.com`` and especially ``socialize.us1.gigya.com``
(They're already blocked by some privacy concerned lists: 
![image](https://user-images.githubusercontent.com/71935156/179965121-c763e1b6-7e5f-42bd-b783-bc972fdf7eca.png))

6. Amazon
6.1. Is ``msh.amazon.co.uk`` a tracking/data collector domain? (It's a question)
It is requested in background and since I blocked it nothing seems to have changed.
And I also saw this domain in some smartTV blocklists...

7. Pinterest
7.1. gw-dv domains
You're already blocking ``pinterest.gw-dv.net`` but is this domain is blocked, then the Pinterest app requests a secondary domain: ``pinterest.cdn-gw-dv.net``, as you can see:
![pinterest](https://user-images.githubusercontent.com/71935156/179966888-c1252dd4-09f1-486d-bd60-7b8c7a8578a4.jpeg)
(You have to read from the bottom to the top for the chronological order.)

8. Vinted
8.1. Domains used by Vinted
If these two domains are blocked, the Vinted app won't work: ``mobile-data.onetrust.io`` and ``cdn.cookielaw.org``

9. Space Ape
9.1. Logs collector domain
You said in #464 that you'll add it but I think you forgot. The domain is: ``logs.prod.flamingo.apelabs.net``

10. Google
10.1. Audit Recording
I'm sure that this domain is a data collector domain (since Android 12 I think): ``auditrecording-pa.googleapis.com``

10.2. Gstatic metrics
I know that this domain is used for testing purpose (like DNS tests, etc...), but if this domain is blocked it doesn't change anything, it just reports to Google as soon as you change networks, connect to a DNS, etc... It has no use for the user.
`` metric.gstatic.com``

11. Samsung
11.1. Weird requests to Picks while using the weather app
The weather app makes some connections to this domain while it has nothing to do with the weather and by blocking it nothing changes: ``samsungnewsapi.picks.my``

12. Mandrillapp
12.1 Email tracking
This domain is like Sendgrid; it tracks the links in emails: mandrillapp.com
![image](https://user-images.githubusercontent.com/71935156/180028009-891643e6-d70b-4687-b444-fde501ea3b83.png)

13. Adobe
13.1. Scene7
Is this normal?
![signal-2022-07-20-122151_008](https://user-images.githubusercontent.com/71935156/180028166-c15b0e40-9bf9-4908-ac8d-71b67ab6613d.jpeg)

Yeah: that's a lot ^^

<br>

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Hello.
Please open separate issues for each. It makes it easy to track things.

**Comment by holequantum** [comment]
for 10.2
https://cs.android.com/search?q=ds.metric.gstatic.com
i think it serve many stuff so can
be just blocked as it does ipv6 and some random ds.metric. stuff.
you can block dnsotls-ds.metric.gstatic.com and it was said that will break internet and stuff but it does not actually but ds.metric.gstatic.com need to be on allow list if using pihole or nextdns
