### ISSUE TITLE
Broken page due to rule widgets.pinterest.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#61]
STR:
1. Visit site `https://www.zadovoljna.si/lepota/zenske-frizure/zenske-frizure-2019-10-frizur-za-kratkolaske-ki-bodo-hit-jeseni.html`
2. Click on "OMOGOCI PISKOTKE" button to allow cookies... see 
![image](https://user-images.githubusercontent.com/17024151/102331485-d2363b80-3f82-11eb-97ff-2d4d7bee2d2c.png)

Expected results: When not blocking `widgets.pinterest.com` we can see pictures
Actual results: When we block `widgets.pinterest.com` there is missing content

Thank you and cheers

NOTE: By observing our household traffic logs for last couple of months, the `widgets.pinterest.com` is used rarely, but when it does, there is a breakage. This make me think that it is not really used for ads or tracking purposes.

**Comment by badmojr** [comment]
Confirmed!

**Comment by badmojr** [comment]
Fixed!

**Comment by crssi** [comment]
Thank you

OT: SHould I close the resolved issues or will you? I didn't want to close those, since I think you have a reason to leave it open.

**Comment by badmojr** [comment]
Hahah!! I was waiting for you to close them actually.

Usually, I tend to close issues after 20 hours or more of inactivity after resolving them.
