### ISSUE TITLE
geotargetly.com

### ISSUE THREAD

**Issue by p1r473** [badmojr/1Hosts#610]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [X] Pro
- [ ] Xtra
<br>

**Client:**

<br>

**Domains:**
```
geotargetly.com
```
<br>

**Details:**
This is a false positive. This is a service that allows you to see how your site would look in other countries, i.e. to check geoblocking

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Anything that breaks with this blocked?
Couldn't find any.

**Comment by U-surper** [comment]
Please remove this site from 1Hosts (Xtra) as well. Thank You

**Comment by p1r473** [comment]
It wasn't breaking anything but the site itself. I was trying to use the site to see what my webserver looks like to other countries
