### ISSUE TITLE
(NSFW) manporn.xxx breakage

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#614]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
imcdn.manporn.xxx
```
<br>

**Details:** Blocking `imcdn.manporn.xxx` completely breaks `manporn.xxx`. False positive.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
Don't know where you stored the record, but should be in any NSFW lists https://mypdns.org/my-privacy-dns/matrix/-/issues/1074075
