### ISSUE TITLE
(NSFW) sexahah.com: new tracker / advertising junk

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#621]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
sexahah.com
```
<br>

**Details:**
Found on websites:
```
https://privatehomeclips.com/videos/1925291/my-favorite-latino-bf-fuck-me-in-his-bedroom-at-s-again-seemybf/
https://hclips.com/videos/8549013/desi-prince-bj/
```
It's a NRD and doesn't break site functionality. Should be good to add to all lists.

![sexah2](https://user-images.githubusercontent.com/11689349/181065070-77dc6d69-af78-404f-b04b-97368b3f8a42.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
**Xtra** has the domain blocked. <sup>[(ref)](https://blocklist-tools.developerdan.com/entries/search?q=sexahah.com)</sup>
I'll add it to the others too.

**Comment by yokoffing** [comment]
> (ref)

Thanks for the resource! Didn't know that existed!

**Comment by badmojr** [comment]
> > [(ref)](https://blocklist-tools.developerdan.com/entries/search?q=sexahah.com)
> 
> Thanks for the resource! Didn't know that existed!

You're welcome!
