### ISSUE TITLE
Add events.mapbox.com

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#622]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
events.mapbox.com
```
<br>

**Details:**
Blocked in `EasyPrivacy`, `Lightswitch05`, and `Anudeep` (see [here](https://blocklist-tools.developerdan.com/entries/search?q=events.mapbox.com)).

It doesn't interfere with loading `api.mapbox.com`. OISD [says](https://oisd.nl/excludes.php?w=events.mapbox.com) it makes Mapbox unusable; but if that was the case, `EasyPrivacy` would not block it.

I also didn't experience breakage in my tests.

Test websites:
```
as 3rd party script:
https://www.wunderground.com/weather/us/ny/new-york-city
https://weather.com/weather/radar/interactive/l/96f2f84af9a5f5d452eb0574d4e4d8a840c71b05e22264ebdc0056433a642c84

as 1st party script:
https://www.kayak.com/
```

Looks good to block in all 1Hosts lists, but should be blocked in `Pro` and `Xtra` at the very least.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
I remember this interfering with the maps on Cloudflare dashboard.
Will give it another go in Pro, and Xtra.
