### ISSUE TITLE
`tags.tiqcdn.com`| should be blocked

### ISSUE THREAD

**Issue by holequantum** [badmojr/1Hosts#623]
`tags.tiqcdn.com`
Blocked by NextDNS Ads & Trackers Blocklist, Goodbye Ads, notracking, Lightswitch05 - Ads & Tracking, Energized Ultimate
but does not blocked by 1host pro line

**Comment by badmojr** [comment]
Quite a number of issues have been reported on GH, pointing to the above domain as the culprit.
e.g https://github.com/uBlockOrigin/uAssets/search?o=desc&q=tags.tiqcdn.com&s=created&type=issues

**Comment by holequantum** [comment]
okey then it can't be blocked
