### ISSUE TITLE
False Positive: thelineofbestfit.com

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#629]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
thelineofbestfit.com
```
<br>

**Details:** Celebrity / Music news site

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/983954

</details>
