### ISSUE TITLE
static.1tv.ru

### ISSUE THREAD

**Issue by opq1** [badmojr/1Hosts#634]
Lists in use: Xtra

Client: nextdns

blocks the request:
static.1tv.ru

I can't access the site because of this:
https://www.1tv.ru/

**Comment by yokoffing** [comment]
Yeah, `static.1tv.ru` needs allowlisting.

However, this website has unblock trackers that we should add to 1Hosts. You can view the details [here](https://github.com/easylist/easylist/issues/12836).
