### ISSUE TITLE
problem.

### ISSUE THREAD

**Issue by opq1** [badmojr/1Hosts#635]
Lists in use: Xtra

Client: nextdns

I have three different requests blocked, so the site does not work correctly:
https://www.ivi.ru/

blocked requests:
ds.tivision.ru
icons.tivision.ru
st.tivision.ru
I don't know which ones can be unlocked.

That's the problem. I haven't tested any further.
![Снимок экрана от 2022-08-04 20-04-52](https://user-images.githubusercontent.com/108897696/182910557-0f6d8b9f-be7f-43b9-be2f-d5e4439ffc42.png)

**Comment by yokoffing** [comment]
> ds.tivision.ru
> icons.tivision.ru
> st.tivision.ru

To make the site functional, I had to allowlist the first two, `ds.tivision.ru` and `icons.tivision.ru`. I don't have an account and I'm not Russian, so I don't know if anything else is needed to login or for video playback.

![ivi ru](https://user-images.githubusercontent.com/11689349/183252568-9380e270-6add-4b5d-a688-de95b82b49ce.png)

**Comment by spirillen** [comment]
Before just whitelisting stuff from any blacklist

does anyone then actual know why any of the `tivision.ru` is added?
