### ISSUE TITLE
pdst.fm

### ISSUE THREAD

**Issue by bbhtt** [badmojr/1Hosts#639]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:** AhaDNS, NextDNS

<br>

**Domains:**
```
pdst.fm
```
<br>

**Details:**

It is used by some some podcast services for example Spotify See also https://github.com/lightswitch05/hosts/issues/160

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
As `pdst.fm` aint providing contents, I don't see any reasons for not keep blacklisting the tracking script

`https://cdn.pdst.fm/ping.min.js`

Source: https://mypdns.org/my-privacy-dns/matrix/-/issues/3998

**Comment by bbhtt** [comment]
> As pdst.fm aint providing contents

It is providing the content. For example try playing https://open.spotify.com/show/7nfSBCYRgk7mF2TAlkBvP0 with `pdst.fm` blocked, it'll fail.

In the browser the following requests are coming from that domain:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +49 |  |  | open.spotify.com | 3 | media | `https://pdst.fm/e/rss.art19.com/episodes/56e81d93-e286-45d1-860b-664bf403d084.mp3?rss_browser=BAhJIgxTcG90aWZ5BjoGRVQ%3D--c73337271af676556b67a4f8fe9332bd11c6baf9` |
| +47 |  |  | open.spotify.com | 3 | media | `https://pdst.fm/e/rss.art19.com/episodes/9126d26f-51c2-4976-9ee8-1a48cb599558.mp3?rss_browser=BAhJIgxTcG90aWZ5BjoGRVQ%3D--c73337271af676556b67a4f8fe9332bd11c6baf9` |
| +45 |  |  | open.spotify.com | 3 | media | `https://pdst.fm/e/rss.art19.com/episodes/1fb33a7b-d40a-4d91-94bd-e0b0dd747401.mp3?rss_browser=BAhJIgxTcG90aWZ5BjoGRVQ%3D--c73337271af676556b67a4f8fe9332bd11c6baf9` |
| +43 |  |  | open.spotify.com | 3 | media | `https://pdst.fm/e/rss.art19.com/episodes/acef626e-85bd-4685-8563-1de981f3966a.mp3?rss_browser=BAhJIgxTcG90aWZ5BjoGRVQ%3D--c73337271af676556b67a4f8fe9332bd11c6baf9` |
| +41 |  |  | open.spotify.com | 3 | media | `https://pdst.fm/e/rss.art19.com/episodes/3d8a87f1-d09b-4d5e-842a-c45ce2e29fc4.mp3?rss_browser=BAhJIgxTcG90aWZ5BjoGRVQ%3D--c73337271af676556b67a4f8fe9332bd11c6baf9` |
| +38 |  |  | open.spotify.com | 3 | media | `https://pdst.fm/e/rss.art19.com/episodes/bb2b9a0e-ae03-4752-99ff-dda98b1f0552.mp3?rss_browser=BAhJIgxTcG90aWZ5BjoGRVQ%3D--c73337271af676556b67a4f8fe9332bd11c6baf9` |
| +0 |  |  | open.spotify.com | 3 | media | `https://pdst.fm/e/rss.art19.com/episodes/acef626e-85bd-4685-8563-1de981f3966a.mp3?rss_browser=BAhJIgxTcG90aWZ5BjoGRVQ%3D--c73337271af676556b67a4f8fe9332bd11c6baf9` |
</details>

> https://cdn.pdst.fm/ping.min.js

However I haven't seen that subdomain being requested anywhere, so I think it can be blocked. (Can't test because in NextDNS allowlist takes precedence over everything else and it allows all subdomains.)

**Comment by spirillen** [comment]
@bbhtt 

Nice reply and some very good points in your reply. Is it possible to have you replicating your comment/knowledge to https://mypdns.org/my-privacy-dns/matrix/-/issues/3998 so we can get that fixed and spread the words to everyone who uses the knowledge base
