### ISSUE TITLE
pov.spectrum.net

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#640]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** NextDNS (and uBlock Origin)

<br>

**Domains:**
```
pov.spectrum.net
```
<br>

**Details:**
Cannot sign in to my ISP, Spectrum, at `https://www.spectrum.net/` due to blocking a CNAME:

![pov spec](https://user-images.githubusercontent.com/11689349/183259645-09ce4572-5cee-453d-bd40-c4ae9645b1f6.png)

If I add `pov.spectrum.net` to my allowlist, I am able to login successfully. Users must allowlist at an adblocker and DNS level in order to sign in.

Login breakage has been occurring for over a month. I decided to look and see if it was caused by CNAME blockage; and what do you know? it was.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Here's what I've found about **online-metrix.net**.
- https://www.bleepingcomputer.com/news/security/list-of-well-known-web-sites-that-port-scan-their-visitors/

**Comment by yokoffing** [comment]
> Here's what I've found out about **online-metrix.net**.

I wouldn't advise allowlisting `online-metrix.net` outright either, but `pov.spectrum.net` must be allowlisted so account holders may login and pay their bill, access services, etc.

From what I've seen, the request only appears at the login screen. Nowhere else on the site.
