### ISSUE TITLE
eulatracking-public-service-prod06.ol.epicgames.com

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#643]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
eulatracking-public-service-prod06.ol.epicgames.com
```
<br>

**Details:** When downloading Epic Games launcher on a new PC, blocking this domain prevented me from downloading Fortnite. You will keep getting an error screen until you allow the request.

The error will also occur anytime you need to Verify the game's files.

![Screenshot 2022-08-08 202935](https://user-images.githubusercontent.com/11689349/183537272-53b3b9d3-ed85-4459-866e-ba230f524ef6.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
Except from the naming `eulatracking-public-service-`, which gives some thought on what is going on, is there any actual knowledge about why this record my exist?

**Comment by badmojr** [comment]
Previously requested in #365 .
