### ISSUE TITLE
False Positive: prodapp.babytrackers.com

### ISSUE THREAD

**Issue by realflight1** [badmojr/1Hosts#648]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [X] Xtra
<br>

**Client:**

<br>

**Domains:**
```
babytrackers.com
prodapp.babytrackers.com
```
<br>

**Details:**
This is a legitimate mobile app to log baby-related information. Just go to [babytracker.com](https://www.babytrackers.com/) or the [app page](https://play.google.com/store/apps/details?id=com.nighp.babytracker_android) on Google Play and see that it's not related to online tracking or advertisements. By blocking `prodapp.babytrackers.com` the multi-device synchronization feature of the app is essentially deactivated. Thank you

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
That's spy- trackware
