### ISSUE TITLE
es.akinator.mobi es.akinator.com

### ISSUE THREAD

**Issue by Maario03** [badmojr/1Hosts#652]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
es.akinator.mobi
es.akinator.com
g.ezoic.net
es.akinator.com.cdn.ezoic.net
```
<br>

**Details:**
This two domains broke the  "Akinator" website which is a famous online game, nothing malicious here 

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
```
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56107
;; flags: qr rd ra ; qd: 1 an: 8 au: 0 ad: 1 

;; OPT PSEUDOSECTION: 
; EDNS: version: 0; flags: ; udp: 1280
;; QUESTIONS:
;;	es.akinator.com., type = A, class = IN

;; ANSWERS:
es.akinator.com.	60	IN	CNAME	es.akinator.com.cdn.ezoic.net.
es.akinator.com.cdn.ezoic.net.	60	IN	CNAME	es.akinator.com.cdn.cloudflare.net.
es.akinator.com.cdn.cloudflare.net.	60	IN	CNAME	g.ezoic.net.
g.ezoic.net.		60	IN	A	18.232.245.187
g.ezoic.net.		60	IN	A	50.16.49.81
g.ezoic.net.		60	IN	A	3.234.104.255
g.ezoic.net.		60	IN	A	35.175.60.16
g.ezoic.net.		60	IN	A	52.86.133.10

;; AUTHORITY RECORDS:

;; ADDITIONAL RECORDS:


;; Message size: 373 bytes
```

**Comment by badmojr** [comment]
The Ezoic system uses Machine Learning to help publishers make better decisions. By effectively 'predicting' how a website visitor will respond to an automated & individualized change, Ezoic can boost user experience metrics and increase ad earnings.

Ezoic optimizes over 400m visitor experiences each month (May 2017) and thesystem is offered as a Self-Serve ad-funded or subscription-based service, or as an Enterprise (SaaS) solution.
Ezoic was Google's first North American Certified Partner for AdSense and is a Google Certified Publishing Partner; winning their Business Innovation Award in 2016.

ref: https://www.crunchbase.com/organization/ezoic
