### ISSUE TITLE
fwmrm.net

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#654]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
fwmrm.net
```
<br>

**Details:**

Video is not loading
https://sportowefakty.wp.pl/pilka-nozna/wideo/44323/darwin-przywital-sie-z-anfield-najgorzej-jak-mogl-nerwy-mu-kompletnie-puscily
![Screenshot_20220816_105725](https://user-images.githubusercontent.com/80338577/184840122-78b16487-949d-4fbc-b0e9-3e42e014c059.png)
https://oisd.nl/excludes.php?w=m1.fwmrm.net
https://oisd.nl/excludes.php?w=mssl.fwmrm.net

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by yokoffing** [comment]
![Screenshot 2022-08-21 105709](https://user-images.githubusercontent.com/11689349/185797248-106e6921-67fd-4464-b486-cea5e3c80e07.png)

USA

**Comment by badmojr** [comment]
I'm gonna need a couple more examples of broken videos on other different sites.

**Comment by badmojr** [comment]
The URL from [oisd](https://oisd.nl/excludes.php?w=mssl.fwmrm.net) plays fine with 1Hosts (Pro) enabled.

**Comment by spirillen** [comment]
And `fwmrm.net` is used for hosting both AdWare and Tracking code https://mypdns.org/my-privacy-dns/matrix/-/issues/1078638
