### ISSUE TITLE
Site does not open due to van.tdn.gtranslate.net

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#66]
Site `https://sl.xiaomiplanet.sk/7.-masažna-pištola-xiaomi-yunmai-XNUMX/` does not open since `sl.xiaomiplanet.sk` is blocked) due to cname `van.tdn.gtranslate.net`.

Cheers

**Comment by badmojr** [comment]
Fixed!

**Comment by crssi** [comment]
Wish you best in the 2021. ❤️
