### ISSUE TITLE
browser.sentry-cdn.com

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#663]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
sentry-cdn.com
```
<br>

**Details:** does not show search results https://www.castorama.pl/result/?q=test
![Screenshot_20220821_182049](https://user-images.githubusercontent.com/80338577/185801011-85074fdc-66b8-4312-98a9-2b4e1be09608.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
Beacause `sentry-cdn.com` is tracking, and it have been discussed so many places that it should possible to search this. 

This is a whitelist it your self if you don't care about being tracked.

**Comment by yokoffing** [comment]
I did not need to allowlist `sentry-cdn.com` for this to work. Blocking `inte.searchnode.io` will break results, but 1Hosts isn't blocking that domain.

![Screenshot 2022-08-22 192944](https://user-images.githubusercontent.com/11689349/186037395-c389951e-4bb4-44e9-ad0d-1bfb40ff4ab6.png)

![Screenshot 2022-08-22 193026](https://user-images.githubusercontent.com/11689349/186037404-dfe15c25-d9d2-42ea-a060-5383867fdaae.png)

**Comment by spirillen** [comment]
When `js.sentry-cdn.com` is blocked it breaks `https://www.pizzahut.com.au/` can't put store information or address in etc.

Unblocking `js.sentry-cdn.com` allows for postcode/address to be put in to set delivery or pickup of pizza.

**Comment by badmojr** [comment]
One does not simply fix bad design choices.
