### ISSUE TITLE
get.x-link.pl

### ISSUE THREAD

**Issue by gita6t5** [badmojr/1Hosts#664]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
get.x-link.pl
```
<br>

**Details:**

needed for video playback on https://zdrowie.tvn.pl/a/co-nam-daje-plywanie-i-jaki-jest-zalecany-trening-lista-zalet-chodzenia-na-basen
![Screenshot_20220822_110516](https://user-images.githubusercontent.com/80338577/185883668-eafe3867-946e-4191-a1e9-76cf8965977f.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by yokoffing** [comment]
I am able to reproduce. Blocking `x-link.pl` at the browser (uBlock Origin) and DNS level (NextDNS) prevents the video playback.
