### ISSUE TITLE
js.sentry-cdn.com

### ISSUE THREAD

**Issue by gyCfjSnO** [badmojr/1Hosts#668]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:**

<br>

**Domains:**
```
js.sentry-cdn.com
```
<br>

**Details:**
When ```js.sentry-cdn.com``` is blocked it breaks ```https://www.pizzahut.com.au/``` can't put store information or address in etc.

Unblocking ```js.sentry-cdn.com``` allows for postcode/address to be put in to set delivery or pickup of pizza.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
related: #663

**Comment by hagezi** [comment]
@badmojr
I could reproduce it when ` js.sentry-cdn.com` is blocked, no search hits are displayed on https://www.pizzahut.com.au/, see: https://github.com/hagezi/dns-blocklists/issues/27

Cheers,
Gerd

**Comment by badmojr** [comment]
> @badmojr I could reproduce it when ` js.sentry-cdn.com` is blocked, no search hits are displayed on https://www.pizzahut.com.au/, see: [hagezi/dns-blocklists#27](https://github.com/hagezi/dns-blocklists/issues/27)
> 
> Cheers, Gerd

Any other broken websites caused by that domain being blocked?

**Comment by hagezi** [comment]
so far I have not found any ...

**Comment by gyCfjSnO** [comment]
I haven't found any either.

**Comment by badmojr** [comment]
One does not simply fix bad design choices.
