### ISSUE TITLE
forskning.no blocked by Xtra

### ISSUE THREAD

**Issue by TorsteinVin** [badmojr/1Hosts#670]
This is a norwegian news site / blog concerning latest popular articles about current research. It is blocked bt Xtra.

**Comment by TorsteinVin** [comment]
@badmojr I see you added the "removal" label. Does that mean you have added the webpage to your whitelist, or did I report this broken webpage in the wrong place?

**Comment by badmojr** [comment]
Ha ha! Of course not.
Changed the wording.. Sorry!

**Comment by TorsteinVin** [comment]
I'm not sure I understand. To which of my two questions did you respond "Of course not"? That you have whitelisted the domain or that I made a mistake?

**Comment by badmojr** [comment]
Both.
When the domain gets whitelisted, this issue will automatically be closed.

**Comment by TorsteinVin** [comment]
Ah I think understand. So you are inspecting the issue, and when you have considered it, you will decide whether to whitelist it or not? So the "removal request" is your "i'm-looking-into-it"-tag? :) I'm gonna use your fancy template from now on btw.

**Comment by badmojr** [comment]
> Is that correct?

When you see the "removal request" label, it's me saying:
*I've looked into it and deemed it safe to whitelist.
I'll remove it soon.*
