### ISSUE TITLE
hn.nhn.no

### ISSUE THREAD

**Issue by TorsteinVin** [badmojr/1Hosts#671]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
www.nhn.no
frontend-fnsp.hn.nhn.no
api-fnsp-backend.hn.nhn.no
```
<br>

**Details:**
This page is broken:
https://spesialisthelsetjenesten.no/lis/kurs-for-leger-i-spesialisering#Default=%7B%22k%22%3A%22%22%7D%23d53c740f-e3e5-4c6e-ad8d-11def697caff=%7B%22k%22%3A%22%22%2C%22r%22%3A%5B%7B%22n%22%3A%22owstaxIdTaxKeyword%22%2C%22t%22%3A%5B%22string(%5C%22L0%7C%230bc15419e-cc94-4984-bc39-5f68e2fa3d78%7COrtopedisk%20kirurgi%5C%22)%22%5D%2C%22o%22%3A%22and%22%2C%22k%22%3Afalse%2C%22m%22%3Anull%7D%5D%7D%230eedf211-7662-4213-900d-17fb91372f67=%7B%22k%22%3A%22%22%2C%22r%22%3A%5B%7B%22n%22%3A%22owstaxIdTaxKeyword%22%2C%22t%22%3A%5B%22string(%5C%22L0%7C%230bc15419e-cc94-4984-bc39-5f68e2fa3d78%7COrtopedisk%20kirurgi%5C%22)%22%5D%2C%22o%22%3A%22and%22%2C%22k%22%3Afalse%2C%22m%22%3Anull%7D%5D%7D

www.spesialisthelsetjenesten.no is used by norwegian physicians/doctors for their medical training. With 1Hosts Xtra, the webpage looks like a word-document with no styling. The webpage is dependent on NHN.no-domain. NHN stands for Norsk helsenett (Norwegian Health Net). The domain www.nhn.no is also completely blocked and unavailable with 1Hosts Xtra running.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Please link to the broken page too.

**Comment by TorsteinVin** [comment]
This is the exact URL. It displays with no styling, looking like a word-document. It is dependent on *.NHN.no to display correctly. 

``https://spesialisthelsetjenesten.no/lis/kurs-for-leger-i-spesialisering#Default=%7B%22k%22%3A%22%22%7D%23d53c740f-e3e5-4c6e-ad8d-11def697caff=%7B%22k%22%3A%22%22%2C%22r%22%3A%5B%7B%22n%22%3A%22owstaxIdTaxKeyword%22%2C%22t%22%3A%5B%22string(%5C%22L0%7C%230bc15419e-cc94-4984-bc39-5f68e2fa3d78%7COrtopedisk%20kirurgi%5C%22)%22%5D%2C%22o%22%3A%22and%22%2C%22k%22%3Afalse%2C%22m%22%3Anull%7D%5D%7D%230eedf211-7662-4213-900d-17fb91372f67=%7B%22k%22%3A%22%22%2C%22r%22%3A%5B%7B%22n%22%3A%22owstaxIdTaxKeyword%22%2C%22t%22%3A%5B%22string(%5C%22L0%7C%230bc15419e-cc94-4984-bc39-5f68e2fa3d78%7COrtopedisk%20kirurgi%5C%22)%22%5D%2C%22o%22%3A%22and%22%2C%22k%22%3Afalse%2C%22m%22%3Anull%7D%5D%7D``

**Comment by badmojr** [comment]
Are you running Xtra as a daily driver?
