### ISSUE TITLE
False Positive: Weather site accuweather.com not working

### ISSUE THREAD

**Issue by d-Rickyy-b** [badmojr/1Hosts#677]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
uBlock Origin

<br>

**Domains:**
```
www.awxcdn.com
```
<br>

**Details:**
The website [accuweather.com](https://www.accuweather.com/de/de/berlin/10178/august-weather/178087?year=2021) doesn't work properly with the 1Hosts list, because the cdn `www.awxcdn.com` is being blocked.
I am not sure if that CDN is also being used to load tracking scripts.

![grafik](https://user-images.githubusercontent.com/5798157/186787804-b7549eaa-2b41-47c5-9c77-0ff07d50e252.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
cc: @migueldemoura

**Comment by migueldemoura** [comment]
Fixed with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/52d5b7d0e358a9667d2f606cdc17fb2821c71e05.
