### ISSUE TITLE
consent.trustarc.com

### ISSUE THREAD

**Issue by TorsteinVin** [badmojr/1Hosts#687]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:
NextDNS**

<br>

**Domains:**
``consent.trustarc.com``

``https://www.forbes.com/cloud100/list/2/``
<br>

**Details:
The Forbes 100 Cloud list webpage ``https://www.forbes.com/cloud100/list/2/`` fails to open  due to both Xtra and Pro blocking the cookie consent form delivered by trustarc.com. ``consent.trustarc.com`` **

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by yokoffing** [comment]
A request to `trustarc.com` doesn't appear for me when I navigate to `https://www.forbes.com/cloud100/list/2/`. ???

**Comment by TorsteinVin** [comment]
Strange, that’s the domain that came up in Nextdns log marking Xtra and Pro as the culprits. When i whitelisted that domain, the website opened up like it should. I dont know what to tell you, other than good luck and hope you figure it out! :)

T

**Comment by spirillen** [comment]
Tracking/SpyWare

`https://consent.trustarc.com/notice?domain=flickr.com&c=teconsent&js=nj&noticeType=bb&gtm=1&dl=TADataLayer`

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | \|\|consent.trustarc.com^$3p | -- | `www.forbes.com` | 3 | image | `https://consent.trustarc.com/bannermsg?action=views&domain=forbes_iab2.com&behavior=implied&country=dk&language=en&rand=0.85353249956205` |
| +1 | @@\|\|consent.trustarc.com/asset/$domain=forbes.com | ++ | `www.forbes.com` | 3 | image | `https://consent.trustarc.com/asset/trustarc-without-truste-logo-xs.svg` |
| +1 | @@\|\|consent.trustarc.com/asset/$domain=forbes.com | ++ | `www.forbes.com` | 3 | image | `https://consent.trustarc.com/asset/ic-close-white.svg` |
| +1 | @@\|\|consent.trustarc.com/asset/$domain=forbes.com | ++ | `www.forbes.com` | 3 | image | `https://consent.trustarc.com/asset/ic-error.svg` |
| +1 | no-remote-fonts: * true | -- | `www.forbes.com` | 3 | inline-font | `https://trustarc.mgr.consensu.org/asset/cmpcookie.v2.html` |
| +1 | @@\|\|consent.trustarc.com/notice$domain=forbes.com | ++ | `www.forbes.com` | 3 | script | `https://consent.trustarc.com/notice?domain=forbes_iab2.com&country=dk&js=nj2&c=teconsent&noticeType=bb&gtm=1` |
| +1 | @@\|\|consent.trustarc.com/asset/$domain=forbes.com | ++ | `www.forbes.com` | 3 | script | `https://consent.trustarc.com/asset/uspapi.js` |
| +1 | @@\|\|consent.trustarc.com/asset/$domain=forbes.com | ++ | `www.forbes.com` | 3 | image | `https://consent.trustarc.com/asset/forbes.png` |
| +1 | @@\|\|consent.trustarc.com/asset/$domain=forbes.com | ++ | `www.forbes.com` | 3 | script | `https://consent.trustarc.com/asset/notice.js/v/v1.7-9751` |
| +0 | \|\|consensu.org^$3p | -- | `www.forbes.com` | 3 | script | `https://trustarc.mgr.consensu.org/asset/tcfapi.js/v/2.1` |
| +0 | \|\|consent.trustarc.com^$3p | -- | `www.forbes.com` | 3 | image | `https://consent.trustarc.com/log?domain=forbes_iab2.com&country=dk&state=&behavior=implied&c=ac44` |
| +0 | @@\|\|trustarc.mgr.consensu.org/asset/cmpcookie.*.html$domain=forbes.com | ++ | `www.forbes.com` | 3 | frame | `https://trustarc.mgr.consensu.org/asset/cmpcookie.v2.html` |
| +0 | @@\|\|consent.trustarc.com/notice$domain=forbes.com | ++ | `www.forbes.com` | 3 | script | `https://consent.trustarc.com/notice?domain=forbes_iab2.com&c=teconsent&js=nj&noticeType=bb&gtm=1` |
</details>

**Comment by TorsteinVin** [comment]
So Forbes has put spyware in their consent form? odd...

**Comment by spirillen** [comment]
Why, all other "news" media are doing the same just try the danish dr.dk (obligated to pay for the service) they uses about 58 - 60 trackers/spyware

**Comment by badmojr** [comment]
Please provide some before and after screenshots.

**Comment by spirillen** [comment]
Well as the above link is redirected to `https://www.forbes.com/consent/?toURL=https://www.forbes.com/cloud100/list/2/` until the no privacy is "accepted" you can't do anything....

- https://mypdns.org/my-privacy-dns/matrix/-/issues/4240#note_5416715
- https://mypdns.org/my-privacy-dns/matrix/-/issues/1168839
