### ISSUE TITLE
Not an issue... close at will.

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#69]
Just wanted to wish you best in the year 2021. 😉

**Comment by badmojr** [comment]
Thanks! Happy new year to you too.
Here's to 2021 => https://github.com/badmojr/1Hosts/tree/master/xtra

**Comment by crssi** [comment]
Nice... I will guess this is meant as domain and everything that goes under... like NextDNS is doing.
So for example `hicloud.com` represents `hicloud.com` and everithing uder like `*.hicloud.com`.

Did I guess correctly?

Cheers

**Comment by badmojr** [comment]
yES! Correct.

**Comment by crssi** [comment]
> To be used in conjunction with the Pro variants

I don't understand... is it to be used instead of Pro or additional to Pro?
Is there also Lite version in plan?

**Comment by badmojr** [comment]
It's an addon to the Pro variants.

**Comment by badmojr** [comment]
https://github.com/badmojr/1Hosts/tree/master/Pro/xtra
So as to avoid confusion, here's the new location.

**Comment by crssi** [comment]
Nice work. Thank you.
