### ISSUE TITLE
You.com, resumebuild.com & synthesia.io should be unblocked

### ISSUE THREAD

**Issue by fdhfgbsjedfg-775** [badmojr/1Hosts#692]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
you.com, resumebuild.com, synthesia.io
<br>

**Details:** You.com is a search engine that you have control over everything, it let's you choose what sources to get search results from. Resumebuild.com is a resume builder, it isn't a tracker, ad hosting server or malware.
Synthesia.io is a web-based platform for creating videos with AI avatars and voices.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
Eeehh Privacy?? it is full of spyware..

you.com

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +7 | \|\|events.launchdarkly.com^$3p | -- | you.com | 3 | xhr | `https://events.launchdarkly.com/events/bulk/61fc70ffa79e9a158922a4b2` |
| +7 | \|\|events.launchdarkly.com^$3p | -- | you.com | 3 | xhr | `https://events.launchdarkly.com/events/bulk/61fc70ffa79e9a158922a4b2` |
| +4 | `##[href^="https://www.facebook.com"]` |  | you.com |  | dom | `https://you.com/` |
| +4 | `##[href^="https://twitter.com"]` |  | you.com |  | dom | `https://you.com/` |
| +4 | \|\|plausible.io/api/event | -- | you.com | 3 | xhr | `https://plausible.io/api/event` |
| +0 | \|\|events.launchdarkly.com^$3p | -- | you.com | 3 | xhr | `https://events.launchdarkly.com/events/bulk/61fc70ffa79e9a158922a4b2` |
| +0 | \|\|events.launchdarkly.com^$3p | -- | you.com | 3 | xhr | `https://events.launchdarkly.com/events/bulk/61fc70ffa79e9a158922a4b2` |
</details>


launchdarkly.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/4372
plausible.io: https://mypdns.org/my-privacy-dns/matrix/-/issues/967161

----------

resumebuild.com

Same story: `||static.olark.com/jsclient/$3p,domain=~fooda.com`
olark.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/967075


-----------------

`synthesia.io`

> Create professional videos in 60+ languages
> We will keep nonirritating you all the time and month to come...

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +4 | `##[href^="https://twitter.com"]` |  | `www.synthesia.io` |  | dom | `https://www.synthesia.io/` |
| +4 | \|\|licdn.com/*li.lms-analytics/ | -- | `www.synthesia.io` | 3 | script | `https://snap.licdn.com/li.lms-analytics/insight.min.js` |
| +4 | \|\|ads-twitter.com^ | -- | `www.synthesia.io` | 3 | script | `https://static.ads-twitter.com/uwt.js` |
| +4 | \|\|js.hs-scripts.com^ | -- | `www.synthesia.io` | 3 | script | `https://js.hs-scripts.com/8269203.js` |
| +3 | /videojs-ie8.$script | -- | `www.synthesia.io` | 3 | script | `https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js` |
| +3 | \|\|wdfl.co^ | -- | `www.synthesia.io` | 3 | script | `https://r.wdfl.co/rw.js` |
| +3 | \|\|facebook.net^ | -- | `www.synthesia.io` | 3 | script | `https://connect.facebook.net/en_US/fbevents.js` |
| +3 | \|\|bat.bing.com^ | -- | `www.synthesia.io` | 3 | script | `https://bat.bing.com/bat.js` |
| +2 | \|\|googleapis.com^$important | -- | `www.synthesia.io` | 3 | script | `https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js` |
| +2 | \|\|js.hs-scripts.com^ | -- | `www.synthesia.io` | 3 | script | `https://js.hs-scripts.com/8269203.js` |
| +2 | /videojs-ie8.$script | -- | `www.synthesia.io` | 3 | script | `https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js` |
| +2 | \|\|wdfl.co^ | -- | `www.synthesia.io` | 3 | script | `https://r.wdfl.co/rw.js` |
| +2 | googletagmanager_gtm.js | << | `www.synthesia.io` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-123255862-1` |
| +2 | \|\|googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | `www.synthesia.io` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-123255862-1` |
| +2 | \|\|googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js | -- | `www.synthesia.io` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-123255862-1` |
| +2 | \|\|googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager-gtm | -- | `www.synthesia.io` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-123255862-1` |
| +2 | \|\|googletagmanager.com^ | -- | `www.synthesia.io` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-123255862-1` |
| +2 | \|\|googleapis.com^$important | -- | `www.synthesia.io` | 3 | script | `https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js` |
</details>

licdn.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/968884
ads-twitter.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/873
hs-scripts.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/967158
wdfl.co: https://mypdns.org/my-privacy-dns/matrix/-/issues/498
googletagmanager.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/3226
googleapis.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/1163997

**Comment by fdhfgbsjedfg-775** [comment]
I didn't know these domains had trackers in them, but still, some important things to remember.

First of all, these domains have not been blocked by all the lists I am currently using (Basically toggled all blocklists there is on NextDNS) except for 1Hosts Xtra, and these domains will have trackers (for You.com, changed the description to not say privacy friendly alternative), like 80%+ of all websites have some kind of ads or trackers in them. And using in conjunction a blocklist, most tracking capabilities of these sites are blocked (I know some websites use sophisticated methods of tracking users but these domains won't go that far)

I want to whitelist the site, not all the domains in them.

If I missed out on something, please let me know.

**Comment by spirillen** [comment]
> If I missed out on something, please let me know.

I'm sure your good, it was the comment that you.com should be any privacy I responded to.

Rest of the commends are your opinion and I admire you are being open about it.
