### ISSUE TITLE
dtioykqj1u8de.cloudfront.net

### ISSUE THREAD

**Issue by PoodleAWS** [badmojr/1Hosts#694]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
dtioykqj1u8de.cloudfront.net
```
<br>

**Details:**
CDN Distribution for the Amazon.co.jp website

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
Doesn't mean it can't contain trackers/fingerprinting/adware etc. Any clue where this is imported from?
