### ISSUE TITLE
5movierulz.tc

### ISSUE THREAD

**Issue by pritkr** [badmojr/1Hosts#695]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
5movierulz.tc
```
<br>

**Details:**
This is a false positive. This is a genuine website of 7movierulz.com a online movie website.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by t0mr22** [comment]
Hello @pritkr 😄,

The website domain you suggest is a website used to provide illegal video content. Thus, it will not be removed from the list. 

If you still want to use that website, you can still unblock it with NextDNS.

Have a nice day wherever you are.
