### ISSUE TITLE
tamilblasters.casa , 1tamilmv.cyou , 5movierulz.tc

### ISSUE THREAD

**Issue by pritkr** [badmojr/1Hosts#698]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
tamilblasters.casa
1tamilmv.cyou
5movierulz.tc
```
<br>

**Details:**
These domains should be removed from the list as these are not ads or trackers. These are Indian movies, songs ,torrents sharing websites. The official links are 1tamilmv.com , tamilblasters.com , 7movierulz.com which redirect to these domains to resist censorship.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
The following domain are fingerprinting, so can't confirm, any change you could post some screenshots including the addressbar?

`tamilblasters.casa`

**Comment by pritkr** [comment]
![Screenshot_2022-09-05-03-31-25-847_org bromite bromite](https://user-images.githubusercontent.com/81620727/188335124-586f0048-d753-45ff-8be3-977643b0f884.jpg)

**Comment by spirillen** [comment]
Thanks

<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/1164032

</details>
