### ISSUE TITLE
False Positive: Feedback on neodigital.de not working

### ISSUE THREAD

**Issue by d-Rickyy-b** [badmojr/1Hosts#699]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
uBlock Origin

<br>

**Domains:**
```
ekomi.com
```
<br>

**Details:**
When I try to give feedback to my insurance company (neodigital.de), uBlock prevents a script from ekomi.com from being loaded.
ekomi.com doesn't seem to track me. From what I gathered it's just a feedback form.

![grafik](https://user-images.githubusercontent.com/5798157/188755058-a05beaba-d8bd-4cf8-b9d5-219f0b21eaec.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Please provide the specific page where the issue above occurs.

**Comment by d-Rickyy-b** [comment]
The page is behind a login. I'll check later and provide you with the url.
