### ISSUE TITLE
Can’t Log In to Netflix in Safari

### ISSUE THREAD

**Issue by zeezeepiggy** [badmojr/1Hosts#700]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**

 NextDNS

<br>

**Domains:**
```
beaconimages.netflix.net
```
<br>

**Details:**
Cant log in to Netflix in Safari.

it says password not match. This is because the area where the password text is entered is used by the beaconimages domain. Whitlisting it fixes the error.

see image attach.
![5D720F88-C04F-40B1-B4C8-2730A461DE98](https://user-images.githubusercontent.com/27464836/188889199-7de7b7cc-08e9-4b12-9d44-d42d79829b3c.jpeg)
![CAC02BAF-9174-47C4-B43E-D239DCA3EC9F](https://user-images.githubusercontent.com/27464836/188889216-7592032b-5e76-4e4c-bf8c-0a5eb11bf01e.jpeg)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
One does not simply fix bad design choices.
