### ISSUE TITLE
||mynt.xyz^ This is blocked on xtra. It is use for online wallet transaction and i cant log in. Whitelisting this fixed the problem.

### ISSUE THREAD

**Issue by Domsicols** [badmojr/1Hosts#701]
![image](https://user-images.githubusercontent.com/104392824/189015497-ecbf0fdb-f085-42e1-baee-8b637519a8b7.png)![image](https://user-images.githubusercontent.com/104392824/189015513-b5aca9bc-8842-4273-9b9b-3262c7b148e0.png)

**Comment by spirillen** [comment]
Hmm a wallet transaction over a xyz domain sounds spooky to me by default. Are you absolutely sure this is a safe gateway?

**Comment by Domsicols** [comment]
Yes i think because this is a mojor network provider to start with here in my country.
