### ISSUE TITLE
False positives 

### ISSUE THREAD

**Issue by JYYJ1986** [badmojr/1Hosts#705]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS 

<br>

**Domains:**
```

unagi-fe.amazon.com

fls-fe.amazon.co.jp

```
<br>

**Details:**
It’s needed for Amazon app to load properly on android devices.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Please provide some before and after screenshots.
Unable to reproduce as the app loads fine with Pro on my side.

**Comment by JYYJ1986** [comment]
![Uploading 47F0859A-4AF9-429D-A4CC-40564ADF97A6.png…]()

**Comment by JYYJ1986** [comment]
![95226326-DD89-405F-B79B-CDC5FCE5BDCC](https://user-images.githubusercontent.com/106444248/190135913-3fd0d571-7aef-42ca-a382-d648932bf870.png)
![5E0BB720-423F-43D3-A0A9-0817977A4B69](https://user-images.githubusercontent.com/106444248/190135940-41734d97-701d-4547-ae55-dc3c5a0560c9.png)
![3E2A9F02-6BA3-4F82-9D16-54DED9C70DBA](https://user-images.githubusercontent.com/106444248/190135957-0d8e2a2b-b435-4ad7-8e9f-5a290ad2c9c2.png)
![7B13ED88-139E-425A-8388-45E3EC3EC5FD](https://user-images.githubusercontent.com/106444248/190135966-c68ca863-8954-4fe3-b01b-cc0eb72b7cd7.png)
![0E292485-AB79-41A0-BBD5-EFDB6F180946](https://user-images.githubusercontent.com/106444248/190135974-95c807f0-8ddf-4278-a6a4-a7e05817b354.png)

**Comment by badmojr** [comment]
Just to be sure, which blocklists do you use?

**Comment by JYYJ1986** [comment]
I do use quite a few.. but only yours seems to block.. 

![Uploading image.jpg…]()

**Comment by JYYJ1986** [comment]
![Uploading Screenshot_20220914-195802.png…]()

**Comment by JYYJ1986** [comment]
![Screenshot_20220914-195802](https://user-images.githubusercontent.com/106444248/190149820-d04b492c-9572-4887-a77f-9aee1ca02aa5.png)

**Comment by badmojr** [comment]
I can't seem reproduce this.

**Comment by MaXfAa** [comment]
> I can't seem to reproduce this.
> 

Same here, it works perfectly with the list (the Pro one)...
