### ISSUE TITLE
Remove myteletalk.tiger-park.com

### ISSUE THREAD

**Issue by touhidurrr** [badmojr/1Hosts#706]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
Rethink DNS

<br>

**Domains:**
```
myteletalk.tiger-park.com
```
<br>

**Details:**

This prevents the usage of MyTeletalk app.
Play Store Link:
https://play.google.com/store/apps/details?id=teletalk.teletalkcustomerapp

MyTeletalk is an account management app for the users of **Teletalk Bangladesh Limited**, an state owned mobile network operator in Bangladesh. The app is likely developed by **Tiger Park Limited** and thus uses their domain. Dunno why it is blocked though.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by touhidurrr** [comment]
![Screenshot_2022-09-15-21-32-00-25_0b9664ef80c091d1f7f67d603c46d1dc](https://user-images.githubusercontent.com/46617994/190445608-baae70fa-90fa-4b03-b283-f10e4043a505.jpg)

**Comment by touhidurrr** [comment]
I think the screenshots are enough to prove the existence of this issue.

**Comment by fdhfgbsjedfg-775** [comment]
I disagree, the domain isn't being blocked:
![Screenshot_20220915_215810](https://user-images.githubusercontent.com/58587609/190451550-19bd11dc-7d14-443d-9dd8-1f3a1d2d9085.jpg)
![Screenshot_20220915_215742](https://user-images.githubusercontent.com/58587609/190451563-a18e5796-5285-48db-89eb-386d675aebf9.jpg)

> Did you enable 1Hosts Extra before checking?

Yes, I did.

I am wondering, is the app updated to the latest version, or is it downloaded from alternative sources like f-droid.

**Comment by touhidurrr** [comment]
Ok, I couldn't find `myteletalk.tiger-park.com` anywhere in 1Hosts Xtra. Not sure why I am having this problem in Rethink DNS. Anyways, I am closing this issue.

**Comment by touhidurrr** [comment]
@badmojr confused why you reopened it.

**Comment by badmojr** [comment]
It was included on Xtra but got immediately removed by upstream as seen [here](https://blocklist-tools.developerdan.com/entries/search?q=myteletalk.tiger-park.com) .

I've reopened it 'coz I wanna make sure it's never reintroduced again by any of the upstream lists, by adding it to [this list](https://github.com/badmojr/1Hosts/blob/master/submit_here/exclude_for_all.txt) .

**Comment by touhidurrr** [comment]
> Yes, I did.
>
>I am wondering, is the app updated to the latest version, or is it downloaded from alternative sources like f-droid.

@fdhfgbsjedfg-775 yes, I installed it from F-Droid cause the F-Droid latest **053j** was greater than Play Store latest **053i**. Also updated the lists properly before taking the screenshots.
