### ISSUE TITLE
Whitelist kiwibrowser.com

### ISSUE THREAD

**Issue by fdhfgbsjedfg-775** [badmojr/1Hosts#708]
<br>
<h1 align="center">Submit Form</h1>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
kiwibrowser.com
```
<br>

**Details:** Kiwi Browser is a free and open-source Android web browser based on Chromium and WebKit. It was created by Geometry OU and a team of volunteers.

<div align="center">
  <h3>Thank you for supporting 1Hosts.</h3>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
See the reason behind it's blockage [here](https://github.com/badmojr/1Hosts/blob/4edac42aac91f7d02fd9f96689daee6735beb334/submit_here/include_for_Pro_Xtra_only.txt#L39) .

**Comment by fdhfgbsjedfg-775** [comment]
👍

**Comment by fdhfgbsjedfg-775** [comment]
?
