### ISSUE TITLE
Please do not force push or what happened here?

### ISSUE THREAD

**Issue by thomasmerz** [badmojr/1Hosts#710]
I wanted to sync my fork today (after only one month after my last sync)… but what's this? @badmojr 

> This branch is [560 commits ahead](https://github.com/thomasmerz/1Hosts/compare/badmojr:1Hosts:master...master), [38 commits behind](https://github.com/thomasmerz/1Hosts/compare/master...badmojr:1Hosts:master) badmojr:master.

<img width="1095" alt="grafik" src="https://user-images.githubusercontent.com/18568381/190689602-3371dcae-fbb0-45eb-93b1-8dfa55fa4ff9.png">

---

ℹ️  So, please do not force-push because it breaks other's people's forks… Thank you so much for respecting this 😘

**Comment by badmojr** [comment]
Hello.
This has been discussed before.
Please refer to #408 .

And if you're interested on how this is accomplished, see https://github.com/badmojr/1Hosts/blob/master/.github/workflows/init.yml .
