### ISSUE TITLE
Huawei GRS (russian version)

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#713]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
grs.platform.dbankcloud.ru
```
<br>

**Details:**
The russian version of the grs domains isn't blocked.
The phone tries every domain one by one, if you don't block the russian one then it's no use.
![179962224-b9015d14-d1d9-48a4-928e-a051eeadc9da](https://user-images.githubusercontent.com/71935156/190728548-ac6c9ac2-5cfa-4132-ba2e-4aa1f309dd47.png)
(In this screenshot, there is a red tab on the left because I blacklisted it myself.)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Which app requested that domain? Link please...

**Comment by MaXfAa** [comment]
> Which app requested that domain? Link please...

HMS Core (Huawei's Play Services equivalent): https://play.google.com/store/apps/details?id=com.huawei.hwid or https://appgallery.huawei.com/app/C10132067
