### ISSUE TITLE
Pinterest gw-dv domains

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#715]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
pinterest.cdn-gw-dv.net
```
<br>

**Details:**
You're already blocking ``pinterest.gw-dv.net`` but is this domain is blocked, then the Pinterest app requests a secondary domain: ``pinterest.cdn-gw-dv.net``, as you can see:
![179966888-c1252dd4-09f1-486d-bd60-7b8c7a8578a4](https://user-images.githubusercontent.com/71935156/190729600-cb991e80-f181-4702-bfdd-d9c43b16ec7c.jpg)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Which app requests the domain above? Share a link please.

**Comment by MaXfAa** [comment]
> Which app requests the domain above? Share a link please.

Uh... the Pinterest app of course
https://play.google.com/store/apps/details?id=com.pinterest
