### ISSUE TITLE
Vinted's required domain

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#716]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
mobile-data.onetrust.io
```
<br>

**Details:**
If these two domains are blocked, the Vinted app won't work: ``mobile-data.onetrust.io`` (and ``cdn.cookielaw.org``).

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Hello.
You requested this domain be blocked in #522.

**Comment by MaXfAa** [comment]
> Hello. You requested this domain be blocked in #522.

Yeah, it was a mistake, sorry 😔
