### ISSUE TITLE
Google's audit recording domain

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#718]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
auditrecording-pa.googleapis.com
```
<br>

**Details:**
I'm almost sure this domain is a data collector domain since Android 12.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Share a link to the app which requested the domain.
