### ISSUE TITLE
Weird requests to Picks while using Samsung's weather app

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#719]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
samsungnewsapi.picks.my
```
<br>

**Details:**
The weather app makes some connections to this domain while it has nothing to do with the weather and by blocking it nothing changes.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Send a link to the app.

**Comment by MaXfAa** [comment]
> Send a link to the app.

https://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-weather/
(The app isn't available on the Play Store or Galaxy Store: https://play.google.com/store/apps/details?id=com.sec.android.daemonapp https://galaxystore.samsung.com/detail/com.sec.android.daemonapp)

**Comment by badmojr** [comment]
I won't be adding this one as it may be related to some type of weather news by the app, which some users might find useful.
