### ISSUE TITLE
playmoviesdfe new substitute domain (Android TV)

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#722]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
androidtvgtvmfe-pa.googleapis.com
```
<br>

**Details:**
You are already blocking the domain of Play Movies but not this of the replacement "Android TV"
![tv](https://user-images.githubusercontent.com/71935156/190851975-b670282b-7635-47e4-b6da-fb215bc92d15.jpg)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Any other reason on why this should get blocked?

**Comment by MaXfAa** [comment]
> Any other reason on why this should get blocked?

Not really
