### ISSUE TITLE
Whitelist metricool.com

### ISSUE THREAD

**Issue by mcprol** [badmojr/1Hosts#728]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [x] mini
- [x] Lite
- [x] Pro
- [x] Xtra
<br>

<br>

**Domains:**
```
metricool.com
```
<br>

**Details:**

Metricool is a social media tool and in no way should it be considered used for 'advertisements'.
Some customers are complaining that their ad blocker is denying them access to metricool.com

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by mcprol** [comment]
Hi, Could you tell us why you consider metricool.com as an ad generator? It would help us find a solution and avoid problems for our customers who use ad blockers.

Regards
Marcos

**Comment by badmojr** [comment]
It's been on a number of other lists for quite a while now.
see: https://blocklist-tools.developerdan.com/entries/search?q=metricool.com

My only guess is that it's been deemed as a tracking service and hence blocked, as can be seen [here](https://publicwww.com/websites/%22metricool.com%22/).

**Comment by mcprol** [comment]
Thanks for the info about other lists. I will try that metricool.com to be removed from them.

Regarding the tracking service, thats is the tracker code that our customers install on their wordpress or their CMS. It is not used to generate ads or spam, but it is part or our service.

Regards
Marcos
