### ISSUE TITLE
TikTok's logs domain (via byteoversea)

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#731]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
log-tiktok.byteoversea.net
```
<br>

**Details:**
ByteDance/TikTok's logs domain (one of)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Where did u get this? Share some screenshots.

**Comment by MaXfAa** [comment]
> Where did u get this? Share some screenshots.

It's requested by the TikTok app
!-- Error while uploading Screenshot_20220924_142900.jpg --

**Comment by badmojr** [comment]
Can't see it. Please resend!

**Comment by MaXfAa** [comment]
> Can't see it. Please resend!

Oops sorry, it works now
