### ISSUE TITLE
heads-fa.scdn.co

### ISSUE THREAD

**Issue by bbhtt** [badmojr/1Hosts#734]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**

AhaDNS
personalDNSFilter

<br>

**Domains:**
```
heads-fa.scdn.co
```
<br>

**Details:**

heads-fa.scdn.co is used by the Spotify app to display album art.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Can't reproduce.

![Screenshot_20220925-174153_Chrome](https://user-images.githubusercontent.com/40524316/192149771-40ece07b-7901-40bf-b118-cda7f701e487.jpg)
![Screenshot_20220925-174053_Spotify](https://user-images.githubusercontent.com/40524316/192149785-4052942f-bc5e-45e5-a2b7-89557ac4fd75.jpg)
