### ISSUE TITLE
shalltry.com

### ISSUE THREAD

**Issue by ghost** [badmojr/1Hosts#736]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [x] mini
- [x] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:** NextDNS + AdGuard (Android)

<br>

**Domains:** 
```
shalltry.com
```
<br>

**Details:**
Tracking and telemetry on Infinix and Tecno devices, phone system telemetry and system apps. This domain has been added to OISD, AdGuard and EasyList.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
I've blocked most of its offending subdomains.
The root domain also serves legit content such as wallpapers, themes, etc.

**Comment by spirillen** [comment]
> The root domain also serves legit content such as wallpapers, themes, etc.

:question: :question: :question: :question: :question: 

Where?

![image](https://user-images.githubusercontent.com/44526987/193054340-48ddee13-fb40-40a4-9610-11df63faabb8.png)

**Comment by badmojr** [comment]
Through this subdomain. You first have to download their launcher though!
`cdn-theme-eu-central-1.shalltry.com`

**Comment by spirillen** [comment]
ok, thanks for your feedback
