### ISSUE TITLE
transacme.com

### ISSUE THREAD

**Issue by ghost** [badmojr/1Hosts#737]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [x] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:** NextDNS + AdGuard (Android)

<br>

**Domains:**
```
transacme.com
public.transacme.com
app.transacme.com
magazine.transacme.com
```
<br>

**Details:**
Tracking and telemetry on Infinix and Tecno devices. I tested one of the domains (magazine.transacme.com) and it doesn't work. It displays the error message but the domain is not blocked and continues to show up in the logs. The same with the others. These domains are blocked by 1Hosts (Xtra).

Screenshots:
![Screenshot_20220919-110402](https://user-images.githubusercontent.com/109208335/192494940-1e5a0390-aeb8-4473-893c-9a3833546b95.jpg)
![Screenshot_20220927-175149](https://user-images.githubusercontent.com/109208335/192494963-b337b7de-08f5-48dd-aff8-1ea1e051d25f.jpg)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
What I am supposed to do with? Remove them?
