### ISSUE TITLE
Trackers

### ISSUE THREAD

**Issue by trackerct** [badmojr/1Hosts#738]
Can you add blocklist please?

Trackers by Vivo Mobile (have a couple of dns queries)

tr-vcode-od.vivoglobal.com
tr-vcode-api.vivoglobal.com
tr-st-sl.vivoglobal.com
tr-domaincfg.vivoglobal.com
tr-timesync.vivoglobal.com
tr-romsp-unifyconfig.vivoglobal.com
asia-exstsdk.vivoglobal.com
asia-comonrt-stsdk.vivoglobal.com

Trackers by Vodafone

netperform-is.vodafone.com.tr
Vodafone NetPerform · Network coverage. This application will capture statistics about your connectivity for phone calls. · Internet connectivity · Call quality

mplusps.ims.vodafone.com (tracker)
mpluswf.ims.vodafone.com (tracker)

Advertising/Trackers
config.rcs.mnc002.mcc286.pub.3gppnetwork.org
advertise.ldplayer.net
storeen.ldmnq.com
mobile-tracking.bloomberg.com
data.media-lab.ai
centaurs-rest.coupang.com
me-inbox.eservice.emarsys.net
api.mapbox.com
tags.tiqcdn.com

Google Spyware (have a couple of dns queries)
telephonyspamprotect-pa.googleapis.com
growth-pa.googleapis.com
deviceintegritytokens-pa.googleapis.com
gmscompliance-pa.googleapis.com
mdh-pa.googleapis.com
digitalassetlinks.googleapis.com

**Comment by badmojr** [comment]
How did you come to the conclusions above? What tests were performed to ensure the domains are not negatively affecting UX?

Anyway I may reproduce your findings?
Please do provide as much detail as necessary, with some screenshots if possible.

**Comment by trackerct** [comment]
> tr-vcode-od.vivoglobal.com
> tr-vcode-api.vivoglobal.com
> tr-st-sl.vivoglobal.com
> tr-domaincfg.vivoglobal.com
> tr-timesync.vivoglobal.com
> tr-romsp-unifyconfig.vivoglobal.com
> asia-exstsdk.vivoglobal.com
> asia-comonrt-stsdk.vivoglobal.com

in my vivo phone. have a couple of dns queries. I blocked them manually with persoaldnsfilter app. My phone is now very fast:)
https://play.google.com/store/apps/details?id=dnsfilter.android



advertise.ldplayer.net
storeen.ldmnq.com
-and this, LDPlayer 4 in my windows. / Android emulator.  Showing advertising
https://www.ldplayer.net/


mobile-tracking.bloomberg.com
data.media-lab.ai
centaurs-rest.coupang.com
me-inbox.eservice.emarsys.net
-and this, bloomberg apk trackers.
https://www.apkmirror.com/apk/bloomberg-lp-cm/bloomberg-market-financial-news/


api.mapbox.com
-and this, The Walking Dead: Our World game
https://www.apkmirror.com/apk/next-games/the-walking-dead-our-world/the-walking-dead-our-world-19-0-2-7335-release/



netperform-is.vodafone.com.tr
mplusps.ims.vodafone.com
mpluswf.ims.vodafone.com
tags.tiqcdn.com
config.rcs.mnc002.mcc286.pub.3gppnetwork.org
-and this, Vodafone Mobile Apk
https://www.apkmirror.com/apk/vodafone-holding/vodafone-yanimda/



telephonyspamprotect-pa.googleapis.com
growth-pa.googleapis.com
deviceintegritytokens-pa.googleapis.com
gmscompliance-pa.googleapis.com
mdh-pa.googleapis.com
digitalassetlinks.googleapis.com
-and this, Android Os. 
i want to block unneccessary googleapis. GoogleAPIs are flooding my Phone.

more info
https://mypdns.org/my-privacy-dns/matrix/-/issues/1837

**Comment by spirillen** [comment]
Just a service... `googleapis.com` is moved to https://mypdns.org/my-privacy-dns/matrix/-/issues/1163997

**Comment by trackerct** [comment]
co-vcode-api.vivoglobal.com
co-vcode-h5-od.vivoglobal.com
asia-vcode-or.vivoglobal.com
asia-exstatic.vivo.com
vcm-static.vivo.com
asia-commonitor-stsdk.vivoglobal.com
asia-romsp-unifyconfig.vivoglobal.com
asia-stp.vivoglobal.com
asia-vcode-api.vivoglobal.com

freegeoip.live
geocheck.sim-technik.de
ipapi.co
analytics.coollabs.io
statistic.live.126.net
m.equinoxplus.com
akamai.tiqcdn.com
app.anch.co
crash.uu.easebar.com
mobile.uu.easebar.com
uumov.fp.ps.easebar.com
uuov.fp.ps.easebar.com
uu.fp.ps.netease.com
mg.uu.163.com
adx.adsgaga.com
177657.tracking.hyros.com
ma1226-r.analytics.edgesuite.net
netperform-lz.vodafone.com
js-eu1.hscollectedforms.net
forms-eu1.hsforms.com
restapi.netmera.com
eturkcell.netmera.com
adiu.amap.com
alimelog.taobao.com
localization.services.pbs.org
cc-api-data.adobe.io
app-1c835e5474e6a378.mobileapi.usebutton.com
logs.us-east-1.amazonaws.com
vmweb-va.byteoversea.com
mcs-va.tiktok.com.edgekey.net
appad.cyberlink.com
abtest.tantanapp.com
report.tantanapp.com
client-tracking.tantanapp.com
sc-report.tantanapp.com
deviceid.tantanapp.com
counter.tantanapp.com
lorempixel.com
analytics-lal-nba.yinzcam.com
ads-lal-nba.yinzcam.com
api.adtech.etermax.com
gdpr-tcfv2.sp-prod.net
mynt-test-privacy.my.onetrust.com
analytics.meaww.com
vmweb-va.byteoversea.com
mssdk-va.tiktok.com
sf16-muse-va.ibytedtos.com
sotalcloud.blob.core.windows.net
xtrapath1.izatcloud.net
xtrapath2.izatcloud.net
xtrapath3.izatcloud.net
fl-badger-prod-statscluster.moonfroglabs.com
internetbrands-d.openx.net
