### ISSUE TITLE
Allowlist mcs-va.tiktok.com

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#741]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** NextDNS + uBO

<br>

**Domains:**
```
mcs.us.tiktok.com
direct.applog-lb-texas.useast5.byteoversea.net

mcs-va.tiktok.com
mcs-va.tiktok.com.edgekey.net
e35058.api3.akamaiedge.net
```
<br>

**Details:** Blocking the CNAME (or not allowlisting `mcs.us.tiktok.com` specifically) causes breakage of in-page embedded TikTok posts. CNAME appears connected with the parent company of TikTok.

Example: `https://toofab.com/2022/09/28/netflix-drops-lgbtq-tag-dahmer-backlash/`

![Screenshot 2022-09-28 160320](https://user-images.githubusercontent.com/11689349/192878642-46899f3e-0320-4618-bbee-c85ffc160d51.png)

![Screenshot 2022-09-28 160605](https://user-images.githubusercontent.com/11689349/192878645-d90883cf-2823-4137-ad49-c359457ce25b.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
I got it to load by allowing `mcs-va.tiktok.com` only.
The above provided domain wasn't needed. Would you please test again with this?

**Comment by spirillen** [comment]
> mcs-va.tiktok.com

How did you test this, :thinking: if you tested via hosts file you would get the same restult as if you blocking by RPZ where any hit to one of the domains would leads to a manipulated results

IE if you block just one of these domains, it would response with NXDOMAIN

```
mcs-va.tiktok.com.    CNAME . ; SpyWare
mcs-va.tiktok.com.edgekey.net.    CNAME . ; SpyWare
e35058.api3.akamaiedge.net.    CNAME . ; SpyWare
```

**Comment by yokoffing** [comment]
> I got it to load by allowing `mcs-va.tiktok.com` only.

Yes. That was I was intending to communicate. I apologize for the miscommunication; I could've worded this better.

**Comment by yokoffing** [comment]
Apologies once again. I overlooked the `va` in your request and didn't realize it was different from `mcs.us.tiktok.com`.

Using the example page, I don't see `mcs-va.tiktok.com` (`va`) or the other two requests you've listed in my logs.

To be clear: I still need to allowlist `mcs.us.tiktok.com` (`us`) to get the TikTok embed to work. None of the other requests are showing for me at the DNS-level or adblock level.

I suspect **TikTok is serving different domains based on user location**. Notice yours is `va` while mine is `useast`.

My guess is you need to allowlist both `mcs.us.tiktok.com` and `mcs-va.tiktok.com`. I'm sure there's more domains based on user locations, but these are the two we know about right now.

```
mcs.us.tiktok.com
direct.applog-lb-texas.useast5.byteoversea.net
```

![aka](https://user-images.githubusercontent.com/11689349/193151041-3f99eddd-d459-42eb-ba39-c8527592c5d9.png)

![Screenshot 2022-09-29 180011](https://user-images.githubusercontent.com/11689349/193149788-990ab468-3fbc-4977-b137-edcd06abb090.png)

![Screenshot 2022-09-28 160320](https://user-images.githubusercontent.com/11689349/192878642-46899f3e-0320-4618-bbee-c85ffc160d51.png)
