### ISSUE TITLE
Allowlist tyk.io

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#743]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:** NextDNS + uBO

<br>

**Domains:**
```
tyk.io
```
<br>

**Details:** Looks like a legitimate site?

![Screenshot 2022-09-29 234441](https://user-images.githubusercontent.com/11689349/193185789-b122a13d-e801-46fd-badb-e6507841285b.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
I doubt it! Bunch of red flags on a bunch of public TI feeds.

**Comment by yokoffing** [comment]
> Bunch of red flags on a bunch of public TI feeds.

I didn't research it. I stumbled upon the site while searching for something else. Looked like a legitimate site, but I know nothing about `tyk.io`.
