### ISSUE TITLE
blocking sekindo.com breaks the video on nationalinterest.org

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#75]
Blocking
```
live.sekindo.com
video.sekindo.com
```
breaks video on
`https://nationalinterest.org/blog/coronavirus/coronavirus-spike-inevitable-why-16-medical-experts-are-worried-175985`

Cheers

**Comment by badmojr** [comment]
- The only videos found playing from these domains seems unrelated to the rest of the content/article & are in outoplay.
- Quite a number of upstream lists have this blocked
- https://github.com/search?o=desc&q=sekindo&s=created&type=Issues

Can't get myself to unblock this! Sorry, bud!

**Comment by crssi** [comment]
No hard feelings at all. In the following text of reply I am just thinking out loud.

> The only videos found playing from these domains seems unrelated to the rest of the content/article & are in outoplay.

All the tutorials are over those two hosts at `https://aternos.org/`... so it is related.

Actually the whole household never got a hit (from the DNS log) to this domain, except for the kid playing Minecraft over Athernos daily/weekly and me only once a few months back on mobile device opening the link in the original post.
This means a few millions DNS hits/queries in the last year of log (a little less than a million per month).
Its not hard to dig into over NextDNS logs.

The logs are the actually the reason that I have found the link in the original posts as a sample. 😉 
So I don't know how the upstreams got this domain on a list, but I would say it is a rarity.

I will whitelist it manually.

Thank you as always for you work and time
Cheers

**Comment by badmojr** [comment]
No problem!
I just found out it has been on an upstream list seen 2013.
https://blocklist-tools.developerdan.com/entries/search?q=live.sekindo.com

**Comment by crssi** [comment]
No worries. 😄 ❤️
