### ISSUE TITLE
Rethink DNS does support wildcard/subdomain hosts

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#752]
Resolver: https://github.com/serverless-dns/serverless-dns/blob/d72be3fe43b2ea6792f768118c8a8938a553d20f/src/plugins/rdns-util.js#L116

App: https://github.com/celzero/gotrie/blob/d9d0dcea9cbdb7738628cea0668c5fb99b959a9d/trie/frozentrie.go#L427

---

Though Rethink doesn't use wildcard/subdomain [host files from 1Hosts](https://github.com/serverless-dns/blocklists/blob/5a847d0/blocklistConfig.json). Should we?

**Comment by badmojr** [comment]
Here's the thing  @ignoramous .
If the two lacking features (i.e daily updates & subdomain/wildcard blocking)  got implemented on RethinkDNS, I'd recommend and rank it first above all.
Why you ask? Simply because it's open source.

**Comment by ignoramous** [comment]
> If the two lacking features (i.e daily updates & subdomain/wildcard blocking) got implemented on RethinkDNS

Rethink already supports wildcard / subdomain. See the linked code in desc.

Frequent updates are coming to `max.rethinkdns.com`, soon (: I'm working on fixing the broken automation, as we speak. May be I get it done in a week, may be in in a month. I'll let you know.

**Comment by ignoramous** [comment]
The blocklist updates are automated and published 4 times a month: https://github.com/serverless-dns/blocklists/commit/0face560fcf1012ce8e6a18d7e96a5b49ca816e9

It was 5 weeks in the making! When we finish releasing `v055` (for the android app) sometime in the beginning of 2023, I'll return to this automation to see if we can update daily (storage costs are too prohibitive right now, and also the servers lose their caches frequently if blocklists are updated daily, which makes it not only slower but expensive to run them).

**Comment by ignoramous** [comment]
In the sixth week, and wildcard domains are live! We had to do it because of the ballooning blocklist sizes!

1Hosts (all lists): `1-gadagaaaqaiaaaia.max.rethinkdns.com` (DoT) / https://sky.rethinkdns.com/1:MAYDAACAEAABAA==

LMK if you find any issues with wildcard blocks... even though the code is pretty raw, I don't expect bugs.
