### ISSUE TITLE
Overwatch 2 tracking domain not being blocked

### ISSUE THREAD

**Issue by RouterCFW** [badmojr/1Hosts#759]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client: NextDNS**

<br>

**Domains:**
```
overwatch.ingest.gdp.blizzard.com
```
<br>

**Details:**

Overwatch 2 tracking domain isn’t blocked 

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by yokoffing** [comment]
> Overwatch 2 tracking domain isn’t blocked

Do you play Overwatch 2? Does blocking this break the game?

**Comment by RouterCFW** [comment]
> > Overwatch 2 tracking domain isn’t blocked
> 
> Do you play Overwatch 2? Does blocking this break the game?

Play it all the time and blocking does not cause any issues

**Comment by spirillen** [comment]
@RouterCFW You only listed one domain, but you are speaking of two?

**Comment by RouterCFW** [comment]
> @RouterCFW You only listed one domain, but you are speaking of two?

my bad there’s only one

**Comment by badmojr** [comment]
How do you know it's actually a tracking domain?

**Comment by RouterCFW** [comment]
> How do you know it's actually a tracking domain?

The game contacts the domain every game played and blocking the domain doesn’t effect anything in game when blocked

**Comment by RouterCFW** [comment]
> How do you know it's actually a tracking domain?

Further digging I found that they have different domains for every game where they collect data all leading back to ingest.gdp.blizzard.com

**Comment by yoshimo** [comment]
I haven't been able yet to look inside the pinned TLS connection to see what it transmitted.

**Comment by RouterCFW** [comment]
> I haven't been able yet to look inside the pinned TLS connection to see what it transmitted.

I would look but I’m on PlayStation so I can’t check without additional hardware
