### ISSUE TITLE
False positive: tracker.avistaz.to

### ISSUE THREAD

**Issue by hlqviet** [badmojr/1Hosts#760]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
tracker.avistaz.to
```
<br>

**Details:**
This is a torrent tracker. It's not a tracking domain which tracks user interactions.
https://avistaz.to

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by hagezi** [comment]
Thanks, removed from my list: https://github.com/hagezi/dns-blocklists/commit/67d613c9ee8e7480ad6dbd3f91c3b7f4451400be
