### ISSUE TITLE
Allowlist ads-fa-darwin.hulustream.com | Hulu playback errors

### ISSUE THREAD

**Issue by yokoffing** [badmojr/1Hosts#762]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** NextDNS, uBlock Origin

<br>

**Domains:**
```
ads-fa-darwin.hulustream.com
```
<br>

**Details:** Breaks Hulu streaming when at ad play periods. Unable to watch unless this is allowed, even after restarting. 

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Doesn't it load ads after it's allowed?

**Comment by yokoffing** [comment]
Yes, but it's either allow the ad to play or don't watch the content any further when on iOS or SmartTV.

On desktop, uBlock Origin still blocks ads even with this request allowlisted.
