### ISSUE TITLE
Samsung GPM domain (via Tizen Services' domain)

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#764]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
gpm.tizenservice.com
```
<br>

**Details:**
![image](https://user-images.githubusercontent.com/71935156/194934835-37153bf0-6983-4724-bcdf-6e008bfb335d.png)
![image](https://user-images.githubusercontent.com/71935156/194934917-a492fbd0-d84f-4e07-a289-c18d5a97dcdf.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Could be a false positive.
