### ISSUE TITLE
Block chtbl.com

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#767]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Domains:**
```
web.chtbl.com
chtbl.com
```
<br>

**Details:**
Found this on `merkle.com` sending POST requests to its `/track` endpoint. AdAway had this in its blocklist (https://github.com/AdAway/adaway.github.io/issues/243), but the maintainer opted to remove it. May be it makes sense for 1Hosts Extra?

**Comment by yoshimo** [comment]
that one is problematic as it is used for podcasts to do analytics. If you block chtbl and therefore the redirect, downloading episodes fails.
