### ISSUE TITLE
a.klaviyo.com prevents registration on rungne.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#771]
**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:** NextDNS, uBO

<br>

**Domains:**
```
a.klaviyo.com
```
<br>

**Details:**
STR:
1. Visit rungne.com
2. stumble around... wait for a minute until 10% discount offer is shown
3. Enter some email to get the discount
4. after submiting email an error occurs

When `a.klaviyo.com` is whitelisted the registration works

Cheers

**Comment by crssi** [comment]
@badmojr you are making me worry, since you are away quite long... are you OK?

**Comment by mahtd** [comment]
Blocking a.klaviyo.com also prevents me from unsubscribing from Graf Lantz and Darn Tough Vermont marketing emails, both which use Klaviyo to manage the lists

**Comment by crssi** [comment]
Thank you ❤️
