### ISSUE TITLE
Unblock: offers.sheerid.com

### ISSUE THREAD

**Issue by bbhtt** [badmojr/1Hosts#772]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:** AhaDNS

<br>

**Domains:**
```
offers.sheerid.com
```
<br>

**Details:**

The GitLab open source program form doesn't load with it blocked https://about.gitlab.com/solutions/open-source/join/

![image](https://user-images.githubusercontent.com/62639087/196307120-ca4b0a6a-6397-4a7f-ae4d-f200dbf8e02d.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
Confirmed, however, I would personally only keep this as a mentioned situation for the individual to whitelist, as it is so rare you actually would ever need to provide access to this subdomain, and even then I would only do so over tor.
