### ISSUE TITLE
Unblock: repology.org

### ISSUE THREAD

**Issue by bbhtt** [badmojr/1Hosts#774]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:** AhaDNS

<br>

**Domains:**
```
repology.org
```
<br>

**Details:** Packaging information for software

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
What makes you believe this should be blacklisted?

**Comment by bbhtt** [comment]
> What makes you believe this should be blacklisted?

It's for unblocking, I should mention that in the title
