### ISSUE TITLE
sentry.cdn77.eu

### ISSUE THREAD

**Issue by r2fo** [badmojr/1Hosts#777]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
sentry.cdn77.eu
```
<br>

**Details:**
This is a Sentry.io error logging and  analytics service. I saw other Sentry domains getting blocked and found this one left unblocked, so I decided to report it.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
Thanks
