### ISSUE TITLE
Unblock akamai-images-content.com

### ISSUE THREAD

**Issue by bbhtt** [badmojr/1Hosts#782]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:** dnscrypt-proxy

<br>

**Domains:**
```
akamai-images-content.com
```
<br>

**Details:**

Seems to be a CDN of Akamai

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Breaks anything, anywhere?

**Comment by bbhtt** [comment]
> Breaks anything, anywhere?

I don't remember the original site that broke and prompted me to open this issue. But searching the domain online I found https://www.anime-base.net/episode/132/59/1/1/0 which redirects to https://watchsb.com/6mwj2ds7yjka.html and the domain in question seems to serving the cover images for the video https://akamai-images-content.com/6mwj2ds7yjka_t.jpg and what seems to be chunks of the video:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +45 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_o/seg-3-v1-a1.ts?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +45 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_o/seg-2-v1-a1.ts?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +45 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_o/seg-1-v1-a1.ts?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +38 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_o/seg-2-v1-a1.ts?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +34 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_n/seg-1-v1-a1.ts?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +28 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_n/seg-2-v1-a1.ts?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +28 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_n/index-v1-a1.m3u8?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +25 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_l/seg-2-v1-a1.ts?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +24 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_l/index-v1-a1.m3u8?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +15 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_o/seg-1-v1-a1.ts?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +15 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_o/index-v1-a1.m3u8?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +15 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_,l,n,o,.urlset/master.m3u8?t=cKywOG--Ou3UszgExkHGRkVLm3YtcrxVAAgwHdPtqm4&s=1668700170&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +0 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_o/seg-3-v1-a1.ts?t=OBGMp1rjLs11PaLZDdCT0no14dEBFIU8AEmLK5Udh3c&s=1668700140&e=10800&f=26194492&srv=sto204&client=<client ip>` |
| +0 |  |  | watchsb.com | 3 | xhr | `https://delivery278.akamai-cdn-content.com/hls2/01/05238/6mwj2ds7yjka_o/seg-2-v1-a1.ts?t=OBGMp1rjLs11PaLZDdCT0no14dEBFIU8AEmLK5Udh3c&s=1668700140&e=10800&f=26194492&srv=sto204&client=<client ip>` |
</details>

**Comment by marcuskbr** [comment]
akamai-images-content.com is not akamai:
- whois akamai-images-content.com shows that the name servers are non-akamai (compare it with whois akamai.com).
- nslookup gives 104.21.235.172 which is non-akamai.
Definitely an imposter.

**Comment by bbhtt** [comment]
I think you're correct, the registrar for Akamai (akamai.com, akamai.net, akamaitech.net, akamaihd.net akamaistream.net...) seems to be MarkMonitor Inc while here it is Namecheap.

So they are using the name of Akamai but I haven't seen the domain doing something nefarious. It seems to be used for serving images like I said above.

Maybe it can be "yellow" listed or something? Or kept in pro, ultimate etc. and removed for mini, lite @badmojr
