### ISSUE TITLE
Yandex false positives

### ISSUE THREAD

**Issue by mehov** [badmojr/1Hosts#783]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
```
/etc/hosts
```
<br>

**Domains:**
Breaking false positives:
```
sso.passport.yandex.ru
mx.yandex.ru
```
Potentially breaking false positives:
```
ysa-static.passport.yandex.ru
export.yandex.ru
soft.export.yandex.ru
informer.yandex.ru
share.yandex.ru
```
<br>

**Details:**

- `sso.passport.yandex.ru` is their Single Sign On used during authentication
- `mx.yandex.ru` is their [MX server](https://yandex.com/support/business/dns/mx.html) for Yandex.Mail. The reason it's on this list is it may have been confused with `mc.yandex.ru`

**Comment by badmojr** [comment]
Breaks anything, anywhere?

**Comment by mehov** [comment]
> Breaks anything, anywhere?

Yep, 

- `sso.passport.yandex.ru` breaks switching accounts on their site
- `mx.yandex.ru` will break delivering e-mail to their users
