### ISSUE TITLE
Unblock Vedio site

### ISSUE THREAD

**Issue by a77841s** [badmojr/1Hosts#785]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
msg.ettoday.net
```
<br>

**Details:**
This is the video site of the Ettoday News Cloud.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Provide some screenshots please.

**Comment by hagezi** [comment]
@badmojr 
https://star.ettoday.net/news/2381802

<details>
  <summary>Screenshot</summary>
  
![grafik](https://user-images.githubusercontent.com/104343908/202417805-3d4741e6-e6a4-434b-8305-345aba358737.png)

</details>

**Comment by badmojr** [comment]
I still don't get it. What exactly should I be looking for?

**Comment by hagezi** [comment]
Try to start the video from the screenshot...

**Comment by badmojr** [comment]
It's used for some kind of redirect.
Not really need on the destination page for video playback.

Gonna keep it blocked on Pro-Xtra.
