### ISSUE TITLE
Unblock LINE app Today News

### ISSUE THREAD

**Issue by a77841s** [badmojr/1Hosts#786]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
googletagmanager.com
```
<br>

**Details:**
This is the URL that must be used for the Today news in the LINE App. Blocking will make it impossible to browse the Today news in the LINE App.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by Dynasty-Dev** [comment]
That domain is also used to track users. Though it is also known to break functionality on some sites and apps, you are using a list that prioritizes blocking over functionality. This will likely not be removed and should be manually whitelisted in your client.

**Comment by yokoffing** [comment]
> Blocking will make it impossible to browse the Today news in the LINE App.

Either allowlist `googletagmanager.com` or step down to 1Hosts (Lite).
