### ISSUE TITLE
syndication.twitter.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#79]
Hi @badmojr 

Today we got `syndication.twitter.com` to 1hosts (Lite) which causes breakages.

Is there a possibility to be removed?

Thank you and cheers

**Comment by badmojr** [comment]
Currently blocked on Pro only. Please update & recheck!

**Comment by crssi** [comment]
Hmmm strange... see those for example on current `1Hosts Lite`:
https://github.com/badmojr/1Hosts/blob/c4ffc4fb600fb4397f1f02c0251b2070dc0d7a2b/Lite/adblock.txt#L29125
https://github.com/badmojr/1Hosts/blob/c4ffc4fb600fb4397f1f02c0251b2070dc0d7a2b/Lite/wildcards.txt#L29125

Cheers

**Comment by crssi** [comment]
^^ Do you might have some glitch behind the scenes (in the some sort of update process) ?

**Comment by badmojr** [comment]
Should be fine now! Update & recheck.

**Comment by crssi** [comment]
Thank you 👍
