### ISSUE TITLE
efarketingplansfo.xyz

### ISSUE THREAD

**Issue by r2fo** [badmojr/1Hosts#796]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
efarketingplansfo.xyz
```
<br>

**Details:**
This domain hosts calendars filled with ads. It gets used in those intrusive ads that send you to the calendar app and want to add their own calendar filled with spam

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

`mitsubilla.xyz` is not commit: https://mypdns.org/my-privacy-dns/matrix/-/issues/5827244

</details>
