### ISSUE TITLE
q.stripe.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#80]
Hi @badmojr

Also `q.stripe.com` got to 1hosts (Lite) which causes breakages with some online payments.

Is there a possibility to be removed?

Something strange must happen in the last update, since we have also breakage as per https://github.com/badmojr/1Hosts/issues/79.

Thank you and cheers

**Comment by badmojr** [comment]
S/th really did happen! It's fine now.

**Comment by badmojr** [comment]
S/th really did happen! It's fine now.

**Comment by crssi** [comment]
Thank you 😄
