### ISSUE TITLE
One of Huawei's data collector domain is missing

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#804]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
datacollector-drcn.dt.hicloud.com
```
<br>

**Details:**
https://linksharing.samsungcloud.com/aIHEi16NKAvn

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

Already listed in [https://mypdns.org/my-privacy-dns/matrix/-/issues/1876](https://mypdns.org) 

</details>

**Comment by MaXfAa** [comment]
Successfully added! ✅
Thanks! 🙃 
![image](https://user-images.githubusercontent.com/71935156/200346310-08cc3d35-ff7e-43e2-9b65-c2be411e9cfb.png)
