### ISSUE TITLE
A Yandex startup tracking domain

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#805]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
startup-mobile.ap.yandex-net.ru
```
<br>

**Details:**
Each similar startup domain is blocked (-> screenshot) by your list except this one.
https://linksharing.samsungcloud.com/okqvkEhsug62

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
Need full url to confirm and your link is outdated, and please don't use any url_redirectors (trackers) in you reports

~unconfirmed

**Comment by MaXfAa** [comment]
![signal-2022-11-07-160559_002](https://user-images.githubusercontent.com/71935156/200352328-41738251-810e-4c13-b39f-df2fd24cc5a5.jpeg)

> Need full url to confirm and your link is outdated, and please don't use any url_redirectors (trackers) in you reports

(If you talk about the linksharing link from Samsung, I used it because the uploading of images in my GitHub mobile app is broken.)
