### ISSUE TITLE
Block plausible.safing.io

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#809]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Domains:**
```
plausible.safing.io
```
<br>

**Details:**
`plausible.io` (analytics) instance on `safing.io`

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

fixed in `[mypdns.org](https://mypdns.org/my-privacy-dns/matrix/-/issues/967161)`

</details>
