### ISSUE TITLE
Unblock iframely.net

### ISSUE THREAD

**Issue by bbhtt** [badmojr/1Hosts#812]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:** dnscrypt-proxy

<br>

**Domains:**
```
iframely.net
```
<br>

**Details:** Seems to provide embedded media content

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by yokoffing** [comment]
> Seems to provide embedded media content

Yes, it is used on a few sites as a CDN.

**Comment by bbhtt** [comment]
Seems to be no longer in Xtra

**Comment by bbhtt** [comment]
Example uses I could find:

https://blog.devoc.ninja/2022/11-01/

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 |  |  | blog.devoc.ninja | 3 | image | `https://iframely.net/U6WmRcE/thumbnail` |
| +1 |  |  | blog.devoc.ninja | 3 | script | `https://iframely.net/api/import/v2?touch=0&flash=0&app=1&ids=MHoMZyk%26U6WmRcE%26HMKJTqz%26OFsmByP&v=1` |
| +0 |  |  | blog.devoc.ninja | 3 | script | `https://iframely.net/embed.js` |
| +0 |  |  | blog.devoc.ninja | 3 | script | `https://iframely.net/embed.js` |
| +0 |  |  | blog.devoc.ninja | 3 | script | `https://iframely.net/embed.js` |
| +0 |  |  | blog.devoc.ninja | 3 | script | `https://iframely.net/embed.js` |
</details>

https://budougumi0617.github.io/2021/12/26/retrospective-on-github-2021/

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +5 |  |  | cdn.iframe.ly | 3,3 | image | `https://iframely.net/aN9bpAm/thumbnail` |
| +5 |  |  | cdn.iframe.ly | 3,3 | image | `https://iframely.net/KTvYRKD/thumbnail` |
| +5 |  |  | cdn.iframe.ly | 3,3 | image | `https://github.githubassets.com/favicons/favicon.svg` |
| +2 |  |  | budougumi0617.github.io | 3 | script | `https://cdn.iframe.ly/api/import/v2?card=small&touch=0&flash=0&app=1&ids=qV93q0Z%26HrUY585%26TTjYmqy%262Ijbpvo%26G9h6xiw%26oV2j4cf%261xA1AO2&v=1` |
| +2 |  |  | budougumi0617.github.io | 3 | frame | `https://cdn.iframe.ly/aN9bpAm?v=1&app=1` |
| +2 |  |  | budougumi0617.github.io | 3 | frame | `https://cdn.iframe.ly/KTvYRKD?v=1&app=1` |
| +1 |  |  | budougumi0617.github.io | 3 | script | `https://cdn.iframe.ly/embed.js` |
| +1 |  |  | budougumi0617.github.io | 3 | script | `https://cdn.iframe.ly/embed.js` |
| +1 |  |  | budougumi0617.github.io | 3 | script | `https://cdn.iframe.ly/embed.js` |
| +1 |  |  | budougumi0617.github.io | 3 | script | `https://cdn.iframe.ly/embed.js` |
| +1 |  |  | budougumi0617.github.io | 3 | script | `https://cdn.iframe.ly/embed.js` |
| +1 |  |  | budougumi0617.github.io | 3 | script | `https://cdn.iframe.ly/embed.js` |
| +1 |  |  | budougumi0617.github.io | 3 | script | `https://cdn.iframe.ly/embed.js` |
| +1 |  |  | budougumi0617.github.io | 3 | script | `https://cdn.iframe.ly/embed.js` |
| +1 |  |  | budougumi0617.github.io | 3 | script | `https://cdn.iframe.ly/embed.js` |
</details>
