### ISSUE TITLE
Unblock some mastodon domains

### ISSUE THREAD

**Issue by bbhtt** [badmojr/1Hosts#819]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:** dnscrypt-proxy

<br>

**Domains:**
```
mastodon.lol
mastodon.green
mastodonapp.uk
mastodon.scot
mastodon.world
mastodon.nl
mastodon.top (shows error)
mastodon.coffee
files.mastodon.green
mastodontech.de
mastodon.thrustcarbon.com (redirects to an analytics website)
mastodon.art
mastodon.gamedev.place (gamedev.place is also blocked)
mastodon.sdf.org (sdf.org is also blocked)
octodon.social
mathstodon.xyz
botsin.space
qoto.org
infosec.exchange
chaos.social
```
<br>

**Details:** All mastodon instances

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by bbhtt** [comment]
Since these are all different domains and randomly are blocked I think a list can be pulled from instances.social using their API https://instances.social/api/doc/ and automatically whitelisted.

**Comment by yoshimo** [comment]
Depending on the neutrality of this blocklist, maybe not all instances should be whitelisted. Some promote spam, porn and fascist opinions.
I think instances.social as basic whitelist is ok. Especially since the number of instances is likely to grow.

I also think the problem should be solved at the root as well. People might be subscribed to the upstream source as well and wonder why the twitter alternative works badly

**Comment by bbhtt** [comment]
Most of these are coming from http://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip . This is the main offending list, I haven't looked at it in its entirety as it's quite big ~33 MB.

4 of them are from here https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tracking but all of them redirect to usefathom analytics.

https://github.com/notracking/hosts-blocklists/raw/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt, https://dbl.oisd.nl/ https://filters.adtidy.org/extension/chromium/filters/2.txt, https://filters.adtidy.org/extension/chromium/filters/3.txt has mastodon.thrustcarbon.com (redirects to analytics)

https://www.bentasker.co.uk/adblock/blockeddomains.txt has mastodon.internalnewsletters.co and mastodon.keldrik.com

https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt has mastodon.thoughtbot.com, mastodon.webseed.com, mastodon.large-adv.com

**Comment by yoshimo** [comment]
Cisco  Umbrella is just a list of domains that were popular and asked for very often on the Internet.  There must be post processing  or it is bound  to get a lot of false positives.
