### ISSUE TITLE
Huawei metrics domain

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#824]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
metrics-dre.data.dbankcloud.cn
```
<br>

**Details:**
A new Huawei tracking (metrics) domain
>!-- Error while uploading Screenshot_20221111_174743.jpg --<

https://linksharing.samsungcloud.com/6JY0IOkIAEgS

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by MaXfAa** [comment]
**Domains:**
```
logservice-dre.platform.dbankcloud.cn
```
<br>



**Details:**
A new Huawei tracking (logs) domain
>!-- Error while uploading Screenshot_20221111_174559.jpg --<

https://linksharing.samsungcloud.com/reAipMoQqSfA

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/3529

</details>
