### ISSUE TITLE
Unblock legitimate canarymail.io

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#826]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [X] Pro
- [ ] Xtra
<br>

**Client:**NextDNS 

<br>

**Domains:**
```
https://canarymail.io
```
<br>

**Details:**
Website is blocked.
![image](https://user-images.githubusercontent.com/49731083/201528040-7c080c6d-8f95-4265-9bf5-2fd114da7f37.jpeg)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by RainmakerRaw** [comment]
I came here to report the same issue. Still blocked in 1Hosts Pro (haven't checked the others) as of 2022-11-16 20:45 UTC.
