### ISSUE TITLE
blocking stats.oecd.org breaks the OCED API

### ISSUE THREAD

**Issue by AlexMeier99** [badmojr/1Hosts#83]
Hi,
first of all big thanks for maintaining this list! 👍 
I'm a web developer trying to consume the Rest API of the _[Organisation for Economic Co-operation and Development](https://en.wikipedia.org/wiki/OECD)_ (OECD) at stats.oecd.org. Please also see their [docs](https://data.oecd.org/api/sdmx-json-documentation/) for further reference.
Afaik that domain is blocked by the "1Hosts Pro" filter list.

Could you please take a look into that issue?
Once again thank you very much for the time and effort involved in maintaining this list!
Regards,
Alex

**Comment by badmojr** [comment]
Hello!
Welcome! Should be fixed now.
