### ISSUE TITLE
Allow Slickdeals Links: links.da.slickdeals.net

### ISSUE THREAD

**Issue by Sea-Worker9552** [badmojr/1Hosts#832]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
links.getblueshift.com
links.da.slickdeals.net
```
<br>

**Details:**
Just trying to be able to click on email links

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Forward the email so that I can further investigate.

**Comment by Sea-Worker9552** [comment]
What's your email? Sorry dumb question but I couldn't find it

**Comment by badmojr** [comment]
> What's your email? Sorry dumb question but I couldn't find it

`badmojr@gmail.com`

**Comment by Sea-Worker9552** [comment]
Forwarded you the Slickdeals Deal Alert email, not sure if you saw it.
