### ISSUE TITLE
BLOCK sentry.wearetriple.com

### ISSUE THREAD

**Issue by r2fo** [badmojr/1Hosts#835]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
sentry.wearetriple.com
```
<br>

**Details:**
This appears to be used for Sentry error logging (both the name and favicon suggest this)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/7845571

</details>
