### ISSUE TITLE
himg.nl

### ISSUE THREAD

**Issue by botthebestplayerintheworld** [badmojr/1Hosts#837]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
uBlock Origin, NextDNS

<br>

**Domains:**
```
himg.nl
```
<br>

**Details:**
doesn't load images in `hentaihaven.xxx` (NSFW)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
[himg.nl](https://mypdns.org/my-privacy-dns/matrix/-/issues/7845887) is a CDN for [hentaidude.xxx](https://mypdns.org/my-privacy-dns/matrix/-/issues/1159955) and [porngifs.xxx](https://mypdns.org/my-privacy-dns/matrix/-/issues/1157104)

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +74 |  |  | hentaihaven.xxx | 3 | image | `https://himg.nl/images/hh/Akiba-Girls-1/s_poster.jpg` |
| +74 |  |  | hentaihaven.xxx | 3 | image | `https://himg.nl/images/hh/Akiba-Girls-2/s_poster.jpg` |
| +74 |  |  | hentaihaven.xxx | 3 | image | `https://himg.nl/images/hh/Akiba-Girls-3/s_poster.jpg` |
