### ISSUE TITLE
dpm.demdex.net

### ISSUE THREAD

**Issue by ninjaguardsheep** [badmojr/1Hosts#838]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
unbound

<br>

**Domains:**
```
dpm.demdex.net.
```
<br>

**Details:**

Blocking this domain prevents loading of the NOW TV app on Roku devices.

The rather unhelpful error message  "Sorry, Now isn't available at the minute." is displayed.

Seems to be needed for the cookie consent dialog on the first run of the app.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by bbhtt** [comment]
Analytics provider owned by adobe https://experienceleague.adobe.com/docs/id-service/using/id-service-api/configurations/subdomain-config.html?lang=en, https://experienceleague.adobe.com/docs/id-service/using/id-service-api/configurations/subdomain-config.html?lang=en

**Comment by badmojr** [comment]
This is a tracker. Unless it breaks a considerable number of services, it's gonna stay blocked for now.
