### ISSUE TITLE
Unblock js.captcha-display.com

### ISSUE THREAD

**Issue by JohnChristianD** [badmojr/1Hosts#842]
**Lists in use:**
- [x ] mini
- [ ] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
js.captcha-display.com
```
<br>

**Details:**
Migration is being blocked in https://leaguelink.riotgames.com/en-us/
Can't login to Garena
Firefox users have to disable enhanced tracking protection also.

**Comment by spirillen** [comment]
```
easylist$ git grep 'captcha-display.com'
easyprivacy/easyprivacy_allowlist.txt:@@||js.captcha-display.com/xhr_tag.js$script,domain=auth.garena.com
easyprivacy/easyprivacy_trackingservers.txt:||captcha-display.com^
```
