### ISSUE TITLE
mymaster-uk.cyou

### ISSUE THREAD

**Issue by botthebestplayerintheworld** [badmojr/1Hosts#843]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
uBlock Origin, NextDNS

<br>

**Domains:**
```
mymaster-uk.cyou
```
<br>

**Details:**
breakage in `hentaihaven.xxx` (NSFW)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
Confirmed

hentaihaven.xxx: https://mypdns.org/my-privacy-dns/matrix/-/issues/1089263 `NSFW::Porn`
mymaster-uk.cyou: https://mypdns.org/my-privacy-dns/matrix/-/issues/7861587 `CDN::NSFW`
anpustream.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/7861830 `CDN::NSFW`
