### ISSUE TITLE
Unblock jorropo.net

### ISSUE THREAD

**Issue by marek22k** [badmojr/1Hosts#846]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
Manual checking of the list - own script

<br>

**Domains:**
```
jorropo.net
```
<br>

**Details:**
Hello,

jorropo.net is a part of [Yggdrasil network](https://yggdrasil-network.github.io/). It is listed as a public peer in [https://github.com/yggdrasil-network/public-peers/blob/master/europe/france.md](https://github.com/yggdrasil-network/public-peers/blob/master/europe/france.md). I have tried to connect to the peer several times but without success until I checked the DNS blacklists. Apparently jorropo.net is in the Xtra blacklist. I find this a bit confusing. When I go to jorropo.net with a browser, all I see is a white template page with contact information and nothing that would be spam or anything. Is there any particular reason why the domain is blacklisted? Is it possible to remove the domain?

(I am not the operator of this node or domain, only a participant in the Yggdrasil network)

**Comment by RicoHeat** [comment]
I suggest downgrading to a less restrictive list.. the Xtra list is more for advanced users.. 

https://github.com/badmojr/1Hosts#quickstart-guide
