### ISSUE TITLE
*.ydstatic.com [false alarm]

### ISSUE THREAD

**Issue by 3xploiton3** [badmojr/1Hosts#85]
images can't load

![image](https://user-images.githubusercontent.com/19517680/106388831-dd4e0980-6412-11eb-97f8-0d26a25e26cf.png)

source
https://play.google.com/store/apps/details?id=com.youdao.hindict&hl=en&gl=US

**Comment by badmojr** [comment]
You sure the images are essential, & not ads?
Can't find that large no. of people in the community whitelisting the above.

**Comment by 3xploiton3** [comment]
oimagea*.ydsatic.com
oimageb*
oimagec*

yes crucial for that apps

**Comment by badmojr** [comment]
Fixed!
