### ISSUE TITLE
Add heytapmobile.com

### ISSUE THREAD

**Issue by Guru-25** [badmojr/1Hosts#852]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:** NextDNS

<br>

**Domains:**
```
heytapmobile.com
slb-apisnd-in.heytapmobile.com
obus-dc20123-in.heytapmobile.com
httpdns-ocloud.heytapmobile.com
```
<br>

**Details:**
The above are the trackers found in realme devices connecting to multiple times for no reason.

![image](https://user-images.githubusercontent.com/70903440/204082566-7bd16f7b-64cb-4e18-8840-bbccac09ddd5.png)

I also didn't experience breakage in my tests.

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/7860118

</details>

**Comment by Guru-25** [comment]
"heytap" domains are telemetry in chinese mobile devices like oppo, realme...

Some of the similar domains like `heytapcs.com` [[1]](https://blocklist-tools.developerdan.com/entries/search?q=heytapcs.com), `heytapcs2.com` [[2]](https://blocklist-tools.developerdan.com/entries/search?q=heytapcs2.com), `heytapmobi.com` [[3]](https://blocklist-tools.developerdan.com/entries/search?q=heytapmobi.com) and `heytapdl.com` [[4]](https://blocklist-tools.developerdan.com/entries/search?q=heytapdl.com) are blocked by Xtra list.

so `heytapmobile.com` also can be considered to be added at least in Xtra list.
