### ISSUE TITLE
Block dreamdata.io

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#853]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
RethinkDNS

<br>

**Domains:**
```
dreamdata.io
```
<br>

**Details:**
Xtra already blocks `dreamdata.cloud`. The `.io` is the main domain which also serves their APM JavaScript over `cdn.dreamdata.io`.

Thanks.

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

dreamdata.io: https://mypdns.org/my-privacy-dns/matrix/-/issues/7854521

dreamdata.cloud: https://mypdns.org/my-privacy-dns/matrix/-/issues/7854520

</details>
