### ISSUE TITLE
BLOCK several pop up ad domains

### ISSUE THREAD

**Issue by r2fo** [badmojr/1Hosts#857]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
roceau.com
pasiac.com
ipalam.com
```
<br>

**Details:**
This is an ad domain used for ads which open a new tab at random clicks. An example of these ads can be found at 1stream.link

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/7859903

https://mypdns.org/my-privacy-dns/matrix/-/issues/7859901

https://mypdns.org/my-privacy-dns/matrix/-/issues/7859900

https://mypdns.org/my-privacy-dns/matrix/-/issues/7859899

</details>
