### ISSUE TITLE
false positive: ichnaea.netflix.com

### ISSUE THREAD

**Issue by beerisgood** [badmojr/1Hosts#86]
(i use your Lite version)
blocking this domain prevents Netflix from continuing to play files where you stopped or paused them.

**Comment by badmojr** [comment]
I do not consider this to be a false positive 'coz it's "a logging endpoint used to collect client information".
https://firebounty.com/104-netflix/

I stand to be corrected!

**Comment by beerisgood** [comment]
> client information  

Like what I wrote. It doesn't make sense cripple down the service if you pay for.

**Comment by badmojr** [comment]
@crssi, You got Netflix? Please chip in.

**Comment by crssi** [comment]
Not me. When I did a NF testing last time a friend of mine was willing to share credentials.

But `Ichnaea is a logging endpoint used to collect client information` does not say what information... maybe it is really only when someone stop or pause the video, so the stream service will know where to begin some other time.
Anyway, NF already got a ton of user info and a ton of other means to do a real user data collection if they wanted.

From my perspective and experiences "my users" hates breakages so much that they would drop any protection to make things work, so its always the best way to give them a lot of protection with a few loose end point so they do not flee.

I would consider the `Lite` version as such and if you are not sure, why don't you drop it in `Lite` and keep it in `Pro`?

That is just my part of brainstorming.
I can ask the friend again if necessary.
Let me know if I should go extra mile to ask a friend for a NF credentials to dive in.

Cheers

**Comment by badmojr** [comment]
Appreciate it! No need for the extra mile.

**Comment by badmojr** [comment]
Fixed!

**Comment by beerisgood** [comment]
> Fixed!

Thanks!
