### ISSUE TITLE
Block: s-bid.rmp.rakuten.com

### ISSUE THREAD

**Issue by 8227846265** [badmojr/1Hosts#870]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [X] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
Control D

<br>

**Domains:**
```
s-bid.rmp.rakuten.com
```
<br>

**Details:**
- Viber Ads 3rd domain is not blocked on 1Host Lite hence ads still show on Viber (Reference about this domain: https://www.joe0.com/2019/01/24/how-to-disable-viber-annoying-ads-on-windows-and-macintosh/)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Possible for you to just upgrade?

**Comment by 8227846265** [comment]
I had not considered upgrading since my only issue on `Lite` is just this single domain.

`Lite` works perfectly for me except for this one domain causing Viber application to show ads on Windows.

Lastly, `s-bid.rmp.rakuten.com` is one of the 3 core ad domains of Viber application. The other two are already included on `Lite` except for this one.
