### ISSUE TITLE
theporngrid.com

### ISSUE THREAD

**Issue by botthebestplayerintheworld** [badmojr/1Hosts#871]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
theporngrid.com
```
<br>

**Details:**
video doesn't load in `leaknudes.com` (NSFW)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by yokoffing** [comment]
On the adblock side of things, `kw3y5otoeuniv7e9rsi.com` is being blocked by Easylist and leads to the site not loading for me.

**Comment by yokoffing** [comment]
FYI https://github.com/easylist/easylist/issues/14347

**Comment by botthebestplayerintheworld** [comment]
removed

**Comment by botthebestplayerintheworld** [comment]
in xtra
