### ISSUE TITLE
Unblock quicksilver.scdn.co

### ISSUE THREAD

**Issue by bbhtt** [badmojr/1Hosts#872]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:** dnscrypt-proxy

<br>

**Domains:**
```
quicksilver.scdn.co
```
<br>

**Details:** Sometimes Spotify web player shows these modals, the image comes from that domain like https://quicksilver.scdn.co/assets/eede3326-8250-401c-8d85-9982ae120e26. If it is blocked the image doesn't load

![spotify](https://user-images.githubusercontent.com/62639087/206150929-33d6394d-abbd-4446-a8c5-a17d49a32a14.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Is there a way that I too can reproduce this?

**Comment by mehov** [comment]
@bbhtt are you confident this hostname is used just for that harmless image only? For all I know, it could be used for some ads/tracking as well

**Comment by bbhtt** [comment]
> Is there a way that I too can reproduce this?

I haven't found a way. They seem to fairly random. IIRC, this appeared after I renewed my subscription and messed a bit with the notification settings. Not sure if either of those is a trigger.

> @bbhtt are you confident this hostname is used just for that harmless image only? For all I know, it could be used for some ads/tracking as well

It don't know for sure, they don't document what each domain is used for. I have only seen this domain accessed once or twice while displaying these product modals or suggested album/artists etc. modals. It doesn't normally appear when playing in the web player.
