### ISSUE TITLE
kro.kr

### ISSUE THREAD

**Issue by botthebestplayerintheworld** [badmojr/1Hosts#887]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:**
uBlock Origin, NextDNS

<br>

**Domains:**
```
kro.kr
```
<br>

**Details:**
Would you allow `kro.kr`?
I've seen it being used for redirecting to malicious sites a lot of times
It's not malicious and subdomains of `kro.kr` can be registered in `xn--220b31d95hq8o.xn--3e0b707e`

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by Dynasty-Dev** [comment]
> I've seen it being used for redirecting to malicious sites a lot of times

So we should keep it on the list...

If you require to access this site then whitelist this domain in your own adblocker...

**Comment by botthebestplayerintheworld** [comment]
didn't think about that 👍
