### ISSUE TITLE
[Question] device-provisioning.googleapis.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#89]
Hi @badmojr 

I am seeing several times a day the requests to `device-provisioning.googleapis.com` from also iphones, not only androids.

Do you might have better knoweldge what this is about?

Thank you and cheers

**Comment by badmojr** [comment]
Hello!
No. My only guess is that it has s/th to do with [this](https://developers.google.com/android/management/provision-device).

**Comment by crssi** [comment]
Thank you, will need to keep eye on it.

Cheers
