### ISSUE TITLE
Why are you blocking Amazon Belgium?

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#890]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
amazon.com.be
```
<br>

**Details:**
Why is Amazon Belgium blocked?
![image](https://user-images.githubusercontent.com/71935156/207625452-9053e06d-04c4-4310-8da2-e42950105133.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by hagezi** [comment]
Ping @notracking

**Comment by notracking** [comment]
Thanks, fixed!
