### ISSUE TITLE
Block userback.io and api.userback.io

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#891]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
RethinkDNS

<br>

**Domains:**
```
userback.io
api.userback.io
```
<br>

**Details:**
A tool that collects user feedback, session recordings etc; I saw it used on `eptura.com` homepage.

`userback.io` is blocked by [mtxadmin/ublock/hosts](https://github.com/mtxadmin/ublock/blob/master/hosts.txt).

**Comment by badmojr** [comment]
Used as feedback widget.
