### ISSUE TITLE
xp.apple.com

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#908]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS 

<br>

**Domains:**
```
xp.apple.com 
```
<br>

**Details:**

I found out that xp.apple.com is blocked by 1Hosts Pro. 
This domain seems to be related to Apple OS updates. 
https://support.apple.com/en-hk/HT210060

Should we consider it as a false positive?

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by Quorum75** [comment]
> It collects analytics about updates from iOS's perspective, and isn't required for the ability of iOS to successfully update applications.

Some people don't agree with you.
https://github.com/badmojr/1Hosts/issues/536
https://github.com/badmojr/1Hosts/issues/562

**Comment by hagezi** [comment]
This will be an endless discussion. badmojr does not want to remove it. His decision.

I can only confirm some things, I had problems with the latest iOS and watchOS updates. They could not be installed with blocked `xp.apple.com`. I tried on 4 Apple Watches, 4 iPhones and 2 iPads from my household. No update possible without unblocking `xp.apple.com`.
No idea why this works for some and apparently not for some. Maybe it's related to region, humidity, wind direction or something else.
Next update I will block it before and see if the problems occur again.

**Comment by devipasigner** [comment]
> This will be an endless discussion. badmojr does not want to remove it. His decision.
> 
> I can only confirm some things, I had problems with the latest iOS and watchOS updates. They could not be installed with blocked `xp.apple.com`. I tried on 4 Apple Watches, 4 iPhones and 2 iPads from my household. No update possible without unblocking `xp.apple.com`. No idea why this works for some and apparently not for some. Maybe it's related to region, humidity, wind direction or something else. Next update I will block it before and see if the problems occur again.

Most of the devices in my household consist of apple devices. I have xp.apple.com blocked and was always able to update. What iOS version are you using, some Betas, etc have issues finding updates sometimes not related to apple

**Comment by hagezi** [comment]
@devipasigner The problems occurred when I updated to iOS 16.1 and watchOS 9.1. I had the same behavior with iOS 16.2 and watchOS 9.2. iOS 16.0 could still be installed with blocked xp.apple.com.

**Comment by devipasigner** [comment]
> @devipasigner The problems occurred when I updated to iOS 16.1 and watchOS 9.1. I had the same behavior with iOS 16.2 and watchOS 9.2. iOS 16.0 could still be installed with blocked xp.apple.com.

Hmm I and a lot of other people on Reddit who don’t use dns as locker  also had some issues on iOS 16. It wasn’t because of dns filtering though, even switching to 1.1.1.1 or 8.8.8.8 per say wouldn’t fix the issue. Thought I don’t know if you’re having the same issue

**Comment by Thomas-Schubert** [comment]
My HomePods reported an Internet connection problem until I manually whitelisted this domain.
