### ISSUE TITLE
Breakage due to rdrtr.com

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#93]
After finalization flight booking on `flights.google.com` the redirection to airline is broken since it is rerouted over `rdrtr.com` to the final destination.

Cheers

**Comment by badmojr** [comment]
Booking aint supported from my geolocation. Cant thoroughly test this.
Please recheck if it's fixed.

**Comment by crssi** [comment]
Its all great now.

Thank you and cheers
