### ISSUE TITLE
arc.msn.com

### ISSUE THREAD

**Issue by beerisgood** [badmojr/1Hosts#94]
(using Lite version)

Blocking this domain stop loading images from Windows Spotlight and more:

> 

Windows Spotlight | The following endpoints are used to retrieve Windows Spotlight metadata that describes content, such as references to image locations, as well as suggested apps, Microsoft account notifications, and Windows tips. | TLSv1.2/HTTPS/HTTP | arc.msn.com*
-- | -- | -- | --

https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-20h2-non-enterprise-editions

**Comment by badmojr** [comment]
Sorry for the delay! Been hella busy lately.
Fixed.

**Comment by beerisgood** [comment]
Thanks!
