### ISSUE TITLE
Suggestions for 1Hosts (Lite)

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#95]
Hi @badmojr 

I am missing some hosts in Lite version.
Would you consider/is it possible for you to add those? Take this "issue" also as a brainstorming. 😉 

```
addthis.com
api.amplitude.com
e.crashlytics.com
evidon.com
googletagmanager.com
googletagservices.com
gvt2.com
imrworldwide.com
js.hs-scripts.com
s0.2mdn.net
scorecardresearch.com
woodpecker.uc.cn
```

Thank you,
Cheers

**Comment by badmojr** [comment]
Done!
Some did not make it on the list though by design i.e intentional.
Recheck & share your thoughts. 10x!

Also, what did u mean by brainstorming!?

**Comment by crssi** [comment]
Cool, thank you. 👍 

With "brainstorming" I meant this is only a humble request and debatable in a way that you can also tell me/teach me why some yes and why some no. 😉 Nothing really seriously. 😄 

`gvt2.com` got on this list, since I could see in the last half a years of logs, that only `beacons*.gvt2.com` are listed and any of the `*.gvt3.com` are also just a CNAMEs for some beacons in gvt2.

`s0.2mdn.net` is quite prevalent here.

I have forgotten to list `reports.crashlytics.com` in the OP, since this one is also very prevalent from some of the iOS devices and blocking it, does not result in any breakages.

Otherwise, this is a great change and thank you for it. 😄 

Cheers

**Comment by badmojr** [comment]
OK! 10ks.

**Comment by badmojr** [comment]
`reports.crashlytics.com` added.

**Comment by crssi** [comment]
Thank you 👍
