### ISSUE TITLE
ads.reddit.com

### ISSUE THREAD

**Issue by zezodanh** [badmojr/1Hosts#969]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:** uBlock Origin, Adguardhome

<br>

**Domains:**
```
ads.reddit.com

```
<br>

**Details:**

Advertisement

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
Link please!

**Comment by zezodanh** [comment]
ads.reddit.com is the domain of Reddit Ads

**Comment by badmojr** [comment]
Provide a sample page where the domain is used to display ads.

**Comment by zezodanh** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/21109#issuecomment-1166585609
https://github.com/uBlockOrigin/uAssets/issues/13848
This domain is for people who want to create ads on reddit

**Comment by badmojr** [comment]
It's not actively used to display ads to users then.
