### ISSUE TITLE
Cannot purchase due to listing order.shareit.com (also shareit.com)

### ISSUE THREAD

**Issue by crssi** [badmojr/1Hosts#97]
Decided to give it a try with a **Pro** instead of **Lite**... just for my self at the moment... in a few minutes of usage the first issue raised up. 😢 

1. Visit the site `http://www.powertheshell.com/isesteroids/`.
2. In the `Purchasing a License` section click on `Get Private License` or `Get Commercial License`.

The link is broken due to listing `order.shareit.com` (from NextDNS point of view also the `shareit.com`) in **1Hosts Pro**.

Cheers

**Comment by badmojr** [comment]
Removed!
