### ISSUE TITLE
Block referralrock.com

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#977]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [ ] Pro
- [x] Xtra
<br>

**Client:**
Rethink DNS

<br>

**Domains:**
```
referralrock.com
```
<br>

**Details:**
Stumbled on it on `pilot.com`. It sent beacons. Seems like it is used for affiliate marketing. May be too aggressive to block it with Pro? [Blocked by ph00lt0's blocklists](https://archive.is/9fmhz).

**Comment by badmojr** [comment]
> May be too aggressive to block it with Pro?

My thoughts exactly.

**Comment by ignoramous** [comment]
> My thoughts exactly.

Why not in Xtra?
