### ISSUE TITLE
Include missing domains from AdGuard DNS filter

### ISSUE THREAD

**Issue by HellboyPI** [badmojr/1Hosts#979]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
AdGuard Home

<br>

**Domains:**
```
||teleriumads-*.netdna-ssl.com^ 
||putrr*.com^ 
||block.s*block.com^ 
||mf*.advantage.as^ 
||www.fuze-hill*.xyz^ 
||adv0*.msa.cdn.mediaset.net^ 
||adx-*.dbankcloud. 
||ad-*.appacc.dbankedge.cn^ 
||adx-*.dbankedge.cn^ 
||adx-*.op.dbankcloud.com.edgekey.net^ 
||events-*.op.hicloud.com^ 
||iad-*.braze.com^ 
||cdn-adn-*.rayjump.com^ 
||adserver.*.yahoodns.net^ 
||iad-*.appboy.com^ 
||production-adserver-*.amazonaws.com^

```
<br>

**Details:**
More than 200 domain entries of this type can be found in the AdGuard DNS filter ([link1](https://filters.adtidy.org/extension/chromium/filters/15.txt), [link2](https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt)). 
Your script removes them to ensure compatibility for all clients. 
But, these are valid entries and they can be used on clients which support Adblock-style syntax (uBlock Origin, AdGuardHome...)

So, is it possible to include them only in the Adblock list? 

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
> Your script removes them to ensure compatibility for all clients.

Indeed. This will stay so!
