### ISSUE TITLE
Agoda IOS app does not work

### ISSUE THREAD

**Issue by FatLuk** [badmojr/1Hosts#989]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [ ] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
Agoda.com
```
<br>

**Details:**

Agoda ios app does not work

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by hagezi** [comment]
@badmojr  Agoda API is blocked by CNAME `api.agoda.com.edgekey.net`
