### ISSUE TITLE
Block radar.game

### ISSUE THREAD

**Issue by cinatime** [badmojr/1Hosts#992]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [x] Xtra
<br>

**Client:**

<br>

**Domains:**
```
radar.game
```
<br>

**Details:**
malware

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by badmojr** [comment]
More info needed.

**Comment by cinatime** [comment]
https://www.virustotal.com/gui/file/e00609f98a5ce391934710a1a47f748bb063ae939555e1cb491c4e5cff69fa97

**Comment by cinatime** [comment]
And this is also blocked in 

Threat Intelligence Feeds, OISD, notracking, HaGeZi - Multi ULTIMATE, HaGeZi - Multi PRO, HaGeZi - Multi PRO++, HaGeZi - Multi NORMAL and HaGeZi - Multi LIGHT.

**Comment by cinatime** [comment]
Tweets about this that may be useful

[here](https://nitter.net/Another_AH/status/1616151211287412736#m)

[here](https://nitter.net/NabiKAZ/status/1615869330121699329#m)

**Comment by cinatime** [comment]
Joe Sandbox Analysis: 
			
Verdict: MAL
Score: 68/100

HTML Report: https://www.joesandbox.com/analysis/788151/0/html	
PDF Report: https://www.joesandbox.com/analysis/788151/0/pdf
Executive Report: https://www.joesandbox.com/analysis/788151/0/executive
Incident Report: https://www.joesandbox.com/analysis/788151/0/irxml
IOCs: https://www.joesandbox.com/analysis/788151?idtype=analysisid
