### ISSUE TITLE
Block mktoweb.com

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#998]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**

<br>
Rethink DNS

**Domains:**
```
mktoweb.com
mktoedge.com
```
<br>

**Details:**
Marketo endpoints. Blocked by Hagezi (Ultimate), GoodbyeAds, TBPL Tracking, Lightswitch05, and ph00lt0 blocklists: https://archive.is/4SEM2

**Comment by badmojr** [comment]
Popular online services use them as CNAMEs for their email links.
ref:
- gitlab.mktoweb.com
- https://go.veeam.com/
- https://github.com/nextdns/click-tracking-domains/blob/main/domains#L376

**Comment by ignoramous** [comment]
> Popular online services use them as CNAMEs for their email links.

Not eligible for Xtra? Also, I though Pro was aggressive enough to include these trackers.
