### ISSUE TITLE
Block tbstats.com

### ISSUE THREAD

**Issue by ignoramous** [badmojr/1Hosts#999]
**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
Rethink DNS

<br>

**Domains:**
```
tbstats.com
```
<br>

**Details:**
tbstat.com seems to be a counter / ticker from what I can tell mostly used by cryptocurrency news / scoop websites ([urlscan](https://archive.is/Tv5ZW)). Blocked by GoodbyeAds: https://archive.is/4SEM2

**Comment by badmojr** [comment]
Can be found [here](https://www.theblock.co/) blocking article images.
